### ISSUE TITLE
SQL formatting issue = >

### ISSUE THREAD

**Issue by dariusdev** [mtxr/vscode-sqltools#1004]
**Describe the bug**
I am using PosrgreSQL server  and have query:

`
SELECT create_hypertable (
    'test.test2',
    'timestamp',
    chunk_time_interval = > INTERVAL '1 day'
  )
`
Symbol `= >` is formatted with space in the middle and it corrupts the query. How i can ignore that symbol formatting or configure it to format properly ?

it should be formatted 
`chunk_time_interval => INTERVAL '1 day'`

**Comment by gjsjohnmurray** [comment]
Fixed in #995 which will be in the next release.
