### ISSUE TITLE
Can't connect to user

### ISSUE THREAD

**Issue by its-mrarsikk** [mtxr/vscode-sqltools#1006]
**Describe the bug**
I can't log in a user created by phpMyAdmin.

**To Reproduce**
1. Create user with password and all priveleges using phpMyAdmin on server hosted by MAMP
2. Create a connection using SQLTools GUI
3. The connection should be like so:
![image](https://user-images.githubusercontent.com/94739102/194797679-ba25b72a-7b14-4e48-9253-8fa072ac65a5.png)
4. TEST CONNECTION or SAVE CONNECTION > Connect

**Expected behavior**
I expected that i could log in without any errors

**Screenshots**

**Desktop (please complete the following information):**
 - SQLTools Version v0.25.1
 - VS Code Version: 1.72.0
 - OS: Windows 10 Pro x64
 - Driver: MySQL / MariaDB
 - Database version: MySQL, don't know the version (not using cmd)

**Additional context**

**Comment by gjsjohnmurray** [comment]
Are you certain that MAMP's MySQL is listening on port 3306? The doc at https://documentation.mamp.info/en/MAMP-Windows/First-Steps/index.html implies it is on 8889.
