### ISSUE TITLE
Startup script fails and I can't use extension

### ISSUE THREAD

**Issue by Taimoor-Tariq** [mtxr/vscode-sqltools#1016]
**Describe the bug**
Everytime I launch VS Code a terminal is created to run a script, but the script fails and I can't use any of the extension features.

**To Reproduce**
1. Launch VS Code
2. Terminal opens and script fails

**Expected behavior**
Terminal opens, runs the script and enable all features of the extension

**Screenshots**
![image](https://user-images.githubusercontent.com/45585081/197033534-d3cadf12-d804-40da-ade0-5b2c897a3453.png)
![image](https://user-images.githubusercontent.com/45585081/197035060-6b8c267d-f13e-4b71-8a2f-0b0270328197.png)

**Desktop:**
 - SQLTools Version: v0.25.1
 - VS Code Version: v1.72.2
 - OS: Windows
 - Driver:
   - [ ] PostgreSQL/Redshift
   - [x] MySQL/MariaDB
   - [ ] MSSQL/Azure
   - [x] SQLite
   - [ ] Other? Which...

**Comment by gjsjohnmurray** [comment]
#1008 may contain some clues for you. To use the SQLite driver you need a local installation of NodeJS, and at the moment on Windows you also need PowerShell 7 rather than the version of PowerShell that is preinstalled on Windows.

**Comment by Taimoor-Tariq** [comment]
Yea fixed by changing `useNodeRuntime`
```json
"sqltools.useNodeRuntime": "C:\\Program Files\\nodejs\\node.exe"
```
it was set to `true` for some reason
