### ISSUE TITLE
Is anyone working on a SQLTools DuckDB driver as of yet?

### ISSUE THREAD

**Issue by aaronsteers** [mtxr/vscode-sqltools#1018]
We have a use case where it would be awesome to integrate DuckDB into SQLTools and VS Code.

Mirror posted on the DuckDB Issue tracker:

- https://github.com/duckdb/duckdb/discussions/5067

**Comment by RandomFractals** [comment]
I started working on it last week. Here is a brief demo so far using replica of SQLite chinook.db demo file:

![duckdb-sql-tools-2](https://user-images.githubusercontent.com/656833/212547034-5959d490-7855-4dbd-b088-ed552a2c0b95.gif)

I'll be posting more updates on that vscode IDE extension/duckdb driver on twitter: https://twitter.com/TarasNovak/status/1614629029642133504

**Comment by RandomFractals** [comment]
Preview version of DuckDB Sql Tools VSCode extension is now available in marketplace:

https://marketplace.visualstudio.com/items?itemName=RandomFractalsInc.duckdb-sql-tools

**Comment by aaronsteers** [comment]
@RandomFractals - Amazing! 😍 Thanks!
