### ISSUE TITLE
How to get rid of "Element with id ... is already registered" error and get connections listed?

### ISSUE THREAD

**Issue by GegznaV** [mtxr/vscode-sqltools#1022]
**Describe the bug**
I described it here:   
https://stackoverflow.com/questions/74211903/error-element-with-id-already-registered-and-no-sql-connections-in-the-list

**Expected behavior**
I expect no pop-up with the error and MySQL connections to appear in the list.

**Desktop (please complete the following information):**
 - SQLTools Version 0.25.1
 - VS Code Version: 1.72.2
 - OS: Windows 10
 - Driver:
   - [ ] PostgreSQL/Redshift
   - [x] MySQL/MariaDB
   - [ ] MSSQL/Azure
   - [ ] SQLite
   - [ ] Other? Which...
 - Database version: MySQL Workbench 8.0

**Comment by GegznaV** [comment]
The suggestion in https://github.com/mtxr/vscode-sqltools/issues/668#issuecomment-993403972 solved the issue.

**Comment by gjsjohnmurray** [comment]
Starting with today's 0.27.1 release it should no longer be possible to define connections with duplicate IDs using the UI.
