### ISSUE TITLE
Image (icon) of AWS Redshift is missing in VSCode description

### ISSUE THREAD

**Issue by GegznaV** [mtxr/vscode-sqltools#1023]
![image](https://user-images.githubusercontent.com/12725868/198103148-18098278-270a-45c6-b822-50b4e606fd66.png)

**Comment by gjsjohnmurray** [comment]
Thanks for the report. We updated doc today at https://vscode-sqltools.mteixeira.dev to reflect that the use of this official driver is being deprecated (see #991) in favour of the [community driver](https://marketplace.visualstudio.com/items?itemName=kj.sqltools-driver-redshift) from @kj-9.

The official driver will continue to work for connections already defined to use it, but that row will disappear from the Details tab of the SQLTools extension.
