### ISSUE TITLE
nodeJS syntax error prevents SQLTools from being functional

### ISSUE THREAD

**Issue by GegznaV** [mtxr/vscode-sqltools#1024]
**Describe the bug**
Error occurs if nodeJS runtime is enabled. 

**To Reproduce**
1.Set ` "sqltools.useNodeRuntime": true`
2. Reload VSCode
3. A new default terminal gets opened at VSCode startup:  
![image](https://user-images.githubusercontent.com/12725868/198138796-45f66461-c343-4afc-9210-f93c55624fea.png)
4. An error similar to this occurs (in the example Command Prompt is the default terminal) is present in the terminal:

```
D:\dir>node -e 'require(\"fs\").writeFileSync(\"C:\\Users\\user\\AppData\\Local\\vscode-sqltools\\Data\\.node-runtime\", process.execPath)' && exit 0     Data\\.node-runtime\", process.execPath)' && exit 0
[eval]:1
'require("fs").writeFileSync("C:\\Users\\user\\AppData\\Local\\vscode-sqltools\\Data\\.node-runtime",
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

SyntaxError: Invalid or unexpected token
    at new Script (node:vm:100:7)
    at createScript (node:vm:265:10)
    at Object.runInThisContext (node:vm:313:10)
    at node:internal/process/execution:79:19
    at [eval]-wrapper:6:22
    at evalScript (node:internal/process/execution:78:60)
    at node:internal/main/eval_string:28:3

Node.js v18.12.0
```

The list of currently set connections is not present
![image](https://user-images.githubusercontent.com/12725868/198139634-ef1c811e-9da5-4228-9673-2871dde14a50.png)

After pushing "Add New Connection" and a pal period (e.g., 1 min.) additional error occurs as a pop-up:
![image](https://user-images.githubusercontent.com/12725868/198140569-f8d2970b-bcff-46af-9c46-07c418bef4ab.png)

**Expected behavior**
No error, fully functional SQLTools extension.

**Desktop (please complete the following information):**
 - SQLTools Version 0.25.1
 - VS Code Version: 1.72.2
 - OS: Windows 10

**Additional context**
This issue appeared when I tried to connect to an SQLite database.

**Comment by gjsjohnmurray** [comment]
Please see https://github.com/mtxr/vscode-sqltools/pull/993#issuecomment-1265828891 for advice. Let us know if this helps.

**Comment by Ocraftyone** [comment]
The issue seems to be the use of single quotes rather than double. If you change the quotes to double it executes.
Edit: following that comment above does fix this, but only as a workaround. The auto detect still does not work. I am using Command Prompt

**Comment by GegznaV** [comment]
Installing PowerShell 7 and setting it as the default terminal for windows in VSCode worked for me. But does it mean that I am forced to use these settings to make the plugin work? I'd like to use Git Bash or Ubuntu WLS terminal as the default terminal.

**Comment by GegznaV** [comment]
OK, there is more in that comment. I did not use that workaround yet.

**Comment by GegznaV** [comment]
Setting to `    "sqltools.useNodeRuntime": "C:\\Program Files\\nodejs\\node.exe"` and using WSL terminal as default gives the same issue as in the original post.

**Comment by GegznaV** [comment]
So

> But does it mean that I am forced to use these settings to make the plugin work? I'd like to use Git Bash or Ubuntu WLS terminal as the default terminal.

**Comment by gjsjohnmurray** [comment]
Today's 0.26.0 release includes changes that should make this mechanism work even without PowerShell 7. Please let us know here if this helps you.

**Comment by GegznaV** [comment]
I did not change anything, just updated the plugins (use PowerShell 7 as the default shell on the Windows side). Is this warning expected at VSCode startup?

![image](https://user-images.githubusercontent.com/12725868/201471725-53c0853e-7c44-48e0-aee4-6352d6e569d0.png)

**Comment by GegznaV** [comment]
Does this message mean to change this setting  `"sqltools.useNodeRuntime"`?

Can the purpose described in the message be achieved by deleting `"sqltools.useNodeRuntime": "C:\\Program Files\\nodejs\\node.exe"` from `settings.json`?

**Comment by GegznaV** [comment]
OK, the removal of this setting did not help to remove the warning. Please, give more explicit instructions on what to do to get rid of this warning.

**Comment by mikes-gh** [comment]
0.26 with powershell 7 on macOS
```
PS /Users/mikes/Documents/Repos/Workflows> node -e 'require("fs").writeFileSync("/Users/mikes/Library/Application Support/vscode-sqltools/.node-runtime", process.execPath)'
[eval]:1
require(fs).writeFileSync(/Users/mikes/Library/Application
                          ^

SyntaxError: Invalid regular expression flags
    at new Script (node:vm:101:7)
    at createScript (node:vm:262:10)
    at Object.runInThisContext (node:vm:310:10)
    at node:internal/process/execution:77:19
    at [eval]-wrapper:6:22
    at evalScript (node:internal/process/execution:76:60)
    at node:internal/main/eval_string:23:3
PS /Users/mikes/Documents/Repos/Workflows> 
```

**Comment by gjsjohnmurray** [comment]
@mikes-gh what version of node do you have?

`node -v`

**Comment by mikes-gh** [comment]
> @mikes-gh what version of node do you have?
> 
> `node -v`

v15.3.0

edit

Same error with v18.12.1

**Comment by mikes-gh** [comment]
On my machine macOS powershell 7 and I suspect Linux

`node -e 'require("fs").writeFileSync("/Users/mikes/Library/Application Support/vscode-sqltools/.node-runtime", process.execPath)' && $(exit 0)`
Result error

`node -e "require('fs').writeFileSync('/Users/mikes/Library/Application Support/vscode-sqltools/.node-runtime', process.execPath)" && $(exit 0)`
Result succeed

**Comment by mikes-gh** [comment]
Can someone on windows try

`node -e "require('fs').writeFileSync('C:\ChangeThisToYourPath\vscode-sqltools\.node-runtime', process.execPath)" && $(exit 0)`

And if it works just change.

https://github.com/gjsjohnmurray/vscode-sqltools/blob/b13607e1b77049200b897f30bfe4e9033ee3a6bc/packages/extension/src/language-client/detect-node-path.ts#L20

**Comment by gjsjohnmurray** [comment]
> OK, the removal of this setting did not help to remove the warning. Please, give more explicit instructions on what to do to get rid of this warning.

@GegznaV when `sqltools.useNodeRuntime` is set to be a string I wouldn't expect that modal warning ever to appear. When set `true` the modal will appear after 5 seconds if detection hasn't completed. I have created #1034 to increase this timeout. Until then I suggest you either tolerate it, or set the string, or get a faster workstation. 😉

**Comment by GegznaV** [comment]
Thank you for your response, @gjsjohnmurray :)

**Comment by GegznaV** [comment]
> > OK, the removal of this setting did not help to remove the warning. Please, give more explicit instructions on what to do to get rid of this warning.
> 
> @GegznaV when `sqltools.useNodeRuntime` is set to be a string I wouldn't expect that modal warning ever to appear. When set `true` the modal will appear after 5 seconds if detection hasn't completed. I have created #1034 to increase this timeout. Until then I suggest you either tolerate it, or set the string, or get a faster workstation. 😉

In my settings, there was `null`, not logical:
```JSON
"sqltools.useNodeRuntime": null
```

Do you mean string like this:

![image](https://user-images.githubusercontent.com/12725868/201659098-b312ce82-fa85-483a-bcfd-40b9f401995c.png)


If yes, why does the warning appear?

**Comment by GegznaV** [comment]
> Until then I suggest you either tolerate it

No problem :)

***

For me, the initial issue is solved.  So, in my opinion, the thread can be closed.

Just I'm not sure about @mikes-gh's issue: is it solved too? Is it the same issue?

**Comment by gjsjohnmurray** [comment]
@GegznaV in the JSON in your screenshot the word `sqltools` has squiggles under it. Do you get a tip when you hover over the word? Which settings file is this in?

I don't know why `null` is also an accepted value for this setting. @mtxr may do.

**Comment by gjsjohnmurray** [comment]
> Just I'm not sure about @mikes-gh's issue: is it solved too? Is it the same issue?

That's different. I created #1036 for it.

**Comment by GegznaV** [comment]
> JSON in your screenshot the word `sqltools` has squiggles under it.

It is a spellchecker: 
![image](https://user-images.githubusercontent.com/12725868/201661311-2f389026-b86f-47ee-bcff-a6ef12fadb22.png)

**Comment by GegznaV** [comment]
> I don't know why `null` is also an accepted value for this setting.

I deleted the row from the settings, and the one with `null` was auto-generated.

**Comment by GegznaV** [comment]
> Which settings file is this in?

Ctrl+Shift+P then:
![image](https://user-images.githubusercontent.com/12725868/201662177-bf826c6c-a7bd-4f3e-8557-efa150925b3b.png)

**Comment by gjsjohnmurray** [comment]
Do you have a workspace open? If yes there will also be a command `Preferences: Open Workspace Settings (JSON)`. Please run that and check whether you have any `sqltools` settings in it.

**Comment by GegznaV** [comment]
In `"sqltools.useNodeRuntime": "C:\\Program Files\\nodejs\\node.exe"` there was a logical value. I fixed it into character and the issue got fixed. Thank you, @gjsjohnmurray :)
