### ISSUE TITLE
Autodetection of Node.js runtime happens even when an override string is set in `sqltools.useNodeRuntime`

### ISSUE THREAD

**Issue by gjsjohnmurray** [mtxr/vscode-sqltools#1037]
See https://github.com/mtxr/vscode-sqltools/issues/1024#issuecomment-1313615413

**Comment by gjsjohnmurray** [comment]
@GegznaV FYI I have opened this issue.

**Comment by gjsjohnmurray** [comment]
@GegznaV please confirm that you have **not** set a value for the `sqltools.useNodeRuntime` property at the workspace level of VS Code's [settings hierarchy](https://code.visualstudio.com/docs/getstarted/settings). Specifically, is it present in a `settings.json` file in a `.vscode` subfolder of the folder you opened in VS Code? And if your workspace is opened from a .code-workspace file please also check the JSON in that file.

**Comment by GegznaV** [comment]
In `.vscode/settings.json` there was a logical value of `sqltools.useNodeRuntime` setting. Now I changed it to character value and the pop-up message (warning) does not appear. I did not know that there are several `settings.json` files. 

May `"sqltools.useNodeRuntime": null` mean that the default value from other settings file is used?

**Comment by GegznaV** [comment]
So, this issue can be closed too.

**Comment by gjsjohnmurray** [comment]
Just noticed that the alert gives the setting incorrectly. Should say 'sqltools.useNodeRuntime'

![image](https://user-images.githubusercontent.com/6726799/202412375-fce1d82d-329e-4cc8-b7df-20e4f6084fc6.png)
