### ISSUE TITLE
How do I connect to a local DB?

### ISSUE THREAD

**Issue by ivsuleman** [mtxr/vscode-sqltools#104]
### Issue Type

* [ ] Question

### Prerequisites (For bugfixes)

* [ ] Are you running the latest version?
* [ ] Did you check the logs?
* [x] Did you check the Setup?

### Description
I use SQLLite on mac to view database. How can I set-up the connection to db in VS using extension?

### Steps to Reproduce (For bugfixes)

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

- *Version*: vX.Y.Z
- *OS*: ...
- *SGDB*: MySQL, PostgresSQL...

**Comment by mtxr** [comment]
@ivsuleman We are currently not supporting SQLite. There is an issue tracking that already, #51.

I'll keep track of it there, thanks.
