### ISSUE TITLE
All tables from PSQL database are expanded by default

### ISSUE THREAD

**Issue by buzztic** [mtxr/vscode-sqltools#105]
### Issue Type

* [ ] Bug
* [x] Enhancement 
* [ ] Feature Request
* [ ] Question
* [ ] Other

### Prerequisites (For bugfixes)

* [x] Are you running the latest version?
* [ ] Did you check the logs?
* [ ] Did you check the Setup?

### Description

Thank you for updating sqltools. The last release is great,
I noticed that before the release all tables were colapsed by default in side bar whereas now, all tables are expanded. 

Is-there a short cut to collapsed all the table at once ?

Thank you for your job !

- *Version*: 0.15.1
- *SGDB*: PostgresSQL...

**Comment by PapsOu** [comment]
It would be great to have a parameter to set this feature `on` or `off`, like ` "sqltools.tablesStartExpanded": false,`

@buzztic : You can select the first table, and pressing <kbd>space</kbd> will collapse it. Using with the <kbd>down arrow</kbd> you can collapse quickly all tables (but someone may think you're crazy if you have more than 50 tables to collapse every mornings :stuck_out_tongue_winking_eye:)

**Comment by buzztic** [comment]
thank you @PapsOu

**Comment by mtxr** [comment]
I like the idea of an parameter as @PapsOu suggested.

Would you like to make a PR?

I can release it right away.

**Comment by PapsOu** [comment]
@mtxr Do you have planned a release soon ?

**Comment by mtxr** [comment]
My intention is too release this this weekend, but I'm very busy with some work deliveries. I'm sorry.

The next release will have lots of enhancements, as you can check on master-webpack branch, but I have to finish some stuff there first, also test with all sgdb's.

**Comment by mtxr** [comment]
This has already been changed as seen on #155.

I'll be closing, it will be released soon.

**Comment by PapsOu** [comment]
@mtxr Thank you for that release !

**Comment by mtxr** [comment]
@PapsOu thank you for your contributions! Let me know how this release is working. This release had a bunch of enhancements. Should be faster to load, to run and so on. Please, read the #115 and give me some feedback. A review on VSCode marketplace would also be great!
