### ISSUE TITLE
Exasol Connection - Client connection must be encrypted

### ISSUE THREAD

**Issue by BeneBanause** [mtxr/vscode-sqltools#1057]
Hey, 
I am using the sqltools-driver for exasol and have following problem when trying to connect to the exasol:

Operational error [08004] connection exception - Client connection must be encrypted. 

I tried to solve this issue by manually add encryption to the connection.schema and ui.schema but it does not work. 

![error_exa_driver](https://user-images.githubusercontent.com/109584116/206447560-6785bd7c-8103-43c9-ac57-ea4dd48e92a7.png)

Versions: 
SQLTools v0.26.0
sqltools-driver-exasol v0.0.7
VSC v1.710

**Comment by gjsjohnmurray** [comment]
I think this needs to be raised with the author of the driver. Is this where you got it from?

https://github.com/revolut-engineering/sqltools-driver-exasol

**Comment by BeneBanause** [comment]
I think you are right, I was not sure about it. Yes I got it from there.

Best Regards

> I think this needs to be raised with the author of the driver. Is this where you got it from?
> 
> https://github.com/revolut-engineering/sqltools-driver-exasol
