### ISSUE TITLE
firebird support

### ISSUE THREAD

**Issue by budisentosa** [mtxr/vscode-sqltools#106]
### Issue Type

* [ ] Bug
* [ ] Enhancement 
* [X] Feature Request
* [ ] Question
* [ ] Other

### Prerequisites (For bugfixes)

* [ ] Are you running the latest version?
* [ ] Did you check the logs?
* [ ] Did you check the Setup?

### Steps to Reproduce (For bugfixes)

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

- *Version*: vX.Y.Z
- *OS*: ...
- *SGDB*: MySQL, PostgresSQL...

**Comment by mtxr** [comment]
Tracked on #73
