### ISSUE TITLE
ERROR: Failed to start language server

### ISSUE THREAD

**Issue by rameshkithsiri** [mtxr/vscode-sqltools#107]
### Issue Type

* [x] Bug
* [ ] Enhancement 
* [ ] Feature Request
* [ ] Question
* [ ] Other

### Prerequisites (For bugfixes)

* [x] Are you running the latest version?
* [x] Did you check the logs?
* [ ] Did you check the Setup?

### Description

When I install SQL tools from vscode extensions panel it says `ERROR: Failed to start language server:`
I did nothing after installation. only reloaded. 

### Steps to Reproduce (For bugfixes)

**Actual behavior:**
Here is my log:-

```
[2018-10-15T05:19:54.][v0.15.1] ERROR: Failed to start language server: 
[2018-10-15T05:19:54.][v0.15.1] Error: spawn /usr/share/code/code ENOENT
	at _errnoException (util.js:1024:11)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
	at onErrorNT (internal/child_process.js:372:16)
	at _combinedTickCallback (internal/process/next_tick.js:138:11)
	at process._tickDomainCallback (internal/process/next_tick.js:218:9)
[2018-10-15T05:19:54.][v0.15.1] ERROR: Telemetry:screenview error
[2018-10-15T05:19:54.][v0.15.1] {"code":"ECONNRESET"}
[2018-10-15T05:19:54.][v0.15.1] ERROR: Telemetry:timer error
[2018-10-15T05:19:54.][v0.15.1] {"code":"ECONNRESET"}
[2018-10-15T05:20:04.][v0.15.1] ERROR: Telemetry:event error
[2018-10-15T05:20:04.][v0.15.1] {"code":"ECONNRESET"}
[2018-10-15T05:20:04.][v0.15.1] ERROR: Telemetry:exception error
[2018-10-15T05:20:04.][v0.15.1] {"code":"ECONNRESET"}
```

### Versions

- *Version*: v0.15.1
- *OS*: Ubuntu 14.04
- *SGDB*: MySQL, PostgresSQL...

**Comment by benyaminl** [comment]
> ### Issue Type
> * [x]  Bug
> * [ ]  Enhancement
> * [ ]  Feature Request
> * [ ]  Question
> * [ ]  Other
> 
> ### Prerequisites (For bugfixes)
> * [x]  Are you running the latest version?
> * [x]  Did you check the logs?
> * [ ]  Did you check the Setup?
> 
> ### Description
> When I install SQL tools from vscode extensions panel it says `ERROR: Failed to start language server:`
> I did nothing after installation. only reloaded.
> 
> ### Steps to Reproduce (For bugfixes)
> **Actual behavior:**
> Here is my log:-
> 
> ```
> [2018-10-15T05:19:54.][v0.15.1] ERROR: Failed to start language server: 
> [2018-10-15T05:19:54.][v0.15.1] Error: spawn /usr/share/code/code ENOENT
> 	at _errnoException (util.js:1024:11)
> 	at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
> 	at onErrorNT (internal/child_process.js:372:16)
> 	at _combinedTickCallback (internal/process/next_tick.js:138:11)
> 	at process._tickDomainCallback (internal/process/next_tick.js:218:9)
> [2018-10-15T05:19:54.][v0.15.1] ERROR: Telemetry:screenview error
> [2018-10-15T05:19:54.][v0.15.1] {"code":"ECONNRESET"}
> [2018-10-15T05:19:54.][v0.15.1] ERROR: Telemetry:timer error
> [2018-10-15T05:19:54.][v0.15.1] {"code":"ECONNRESET"}
> [2018-10-15T05:20:04.][v0.15.1] ERROR: Telemetry:event error
> [2018-10-15T05:20:04.][v0.15.1] {"code":"ECONNRESET"}
> [2018-10-15T05:20:04.][v0.15.1] ERROR: Telemetry:exception error
> [2018-10-15T05:20:04.][v0.15.1] {"code":"ECONNRESET"}
> ```
> ### Versions
> * _Version_: v0.15.1
> * _OS_: Ubuntu 14.04
> * _SGDB_: MySQL, PostgresSQL...

It seems your development machine isn't connected to interenet, if it's connected, then the problem lies on VS can't resolve the DNS and can't connect to google analytics. I've that problem while a go, and it will gone if it's connected correctly (If you connected to local network, you will be deemed as connected to internet or such, when the request is never fullfil, it cause error)

**Comment by mtxr** [comment]
This has already been changed as seen on #155.

I'll be closing, it will be released soon.
