### ISSUE TITLE
Impala with kerberos support.

### ISSUE THREAD

**Issue by ZuluagaSD** [mtxr/vscode-sqltools#108]
### Issue Type

* [ ] Bug
* [ ] Enhancement 
* [x] Feature Request
* [ ] Question
* [ ] Other

**Comment by mtxr** [comment]
Tracked on #73

**Comment by mtxr** [comment]
Hey @ZuluagaSD , could you please submit a pull request of this feature?

As you are a user that understands the needs for Kerberos, you could follow this structure (https://github.com/mtxr/vscode-sqltools/tree/master/packages/core/dialect/sqlite) to accomplish the same result. Is it ok?

As you can see, it's not difficult, it's almost to define the queries it needs to run.

That's the first step. After creating the dialect, we just need to add it to the UI.

Thanks!

**Comment by ZuluagaSD** [comment]
Done! [https://github.com/mtxr/vscode-sqltools/pull/138](url)

Please let me know if it's ok like that, first time contributing to any project but very happy to help!

**Comment by mtxr** [comment]
I'll review till the end of the week.

@ZuluagaSD thank you! Welcome to the team!

**Comment by mtxr** [comment]
I'll close this issue because I believe will be easier to add support for that using ODBC/JDBC,
So in favor of #44, closed.
