### ISSUE TITLE
After registering duplicate connection name, Connections tree is empty

### ISSUE THREAD

**Issue by dyegoaurelio** [mtxr/vscode-sqltools#1085]
**Describe the bug**
The new option to save passwords on vscode's keystore is registering the connection using only it's name as a unique identifier.

So by creating two connections that uses the SQLTools Driver Credentials, and have the exact same name, database and driver, the extension won't work until one connection is manually erased from the config file

![image](https://user-images.githubusercontent.com/42411160/210853277-b80e84fe-c89d-498c-af84-427a0f63ce62.png)

I think the extension should either prevent duplicate connection names, or add a unique identifier to the connection ID.

**Comment by gjsjohnmurray** [comment]
This problem existed before 0.27.0 and is unrelated to the new capability for drivers to store passwords in the keystore. See https://github.com/mtxr/vscode-sqltools/issues/668#issuecomment-991088634
