### ISSUE TITLE
sql code is highlighted

### ISSUE THREAD

**Issue by generateui** [mtxr/vscode-sqltools#1105]
**Describe the bug**
sql code that is visible in vscode is all highlighted

**To Reproduce**
1. Go to a sql file
2. open it
3. observe all text in the file is selected

**Expected behavior**
text is only highlighted when it is selected

**Screenshots**
https://imgur.com/a/MGxUsYs

**Desktop (please complete the following information):**
 - SQLTools Version [e.g. v0.17.x]
 - VS Code Version: [e.g 1.x.y]
 - OS: [e.g. Windows, Linux, Mac]
 - Driver:
   - [ ] PostgreSQL/Redshift
   - [ ] MySQL/MariaDB
   - [ ] MSSQL/Azure
   - [x] SQLite
   - [ ] Other? Which...
 - Database version: [e.g. MySQL v5.6, PostgreSQL vX...]

**Additional context**
the plugin is now unworkable, as highlighted text completely breaks my normal coding workflow.

as this is related to the setting `sqltools.highlightQuery`, the default of this setting is true which imho should be false  - to stay true to the vscode default behavior.

**Comment by gjsjohnmurray** [comment]
If you change that setting do you get the behaviour that you want?

**Comment by generateui** [comment]
Yes, I guess the default setting is not alike the way vscode handles all the other syntax highlighting behaviors, so it was surprising to me. Selecting text without any user intervention is not that default behvior implemented by vscode (and any other plugin) as far as I have seen. Therefore, I'd argue to change that default setting to not surprise the user.

**Comment by gjsjohnmurray** [comment]
Changing a default usually ends up upsetting at least one existing user who thinks something got broken, so I don't think we're likely to do this.
