### ISSUE TITLE
Unnecessary notifications on every VS Code boot

### ISSUE THREAD

**Issue by fulldecent** [mtxr/vscode-sqltools#1106]
<img width="1471" alt="Screenshot 2023-02-08 at 12 43 43" src="https://user-images.githubusercontent.com/382183/217610024-6e0b030c-4194-4b83-ac05-218588540c50.png">

**Comment by gjsjohnmurray** [comment]
In VS Code's Settings Editor please search for `sqltools.disableNodeDetectNotifications` and set the checkbox.

Does that resolve the issue?

**Comment by fulldecent** [comment]
Thank you. I just tried there. The checkbox was not available, I manually edited the file and then it was not recognized:

![Screenshot 2023-02-09 at 10 42 55](https://user-images.githubusercontent.com/382183/217862744-62e61cac-c32d-4fbe-abb4-bdcf3101d333.png)
![Screenshot 2023-02-09 at 10 42 49](https://user-images.githubusercontent.com/382183/217862766-80038ff2-f1fb-4308-bd88-f11bea867be2.png)

**Comment by gjsjohnmurray** [comment]
What version of the extension are you using?

**Comment by fulldecent** [comment]
0.26.0

![Screenshot 2023-02-09 at 12 40 40](https://user-images.githubusercontent.com/382183/217894521-60bcb362-8db5-42eb-bedc-3cc90dca45a5.png)

**Comment by gjsjohnmurray** [comment]
The current version on Marketplace is 0.27.1

https://marketplace.visualstudio.com/items?itemName=mtxr.sqltools

Please tell VS Code to check for extension updates. If 0.27.1 doesn't show up please confirm you VS Code version details.

**Comment by fulldecent** [comment]
Hmm maybe this new version is hidden on macOS. Or there might be some other configuration bug with VS Code marketplace.


<img width="253" alt="Screenshot 2023-02-10 at 09 54 56" src="https://user-images.githubusercontent.com/382183/218122469-ca6f7394-b584-4be7-8aec-9a8babe91aec.png">

<img width="1478" alt="Screenshot 2023-02-10 at 09 55 55" src="https://user-images.githubusercontent.com/382183/218122724-143393a1-ee00-42bf-acf5-a0936a164ee9.png">

<img width="1478" alt="Screenshot 2023-02-10 at 09 56 01" src="https://user-images.githubusercontent.com/382183/218122744-90e05fd7-1df8-4500-b7bd-d38e1d37506c.png">

<img width="221" alt="Screenshot 2023-02-10 at 09 56 05" src="https://user-images.githubusercontent.com/382183/218122761-5f094539-5b12-4c67-96f9-5b0611280148.png">

<img width="1478" alt="Screenshot 2023-02-10 at 09 56 08" src="https://user-images.githubusercontent.com/382183/218122776-d88d05e8-10dd-478e-806b-2e8c12a52d62.png">

**Comment by gjsjohnmurray** [comment]
Your VS Code version is about 6 months behind the curve. Current is 1.75.1. The most recent version of SQLTools requires 1.72 minimum in order to use a new API.

**Comment by fulldecent** [comment]
Thank you, sorry, that was it! Not sure what's up but I fully uninstalled VS Code and reinstalled and it is good now with your extension working great!
