### ISSUE TITLE
TiDB Driver Support

### ISSUE THREAD

**Issue by Icemap** [mtxr/vscode-sqltools#1112]
**Is your feature request related to a problem? Please describe.**

AFAIK, the SQLTools didn't support TiDB. [TiDB](https://github.com/pingcap/tidb) (/’taɪdiːbi:/, "Ti" stands for Titanium) is an open-source distributed SQL database that supports Hybrid Transactional and Analytical Processing (HTAP) workloads.

**Describe the solution you'd like**
Support it.

**Comment by gjsjohnmurray** [comment]
Community-written driver extensions are welcome. See https://vscode-sqltools.mteixeira.dev/en/contributing/support-new-drivers/

**Comment by Icemap** [comment]
Hi, @gjsjohnmurray. Thanks for your reply!  Can I write the support code in the MySQL driver? Just like the CRDB in the PG driver. TiDB is compatible with MySQL protocol.

**Comment by gjsjohnmurray** [comment]
@mtxr I have requested a review from you, particularly because @Icemap has added TiDB support into the existing MySQL driver rather than contributing a standalone driver.

Seems to me that a benefit of that approach is MySQL / MariaDB users might gain new stuff (SSL support improvements?), but the switch from the mysql package to the mysql2 one brings risks for existing users.

**Comment by Icemap** [comment]
@gjsjohnmurray If the `mysql2` will bring some risks, and it's unacceptable, I can turn it back to the `mysql` lib. But IMO, `mysql` lib wasn't updated for a long while(~3 years). Maybe we can move to the `mysql2`. Please give me your advice! THX!

> **FYI:**
> NPM pages:
> - [mysql](https://www.npmjs.com/package/mysql)
>   ![image](https://user-images.githubusercontent.com/26212551/222880578-6ce14a2e-9600-4cc5-973a-46ce1b6bab40.png)
> - [mysql2](https://www.npmjs.com/package/mysql2)
>   ![image](https://user-images.githubusercontent.com/26212551/222880661-9637e3e3-7052-49c2-a4a8-1e69d8c0168b.png)

**Comment by Icemap** [comment]
Hi @gjsjohnmurray, @mtxr. Anything new?

**Comment by dveeden** [comment]
Shouldn't this be closed now #1113 has been merged? Or are there more changes needed?

**Comment by gjsjohnmurray** [comment]
Closing this now the driver has been published.
