### ISSUE TITLE
Multiple queries fail with: Cannot read properties of undefined (reading 'undefined')

### ISSUE THREAD

**Issue by FrankCoder** [mtxr/vscode-sqltools#1131]
**Description**
Queries with more than one DML statement fail with error: 
**Cannot read properties of undefined (reading 'undefined')**

![Screen Shot 2023-04-07 at 07 37 02](https://user-images.githubusercontent.com/627664/230602602-6721d111-4815-464f-8d08-216aab337abb.png)

**Queries that fail**
```
UPDATE postal_address 
    SET address_1 = 'ACME inc.'
    WHERE person_id = 9;

SELECT * FROM postal_address WHERE person_id = 9;
```

```
USE dbThisSchema;
UPDATE postal_address 
    SET address_1 = 'ACME inc.'
    WHERE person_id = 9;

SELECT * FROM postal_address WHERE person_id = 9;
```

```
UPDATE postal_address 
    SET address_1 = 'ACME inc.'
    WHERE person_id = 9;

SELECT ROW_COUNT();
```

**Queries that succeed**
```
UPDATE postal_address 
    SET address_1 = 'ACME inc.'
    WHERE person_id = 9;
```

```
USE dbThisSchema;
UPDATE postal_address 
    SET address_1 = 'ACME inc.'
    WHERE person_id = 9;
```

**Expected behavior**
Expect result window with tab for result of each query.

**Desktop (please complete the following information):**
 - SQLTools Version  v0.27.1
   - VS Code Version: Version: 1.77.1, 
     - Commit: b7886d7461186a5eac768481578c1d7ca80e2d21
     - Electron: 19.1.11
     - Chromium: 102.0.5005.196
     - Node.js: 16.14.2
     - V8: 10.2.154.26-electron.0
     - OS: Darwin x64 21.6.0
     - Sandboxed: No
 - OS: Mac
 - Driver:
   - [ ] PostgreSQL/Redshift
   - [x] MySQL/MariaDB v0.5.1
   - [ ] MSSQL/Azure
   - [ ] SQLite
   - [ ] Other? Which...
 - Database version: MySQL v8.0.32

**Comment by jpy794** [comment]
I've got the same issue.

**Comment by ncy0817** [comment]
I've got the same issue.

**Comment by windmillcode0** [comment]
I have same issue as well

**Comment by gjsjohnmurray** [comment]
A fix is being tested. See #1140
