### ISSUE TITLE
Using deprecated method new Buffer()

### ISSUE THREAD

**Issue by guanzhongs** [mtxr/vscode-sqltools#1133]
**Describe the bug**
After installed sqltools in vscode, got error in Output > Log(Window)
`2023-04-20 20:18:52.477 [error] [Extension Host] (node:9330) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)`

**To Reproduce**
1. Open a terminal, navigate to OUTPUT > Log(Window)
2. Install SQLTools & SQLTools MySQL/MariaDB Driver in VSCode.
3. Disable the extension SQLTools.
4. The error is eliminated.

**Expected behavior**
No error relates to the extension.

**Screenshots**
![image](https://user-images.githubusercontent.com/22248408/233368994-92d9c1fc-b3b3-4aea-b929-45f10bb135b2.png)

**Desktop (please complete the following information):**
 - SQLTools Version [0.27.1]
 - VS Code Version: [1.76.1]
 - OS: [Windows 10]
 - Driver:
   - [ ] PostgreSQL/Redshift
   - [0.5.1] MySQL/MariaDB 
   - [ ] MSSQL/Azure
   - [ ] SQLite
   - [ ] Other? Which...
 - Database version: [e.g. MySQL v5.6, PostgreSQL vX...]

**Additional context**

**Comment by gjsjohnmurray** [comment]
I think this isn't specific to these extensions. See https://github.com/microsoft/vscode/issues/82524

**Comment by guanzhongs** [comment]
The error is eliminated while disabling the extension.
And see code of the extension at branch dev (ce93cf99cc2355503954fe2879b8ce117e845150):
in file 'vscode-sqltools\packages\util\persistence\serializable-storage.ts'
![image](https://user-images.githubusercontent.com/22248408/233515304-3c02dbfb-55ea-4320-8533-e864d81e91d3.png)

**Comment by gjsjohnmurray** [comment]
You are right. I have submitted a PR to resolve this in the next release.
