### ISSUE TITLE
Does not work in LAN  with no internet connection.(This is with openvscode server)

### ISSUE THREAD

**Issue by woshilaiba** [mtxr/vscode-sqltools#1149]
**Describe the bug**

I have a server in LAN, and it can not access the internet , when i add new connection from the plugin panel, it failed with a message "cannot resolve 19mq80582sdfgdfgsdagasfda.vscode-cdn.net's server IP address coule not be found".

Does it being used only when the there's a internet connection?
Thank you

**To Reproduce**
1. on a pc with no internet connection
2. open the sqltools panel
3. add new connection
4. got the error page "cannot resolve 19mq80582sdfgdfgsdagasfda.vscode-cdn.net's server IP address coule not be found".

**Expected behavior**
I hope it works in LAN with no internet connection.

**Desktop (please complete the following information):**
 - SQLTools Version 0.27.1
 - VS Code Version: 1.77.3
 - OS: Linux
 - Driver:
   - [ ] MySQL/MariaDB

**Comment by gjsjohnmurray** [comment]
Does this also happen if you set `"telemetry.telemetryLevel": "off"` in your VS Code settings?

**Comment by woshilaiba** [comment]
> Does this also happen if you set `"telemetry.telemetryLevel": "off"` in your VS Code settings?

yeah, on window10, I try it when i disconnect the internet at home pc, it works.
tomorrow  i'll try it on my office pc which has no internet.  Thank YOU!

**Comment by woshilaiba** [comment]
Test on my office PC **without internet** connection, and **set "telemetry.telemetryLevel": "off"**:
OS: **windows 7**
VS Code Version: 1.76.2
Driver:
  MySQL/MariaDB
Result:  **PASS**

VS Code Version: OpenVSCode  Server 1.77.3  running on Centos7.6
OS:   **linux**
APP:    **Chrome_x64 109.0.5414 running on Windows7**
Driver:
  MySQL/MariaDB
Result:   **FAILED**
when failed，like this
![image](https://github.com/mtxr/vscode-sqltools/assets/20653360/d10f696d-f3ed-4525-a42b-57de9d021157)

+++++++++++++++++++++++++++++++++++++
Test on my home PC **with internet** connection:
OS:   **windows 10**
VS Code Version: 1.77.3
Driver:
     MySQL/MariaDB
Result:   **PASS**

VS Code Version:  OpenVSCode  Server 1.77.3  running on Debian 11
OS:   **linux**
APP:   **Yandex Browser_x64  23.3.3.719 running on Windows10**
Driver:
  MySQL/MariaDB
Result:  **PASS**

when success，like this
![20230512155114](https://github.com/mtxr/vscode-sqltools/assets/20653360/75875efd-16be-445f-8592-ab41f2439585)


![image](https://github.com/mtxr/vscode-sqltools/assets/20653360/08bdd503-a768-4b50-b3bf-056c438dd5eb)


+++++++++++++++++++++++++++++++++++++++++


**seems none of telemetry‘s bussiness**  （maybe the webview？）
any idea?

**Comment by woshilaiba** [comment]
> VS Code Version: OpenVSCode Server 1.77.3 running on Debian 11 
>

the openvscode server is from  https://github.com/gitpod-io/openvscode-server/releases

**Comment by gjsjohnmurray** [comment]
Maybe https://github.com/gitpod-io/openvscode-server/discussions/383 is relevant?

**Comment by woshilaiba** [comment]
> Maybe [gitpod-io/openvscode-server#383](https://github.com/gitpod-io/openvscode-server/discussions/383) is relevant?

Thank you!
