### ISSUE TITLE
Error loading plugin

### ISSUE THREAD

**Issue by Austin1** [mtxr/vscode-sqltools#1150]
**Describe the bug**
So, this bug applies to a community adapter for Teradata, but I've tried tearing it apart and cannot understand why or where this error comes from and so I'm hoping on this board someone could maybe point me in the right direction.

The specific error is 
```
ERROR (ext): ERROR: Error loading plugin SQLTools Teradata Driver Plugin Request ls/RegisterPlugin failed with message: Error in native callback, {"code":-32603}
    ns: "error-handler"
```

**To Reproduce**
1. Using a Macbook Pro with apple silicon, install [ SQL Tools and SQL Tools for Teradata](https://marketplace.visualstudio.com/items?itemName=scriptpup.sqltools-teradata-driver)
2. Open VS Code
3. Receive errors

**Expected behavior**
Plugin loads successfully

**Screenshots**
Issue with logs and screenshots: https://github.com/ScriptPup/sqltools-teradata-driver/issues/24

**Desktop (please complete the following information):**
 - SQLTools Version [e.g. v0.17.x]
 - VS Code Version: [e.g 1.x.y]
 - OS: [e.g. Windows, Linux, Mac]
 - Driver:
   - [ ] PostgreSQL/Redshift
   - [ ] MySQL/MariaDB
   - [ ] MSSQL/Azure
   - [ ] SQLite
   - [X ] Other? SQLTools Teradata Driver 0.3.4
 - Database version: [e.g. MySQL v5.6, PostgreSQL vX...]

**Additional context**
Issue with logs and screenshots: https://github.com/ScriptPup/sqltools-teradata-driver/issues/24

**Comment by gjsjohnmurray** [comment]
Continuing on https://github.com/ScriptPup/sqltools-teradata-driver/issues/24
