### ISSUE TITLE
Allow user to disable auto formatting `formatOnSave` and `formatOnPaste`

### ISSUE THREAD

**Issue by abenhamdine** [mtxr/vscode-sqltools#116]
### Issue Type

* [ ] Bug
* [x] Enhancement 
* [ ] Feature Request
* [ ] Question
* [ ] Other

### Prerequisites (For bugfixes)

* [ ] Are you running the latest version?
* [ ] Did you check the logs?
* [ ] Did you check the Setup?

### Description

Thx for this useful extension.
Anyway, it would be great to be able to disable automatic formatting, because my formatting rules are quite different.

### Versions

- *Version*: v0.15.1
- *OS*: ...
- *SGDB*: PostgresSQL...

**Comment by mtxr** [comment]
Hey @abenhamdine, actually auto formatting is a VSCode feature, not SQLTools.

Could you please check if you have `formatOnSave` and `formatOnParte` active in you vscode settings?

**Comment by abenhamdine** [comment]
> Could you please check if you have formatOnSave and formatOnParte active in you vscode settings?

Indeed yes, but autoformatting has never been applied on .sql files in vscode for me (and it was fine for us because we have our own sql style rules). it's just after have installed your extension that the autoformatting began to apply.

**Comment by mtxr** [comment]
Right, it's formatting because SQLTools register as a format tool. 

I'll add this option, but it will be enabled by default since you are the first that noticed that, ok?

Thanks @abenhamdine

**Comment by abenhamdine** [comment]
agree. Thanks to you @mtxr !

**Comment by mtxr** [comment]
@abenhamdine you can achieve this by settings option `formatLanguages` to `[]`.

Try it and let me know. It's better than having a option to complete disable the formatting.

Currently there is no way in vscode to disable just auto format via extension api. So for now, I'll keep it like this to avoid bigger issues, ok?

Let me know if this solves your problem.

Thanks.

**Comment by joaoponceleao** [comment]
Hi,
This doesn't seem to be working. The only way I can disable formatting for sql files is by disabling the extension....

**Comment by ufukty** [comment]
Idk about `formatLanguages`. But I find another way.

Open VS Code settings with command plate : `Preferences: Open Settings (JSON)`

Add that section to appropriate place:

```json
"[sql]": {
    "editor.formatOnSave": false,
    "editor.formatOnPaste": false,
    "editor.formatOnType": false
}
```

**Comment by gjsjohnmurray** [comment]
Please make sure you restart VS Code after you set `"sqltools.formatLanguages": [],`
