### ISSUE TITLE
Using http_proxy with the plugin

### ISSUE THREAD

**Issue by adbdkb** [mtxr/vscode-sqltools#1164]
**Unable to connect to Athena from the extension**

I am trying to set-up a VSCode connection using SQLTools to connect to Athena. This is connected to issue # 36 ( https://github.com/kovihq/sqltools-athena-driver/issues/36 )

This is my set-up
Athena-in-VSCode

![](https://user-images.githubusercontent.com/26495406/239364337-b665bdde-53f1-4d37-97fc-7be4d38b26c3.png)

I have http_proxy defined and also tried setting up proxy in VSCode - but get the same error

![](https://user-images.githubusercontent.com/26495406/239364478-00052f4a-eac0-47ee-a0cd-d336058ce48c.png)

VSCode_Proxy_settings
When working with a colleague of mine when he also was trying to connect - we came to this conclusion

it is definately a proxy issue though, you wont be able to connect to the athena endpoint, without a hardcoded proxy in VScode, and that would explain all 3 scenarios: 1 - off network (no proxy needed) works, 2 - on-network terminal (proxy configured) works, 3 - on-network vscode, cannot conenct to the Athena endpoint

He also looked at the extension code and said 'ask for the plugin developer team to use http_proxy settings from VSCode'

 Is is possible to add it to the extension, so it could be used when a proxy needs to be defined?

**Desktop (please complete the following information):**
 - SQLTools Version:  v0.27.1
 - VS Code Version: 1.79.1
 - OS: Windows 10
 - Driver:
   - [ ] Other? ATHENA JDBC Driver

 - Database version: [e.g. Athena ]

**Additional context**

**Comment by gjsjohnmurray** [comment]
This needs to be fixed in the driver. I hope the author of that extension picks up the issue you have opened on that repo.

**Comment by adbdkb** [comment]
Ok.  There has been no response or movement on that one

And one of the tickets I saw of this project where it was commented that making use of the proxy set-up in vscode can  be done in this extension itself, so was hoping it will be picked up here and fixed.  

Thanks for responding though.
