### ISSUE TITLE
[connection].session.sql file opens very eagerly

### ISSUE THREAD

**Issue by archiewood** [mtxr/vscode-sqltools#1169]
Not sure this is a bug as such - more a UX thing

I normally have SQL files open already that I want to run when I start using SQLtools.

Then I want to check for a table name or something so I open the sidebar explorer and the [connection].session.sql file opens over the top of them.

## Repro

- set up a connection
- open the sidebar
- click on the connection to explore the db

Snowflake driver

## Expected

- No [connection].session.sql  file opens

## Actual

- [connection].session.sql  file opens and I have to close it before running my SQL

![CleanShot 2023-06-21 at 18 53 31](https://github.com/mtxr/vscode-sqltools/assets/58074498/b5d4e189-5288-41d1-9b15-c9bbeb839196)

## Proposals
- Setting to configure this file opening or not
- ?Turn this off by default

**Comment by gjsjohnmurray** [comment]
Does https://github.com/mtxr/vscode-sqltools/pull/1161 (just merged and not yet published) help you?

**Comment by archiewood** [comment]
I don't think so, I still want to be able to see the query for any queries I run, I just don't want to be presented with a blank file when I connect to the db

**Comment by gjsjohnmurray** [comment]
Please try with `"sqltools.autoOpenSessionFiles": false`

**Comment by archiewood** [comment]
Ah that's the setting I need, thanks.

I'd propose that this be set to false by default, but if other people find it helpful I understand!

Happy to close this issue now or leave it open if you want to get feedback on this.

**Comment by gjsjohnmurray** [comment]
Changing defaults can be unpopular, so I'm going to close this. Doing that won't prevent further feedback though.
