### ISSUE TITLE
Describe Table / Show Table Records only works for first connection

### ISSUE THREAD

**Issue by jbelford** [mtxr/vscode-sqltools#119]
**Describe the bug**
If I connect to a database and then run show table records or describe table commands I can select a table that is in that database.

However, if I then connect to another database and run this command again it will still show tables for the first connection and also throw an error if I try to choose any of them.

This is not how this used to behave.

**To Reproduce**
1. Create two connections
2. Connect to one connection
3. Connect to another connection
4. Show Table Records / Describe Table (Commands Only)

**Expected behavior**
You will be only provided tables from the first connection and will not be provided any tables from the second.

This renders the current version of the extension pretty unusable for me as the only work around is to either restart vscode then connect to the db I want or to use the GUI which is a pain to scroll through hundreds of tables.

**Comment by mtxr** [comment]
Will be release in 10m.

Thanks @jbelford!

**Comment by jbelford** [comment]
Wow that was quick! Thanks @mtxr!

**Comment by mtxr** [comment]
:D It was simple, so just fixed that.

If the extension helps you, please consider a donation, support or just a review on the marketplace or a GitHub star and help me to keep the development.

Stars and reviews are really important too. ;)
