### ISSUE TITLE
Add newline at the end of a file

### ISSUE THREAD

**Issue by 20manas** [mtxr/vscode-sqltools#1192]
**Is your feature request related to a problem? Please describe.**
In the POSIX standard, a line is defined as: `A sequence of zero or more non- <newline> characters plus a terminating <newline> character`. The formatter should follow this standard and add a newline at the end of a file.

For example, in git diff, when a newline is not present at the end of a file, it shows up like this:
![image](https://github.com/mtxr/vscode-sqltools/assets/14952218/cad3a0e9-7da9-4cd7-b742-43b92b17f286)
which is quite unnecessary.

With a newline at the end of a file, git diff shows this:
![image](https://github.com/mtxr/vscode-sqltools/assets/14952218/e750c9bc-2695-4546-bd8a-b4b1dc9ccd18)

**Describe the solution you'd like**
Add a newline at the end of a file, following the POSIX standard (unless `linesBetweenQueries` is `preserve`?).

**Describe alternatives you've considered**
None

**Additional context**
https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline

**Comment by DavidS-ovm** [comment]
You can set `files.insertFinalNewline` in VS Code settings to get this behaviour.

**Comment by 20manas** [comment]
> You can set `files.insertFinalNewline` in VS Code settings to get this behaviour.

Alright, this is working with the formatter. Thanks!
