### ISSUE TITLE
sqltools redshift driver not available in extensions

### ISSUE THREAD

**Issue by vpfgs** [mtxr/vscode-sqltools#1194]
**Describe the bug**
The redshift driver for sqltools does not show up in vscodium marketplace when typing "ext install kj.sqltools-driver-redshift".
This is official page for the driver: https://marketplace.visualstudio.com/items?itemName=kj.sqltools-driver-redshift

**To Reproduce**
1. CTR + P
2. enter "ext install kj.sqltools-driver-redshift"
3. Redshift driver for sqltools does not show in the marketplace options
4. One can see the 2 other drivers (clickhouse and databricks) are listed but not Redshift (see pdf attachment)
[vscodium_redshift_maprketplace_issue.pdf](https://github.com/mtxr/vscode-sqltools/files/12186230/vscodium_redshift_maprketplace_issue.pdf)

**Expected behavior**
The aws redshift driver is listed as a community driver.
The driver would be available for installation in the marketplace.

**Desktop (please complete the following information):**
 - SQLTools Version 0.28.0
 - VSCodium Version e.g 1.x.y
 - OS: Ubuntu 20.04
 - Driver:
   - [ ] PostgreSQL/Redshift
   - [ ] MySQL/MariaDB
   - [ ] MSSQL/Azure
   - [ ] SQLite
   - [X] Other? Redshift
 
**Additional context**
I think the issue is the listing in the marketplace...

**Comment by vpfgs** [comment]
I forgot to specify vscodium's version: it is 1.80.1, release 23194

**Comment by gjsjohnmurray** [comment]
Please raise this with the author of the extension. I think vscodium uses https://open-vsx.org/ as its marketplace, so the author would need to publish it there as well.

Alternatively, download the VSIX from https://marketplace.visualstudio.com/items?itemName=kj.sqltools-driver-redshift and install it manually.
