### ISSUE TITLE
pg_hba error when connecting to Redshift

### ISSUE THREAD

**Issue by ginokhumz** [mtxr/vscode-sqltools#1206]
**Describe the bug**
There is an error when I try connect to a Redshift database. It fails with the following error 
`no pg_hba.conf entry for host "::ffff:10.81.8.2", user "tes_dev", database "dev", SSL off`
I have added that host to my pg_hba.conf file located at `/usr/local/var/postgres/pg_hba.conf ` and it still won't work.

I also use DBeaver and it connects to that Redshift database just fine. 
I can connect to other Postgres databases without a problem.

**To Reproduce**
1. Go to `SQLTOOLS`
2. Add a new connection and enter Reshift connection details 
3. Click on Test Connection

**Expected behavior**
To connect to the database 

**Screenshots**
![Screenshot 2023-08-24 at 2 21 35 PM](https://github.com/mtxr/vscode-sqltools/assets/25409210/d2a9c54b-86ab-4c72-8d67-407643c81ceb)
![Screenshot 2023-08-24 at 2 19 32 PM](https://github.com/mtxr/vscode-sqltools/assets/25409210/232d2c4e-a06e-4a99-97b7-b1521893dec4)

**Desktop (please complete the following information):**
 - SQLTools Version v0.28.0
 - VS Code Version: 1.81.1 
 - OS: [ Mac]
 - Driver:
   - [ x] PostgreSQL/Redshift
   - [ ] MySQL/MariaDB
   - [ ] MSSQL/Azure
   - [ ] SQLite
   - [ ] Other? Which...
 - Database version:

**Comment by gjsjohnmurray** [comment]
You are using the community-contributed driver. Please raise your issue at https://github.com/kj-9/sqltools-redshift-driver
