### ISSUE TITLE
In Business Application Studio : Driver SAPHana is not installed.

### ISSUE THREAD

**Issue by Mansi190594** [mtxr/vscode-sqltools#1207]
**Describe the bug**
I am trying to debug my CAP Project deployed to hana db. When trying to connect the instance for debugging it says : Driver SAPHana is not installed.

**To Reproduce**
1. Create A CAP application Project
2. Create a Js file in SRV folder , try putting a debugger & run with debugging .
3. Click on  connect as it will be in red in the bottom line
4. After selecting the hana DB, it says : **Driver SAPHana is not installed.** althogh it is installed globally.

**Expected behavior**
connection should be successful.
**Screenshots**

**Desktop (please complete the following information):**
 - SQLTools Version [e.g. v0.17.x]
 - VS Code Version: [e.g 1.x.y]
 - OS: [e.g. Windows, Linux, Mac]
 - Driver:
   - [ ] PostgreSQL/Redshift
   - [ ] MySQL/MariaDB
   - [ ] MSSQL/Azure
   - [ ] SQLite
   - [ ] Other? Which...
 - Database version: [e.g. MySQL v5.6, PostgreSQL vX...]

**Additional context**

**Comment by gjsjohnmurray** [comment]
Please raise this with the author of the driver extension, as they will be best able to investigate.
