### ISSUE TITLE
Screenshots?

### ISSUE THREAD

**Issue by goyalyashpal** [mtxr/vscode-sqltools#1208]
Hi! i think having screenshots will help a lot.

oh wait, there are screenshots at https://vscode-sqltools.mteixeira.dev/en/features/codelens for example, it's just not loading well.

**Comment by goyalyashpal** [comment]
hi @gjsjohnmurray the image is still not loading. there was a problem with serving BLOB resources via gh. 

is it loading at ur side??

<img src="https://github.com/mtxr/vscode-sqltools/assets/19423063/58fe469d-b772-4971-9ca9-4c1a498e1978" width=370px/>

**Comment by gjsjohnmurray** [comment]
https://vscode-sqltools.mteixeira.dev/en/features/codelens works fine for me:

![image](https://github.com/mtxr/vscode-sqltools/assets/6726799/f78e96f6-5fc6-4dd1-8e68-76df954f668b)
