### ISSUE TITLE
Add filter/search box api support to connection explorer

### ISSUE THREAD

**Issue by mtxr** [mtxr/vscode-sqltools#121]
**Describe the solution you'd like**
As an user I want to search columns and tables in the connection explorer.

**Additional context**
Microsoft/vscode/issues/50062 Use native VSCode API

**Comment by benyaminl** [comment]
I agree no more. It would be great anyway !

**Comment by mtxr** [comment]
Vscode recently added this to custom tree views. But the community is not happy it their solution.

Try to focus on connections explorer view and start typing what you are looking for. Let me know what you think. Honestly I don't like it

**Comment by mtxr** [comment]
Closing. This issue is more than 6 months old. VSCode team doesn't seem to be trying this soon.
