### ISSUE TITLE
Keyboard shortcut to execute commands

### ISSUE THREAD

**Issue by mrbing47** [mtxr/vscode-sqltools#1210]
As VS Code is a keyboard extension IDE, it breaks my flow when I when to grab my mouse to select "Run the command on active connection". 

It would be a nice feature to add keyboard shortcut (like `CTRL + ENTER`) to run the query there my cursor is currently at for the sake of convenience.

**Comment by gjsjohnmurray** [comment]
Some keyboard shortcuts are already added by the extension. Search for `sqltools` in the Keyboard Shortcuts editor to see them.

You could add shortcuts of your own to run other commands for which the above search doesn't show a default keybinding. For example, the command `SQLTools Connection: Run Current Query` would do what I think you want.

Alternatively, bind `Show CodeLens Commands For Current Line` to a keyboard shortcut, then use it to access any CodeLens from the keyboard. But be aware that VS Code currently has [a bug](https://github.com/microsoft/vscode/issues/191908) that means you will have to press Enter twice to trigger the selected CodeLens.

**Comment by aodendaal** [comment]
To save the next person looking `Ctrl+E Ctrl+E` for **SQLTOOLS Connection: Run Selected Query**.

**SQLTOOLS Connection: Run Current Query** is unmapped.

**Comment by iTrooz** [comment]
~~unfortunately, "Run Selected Query." is not working for me (does nothing)~~ EDIT: it works when selecting the text, but it has the same problem of triggering in every editor, e.g. ones with code

"Run current query" seem more appropriate for my use case, but mapping it to Ctrl+Enter is problematic because then the shortcut will be global: it will run in any editor, and even outside editors.

I'm not familiar with it, but maybe there is a way to constraint when this shortcut can be triggered using the vscode shortcut "When expression", so that it only triggers in sqltools editors ?

**Comment by iTrooz** [comment]
I'd also argue to reopen this issue since this should be the default behaviour

**Comment by gjsjohnmurray** [comment]
Maybe `editorLangId == sql` in the when clause?

**Comment by gjsjohnmurray** [comment]
More info at https://code.visualstudio.com/api/references/when-clause-contexts

**Comment by gjsjohnmurray** [comment]
> I'd also argue to reopen this issue since this should be the default behaviour

Extension-added keybindings can be controversial, doubly so if they get added later and cause existing users' VS Codes to start behaving differently because of clashes with users' own keybindings (or those from other extensions).

**Comment by iTrooz** [comment]
> Maybe `editorLangId == sql` in the when clause?

It works ! Thanks

**Comment by caiohamamura** [comment]
I actually think that something like F5 should be enough and would probably not conflict with other user keybindings as F5 is supposed to do debugging by default so developers avoid overriding `F5`, specially for global scope, maybe for some restricted scopes. Furthermore for plain SQL there are no debugging solution (for functions there are, but not for plain SQL statements), so `F5` should be fine.

I would bet that `F5` would be one of the first shortcuts developers would try as it is pretty default for any other programming language to execute/debug, so in my opinion it should be safe and a pretty good enhancement for this plugin to create a shortcut for:

```
{
        "key": "F5",
        "command": "sqltools.executeCurrentQuery",
        "when": "editorTextFocus && editorLangId == 'sql'"
}
```

What do you think?

**Comment by jbruneFei** [comment]
> I actually think that something like F5 should be enough and would probably not conflict with other user keybindings as F5 is supposed to do debugging by default so developers avoid overriding `F5`, specially for global scope, maybe for some restricted scopes. Furthermore for plain SQL there are no debugging solution (for functions there are, but not for plain SQL statements), so `F5` should be fine.
> 
> I would bet that `F5` would be one of the first shortcuts developers would try as it is pretty default for any other programming language to execute/debug, so in my opinion it should be safe and a pretty good enhancement for this plugin to create a shortcut for:
> 
> ```
> {
>         "key": "F5",
>         "command": "sqltools.executeCurrentQuery",
>         "when": "editorTextFocus && editorLangId == 'sql'"
> }
> ```
> 
> What do you think?

New here, where do you add this string?

**Comment by iTrooz** [comment]
Ctrl+Shift+P ->  "Open keyboard shortcuts (JSON)"
