### ISSUE TITLE
Completion Languages in php files

### ISSUE THREAD

**Issue by raicabogdan** [mtxr/vscode-sqltools#1212]
**Describe the bug**
Well I just installed and setup the extension with Mysql driver. I tested it to see it working with normal in a normal .sql file.
The autocompletion works as expected.
Then I tried adding `php` to the completion languages in the extension settings and checked to see if it works in a simple
`$query = "SELECT * FROM tablename";`
but the auto completion does not work inside the variable string.
Perhaps I misunderstood the specific setting and it is not intended for this usage?

**To Reproduce**
1. Go to extension settings
2. Add 'php' to the Completion Languages
3. Test in a php file

**Expected behavior**
Expected auto completion to occur within the variable SQL string.

**Desktop (please complete the following information):**
 - SQLTools Version [e.g. v0.28.0]
 - VS Code Version: [e.g 1.82.0]
 - OS: Linux
 - Driver:
   - [ ] PostgreSQL/Redshift
   - [x] MySQL/MariaDB
   - [ ] MSSQL/Azure
   - [ ] SQLite
   - [ ] Other? Which...
 - Database version:  MySQL v5.7

**Comment by PrezesE** [comment]
Having the same problem, and wondering if maybe any solution other than writing sql queries in separate file has been found or maybe if this is unintended behavior and will change in the future?
