### ISSUE TITLE
 reset the SQLTools Driver Credentials

### ISSUE THREAD

**Issue by prevy** [mtxr/vscode-sqltools#1217]
When I'm setting up the database connection using SQLTools Driver Credentials, if I enter the wrong password, I'm unable to re-enter the correct password. How can I clear the incorrect SQLTools Driver Credentials record to allow me to input the correct password again?

**Comment by gjsjohnmurray** [comment]
If you click on the Accounts icon near the bottom of the Activity Bar, does its menu show an entry for the bad credentials? If so, does this have a submenu that lets you sign out?

**Comment by prevy** [comment]
Yes, this method can indeed solve the problem. Thank you for your assistance.
> If you click on the Accounts icon near the bottom of the Activity Bar, does its menu show an entry for the bad credentials? If so, does this have a submenu that lets you sign out?

**Comment by prevy** [comment]
The issue mentioned above has been resolved using the provided solution.
