### ISSUE TITLE
No tables or views in tree using Databricks driver.

### ISSUE THREAD

**Issue by cyaris** [mtxr/vscode-sqltools#1236]
I am able to query as expected, but when I go to the tree it says `Nothing here` beneath Tables and Views.

<img width="365" alt="Screenshot 2023-11-02 at 11 50 28 AM" src="https://github.com/mtxr/vscode-sqltools/assets/35279417/66284b54-ed2a-4016-bb5a-0b656950f367">

I am on the newest version of SQLTools and the Databricks driver.

**Comment by gjsjohnmurray** [comment]
Please raise this with the author of the Databricks driver. One way is to use the "Report Issue" option from VS Code's "Help" menu, then choose "An extension" in the second dropdown and the Databricks driver on the third one.

**Comment by cyaris** [comment]
Understood. Thank you!
