### ISSUE TITLE
Show columns in the pane

### ISSUE THREAD

**Issue by Shujee** [mtxr/vscode-sqltools#125]
Would it be possible to list table columns under each table in the hierarchy? This is how it is displayed in most SQL tools that I have worked with. Currently I have to use Describe command which is not as efficient.

**Comment by mtxr** [comment]
Ref: #cnada

**Comment by Shujee** [comment]
mmmm?

**Comment by mtxr** [comment]
Don't worry. It's a ref for the task manager I'll start to use.

Regarding that, that you be fixed today

**Comment by Shujee** [comment]
Ah, thanks.

**Comment by mtxr** [comment]
Related to #124.

**Comment by mtxr** [comment]
@Shujee which version are you using?

Actually we have this in the connection explorer.

![image](https://user-images.githubusercontent.com/707561/52185515-7687bc80-2807-11e9-9db3-cec2fa9591f1.png)

Is this what you meant?

We had a bug in the previous release and it was not working, but version 0.16.6 already fixed that.

Please, if this is not what you mean, please fell free to reopen the issue.

Thanks!

**Comment by Shujee** [comment]
Yes. This is what I was talking about. At the time of writing, the pane was not showing list of columns under each table, but it looks like this has been fixed now. I can see them now.

Thanks again.
