### ISSUE TITLE
Not being able to save connection or add manually

### ISSUE THREAD

**Issue by felipedalton** [mtxr/vscode-sqltools#1251]
**Describe the bug**
When trying to add a trino connection I'm getting the following error: `Unable to write file '/.vscode/settings.json' (Unknown (FileSystemError): Error: EROFS: read-only file system, mkdir '/.vscode')
`

**To Reproduce**
1. Go to SQL Tools extension on sidebar
2. Click on Add Connection
3. Fill in connection settings
4. Click on save connection

**Expected behavior**
Connection should be saved with details registered into settings.json

**Screenshots**
![image](https://github.com/mtxr/vscode-sqltools/assets/77359655/e85dfc79-d831-425c-a27a-6c09955ba5f7)

**Desktop (please complete the following information):**
 - SQLTools Version v0.28.1
 - VS Code Version: 1.84.2 
 - OS: MacOS Sonoma
 - Driver:
   - Trino

**Additional context**
If I insert all details manually I'm able to see the database, but not sure if I'm getting the manual setup correctly because I can't seem to connect (although when utilizing the UI and clicking on Test Connection it does work - but cannot save)

**Comment by gjsjohnmurray** [comment]
Are you able to change VS Code settings at the User level and get those changes persisted?

**Comment by felipedalton** [comment]
Hello @gjsjohnmurray i believe I can, but I'm not sure how to do it, are you able to give me some tips on where I'd be able to do it? I'm kinda new to VSCode coming from R

**Comment by gjsjohnmurray** [comment]
Please see https://code.visualstudio.com/docs/getstarted/settings and particularly https://code.visualstudio.com/docs/getstarted/settings#_settingsjson

**Comment by felipedalton** [comment]
Thank you! Though I was not able to use the UI i could find the correct json file and add the connection manually, not it is working

**Comment by gjsjohnmurray** [comment]
Perhaps a bug in the Trino driver.
