### ISSUE TITLE
Expose the SQL formatter as a command line tool

### ISSUE THREAD

**Issue by sgronblo** [mtxr/vscode-sqltools#1260]
**Is your feature request related to a problem? Please describe.**
We are looking for a decent SQL formatter that we could use to format all our SQL files. SQLTools seems quite ok. But we wouldn't like to mandate that all members _must_ use VSCode.

**Describe the solution you'd like**
It would be great if the formatter was exposed as a command line tool so it could be used by non-VSCode users or automatically as part of a CI build.

**Describe alternatives you've considered**
I tried googling for "vscode sqltools command line"

**Additional context**
Nothing much to add

**Comment by rangedsp** [comment]
The formatter is a npm package, it should be quite simple to build a script that calls the formatter package: https://github.com/mtxr/vscode-sqltools/tree/dev/packages/formatter
