### ISSUE TITLE
Disable node runtime popup

### ISSUE THREAD

**Issue by fonnesbeck** [mtxr/vscode-sqltools#1263]
It would be nice to be able to disable the node runtime detected popup that appears every time I start VSCode with the SQLTools extension enabled. Its fine to get a popup when there is an issue, but announcing the runtime that is detected every time I start up the editor is too much, especially when the popup has to be manually closed.

**Comment by gjsjohnmurray** [comment]
Is the `sqltools.disableNodeDetectNotifications` setting what you need?

**Comment by fonnesbeck** [comment]
Sounds right. Thanks!
