### ISSUE TITLE
Not able to connect to AWS RDS postgresql

### ISSUE THREAD

**Issue by jqknono** [mtxr/vscode-sqltools#1264]
**Describe the bug**
Can not connect to AWS RDS postgresql.

**To Reproduce**

1. Connect to AWS RDS postgresql with ssl

**Expected behavior**
Should connect success.

**Desktop (please complete the following information):**
 - SQLTools Version: 0.28.1
 - VS Code Version: 1.85.1
 - OS: Windows
 - Driver:
   - [X] PostgreSQL/Redshift: 0.5.2
 - Database version: PostgreSQL 15.4

**Additional context**
Related to #799 and #72

**Comment by jqknono** [comment]
To connect  to AWS RDS, I need to set this TWO:

- SSL: Enabled
- rejectUnauthorized: **Check And Uncheck**. This is important, and make a difference.

The `"rejectUnauthorized": false` should fill in the setting explicitly.

```json
{
  "pgOptions": {
    "ssl": {
      "requestCert": true,
      "rejectUnauthorized": false
    }
  },
  "previewLimit": 50,
  "server": "XXX",
  "port": 5432,
  "driver": "PostgreSQL",
  "name": "aws.rds.starter",
  "username": "XXX",
  "database": "XXX"
}
```

**Comment by jqknono** [comment]
The document said to set the `rejectUnauthorized` with the default value "true", but no action did that.
Fixed with modifying the schema `connection.schema.json`, set the field `rejectUnauthorized` as required with default value `false`.

**Comment by gjsjohnmurray** [comment]
#1265 will resolve this in the next release of the driver.

**Comment by swfc** [comment]
> To connect to AWS RDS, I need to set this TWO:
> 
> * SSL: Enabled
> * rejectUnauthorized: **Check And Uncheck**. This is important, and make a difference.
> 
> The `"rejectUnauthorized": false` should fill in the setting explicitly.
> 
> ```json
> {
>   "pgOptions": {
>     "ssl": {
>       "requestCert": true,
>       "rejectUnauthorized": false
>     }
>   },
>   "previewLimit": 50,
>   "server": "XXX",
>   "port": 5432,
>   "driver": "PostgreSQL",
>   "name": "aws.rds.starter",
>   "username": "XXX",
>   "database": "XXX"
> }
> ```

This fixed my problem with connecting to AWS RDS MySQL 8 server. Thank you!
