### ISSUE TITLE
Interrupting a running query

### ISSUE THREAD

**Issue by gyohza** [mtxr/vscode-sqltools#127]
Hi!

Can I request for any means of killing a running query? As it stands, the only way I can do so is through MySQL Workbench. If there is a way that I'm not aware of I must humbly ask for your guidance (quite new to VS Code, tbh).

I want to migrate out of Workbench and operate everything I can through VS Code and for all its worth, this extension rocks, but some queries turn out to be slower than I predict and I constantly need to kill them to avoid compromising server performance. It's currently the only thing that's preventing me from retiring good ol' Workbench.

Thanks in advance.

**Comment by benyaminl** [comment]
Sometimes I just request a new one, or execute new query and it just stop. For now at least.

**Comment by mtxr** [comment]
That's true. For now there is no way to interrupt a query. I'll take a look at this but I cant do it right now.

**Comment by mtxr** [comment]
I found ways to cancel/kill running queries on potgresql and mysql, but it's more a workaround than a real solution.

It uses queries to kill queries, so i should change to code a bit to keep the pid of a running query to be used when user ask to cancel.

It doesnt look neat, but I believe it works.

See: https://github.com/mysqljs/mysql/issues/137

What do you think @gyohza, @benyaminl ?

For most cases `connectionTimeout` property should be enough. Did you try it?

It automatically kills the connection after exceeding `connectionTimeout`.

**Comment by gyohza** [comment]
@mtxr - you mean like, issuing `KILL` command? Correct me if I'm wrong, but then it would be a two-step workaround:
1. Run `SHOW FULL PROCESSLIST` and take note of the current query's PID;
2. Run `KILL` + the PID.

It would definitely work, I believe (can't test it right now, but I'm used to killing other people's queries in Workbench this way and it works), but think of the actual workload when you're building a complex query - you would have to paste your query somewhere else or open a new tab to avoid losing it, then get the PID and then kill it, only to do it again afterwards (not uncommon when you're optimizing a bulky query). It's impractical.

Any suggestions on how to make the process just a bit more practical?

**Comment by mtxr** [comment]
@gyohza now suggestions so far.

Also, I would like to do that for all dialects, but I don't see an easy way of doing this.

I need to dig deeper because I just know how to do this for MySQL now

**Comment by mtxr** [comment]
I'll close this issue for now.

I can't add this support for all dialects. If someone wants to try it and send PRs, I'll be glad!

But for now I'll try to focus on enhance the results screen features and finish the autocomplete that is stuck for a while
