### ISSUE TITLE
Can't edit doc page

### ISSUE THREAD

**Issue by fuzl-llc** [mtxr/vscode-sqltools#1272]
**Describe the bug**

I can't edit the bookmarks page to fix a typo.

**To Reproduce**

On the https://vscode-sqltools.mteixeira.dev/en/features/bookmarks page I click the "Edit this page" link to fix the typo where "assing a keybind" should be "assign a keybinding" and I get this:

404 - page not found
The dev branch of vscode-sqltools does not contain the path docs/src/pages/en/features/bookmarks.html.mdx.

**Expected behavior**

I should be able to edit the page.

**Comment by gjsjohnmurray** [comment]
Please use the procedure documented(!) at https://vscode-sqltools.mteixeira.dev/en/contributing/documentation

We will remove the 'Edit this page' option.
