### ISSUE TITLE
SQLTools collapsible sections are under "Source Control" and the SQLTools tab is missing

### ISSUE THREAD

**Issue by natperron** [mtxr/vscode-sqltools#1279]
**Describe the bug**
Historically, SQLTools had it's own tab/icon on the left that included its own sections (connections, query history and bookmarks). Now, those sections are under "Source Control" for some reason, which doesn't make sense.

**To Reproduce**
1. Open VSCode
2. Notice the lack of the tab for SQLTools
3. Go to "Source Control" tab
3. Notice that SQLTools sections are present

**Expected behavior**
The sections about SQLTools should be in their own section, as it was before

**Screenshots**
![image](https://github.com/mtxr/vscode-sqltools/assets/68925286/78c51917-237c-4884-8246-4c8dccec1e8d)

**Desktop (please complete the following information):**
 - SQLTools Version [e.g. v0.28.1]
 - VS Code Version: [e.g 1.85.2]
 - OS: Linux (Arch Linux)
 - Driver:
   - [x] PostgreSQL/Redshift
   - [ ] MySQL/MariaDB
   - [ ] MSSQL/Azure
   - [ ] SQLite
   - [ ] Other? Which...
 - Database version: PostgreSQL

**Additional context**
I noticed this issue about a week ago, but it was probably like that for a bit longer (perhaps a few more weeks earlier). It took me a while to even find where they were, as I thought they were simply removed.

**Comment by gjsjohnmurray** [comment]
It looks like you maybe accidentally dragged the SQLTools icon from Activity Bar and dropped it into Side Bar while that was displaying Source Control.

To revert this please right-click on each of the SQLTOOLS: xxx sections in your screenshot and choose `Reset Location`.

**Comment by natperron** [comment]
@gjsjohnmurray Not sure how that happened in the first place, but thank you! That worked
