### ISSUE TITLE
Issue with SQL tools not working with Teradata connector

### ISSUE THREAD

**Issue by TrueRasqal** [mtxr/vscode-sqltools#1284]
I currently installed the SQL Tools extension and the SQLTools Teradata Driver Plugin but have been receiving errors. When trying to create a new connection, the finder is unable to locate the driver plugin. I receive the error: 

Error loading plugin SQLTools Teradata Driver Plugin Request ls/RegisterPlugin failed with message: Error in native callback

I was wondering if anyone knew what the fix is for this and how to go about it.

Thanks!

**Comment by gjsjohnmurray** [comment]
Please report this to the author of the Teradata driver extension.
