### ISSUE TITLE
Firebird Driver

### ISSUE THREAD

**Issue by MrNicolass** [mtxr/vscode-sqltools#1286]
# Issue Type
- [x] Feature Request
- [ ] Bugfix/Errors
- [ ]  Questions
- [ ]  Other

Any chances of adding support to Firebird databases in the future? I've already seen the #73 topic, but it seems dead.

**Comment by gjsjohnmurray** [comment]
A new driver would need to be written. See https://vscode-sqltools.mteixeira.dev/en/contributing/support-new-drivers for information. If you aren't in a position to attempt this yourself but are willing to fund the development please see https://github.com/mtxr/vscode-sqltools?tab=readme-ov-file#about-george-james-software for contact details of my employer.

**Comment by fzhem** [comment]
There's a firebird driver for javascript here: https://www.npmjs.com/package/node-firebird.

Scroll to the bottom and check notes on firebird 3.0 and 4.0 version support. If you are OK with those limitations/workarounds I can create a driver for you @MrNicolass

**Comment by MrNicolass** [comment]
Hello there!
It would be awesome my fellow coder! Unfortunately, I don't have the knowledge to do this my self, but I would be eternally grateful :)

> There's a firebird driver for javascript here: https://www.npmjs.com/package/node-firebird.
> 
> Scroll to the bottom and check notes on firebird 3.0 and 4.0 version support. If you are OK with those limitations/workarounds I can create a driver for you @MrNicolass

**Comment by fzhem** [comment]
@MrNicolass https://marketplace.visualstudio.com/items?itemName=fzhem.sqltools-firebird-driver

**Comment by MrNicolass** [comment]
> @MrNicolass https://marketplace.visualstudio.com/items?itemName=fzhem.sqltools-firebird-driver

Thank you so much my partner, i'm testing right now and i just left a five stars review in VScode Extensions web site <3
