### ISSUE TITLE
BigQuery connections not showing using different project_id

### ISSUE THREAD

**Issue by cecabrera** [mtxr/vscode-sqltools#1300]
First of all, I am a big fan of this extension. Thank you for all of the hard work you have put in it :) 

The bug is:
- When I connect to Bigquery using 1 project, it works perfectly
- When trying to connect to another project inside SQLTools, the connection is working but doesn't show any data

<img width="267" alt="image" src="https://github.com/mtxr/vscode-sqltools/assets/16246591/217103bc-8d4f-481e-9e04-683be528ca3c">

I have two different projects:
1. `real-estate-analysis`
2. `trading`

As you may see in the image, I am able to connect to `real-estate-analysis` Bigquery project using the extension with all available methods: CLI, Service Account and Oauth.

What I have tried so far:
* Connected using Service account. Granted Bigquery Data Owner permissions to both services account
* Connected using Service account. Granted Bigquery jobs executor permission to both services account
* Connected using CLI and configuring the default project via terminal
* Connected using OAuth token

In all of the scenarios above, the connection to `real-estate-analysis` project work but the `trading` connection doesn't. 

I configured also the projects accordingly in the `settings.json` file and didn't work. 

**Desktop (please complete the following information):**
 - SQLTools Version: v0.28.1
 - VS Code Version: 1.87
 - OS: Mac
 - Driver:
   - [x] BigQuery

When I use `Bigquery Runner` extension, it works:

<img width="217" alt="image" src="https://github.com/mtxr/vscode-sqltools/assets/16246591/918e9382-035a-4290-96c3-546230caf131">

What should I try? Thank you!

**Comment by gjsjohnmurray** [comment]
Please report this to the author of the BigQuery driver extension
