### ISSUE TITLE
extension cant show in front screen 

### ISSUE THREAD

**Issue by Kaustubhshitole** [mtxr/vscode-sqltools#1301]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - SQLTools Version [e.g. v0.17.x]
 - VS Code Version: [e.g 1.x.y]
 - OS: [e.g. Windows, Linux, Mac]
 - Driver:
   - [ ] PostgreSQL/Redshift
   - [ ] MySQL/MariaDB
   - [ ] MSSQL/Azure
   - [ ] SQLite
   - [ ] Other? Which...
 - Database version: [e.g. MySQL v5.6, PostgreSQL vX...]

**Additional context**

**Comment by Kaustubhshitole** [comment]
please solved my problem how it is find i  am so confused
![WhatsApp Image 2024-04-09 at 3 57 35 PM](https://github.com/mtxr/vscode-sqltools/assets/133126092/bdf0eab0-2267-407a-9a0c-05b9c2f3d107)
it's a error i cant upload my resporitiries properly please share me any proper and easy way solution

**Comment by gjsjohnmurray** [comment]
This is not related to the SQLTools extension.
