### ISSUE TITLE
Connection is not establishing 

### ISSUE THREAD

**Issue by Nambi2410** [mtxr/vscode-sqltools#1306]
Type: <b>Bug</b>

1) connect to DB in pgadmin and delete all databases in the pg admin and clear all the connections in the vscode and start fresh, when we try to connect again everything will pass. test connection will be successful and when we click on save connection the connection will not save or establish

Extension version: 0.28.1
VS Code version: Code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:20:17.278Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i5-1235U (12 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.69GB (0.88GB free)|
|Process Argv|--crash-reporter-id db5835a3-af67-4c7e-8c38-9c02c13fb42f|
|Screen Reader|no|
|VM|50%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes516:30244333
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp2r3:30993541
dsvsc020:30976470
pythonait:31006305
7ghi1836:30988842
dsvsc021:30996838
gd77d436:30999572

```

</details>

**Comment by gjsjohnmurray** [comment]
What exactly happens when you try to save the connection? Does anything get added to your VS Code settings.json file?

Maybe paste screenshots here, but remember it is a public forum so please don't reveal private information on them.

**Comment by gjsjohnmurray** [comment]
Also, please first update to the latest versions of the extensions, released today.

**Comment by Nambi2410** [comment]
I got it resolved thank you for your time
