### ISSUE TITLE
QueryError component does not wrap long messages

### ISSUE THREAD

**Issue by joaoguilhermeall** [mtxr/vscode-sqltools#1307]
**Describe the bug**

I am developing a new driver to be used with SQLTools and I noticed that when an error message is too long it is not formatted correctly and prevents the error from being read.

When observing, I noticed that this happens because the component uses a `pre` element to display the messages, which by default does not actually wrap the messages. [See reference](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/pre).

However, I understand the use of `pre`, but I believe it would also be valid to have a line break when messages exceed the maximum width of the view used.

**To Reproduce**

1.  Execute any query whose error has a long description

**Expected behavior**

Show the error message with line breaks if necessary so that it can be read

**Screenshots**

How the error screen is displayed if the `pre` element does not have the style to perform the line break
![image](https://github.com/mtxr/vscode-sqltools/assets/94701032/74f0263a-432e-4390-be87-24ab31b8fbf1)

What could the error screen be like if the `pre` element is configured to perform line wrapping
![image](https://github.com/mtxr/vscode-sqltools/assets/94701032/42d236bf-6d0b-417e-a898-2b4356011f08)

**Desktop (please complete the following information):**
 - SQLTools Version: 0.28.1
 - VS Code Version: 1.87.2
 - OS: Ubuntu 22.04.2 LTS
 - Driver:
   - [ ] PostgreSQL/Redshift
   - [ ] MySQL/MariaDB
   - [ ] MSSQL/Azure
   - [ ] SQLite
   - [X] Other? Developing JDBC Driver
 - Database version: Apache Impala 4.2.0

**Additional context**

**Comment by gjsjohnmurray** [comment]
@joaoguilhermeall please update to 0.28.2 (released today) and see if we've fixed this correctly.
