### ISSUE TITLE
please share me option about this 

### ISSUE THREAD

**Issue by Kaustubhshitole** [mtxr/vscode-sqltools#1308]
![WhatsApp Image 2024-04-09 at 3 57 35 PM](https://github.com/mtxr/vscode-sqltools/assets/133126092/a7991ca8-5198-4237-80fe-90eff2ce90bd)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - SQLTools Version [e.g. v0.17.x]
 - VS Code Version: [e.g 1.x.y]
 - OS: [e.g. Windows, Linux, Mac]
 - Driver:
   - [ ] PostgreSQL/Redshift
   - [ ] MySQL/MariaDB
   - [ ] MSSQL/Azure
   - [ ] SQLite
   - [ ] Other? Which...
 - Database version: [e.g. MySQL v5.6, PostgreSQL vX...]

**Additional context**

**Comment by gjsjohnmurray** [comment]
https://github.com/mtxr/vscode-sqltools/issues/1301#issuecomment-2045193154
