### ISSUE TITLE
connect is not the same as server address I used

### ISSUE THREAD

**Issue by JianwenShaw** [mtxr/vscode-sqltools#1322]
**Describe the bug**
Could't connect to MySQL server

**To Reproduce**
I try to use this extension to connect MySQL which was installed in my server but failed.
This is the output.I fountd that it connect to a wrong IP address

**Desktop (please complete the following information):**
 - SQLTools Version 0.28.3
 - VS Code Version:1.8
 - OS: Windows
 - Driver:
   - [ ] MySQL/MariaDB

 - Database version: MySQL v8.0.36

**Additional context**

**Comment by gjsjohnmurray** [comment]
> This is the output

I didn't find any output. If a screenshot please paste it via the GitHub web UI, and make sure to mask any confidential info.

**Comment by JianwenShaw** [comment]
This is my config
 

But the connection is failed


I findd that the server address is not the same as what I config.......




| |
shelly2140306
|
|
***@***.***
|
---- Replied Message ----
| From | John ***@***.***> |
| Date | 4/18/2024 23:01 |
| To | ***@***.***> |
| Cc | Ray ***@***.***> ,
***@***.***> |
| Subject | Re: [mtxr/vscode-sqltools] connect is not the same as server address I used (Issue #1322) |

This is the output

I didn't find any output. If a screenshot please paste it via the GitHub web UI, and make sure to mask any confidential info.

**Comment by gjsjohnmurray** [comment]
Did you perhaps paste screenshots into your email reply? If so, those get stripped when the email is ingested by GitHub, so please go to the issue on the GitHub website (there'll be a handy link there at the foot of a GH notification email), then paste images from your clipboard into a new comment, or drag/drop image files there.

**Comment by JianwenShaw** [comment]
well，thanks for your patiance😃
I will do that later.



---- Replied Message ----
| From | John ***@***.***> |
| Date | 04/19/2024 16:52 |
| To | ***@***.***> |
| Cc | Ray ***@***.***>***@***.***> |
| Subject | Re: [mtxr/vscode-sqltools] connect is not the same as server address I used (Issue #1322) |

Did you perhaps paste screenshots into your email reply? If so, those get stripped when the email is ingested by GitHub, so please go to the issue on the GitHub website (there'll be a handy link there at the foot of a GH notification email), then paste images from your clipboard into a new comment, or drag/drop image files there.

**Comment by JianwenShaw** [comment]
<img width="226" alt="226-3-E312CE25-7126-4D4A-BD14-F1B2A2BABF32" src="https://github.com/mtxr/vscode-sqltools/assets/118002258/9782d7bc-9e70-407a-9a8f-a944b8797188">
<img width="342" alt="226-4-94FA1FFF-7A48-4B34-B740-EEEBE44A759D (1)" src="https://github.com/mtxr/vscode-sqltools/assets/118002258/ccde6074-8ee2-4dd2-9bd5-c85b93d278a6">
<img width="603" alt="226-5-F0D6E45A-32DE-4A1F-A6D7-9DBCC4662EBB" src="https://github.com/mtxr/vscode-sqltools/assets/118002258/f605c43b-0a44-4a3e-96a9-8990e59e0951">

**Comment by gjsjohnmurray** [comment]
Please use VS Code's Command Palette (F1) to run `Preferences: Open User Settings (JSON)`, then search for `113.57.176.222` in that file in case it exists in a `"sqltools.connections"` array object.

Do the same with commands `Preferences: Open Folder Settings (JSON)` and `Preferences: Open Workspace Settings (JSON)` if they are present in Command Palette.

I'm trying to determine why the connection error is reporting a different IP address from the one you think it should be connecting to.

**Comment by JianwenShaw** [comment]
I am certain that no `113.57.176.222 ` in the settings.json file.

In fact I was able to connect to local MySQL normally, but not on the remote server.It's really confusing.I decided to continue to use SQLyog......

**Comment by gjsjohnmurray** [comment]
OK. Thanks for trying SQLTools anyway.
