### ISSUE TITLE
"You need to install sqlite3" prompt has Read More button that points to a 404

### ISSUE THREAD

**Issue by unikitty37** [mtxr/vscode-sqltools#1330]
**Describe the bug**
When attempting to connect to a SQLite 3 database for the first time, a prompt to install `sqlite3@5.1.1` appears. Clicking "Read more" opens a web page (`https://vscode-sqltools.mteixeira.dev/en/drivers/sqlite?umd_source=vscode`) that does not exist.

**To Reproduce**
1. Install SQLTools on a system that does not have `sqlite3@5.1.1` installed.
2. Create a SQLite3 connection.
3. Click "Test Connection".
4. Click "Read more".

**Expected behaviour**
A web page with helpful content opens.

**Screenshots**
![image](https://github.com/mtxr/vscode-sqltools/assets/139183/bbe562a8-d826-4632-9780-e22fb009dc67)

**Desktop (please complete the following information):**
 - SQLTools Version v0.28.3
 - VS Code Version: v1.89.1
 - OS: macOS 14.4.1 (23E224)
 - Driver:
   - [ ] PostgreSQL/Redshift
   - [ ] MySQL/MariaDB
   - [ ] MSSQL/Azure
   - [X] SQLite
   - [ ] Other? Which...
 - Database version: SQLite 3

**Additional context**
It may be easier to add a redirect on the web server than to push code changes to the extension 😁

**Comment by gjsjohnmurray** [comment]
Fixed in today's release.
