### ISSUE TITLE
Add support for Teradata SQL

### ISSUE THREAD

**Issue by JRDK92** [mtxr/vscode-sqltools#1333]
Very simple ask, support for Teradata SQL through VS Code SQL Tools. There's currently a VS Code Teradata driver, but it doesn't function at all. I've tested on 5 different versions of VS Code, and none of them work with Teradata driver (linked below). I don't think I would be able to figure out a fix for this driver, unfortunately, as it's written in typescript which I'm unfamiliar with, and would require a huge amount of time investment to learn how to develop a working extension. 

The error for Teradata driver occurs when the extension tries to register a plugin but encounters a problem with the process. This could be due to incorrect file paths or other issues related to how the extension is set up to handle this registration.

https://github.com/ScriptPup/sqltools-teradata-driver/tree/master

**Comment by gjsjohnmurray** [comment]
I think this needs to be resolved by the extension author. I saw you had created https://github.com/ScriptPup/sqltools-teradata-driver/issues/28 so I am going to close this here.
