### ISSUE TITLE
Keeping default vscode Intellisense in autocompletion

### ISSUE THREAD

**Issue by mickeypearce** [mtxr/vscode-sqltools#135]
**Is your feature request related to a problem? Please describe.**
Autocompletion of DB objects (tables, columns, ...) by SQLTools is really nice. But I miss variables, medhods, ... from my code that VS Code provides in IntelliSense by default.

**Describe the solution you'd like**
Keep default VS Code autocompletion AND SQL tools DB objects autocompletion

**Describe alternatives you've considered**

**Additional context**

If it is possible to have both: Default IntelliSense and SQLTools DB objects autocompletion at the same time it would be perfect!

**Comment by benyaminl** [comment]
Hey pearce, for now implementing intelisense itself is quite dificult task for Max, maybe you could help him a little bit more with supporting via patreon https://www.patreon.com/mteixeira to help fund this project so max have more time to implement such request :) It's a great feature anyway :) 👍

**Comment by mtxr** [comment]
Thanks @benyaminl!

@mickeypearce there is an issue (and a branch) fo this. It's a bit hard because of the variety of SQL parsers around. MySQL has some specific stuff, MSSQL too and PostgreSQL as well.

So I want to work it deeper to make it dialect independent. It's a loot of work, but now with the plugin architecture should be easier.

I'll close this i favor of #110, ok? 

Feel free to reopen if you believe it's not related.

Thanks!

**Comment by mickeypearce** [comment]
Just for clarifiaction... It would be nice to have it both at the same time:

1.  VS Code's word based completions (without SQL Tools, not connected):
![image](https://user-images.githubusercontent.com/1925433/54210612-1cea7000-44e0-11e9-8b44-db3041de5588.png)

2. SQL Tools autocompletion of DB objects (l_param is not on the list anymore):(
![image](https://user-images.githubusercontent.com/1925433/54210844-88344200-44e0-11e9-98dd-3799726c7924.png)

I thought it is not a problem to keep the default autocompletion, but It might be a VS Code issue that is not possible to extend the defaults...

**Comment by mtxr** [comment]
Thanks @mickeypearce .

The idea is to keep both. Just one is not an option. For example, I use VSCode completions and SQLtools completions in my JS/TS files, and this is possible just If both are working.

I found a great SQL parser, it's just for SQLite, but I'm working on extending to other dialect to make it a bit easier. From scratch is almost impossible for me now

**Comment by mtxr** [comment]
Thanks @mickeypearce .

The idea is to keep both. Just one is not an option. For example, I use VSCode completions and SQLtools completions in my JS/TS files, and this is possible just If both are working.

I found a great SQL parser, it's just for SQLite, but I'm working on extending to other dialect to make it a bit easier. From scratch is almost impossible for me now

**Comment by mickeypearce** [comment]
Ok. thanks.
Maybe consider also using `CompletionItemProvider` (`vscode.languages.registerCompletionItemProvider`, ...) as it allow multiple providers for a lang.
