### ISSUE TITLE
Connection Explorer Side Bar Item Ordering

### ISSUE THREAD

**Issue by Irishmanluke** [mtxr/vscode-sqltools#1351]
When viewing SQL objects in the connection explorer it can be difficult to find specific objects since they are not guaranteed to be in any particular order (it's dependent on the order the driver returns them in).  In particular I'm noticing this when viewing tables in Databricks.

**Describe the solution you'd like**
Add logic to sort sidebar items in the connection explorer lexicographically by label.

**Describe alternatives you've considered**
It's not clear to me whether the ordering is better handled by the driver or by SQLTools directly.  If it's meant to be handled by the driver I can move this issue over to the databricks driver extension.

**Comment by gjsjohnmurray** [comment]
Please raise this with the driver author. I think they should be able to fix this by adding an ORDER clause to the relevant query/ies.
