### ISSUE TITLE
Horizontal scroll in results tab

### ISSUE THREAD

**Issue by jdan62** [mtxr/vscode-sqltools#136]
Header row don't scroll when a result cell is selected.

1. Execute a query
2. Click  a cell in results 
3. Try to scroll horizontal
4. The header row stay fix

**Comment by mtxr** [comment]
Which version are you using?

We had a fix at scrolls yesterday

**Comment by jdan62** [comment]
> 
> 
> Which version are you using?
> 
> We had a fix at scrolls yesterday

Version : 0.17.4

**Comment by mtxr** [comment]
I'll take a look. Thanks @jdan62 .

If you have any additional info you could provide would be great.

**Comment by mtxr** [comment]
Fixed in v0.17.5

**Comment by mtxr** [comment]
@jdan62 can you confirm it's working for you?

Feel free to reopen if it persists. But should be totally gone.
