### ISSUE TITLE
Option to Disable Automatic Error Console Opening on Query Errors

### ISSUE THREAD

**Issue by alexandrepgui** [mtxr/vscode-sqltools#1365]
![image](https://github.com/user-attachments/assets/af435b80-5a3f-4e4d-b2f8-b7d9246a679c)

I would like to request a feature to disable the automatic opening of the error console when there is an error in an SQL query. Currently, the error console opens every time there's an issue, even though the error message is already displayed in the result tab. This behavior is disruptive and cumbersome.

It would be greatly beneficial to have a setting in SQLTools that allows users to control this behavior, enabling them to choose whether or not the error console should open automatically on query errors. This feature would enhance the user experience by reducing unnecessary interruptions.

Thank you for considering this feature request.

**Comment by gjsjohnmurray** [comment]
This is in today's release.
