### ISSUE TITLE
Disconnecting does not release lock file in dockdb

### ISSUE THREAD

**Issue by ianpogi5** [mtxr/vscode-sqltools#1393]
**Describe the bug**
Disconnecting does not release lock file in dockdb file.

**To Reproduce**
1. Add duckdb connection
2. Click on connect on the duckdb connection
3. Disconnect duckdb connection
4. Run external command(dbt) that will read and write to the duckdb file.
5. You will get an error that another process still has the lock file and you can only do write operations

**Expected behavior**
After disconnection, lock file should be released.

**Screenshots**
![Screenshot from 2024-11-02 06-24-22](https://github.com/user-attachments/assets/a9b4c34e-d5a9-4801-99e6-b0838e9e4a84)

**Desktop (please complete the following information):**
 - SQLTools Version: v0.28.3
 - VS Code Version: 1.94.2
 - OS: Fedora 40 Workstation Edition
 - Driver:
   - [ x] [duckdb](https://github.com/RandomFractals/duckdb-sql-tools) v1.6.0
 - Database version: Duckdb

**Additional context**
I need to close VSCode to be able to run my external command(dbt).

**Comment by gjsjohnmurray** [comment]
Please report this to the author of the duckdb driver extension.
