### ISSUE TITLE
[Feature request] open cell value in new file

### ISSUE THREAD

**Issue by callamaris** [mtxr/vscode-sqltools#140]
Hi,

please add a new context menu item "Open cell value" to open a new editor and copy the selected cell value.

I am opening a new editor and copy the cell content with the button copy cell value for now.

a new button to do this in one go would improve my workflow a lot, espacially with clob/varchar/xmltype columns with long text content.

**Comment by mtxr** [comment]
Will be released soon. Tks! Great idea.
