### ISSUE TITLE
Docs images are not found

### ISSUE THREAD

**Issue by nbbaier** [mtxr/vscode-sqltools#1405]
Currently, all the images on pages in the `features` section of the docs are returning 404 responses. It looks like the path `https://raw.githubusercontent.com/mtxr/vscode-sqltools/master/docs/assets/` doesn't exist

**Comment by gjsjohnmurray** [comment]
Please clarify. Here's what I'm seeing for an image-containing page in the published Features section:

![image](https://github.com/user-attachments/assets/59d48c4b-90ca-4370-a5d9-38afc36d3a38)

**Comment by nbbaier** [comment]
Sorry, I was too general: the [Session and Multiple Connections](https://vscode-sqltools.mteixeira.dev/en/features/session-multiple-connections) page and [Bookmarks](https://vscode-sqltools.mteixeira.dev/en/features/bookmarks) page don't have the images showing up:

<img width="879" alt="Screenshot 2024-11-27 at 1 25 54 AM" src="https://github.com/user-attachments/assets/0d95a215-4c3b-4829-86f1-4ee7ddab4a04">
<img width="964" alt="Screenshot 2024-11-27 at 1 25 16 AM" src="https://github.com/user-attachments/assets/6163e865-f16c-4391-929d-1253078fd8c6">

**Comment by gjsjohnmurray** [comment]
Thanks for clarifying. Looks like images got deleted [here](https://github.com/mtxr/vscode-sqltools/pull/979/commits/97892edb1c62f75c35e92e6024fd63393bde5357) a couple of years ago in the PR that reworked the documentation.
