### ISSUE TITLE
[Feature] Pass dialectOptions to node-postgres in order to support SSL

### ISSUE THREAD

**Issue by dboune** [mtxr/vscode-sqltools#141]
**Is your feature request related to a problem? Please describe.**

I am unable to connect to a PostgreSQL server that requires SSL.

The values in `dialectOptions` do not appear to be passed to `node-postgres`.

**Describe the solution you'd like**

I should be able to add `"ssl": true` to the connection `dialectOptions`, and establish a connection to PostgreSQL using SSL/TLS.

Additionally, `ssl` should be able to be an object containing the necessary paths to use a certificate as described here: https://node-postgres.com/features/ssl. However, this will require a little more work than is needed to simply support `"ssl": true`.

**Describe alternatives you've considered**

None.

**Additional context**

***Relevant typings***

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/e51e5044b8cf1bb317f5ca052cba4531d051a234/types/pg/index.d.ts#L34-L36

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/e51e5044b8cf1bb317f5ca052cba4531d051a234/types/node/v10/tls.d.ts#L333-L348

***Relevant code in node-postgres***

https://github.com/brianc/node-postgres/blob/6b8176e841584b76bcbd1972bf95e50558ba7395/lib/connection.js#L94-L106

**Comment by mtxr** [comment]
I've added `pgOptions` setting. More info here: https://mtxr.gitbook.io/vscode-sqltools/connections/postgresql#1-1-specific-options
