### ISSUE TITLE
Dollar quoting not properly formatted

### ISSUE THREAD

**Issue by yacinehmito** [mtxr/vscode-sqltools#142]
**Describe the bug**
When using dollar-quoting (`$$`), SQLTools' formatter inserts a space between the two characters (`$ $`), which breaks the script.

**To Reproduce**
Write any piece of SQL with Postgres' dollar quoting.
Example:

```sql
create function foo() returns void AS $$
begin
select true;
end;
$$ language PLPGSQL;
```

**Expected behavior**
The two dollar signs should stay next to each other.

**Desktop (please complete the following information):**
 - OS: Mac
 - Version 10.14.2

**Comment by mtxr** [comment]
Which SQLTools version?

**Comment by mtxr** [comment]
I could confirm it here. Fixed. To be released soon
