### ISSUE TITLE
[SQLite] Views showing as tables on explorer

### ISSUE THREAD

**Issue by julientype** [mtxr/vscode-sqltools#143]
**Describe the bug**
when creating a view it loads in table folder not in view folder.....
sqlite
**To Reproduce**
CREATE VIEW v_tracks 
AS 
SELECT
    *
FROM
    UserCategory;

**Desktop (please complete the following information):**
 - OS: [ Windows]
 - SQLTools Version [-v0.17.x]

**Comment by julientype** [comment]
would be nice if you added more templates off tables.....
like basic formats for insert delete where  ect.....   
like an aid to get started with good formats.......  right click insert template type.....

**Comment by julientype** [comment]
if take a look sql type generator statements you have mass to create templates from
just use the same name and inject the format ......
alter-table-stmt   analyze-stmt   attach-stmt   begin-stmt   commit-stmt   create-index-stmt   create-table-stmt   create-trigger-stmt   create-view-stmt   create-virtual-table-stmt   delete-stmt   delete-stmt-limited   detach-stmt   drop-index-stmt   drop-table-stmt   drop-trigger-stmt   drop-view-stmt   insert-stmt   pragma-stmt   reindex-stmt   release-stmt   rollback-stmt   savepoint-stmt   select-stmt   update-stmt   update-stmt-limited   vacuum-stmt

https://www.sqlite.org/syntax/sql-stmt.html

**Comment by julientype** [comment]
here is what i mean.... on a listed View  you want to delete...menu generate script on view name
 drop-view-stmt
just call the way it is.....   you get full editor this way   add help tips on how to best format the template injection

**Comment by mtxr** [comment]
we already have for inserts. But yes, would be nice for sure.

Can you open a new issue as a feature request for this?
I'm already working on this bug. But the features should be handled separated.

Ok? 

Thanks @julientype . Great insights
