### ISSUE TITLE
Error opening connection Request initialize failed with message: console.debug is not a function

### ISSUE THREAD

**Issue by jtuttas** [mtxr/vscode-sqltools#147]
When I try to open a sqlite database I've got the error "Error opening connection Request initialize failed with message: console.debug is not a function"

OS: Windows 10
Node version: 6.11.1

**Comment by jtuttas** [comment]
One addition, the problem appears on MySQL Databases too!

**Comment by julientype** [comment]
console.debug   yep  a run time debug code needs to be removed...... your not in debug mode its an active app.....  v8 code error......

**Comment by jtuttas** [comment]
Thanks a lot, I updated to the latest node Version and the error disappears. Now I have an other new problem, the extension ask me to install Missing module "sqlite3@4.0.6". When I hit "install" this message still stay on.

**Comment by julientype** [comment]
you have a global folder and a local folder where modules are installed 
the vscode wizard may need a global copy not a local one

**Comment by jtuttas** [comment]
Well if I install the library with ..
`npm install -g sqlite3@4.0.6` the problem still stays on. I've got the Message that sqlite3@4.0.6 needs to be installed, over and over again!

**Comment by mtxr** [comment]
Installing it globally should have no effect. The extension install deps on itself folder.

Which extension version are you using? Whats your VScode version?

This bug was happening a few versions ago, but as far as I know, It's not happening on newer versions.

**Comment by julientype** [comment]
its doing it with me to.....   where i try and connect 3 or 4 times then it kicks in
it could be calling something without  the lib loaded....  
like a call to open yet its not done processing and a second call happens and flags you need to install

**Comment by mtxr** [comment]
whats is printed on the output window? Use the command palette to find 'SQLTools output channel'

**Comment by jtuttas** [comment]
Hello, VS Code I used the latest Version, the Extension Version of SQL Tools is 0.17.9

And here is the output after two cycles of "need to install sqlite....."

`(node:16008) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Telemetry enabled!
Event: sessionStarted:language-server 
Message: Initialized with node version:v10.15.3
Configs reloaded!
Request connection/RefreshAllRequest received
Request connection/RefreshAllRequest received
Request connection/ConnectRequest received
Request DependencyInstaller/install received
Received request to install deps: {"dialect":"SQLite"}
Will install sqlite3 package
Request connection/RefreshAllRequest received
Request connection/RefreshAllRequest received
Request connection/RefreshAllRequest received

> sqlite3@4.0.6 install c:\Users\jtutt\.vscode\extensions\mtxr.sqltools-0.17.9\node_modules\sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download 
[sqlite3] Success: "c:\Users\jtutt\.vscode\extensions\mtxr.sqltools-0.17.9\node_modules\sqlite3\lib\binding\node-v67-win32-x64\node_sqlite3.node" is installed via remote
npm notice created a lockfile as package-lock.json. You should commit this file.
+ sqlite3@4.0.6
added 113 packages from 102 contributors and audited 160 packages in 21.925s
found 0 vulnerabilities

Finished sqlite3 script
Finished installing deps
Request connection/ConnectRequest received
Request DependencyInstaller/install received
Received request to install deps: {"dialect":"SQLite"}
Will install sqlite3 package

> sqlite3@4.0.6 install c:\Users\jtutt\.vscode\extensions\mtxr.sqltools-0.17.9\node_modules\sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download 
[sqlite3] Success: "c:\Users\jtutt\.vscode\extensions\mtxr.sqltools-0.17.9\node_modules\sqlite3\lib\binding\node-v67-win32-x64\node_sqlite3.node" is installed via remote
+ sqlite3@4.0.6
updated 1 package and audited 160 packages in 4.592s
found 0 vulnerabilities

Finished sqlite3 script
Finished installing deps
Request connection/ConnectRequest received` 

Thanks for your help !

**Comment by julientype** [comment]
node-pre-gyp   is a pre-compile version  V6  yet you need V9    
node-gyp is used to compile the correct version with with its run-time node version 
you need c-make tools installed  or run older node version  a node addon  a python connector

**Comment by jtuttas** [comment]
Ok, after uninstall Node and install the latest LTS Version everything works fine !
