### ISSUE TITLE
Allow chose to open results on side

### ISSUE THREAD

**Issue by mtxr** [mtxr/vscode-sqltools#148]
**Is your feature request related to a problem? Please describe.**

When executing queries, The document I'm working looses focus.

**Describe the solution you'd like**
As an user I want to open results on side, below or in the current viewColumn and keep the focus on editor.

**Comment by julientype** [comment]
when you set the css active element color with the  focus color and leave the tree the active color shows up not the focus color or it will go back to the original color
.divToolTree,
a:active {
    color: olive;
}
.divToolTree,
a:focus {
     color:red;
}

**Comment by mtxr** [comment]
@julientype Please, keep it in the same thread

**Comment by julientype** [comment]
look at your css   where is focus....  no code need ... you group a class divtooltree, li
then simply append the classname  to the div and program its internal elements supported by css event actions..... 
li {
    border-color: $lightThemeGray1 !important;

    &:hover {
      background: $lightThemeGray3 !important;
    }
    &.active {
      font-weight: bold;
      background: $lightThemeGray1 !important;
      cursor: initial;
    }
  }

**Comment by julientype** [comment]
never invent code... check. dom css may have the correct solution 
for vcode you only target chrome.......
Pseudo-classes 
https://developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-classes
