### ISSUE TITLE
Allow empty password connection

### ISSUE THREAD

**Issue by flexchar** [mtxr/vscode-sqltools#150]
Doesn't allow empty password connections. It is quite common to use root user with empty password while in localhost development. :)

**Comment by julientype** [comment]
i would insert   prompt for option  login ......  then you dont have  files with user info in vscode txt base files 
its sent into the connection

**Comment by mtxr** [comment]
Did you create the connection using the assistant or manually?

We accept connections without password. I believe just the settings editor handle it as a requirement.

Can you confirm?

If you created the connection using the wizard, you can input a password there, after that, go to your settings file and delete both "password" and "askForPassword" lines.

Anyway, I'll add this option to the wizard.

Will be published soon

**Comment by flexchar** [comment]
Indeed I used assistant. If _Prompt For Password_ is set to _No_, then Validation line for _Password can't be empty_ is shown. Vice versa, if prompted for password, it cannot skip it with no input.

Thanks for the tip thou. :)

**Comment by mtxr** [comment]
@flexchar thanks! Just fixed, I'll be release soon.
