### ISSUE TITLE
sqlite_sequence showing up in the tree

### ISSUE THREAD

**Issue by julientype** [mtxr/vscode-sqltools#152]
in sqlite   when you create an auto increment index value it creates a table called 
sqlite_sequence

this is basically a trigger type operation not an input table operation

to logically group this table type entry it should show up as a trigger entry its not a regular table.

SQLite - Triggers. SQLite trigger may be specified to fire whenever a DELETE, INSERT or UPDATE of a particular database table occurs or whenever an UPDATE occurs on one or more specified columns of a table. At this time, SQLite supports only FOR EACH ROeW triggers, not FOR EACH STATEMENT triggers.

I believe it should show up as a trigger table..... its like it a table holding values yet its not a regular table and its not trigger statement  because its a table yet it it functions the same... 

??????   2+ icons needed   for trigger type statements and icons help in identifying data objects to move around  in code yet seen at a visual  level before coding......  styles implement  code not code implementing styles later

**Comment by mtxr** [comment]
@julientype do you want to work on this issue?

**Comment by mtxr** [comment]
Actually, I'll remove that table from tree.

All other tools doesn't show it. So I won't show it too.

**Comment by julientype** [comment]
sqlite_sequence    just needs to be hidden when you load your tables .... its relay an internal table you should not edit..... in fact sqlight will prevent any operation to it even delete....

**Comment by Romvnly-Gaming** [comment]
Nice!
