### ISSUE TITLE
Support connecting to MySQL (and others) by local AF_UNIX socket

### ISSUE THREAD

**Issue by mappu** [mtxr/vscode-sqltools#163]
Hi,

Current default MySQL behaviour in Debian is to listen on `/var/run/mysqld/mysqld.sock` AF_UNIX instead of localhost AF_INET.

Is it possible to support this in the extension?

Regards
mappu

**Comment by mtxr** [comment]
Hi,

Yes, that's totally possible. The library we are using accepts socket connections, I just need to do some changes on code.

See: https://github.com/mysqljs/mysql#connection-options

If you/someone want to try to develop it, I can provide some guidance.

----------
# How to add this feature

Basically we need to add the options here:
https://github.com/mtxr/vscode-sqltools/blob/master/packages/extension/package.json#L368

and here:
https://github.com/mtxr/vscode-sqltools/blob/master/packages/core/interface/connection.ts#L6

Pass the socket path to the config here:
https://github.com/mtxr/vscode-sqltools/blob/master/packages/core/dialect/mysql/default.ts#L22-L31

And add some documentation about this connection method here:
https://github.com/mtxr/vscode-sqltools/blob/master/docs/Connections/mysql.md

**Comment by mtxr** [comment]
Hi @mappu, would you like to take a shot on this issue?

**Comment by mtxr** [comment]
@mappu let me know how is it going for you.

And if you like the project, please consider a donation or reviewing it on VSCode marketplace. That you help it to keep evolving.

Thanks!
