### ISSUE TITLE
Formatting breaking plain text files

### ISSUE THREAD

**Issue by brandonkal** [mtxr/vscode-sqltools#171]
**Describe the bug**
This extension is messing with the wrong files...
In settings.json:
```json
{
    "sqltools.formatLanguages": [""],
  "[sql]": {
    "editor.formatOnSave": false
  },
  "editor.formatOnSave": true
}
```
Note that formatLanguages is set to an empty string. The intent was to disable SQL formatting. Even if this is not the preferred API for disabling formatting, an empty string should be checked for. This caused strange bugs when saving plain text files (removal of new lines, adding of spaces in date strings, etc...)

Changing to `"sqltools.formatLanguages": ["baz"]` fixes the issue but that doesn't appear very intuitive.

**Desktop (please complete the following information):**
 - OS: MacOS 10.12.6
 - SQLTools Version v0.17.10

**Comment by mtxr** [comment]
This is already fixed. 
I'll be released shortly.

Thanks @brandonkal

**Comment by gjsjohnmurray** [comment]
Please make sure you restart VS Code after you set `"sqltools.formatLanguages": [],`
