### ISSUE TITLE
How do you change font?

### ISSUE THREAD

**Issue by tonydiep** [mtxr/vscode-sqltools#174]
How do you change the font used SQLTools' table view? 

If it's an attribute in settings.json can you provide the css attribute we should be using please?

**Comment by mtxr** [comment]
Actually there is no way. 

But this is a simple change. I can add it within this week.

Do you have any other customizations on table view you believe would be great to have?

**Comment by tonydiep** [comment]
Thank you so much for putting this feature in!

**Comment by mtxr** [comment]
You are welcome!

If you like the project, please consider a donation or reviewing it on VSCode marketplace. That you help it to keep evolving.

Thanks!
