### ISSUE TITLE
Can not connect to to database with only_full_group_by error

### ISSUE THREAD

**Issue by chanaksha** [mtxr/vscode-sqltools#176]
**Describe the bug**
Can not connect to the database

Error

```
Error while preparing columns completions for connection Flow ER_WRONG_FIELD_WITH_GROUP: Expression #4 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'information_schema.f.ROUTINE_NAME' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by Would you like to see the logs?
```

**To Reproduce**
1. Ensure that MySQL has (default) sql_mode=only_full_group_by set.
2. Connect to MySQL database by clicking on configured connection.

**Expected behavior**
Database should connect

**Screenshots**
![Screenshot from 2019-04-09 15-02-53](https://user-images.githubusercontent.com/35898631/55790213-8195ec00-5ad9-11e9-978f-7a349053fd7e.png)

**Desktop (please complete the following information):**
 - OS: Linux (CentOS 7 Gnome)
 - SQLTools Version: 0.17.12 

**Additional context**
I havenot tried making change in MySQL sql_mode yet.

**Comment by chanaksha** [comment]
The stack trace:

```
WARN: stack trace: Error: Request connection/RefreshAllRequest failed with message: ER_WRONG_FIELD_WITH_GROUP: Expression #4 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'information_schema.f.ROUTINE_NAME' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
	at handleResponse (/home/fixspec/.vscode/extensions/mtxr.sqltools-0.17.12/extension.js:534:48)
	at processMessageQueue (/home/fixspec/.vscode/extensions/mtxr.sqltools-0.17.12/extension.js:361:17)
	at Immediate.module.exports.setImmediate (/home/fixspec/.vscode/extensions/mtxr.sqltools-0.17.12/extension.js:345:13)
	at runCallback (timers.js:696:18)
	at tryOnImmediate (timers.js:667:5)
	at processImmediate (timers.js:649:5)
```

**Comment by chanaksha** [comment]
Thanks for quick changes. I wouldn't have been that fast to contribute :)

**Comment by mtxr** [comment]
You are welcome!

If you like the project, consider a donation or reviewing it on VSCode marketplace. That you help it to keep evolving.

Thanks!
