### ISSUE TITLE
Sqlite connection error: Cannot read property 'conn' of undefined

### ISSUE THREAD

**Issue by NanoDano** [mtxr/vscode-sqltools#191]
EDIT: Fix in the comments below and pull request created: https://github.com/mtxr/vscode-sqltools/pull/198

SQLite database is unable to connect with the following error:

```
Error opening connection Request connection/ConnectRequest failed with message: Cannot read property 'conn' of undefined'
```

- Desktop is Fedora 29.
- Node v10.15.0
- vscode built from master (1.34.0 currently)
- Sqlite version: 3.26.0 2018-12-01 12:34:55 bf8c1b2b7a5960c282e543b9c293686dccff272512d08865f4600fb58238alt1
- SQLTools  mtxr.sqltools 0.17.15

**Comment by zetxx** [comment]
it is the same for oracle

**Comment by sigmasoldi3r** [comment]
I confirm that happens also with:
+ VS Code 1.33.1 (User Setup)
+ Electron: 3.1.6
+ Chrome: 66.0.3359.181
+ Node.js: 10.2.0
+ V8: 6.6.346.32
+ OS: Windows_NT x64 10.0.17134

**Comment by daniel-dia** [comment]
Also happens to me

I suspect that it could be due the file system, but i tried with 

```
        {
            "database": ":memory:",
            "dialect": "SQLite",
            "name": "sqlite"
        }
```

with the same results.

**Comment by zetxx** [comment]
no, this is not from file system it is a pure javascript, it means that some object is not initialized somewhere.... but i dont know how to dev extensions, but if issue persists i will need to learn :D

**Comment by AimvenDragtow** [comment]
same issue

**Comment by tomgehrke** [comment]
Same here.

**Comment by tomgehrke** [comment]
Actually, after actually reading the instructions, I got it working.

1. Ensure that Node is installed
2. Make sure sqlite3 is installed - **npm install sqlite3**
3. Make sure that useNodeRuntime is enabled in your settings.

Edit your settings.json file to include the line:

**"sqltools.useNodeRuntime": true**

That solved the issue for me.

**Comment by NanoDano** [comment]
Hmm, I didn't see that in the docs at https://vscode-sqltools.mteixeira.dev/connections/sqlite - It actually says `Extension automatically installs SQLite driver (sqlite@v4.0.6)`

I tried to npm install the sqlite3 package but it failed and I did find a Fedora yum package `nodejs-sqlite3` which I installed, but that does not resolve the problem.

**Comment by tomgehrke** [comment]
What about the 3rd step? If you open your settings.json file, do you have the sqltools.useNodeRuntime line in there? That was the key for resolving this issue for me.

**Comment by NanoDano** [comment]
Double checked the settings, and when I added `"sqltools.useNodeRuntime": true`, it didn't recognize the sqlite package installed by yum, but it did ask me then to install the sqlite package, and it did successfully. So it looks like I didn't need the yum package but the sole step that matters is adding `"sqltools.useNodeRuntime": true` to settings.json. Thanks!

**Comment by NanoDano** [comment]
Now that I re-read the docs, that step was unclear to me. I'm not sure why, it makes sense when I read it now. I guess the wording just didn't click with me because I do remember seeing it, but my eyes went to step 2 and saw the actual settings as json and thought that was all the settings I needed. Personally I think it would be a little clearer if step 1 had a similar block of code like:

```json
// settings.json example
{
  "sqltools.useNodeRuntime": true, // Or a specific node path
}
```

It sounds like several other people missed that critical step.

**Comment by tomgehrke** [comment]
Excellent! It's a happy day for both of us now! :D 

And I'm right there with you. My eyes just slid right over that part initially as well.

**Comment by NanoDano** [comment]
Created a pull request to make that step more prominent in the documentation:

https://github.com/mtxr/vscode-sqltools/pull/198
