### ISSUE TITLE
Code completion is a little too fuzzy

### ISSUE THREAD

**Issue by ransagy** [mtxr/vscode-sqltools#193]
**Describe the bug**
When triggering code completion for SQL, The results i get are a little too verbose for what i wrote. For example, Writing `SomethingID` and triggering completion, I get results that just contain `ID` or just contain `Something`, That seems wrong to me in such cases as i explicitly wrote both.

**To Reproduce**
1. Open a new SQL tab
2. Connect to a DB
3. Write a simple select query for any table with a column ending with the word `ID`.
4. Trigger code completion. Columns with partial matches appear.

**Expected behavior**
Only columns that have the full typed word, i.e. `SomethingID` will be shown.

**Desktop (please complete the following information):**
 - VS Version: 1.33.1 (user setup)
 - OS: Windows_NT x64 10.0.17763 (Windows 10 Pro)
 - SQLTools Version v0.17.15.

**Comment by mtxr** [comment]
Hi @ransagy.

Please try to tweak IntelliSense settings a bit, we don't have much power on this fuzzy search since it's provide by VSCode, I just give it a list to be searchable.

Take a look here: https://code.visualstudio.com/docs/editor/intellisense#_settings

I'll close this since there is another on going work on issue #110 that would reduce the number of itens in the completion list, ok?

Let me know if you have succeeded on tweaking.

Thanks!

**Comment by ransagy** [comment]
Any idea if those are changes in newer VSCode version? Anyway, Tweaking any of those doesn't help, It still matches things incredibly fuzzy making it very hard to find what you're looking for.

I guess i'll look forward to your other change hoping it reduces the pain from VSCode's change.

**Comment by ransagy** [comment]
@mtxr See the suggestion in the latter vscode issue. Can we do something about it?

**Comment by mtxr** [comment]
Yeah, I saw the issue you commented on VSCode. I'll take a look and release it today

**Comment by mtxr** [comment]
Sorry I tooke longer to reply. Response edits are not notified via email.

**Comment by mtxr** [comment]
Closed in https://github.com/mtxr/vscode-sqltools/commit/ac9487a9b3bac22bb8c5002356a5bd873ef9e933

**Comment by mtxr** [comment]
@ransagy how is it going with the new version? Fixed?

**Comment by benyaminl** [comment]
> Describe the bug
> When triggering code completion for SQL, The results i get are a little too verbose for what i wrote. For example, Writing SomethingID and triggering completion, I get results that just contain ID or just contain Something, That seems wrong to me in such cases as i explicitly wrote both.
> To Reproduce
> Steps to reproduce the behavior:
> 
> Open a new SQL tab
> Connect to a DB
> Write a simple select query for any table with a column ending with the word ID.
> Trigger code completion. Columns with partial matches appear.
> 
> Expected behavior
> Only columns that have the full typed word, i.e. SomethingID will be shown.
> Desktop (please complete the following information):
> 
> VS Version: 1.33.1 (user setup)
> OS: Windows_NT x64 10.0.17763 (Windows 10 Pro)
> SQLTools Version v0.17.15.

If you consider maybe support @mtxr monthly via this link https://www.patreon.com/mteixeira/posts. 
5 USD for a cup of coffee a month doesn't hurt but it will help his wife allow him to work more on this tools :)

**Comment by ransagy** [comment]
@mtxr Indeed, It works much better now, Much appreciated! Now I'll wait for the feature to limit it by table/schema (or at least prioritize it with the scoring/filtering system VSCode has) that you're working on for another issue, But this is at least now in a state that is useful for day to day work.

@benyaminl Despite not the place to have this discussion (on a specific issue), As you can see from the main README section - I already have donated.

**Comment by benyaminl** [comment]
Maybe monthly :v just kidding. I just persuade people to donate more. Hahaha..


Regards,
Benyamin Limanto

Send via Outlook for Android<https://aka.ms/ghei36> from my ASUS Pegasus X005

________________________________
