### ISSUE TITLE
Error not supported auth mode

### ISSUE THREAD

**Issue by pavkum** [mtxr/vscode-sqltools#195]
**Describe the bug**
I'm trying to connect mysql 8 but I'm getting an error saying "ER_NOT_SUPPORTED_AUTH_MODE. consider upgrading mysql client"

**To Reproduce**
1. configure the connection for any mysql server running in 8.x using sqltools
2. try connecting to server
3. See error

**Expected behavior**
Should connect to mysql without error

**Desktop (please complete the following information):**
 - OS: Mac
 - SQLTools Version: v0.17.15

**Additional context**
NA

**Comment by mtxr** [comment]
@pavkum  Go to vscode settings and try to add this `authProtocol` option. I might fix I believe. See:

https://github.com/mtxr/vscode-sqltools/blob/e39ef2ebfc111dca7d8e45e320e55a013d9c5cfa/.test-database/.vscode/settings.json#L65-L77

Let me know who it goes.

**Comment by pavkum** [comment]
@mtxr No luck. Now I get an error message saying connection reset (ECONNRESET). My server is running on a different machine. Would that be a problem?

**Comment by mtxr** [comment]
Can you share your connection settings? You can mask the properties if you need

**Comment by pavkum** [comment]
@mtxr Please find my settings below

"askForPassword": false,
"connectionTimeout": 30,
"database": "db",
"dialect": "MySQL",
 "name": "db",
 "password": "db",
 "port": 3306,
 "server": "<my-ip>",
 "username": "db",
 "mysqlOptions": {
     "authProtocol": "xprotocol"
  }
}

**Comment by mtxr** [comment]
can you check if you server has the port 33060 open?

Take a look at MySQL ports section [here](https://mysqlserverteam.com/mysql-guide-to-ports/)

**Comment by pavkum** [comment]
@mtxr It's working fine with the port 33060. Along with the above options, I had to set SSL to true. Thank you :)

**Comment by mtxr** [comment]
You're welcome!

**Comment by jabacchetta** [comment]
@mtxr Wonder if this should be added to the documentation? Adding `xprotocol` and adding a `0` to the end of the port `3306` were both required to connect.

**Comment by mtxr** [comment]
Go ahead @jabacchetta . Do the changes needed in the docs and submit a PR please.

**Comment by sundaycat** [comment]
> @pavkum Go to vscode settings and try to add this `authProtocol` option. I might fix I believe. See:
> 
> https://github.com/mtxr/vscode-sqltools/blob/e39ef2ebfc111dca7d8e45e320e55a013d9c5cfa/.test-database/.vscode/settings.json#L65-L77
> 
> Let me know who it goes.

Hi,  I set up the setting exactly as this post suggested(except the port was set to 33060), but it still doesn't work. The error I got is

 `Error opening connection ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client`
