### ISSUE TITLE
"Describe table" doesn't include schema

### ISSUE THREAD

**Issue by mickeypearce** [mtxr/vscode-sqltools#197]
**Describe the bug**
"Describe table" and "Show table records" command don't parse schema correctly when run from Command palette. It works if executed from table explorer.

**To Reproduce**
If "Describe table" is run from command pallete (table is selected from pick list) it doesn't include schema:

(view query):
```
select * from all_tab_columns
    where table_name = 'undefined'
    and owner = 'my_table'
```
It works if run from explorer table directly:

(view query):
```
select * from all_tab_columns
    where table_name = 'my_table'
    and owner = 'myschema'
```

Similar with "Show table records" command.

**Desktop (please complete the following information):**
 - OS: Windows
 - SQLTools Version: latest

**Comment by mtxr** [comment]
It's the same problem as #196.

Closing in favor of that.

**Comment by mtxr** [comment]
Reopened. I got confused
