### ISSUE TITLE
Error while trying to create columns tree for MSSQL

### ISSUE THREAD

**Issue by omiba** [mtxr/vscode-sqltools#199]
**Describe the bug**
After connecting to MSSQL I receive the error message "Error while trying to create columns tree for MSSQL Cannot read property 'Project' of undefined"

Source: SQLTools (Extension)

**To Reproduce**
1) Open a SQL File
2) Connect to MSSQL database
3) Wait for error to display

**Expected behavior**
I shouldn't get an error

**Screenshots**
https://cl.ly/371beaba6456

**Desktop (please complete the following information):**
 - SQLTools Version [e.g. v0.17.17]
 - VSCode Version: [e.g 1.33.1]
 - Dialect Used: [MSSQL]
 - OS: [Mac]

**Additional context**
This wasn't happening on a previous release.

**Comment by mtxr** [comment]
@omiba what's the name of the table that has `Project` column?

**Comment by mtxr** [comment]
@omiba Also, what's the `tree` prop of this result query:
```
SELECT
  C.TABLE_NAME AS tableName,
  C.COLUMN_NAME AS columnName,
  C.DATA_TYPE AS type,
  C.CHARACTER_MAXIMUM_LENGTH AS size,
  C.TABLE_SCHEMA as tableSchema,
  C.TABLE_CATALOG AS tableCatalog,
  DB_NAME() as dbName,
  C.COLUMN_DEFAULT as defaultValue,
  C.IS_NULLABLE as isNullable,
  TC.CONSTRAINT_TYPE as constraintType,
  CONCAT(
    C.TABLE_CATALOG,
    '/',
    C.TABLE_SCHEMA,
    '/',
    (
      CASE
        WHEN T.TABLE_TYPE = 'VIEW' THEN 'views'
        ELSE 'tables'
      END
    ),
    '/',
    C.TABLE_NAME,
    '/',
    C.COLUMN_NAME
  ) AS tree
FROM
  INFORMATION_SCHEMA.COLUMNS C
  LEFT JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE AS KCU ON (
    C.TABLE_CATALOG = KCU.TABLE_CATALOG
    AND C.TABLE_NAME = KCU.TABLE_NAME
    AND C.TABLE_SCHEMA = KCU.TABLE_SCHEMA
    AND C.TABLE_CATALOG = KCU.TABLE_CATALOG
    AND C.COLUMN_NAME = KCU.COLUMN_NAME
  )
  LEFT JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS AS TC ON (
    TC.CONSTRAINT_NAME = KCU.CONSTRAINT_NAME
    AND TC.TABLE_SCHEMA = KCU.TABLE_SCHEMA
    AND TC.TABLE_CATALOG = KCU.TABLE_CATALOG
  )
  JOIN INFORMATION_SCHEMA.TABLES AS T ON C.TABLE_NAME = T.TABLE_NAME
  AND C.TABLE_SCHEMA = T.TABLE_SCHEMA
  AND C.TABLE_CATALOG = T.TABLE_CATALOG
WHERE
  C.TABLE_CATALOG = DB_NAME()
  AND (C.COLUMN_NAME = 'Project' OR   C.TABLE_NAME = 'Project')
ORDER BY
  C.TABLE_NAME,
  C.ORDINAL_POSITION
```

**Comment by omiba** [comment]
Below is the output of your query:
`
"tableName","columnName","type","size","tableSchema","tableCatalog","dbName","defaultValue","isNullable","constraintType","tree"
"v_CommissionList","Project","nvarchar",222,"dbo","**DATABASE**","**DATABASE**","","YES","","**DATABASE**/dbo/views/v_CommissionList/Project"
"v_EX_Search","project","nvarchar",100,"dbo","**DATABASE**","**DATABASE**","","NO","","**DATABASE**/dbo/views/v_EX_Search/project"
"v_TE_Search","project","nvarchar",100,"dbo","**DATABASE**","**DATABASE**","","NO","","**DATABASE**/dbo/views/v_TE_Search/project"
`

There are no tables that I see named "Project" in the database that's being connected to.

**Comment by mtxr** [comment]
@omiba I'm realeasing a new version. Will be available shortly (v0.17.18).

I've changed the tree separator for something uncommon. I believe it can fix your issue. I couldn't reproduce it here.

Let me know how it goes.

**Comment by mtxr** [comment]
Reopening. Closed by mistake

**Comment by omiba** [comment]
Confirmed that the issue is not happening any longer.  Thanks!

**Comment by mtxr** [comment]
@omiba thanks!
