### ISSUE TITLE
HANA database support

### ISSUE THREAD

**Issue by michalwiecz** [mtxr/vscode-sqltools#20]
> This is a guideline to help us to understand SQLTools Issues. 
> 
> You don't need to stick to this, but please try to guide us to reproduce the errors or understand your feature requests.

### Issue Type

* [ x] Feature Request
* [ ] Bugfix/Errors
* [ ] Questions
* [ ] Other

### Prerequisites (For bugfixes)

* [ ] Are you running the latest version?
* [ ] Did you check the logs?
* [ ] Did you check the Setup?

### Description

[Description of the bug or feature]
I would like to see a HANA database support 
### Steps to Reproduce (For bugfixes)

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

- *Version*: vX.Y.Z
- *OS*: ...
- *SGDB*: MySQL, PostgresSQL...

You can get this information from executing `SQLTools: Version` from VSCode `Quick Open`.

**Comment by mtxr** [comment]
Hey @michalwiecz , could you please submit a pull request of this feature?

As you are a user that understands the needs for HANA db, you could follow this commit mtxr/vscode-sqltools@6cc9774d867b70054b5902e7d0846d2366527012 and use this lib https://github.com/SAP/node-hdb to accomplish the same result that I've got with Postgres. Is it ok?

**Comment by mtxr** [comment]
Closing due lack of response and iteraction.
