### ISSUE TITLE
Results window header doesn't stay locked to results

### ISSUE THREAD

**Issue by omiba** [mtxr/vscode-sqltools#201]
**Describe the bug**
After selecting a bunch of data with lots of columns that go beyond the screen, when you initially scroll back and forth it works fine, but after going off the tab and resizing a few of the column widths it loses the lock between the header and the data.

**To Reproduce**
1. Run a query with enough columns to go past the end of your screen (so it will scroll left and right)
2. Scroll left and right
3. Resize one of the columns
4. Scroll left and right
5. Navigate to another tab (could be the sql one you executed or another)
6. Navigate back to the results tab
7. Scroll left and right
8. Resize one of the columns
9. Scroll left and right

This process reproduced the issue for me every time.

**Expected behavior**
The header row and the data rows should always match the data below the header.

**Screenshots**
Sorry for having to pixelate, but watch around the pixelation and you can see that the data is moving but the header is not.
https://cl.ly/f490acdc234e

**Desktop (please complete the following information):**
 - SQLTools Version [v0.17.18]
 - VSCode Version: [1.33.1]
 - Dialect Used: [MSSQL]
 - OS: [Mac]

**Comment by mtxr** [comment]
No problem @omiba.

I'll work on that, I got it reproduced here, doesn't seem hard to fix. But I'll have time to fix it only tomorrow, ok?

Also thank you for donating! I you update the docs with your name, let me know if you don't want it or want to put another name.

**Comment by mtxr** [comment]
Fixes. To be released.
