### ISSUE TITLE
Sidebar database explorer only shows tables and views

### ISSUE THREAD

**Issue by weltherrschaf** [mtxr/vscode-sqltools#203]
**Describe the bug**
The only objects I'm shown in my sidebar database explorer are tables and views. 

**Expected behavior**
I expected to see my Stored Procedures, Triggers, Assembly, etc, that are in my databases.

**Desktop (please complete the following information):**
 - SQLTools Version v0.17.18
 - VSCode Version: 1.33.1
 - Dialect Used: MSSQL 2016
 - OS: Windows

**Additional context**
Querying works though, I did not test yet with other dialects as I'd have to set up a DB for this.

**Comment by mtxr** [comment]
That's expected. I didn't develop to list stored procedures yet for mssql, I need to put some effort on it.

Also this is a good first issue, someone can just add the queries to retrieve that information and it will start to work.

Would you like to try @weltherrschaf ? I can provide some guidance

**Comment by mtxr** [comment]
Hi @weltherrschaf!

How is it going with the extension? Is it working as expected now? Hope so!

Just came to remember, if you like the project, please consider a donation or reviewing it on VSCode marketplace. That you help it to keep evolving.

Thanks!
