### ISSUE TITLE
SSL Error when trying to connect in MySQL database

### ISSUE THREAD

**Issue by deadpyxel** [mtxr/vscode-sqltools#205]
**Describe the bug**
I am trying to setup a connection using the extension to my remote Azure MySQL database, and keep getting an error about SSL options

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the extension
2. Create a new connection to an azure MYSQL database
3. Try to connect
4. See error message: "ERROR: Error:  { [Error: UNKNOWN_CODE_PLEASE_REPORT: SSL connection is required. Please specify SSL options and retry."

**Expected behaviour**
The connection should happen and show me the database

**Screenshots**

**Desktop (please complete the following information):**
 - SQLTools Version 0.17.18
 - VSCode Version: 1.33.1 (installed via snap)
 - Dialect Used: MySQL
 - OS: Linux Ubuntu 18.04 LTS x64

If there's need of any additional information, please let me know.

**Additional context**

P.S.: I've been trying to get to the documentation, but I it never loads and times out.

**Comment by deadpyxel** [comment]
Update, I got it working after fiddling around with the project in my local environment. The extension site is down for me, but the docs inside the project helped me out to  work around (the non recommended practice). 

I would suggest that this error message was a bit clearer, since I had no idea which settings were missing.

Feel free to close this issue for now.

**Comment by mtxr** [comment]
@deadpyxel thanks for the update.

Can you describe what you did to fix it? I can improve the docs with your findings or you can send a PR with you suggestions.

Thanks!

**Comment by deadpyxel** [comment]
Sure, I'll open a PR. It's not an elegant solution, but It worked nonetheless.
