### ISSUE TITLE
Black boxes over cells of types 'json' and 'jsonb' in "SQLTools Results" (PostgreSQL)

### ISSUE THREAD

**Issue by KorneiDontsov** [mtxr/vscode-sqltools#207]
**Describtion**
"SQLTools Results" renders black boxes over cells of types 'json' and 'jsonb' for PostgreSQL database.

**To Reproduce**
1. Create and connect to PostgreSQL database
2. Run queries
```sql
CREATE TABLE json_test_table (id int, json_value json, jsonb_value jsonb);
INSERT INTO
    json_test_table
VALUES
    (1, '{}', '[]');
SELECT
    *
FROM
    json_test_table;
```
3. Third query gives described result

**Expected behavior**
No black boxes. Ideally there also should be a customization option to get json formatted. 

**Screenshots**
![image](https://user-images.githubusercontent.com/18506086/57179411-5909d380-6e86-11e9-9455-c7183e889fe3.png)

**Desktop:**
 - SQLTools Version: 0.17.18
 - VSCode Version: 1.33.1
 - Dialect Used: PostgreSQL
 - OS: Windows Version 1809 (OS Build 17763.253)
 - PostgreSQL Version: 11

**Comment by mtxr** [comment]
Hi @KorneiDontsov!

How is it going with the extension? Is it working as expected now? Hope so!

Just came to remember, if you like the project, please consider a donation or reviewing it on VSCode marketplace. That you help it to keep evolving.

Thanks!

**Comment by KorneiDontsov** [comment]
Hi @mtxr!
I became your patreon and reviewed the extension. Thank you for you work! All is working pretty good. Nice to meet the new releases. It just keeps getting better and better :)

**Comment by mtxr** [comment]
Thanks @KorneiDontsov!

Glad to hear that :smiley: !

Let's keep it moving forward!

Have a great week,

Best regards,
@mtxr
