### ISSUE TITLE
Oracle Procedures and Functions Support

### ISSUE THREAD

**Issue by mtxr** [mtxr/vscode-sqltools#208]
**Describe the solution you'd like**
We need to add the same support we already have for stored procedures/functionsin PostgeSQL, MySQL and MSSQL to Oracle.

**Additional context**
There is a query I've used in this project for Sublime Text, see: 
https://github.com/mtxr/SublimeText-SQLTools/blob/ca45799b0b1699280478b464a1bc4a44fe4d5454/SQLTools.sublime-settings#L348

The problem is the currently I can't test too much oracle, I've been far way from it for so long that I prefer to let someone with daily experience to do it.

Here is a commit that adds this feature for MSSQL, we basically need to do the same for Oracle and enhance that query provided above a bit.
Related commit: https://github.com/mtxr/vscode-sqltools/commit/e2295d8ef0526908e4357faf480d5d8d82be4bda

**Comment by mtxr** [comment]
@mickeypearce if you have time, please take a look at this, let me know what do you think.

**Comment by mickeypearce** [comment]
I will gladly do it. :+1: 

Just help me understand this functionality. It basically lists signatures of functions/procedures (parameters and return values data types) in explorer view. Standalone func/proc and package func/proc all under same tree node, is that correct?

**Comment by mtxr** [comment]
Yes! Thanks!

Internal functions should not be listed for now. I plan to list it after completing the intellisense in a separate folder of the tree

**Comment by mickeypearce** [comment]
For Oracle I think it should be better to keep the "original" structure:
- procedures
-- proc1()
-- proc2()
- functions
-- func1()
-- func2()
- packages
-- pck_1
---- func()
---- proc()
-- pck_2

or not? For example If you have 40-50 user packages with more than 1K proc/func it will get quite messy otherwise.

**Comment by mtxr** [comment]
That's up to you. It's just a change on the tree and we will achieve this. It does make sense to me. Thanks @mickeypearce
