### ISSUE TITLE
Store connections somewhere else than settings

### ISSUE THREAD

**Issue by jordyvandomselaar** [mtxr/vscode-sqltools#210]
Would it be possible to store connections somewhere else than in the config of VSCode? I sync my settings with a public gist and I don't want production credentials in there.

**Comment by mickeypearce** [comment]
I agree. I would suggest maybe adding a setting for specifing a DB connection configuration file, e.g: `"sqltools.connectionsConfigPath"`.

Also making the specification extension-independent, a general DB configuration that could be shareable between different extension for DB connection, e.g:
```json
{
"connections": [
    {
      "askForPassword": true,
      "connectionTimeout": 30,
      "database": "dev",
      "dialect": "OracleDB",
      "name": "hr",
      "username": "hr"
    }
]
}
```

**Comment by mtxr** [comment]
Agreed! 

@jordyvandomselaar would you like to take a shot and submit a PR for that?

**Comment by jordyvandomselaar** [comment]
@mtxr Thanks for the reply! I'll have a look when I can, I've never touched VS code plugins before ( I only switched from PHPStorm to VSCode a week ago) so it might take some time.

I'm excited to learn about the plugin system though, should be a learning experience =)

**Comment by mtxr** [comment]
Useful information:

https://code.visualstudio.com/docs/languages/json
https://www.npmjs.com/package/comment-json

Requirements:

1. Support json with comments
2. Include Connections schema somewhere else to allow autocomplete when not using vscode settings file

**Comment by jordyvandomselaar** [comment]
Hi @mtxr,

I stopped using VSCode so I won't be able to fix this issue after all, my sincerest apologies for that.  It would be awesome if someone else could help out!

**Comment by aaronsteers** [comment]
Related to: #479

**Comment by gjsjohnmurray** [comment]
Closing in favour of #927

**Comment by davidt4444** [comment]
You can store any of the project setting in the global user settings. I usually just copy them over to avoid having them in my project that I store on github.

The global user settings are stored here.
Windows %APPDATA%\Code\User\settings.json.
macOS $HOME/Library/Application\ Support/Code/User/settings.json.
Linux $HOME/.config/Code/User/settings.json.
