### ISSUE TITLE
SAP Hana database support

### ISSUE THREAD

**Issue by ariel-bentu** [mtxr/vscode-sqltools#212]
Hello,
Before I put the effort to prepare a Pull requestm I'd like to know if you would welcome a new dialect for SAP Hana.

Many thanks,
Ariel

**Comment by mtxr** [comment]
Absolutely @arial-bentu!

Go for it. I'm totally welcome with contributions, dialects is were I need it most since I don't know all of them.
Please, go ahead and let me know if you need any help/guidance on it!
Welcome aboard!

**Comment by mtxr** [comment]
Related to #20.

**Comment by ariel-bentu** [comment]
One more important question: Would you consider changing the license to something less viral? preferablly Apache, Eclipse ot similar?
Thanks

**Comment by mtxr** [comment]
I need to check the differences first, but I don't see why not to change.

What do you want to achieve with this new licensing?

**Comment by ariel-bentu** [comment]
As far as I know GPL, if I use it in our products, it requires that my product becomes open source.
I would like to prepackage your extension in our bundle.

**Comment by mtxr** [comment]
Ok. Will need some time to check it, because I believe we are using some GPL libs too.

I can't check it right now, is it ok if I answer it tomorrow? I'll be checking the licenses here https://choosealicense.com/licenses/, also I'll take a look at Eclipse license that I don't know

**Comment by ariel-bentu** [comment]
Sure. Thanks

בתאריך יום ג׳, 7 במאי 2019, 14:53, מאת Matheus Teixeira ‏<
notifications@github.com>:
