### ISSUE TITLE
Integrated Authentication not working with Mac and MSSQL

### ISSUE THREAD

**Issue by raedwa01** [mtxr/vscode-sqltools#214]
I know that there have been open issues with Trusted Connections and WIndows.

I am using a mac.  I use kinit to sync with the domain and can do trusted connection using the command line MSSQL tools and the Azure Data Studio.  

Was hoping your DB tool was a good way to get the features into VSCode.

I created a connection to my SQL server and got this response:

```
ERROR: Error:  { [Error: Login failed. The login is from an untrusted domain and cannot be used with Integrated authentication.
	at handleResponse (/Users/redwards/.vscode/extensions/mtxr.sqltools-0.17.18/extension.js:534:48)
	at processMessageQueue (/Users/redwards/.vscode/extensions/mtxr.sqltools-0.17.18/extension.js:361:17)
	at Immediate.module.exports.setImmediate (/Users/redwards/.vscode/extensions/mtxr.sqltools-0.17.18/extension.js:345:13)
	at runCallback (timers.js:696:18)
	at tryOnImmediate (timers.js:667:5)
	at processImmediate (timers.js:649:5)] code: -32001, data: { dialect: 'MSSQL', dialectOptions: {} } }
```

**Comment by mtxr** [comment]
Hi @raedwa01!

I need to take a look on this. I don't have a way to test it on Mac right now, but I'm pretty sure we can do this. I've done it before in an old project.

Meanwhile, @ransagy I know you are using SQLTools with MSSQL in Azure as well, if you have any tips you could share, please give us a hand here, I'm blind for a moment. lol

**Comment by mtxr** [comment]
@raedwa01 I did a quick search here because I thought I had seen it before, and I was right.

We similar issues before, take a look at #61, #126 and #129.

If that fixes you problem, please, let me know exactly what you did. I'll update the docs to include that guide.

If it works and you want to updates the docs, please go ahead and open a PR, I'll be very thankful!

**Comment by ransagy** [comment]
All our Azure SQL connections are SQL authentication based and routed through a VPN when working remote, So I'm afraid my experience isn't very applicable here.

**Comment by mtxr** [comment]
@raedwa01 did you get it working?

**Comment by SciFreakholic** [comment]
Hello, please excuse my ignorance, but is it possible to connect with integrated credentials? I've been trying to do that in Windows with no successful results. Thanks in advance.

**Comment by mtxr** [comment]
@raedwa01 any updates?

@SciFreakholic We similar issues before, take a look at #61, #126 and #129. Keep me posted

**Comment by mtxr** [comment]
Closing due a lack of response.
