### ISSUE TITLE
[Feature Request] Oracle: Add toggle setting for table/column lookup

### ISSUE THREAD

**Issue by Anon232** [mtxr/vscode-sqltools#218]
Currently for the Oracle dialect the script that retrieves all tables/columns from the database has a condition where the owner of the objects must equal the current logged in user. This is a problem for me personally since where I am at, all the objects are owned by business accounts created and managed by our DBA's. 

It would be great to have some kind of setting where we can toggle whether to ignore this condition in the case where the objects we want listed are owned by other user accounts.

As a personal workaround I've been cloning this project and making a modification to queries.ts in the oracle dialect and removing the "where c.owner = user" conditions, unfortunately this breaks every time the extension is updated.

**Comment by mickeypearce** [comment]
Thanks for the request. 👍 

Listing objects of all DB schemas is very useful. I am thinking about a extension setting in the manner of "sqltools.onlyUsersObjects" because with large databases with many schemas, it takes quite some time to load all the schemas and objects.

The other option would maybe be to add a property to connections, for example named "schema", that would be useful in cases where your connection user is not the owner of objects in your DB:

```
{
  "dialect": "OracleDB",
  "name": "oracledb1",
  "username": "devuser",
  "schema": "hr"
...
}
```
Maybe both? 😄

**Comment by Anon232** [comment]
Oh yeah for sure, this does create a bit of a "loading" period for objects to load because we have a rather large database so all the tables in each schema take a while to load.

I think both settings should exist. What would be useful for me is to have the onlyUsersObjects set to false, and I can include a JSON config as follows:

{
  "dialect": "OracleDB",
  "name": "oracledb1",
  "username": "devuser",
  "schemas": ["hr", "student", "payroll"]
...
}

Our database has over 20 schemas but I only deal with about 3 of them, so there's no point to load all the other db objects.

**Comment by mickeypearce** [comment]
You are right. That is exactly what exists in Oradew, although I never had a chance to properly test it:
https://github.com/mickeypearce/oradew-vscode/blob/13f9056b778256b3455dc4af6762de5c72ed5285/resources/dbconfig-schema.json#L69-L71
(sorry for cross-reference)

For loading, eventually a partial loading (for object types) or similar will be needed I guess...

**Comment by mtxr** [comment]
Merging into #322
