### ISSUE TITLE
Add date to changelog entries

### ISSUE THREAD

**Issue by Liturgist** [mtxr/vscode-sqltools#220]
Please add a date for the changelog entries so that the user can know when it became available or fixed.

**Comment by mtxr** [comment]
Will do. But for now you can check the dates here: https://github.com/mtxr/vscode-sqltools/releases

Is it ok?

I'll update the changelog on next release

**Comment by Liturgist** [comment]
Thanks for letting me know about dates in the history tree. I will
still be helpful to see them in the changelog. Thanks.

**Comment by mtxr** [comment]
I've also added on changeling. At least for the most recent versions
