### ISSUE TITLE
ER_UNKNOWN_TABLE: Unknown table 'parameters' in information_schema

### ISSUE THREAD

**Issue by NMSAzulX** [mtxr/vscode-sqltools#221]
**Describe the bug**
INFO: Executing SQLTools.selectConnection
ERROR: Error:  ER_UNKNOWN_TABLE: Unknown table 'parameters' in information_schema
ERROR: Error:  { [Error: ER_UNKNOWN_TABLE: Unknown table 'parameters' in information_schema
	at handleResponse (c:\Users\Administrator\.vscode\extensions\mtxr.sqltools-0.18.2\extension.js:2164:48)
	at processMessageQueue (c:\Users\Administrator\.vscode\extensions\mtxr.sqltools-0.18.2\extension.js:1991:17)
	at Immediate.module.exports.setImmediate (c:\Users\Administrator\.vscode\extensions\mtxr.sqltools-0.18.2\extension.js:1975:13)
	at runCallback (timers.js:696:18)
	at tryOnImmediate (timers.js:667:5)
	at processImmediate (timers.js:649:5)] code: -32001, data: { dialect: 'MySQL', dialectOptions: {} } }

![image](https://user-images.githubusercontent.com/16236903/57500004-4541ef80-7314-11e9-93cf-d8b2bf0fe88f.png)

**Comment by mtxr** [comment]
Which version of MySQL are you using?

**Comment by mtxr** [comment]
I'll release a new version with a possible fix. You are probably using MySQL older than v5.5 I believe by the searches I've made.

Let me know if it works for you.

**Comment by NMSAzulX** [comment]
@mtxr 
Thanks.  There is another problem :

>"INFO: Executing SQLTools.selectConnection
ERROR: Error:  ER_BAD_FIELD_ERROR: Unknown column 'f.data_type' in 'field list'
ERROR: Error:  { [Error: ER_BAD_FIELD_ERROR: Unknown column 'f.data_type' in 'field list'
	at handleResponse (C:\Users\Administrator\.vscode\extensions\mtxr.sqltools-0.19.1\extension.js:919:48)

MySql Version: 5.1.73. 
Is the Mysql version too low?

**Comment by mtxr** [comment]
Yes, the extension works better for 5.5 or newer. 

But we can make it work for 5.5 or older, but it requires some adjustments, also some features will be disabled. But this happens in other tools as well.

For you case, the only feature that won't work would be the functions/procedures having the type signature.

@NMSAzulX If I show you where do we need to change, would you like to try to change it and test?

https://github.com/mtxr/vscode-sqltools/blob/ba7b2056014c3c4c8829bb3e07498adf58176ff3/packages/core/dialect/mysql/queries.ts#L144-L180

This is the query that get functions/procedures. Basically you need to remove the fields that does not exist in this version, like `f.data_type`, compile and test. Once it works, you can submit a PR with the changes.

**Comment by NMSAzulX** [comment]
@mtxr Thank you very much. First of all, I will upgrade the database. I'll learn about plug-in development later. I have to say, this plugin is really great.      : )

**Comment by mtxr** [comment]
Ok, thanks for reaching me with this issue.

I'll try to take some time to make it work for older versions, but it's not a priority since MySQL 5.1 has been replaced a long time ago

Let me know how if you need anything else

**Comment by NMSAzulX** [comment]
This is a mistake in my work, we did not upgrade in time. Thanks to the author's enthusiasm, I have no other questions at the moment.
