### ISSUE TITLE
Oracle datatypes in stored procedures

### ISSUE THREAD

**Issue by callamaris** [mtxr/vscode-sqltools#222]
**Is your feature request related to a problem? Please describe.**
Oracle 12c Database
When clicking on a stored procedure, the procedure signature will be inserted into the current editor.

This is a very usefull feature, but unfortunately it does not propperly show parameter datatypes. 

1. it does not show user defined data types, but just the base type OBJECT
2. It shows __PL/SQL BOOLEAN__ instead of __BOOLEAN__
3. Some other minor issues (will comment this later)

**Describe the solution you'd like**
This will return user defined data types and boolean propperly
````SQL
select
CASE WHEN TYPE_NAME IS NOT NULL -- user defined types
       THEN TYPE_OWNER || '.' || TYPE_NAME  || CASE WHEN TYPE_SUBNAME IS NOT NULL
                                                      THEN '.' || TYPE_SUBNAME
                                               END
     WHEN PLS_TYPE IS NOT NULL -- oracle build in data types
       THEN PLS_TYPE
     ELSE DATA_TYPE -- fallback for generic record types and future oracle versions
END ORA_TYPE
from user_arguments
;
````

**Optional**

Some other usefull information in USER_ARGUMENTS (could be printed as comments):

- Column IN_OUT
  - IN = Input parameter
  - OUT = Output parameter (this is the way, oracle handles multiple return values)
  - IN OUT = similar to pass as reference in other languages
- Column ARGUMENT_NAME
  - Oracle supports named parameters, which is the recommended way to pass parameters to a procedure. Example:
````SQL
my_procedure(
   argument1 => value1
  ,argument2 => value2
);
````
- Columns DEFAULTED and DEFAULT_VALUE
  - Optional parameter (Y / N) and default value
- Column POSITION=0
  - this is the return value data type of an plsql function

Formatting:
 - Line breaks after each parameter would increase readability

The formatting i prefere to use:
````SQL
my_procedure( /* RETURNING VARCHAR2 */
   argument1 => /* IN     */ BOOLEAN                       /* DEFAULT NULL */
  ,argument2 => /* IN OUT */ MY_USER.MY_USER_DEFINED_TYPE
);
````

**Comment by mickeypearce** [comment]
That would be really useful. Arguments and datatypes are read from the `args` column in `fetchFunctions` query:

https://github.com/mtxr/vscode-sqltools/blob/747ca71818f6125de279912c1130e1851c35ba3a/packages/core/dialect/oracle/queries.ts#L75

note:  `xmlagg` is used beacuse `listagg` exceeds 4000 in large procedures.

**Comment by callamaris** [comment]
Hi, i will look into it next week.

Listagg returns a varchar2, which is limited to 4000 characters in the sql engine but it can exceed 4000 characters when used in the plsql engine (up to ~32000 characters).

the only solution i could think of, is using a stored procedure instead. but creating stored procedures just for this purpose is a bad idea since it would break the whole thing when used with an user that does not have create procedure permission.

in a plsql application i would go for a stored procedure, but for a connection from an editor xmlagg is perfectly fine

**Comment by mickeypearce** [comment]
@callamaris , are you maybe working on this? if not I will go ahead...
