### ISSUE TITLE
Updating an existing global connection BUG.

### ISSUE THREAD

**Issue by shyce** [mtxr/vscode-sqltools#224]
**Describe the bug**
Editing connections doesn't work right. Defaults are displayed instead of the actual connection properties. After updating a connection, the port resets to default because of the prior issue and the old connection name re-appears.

**To Reproduce**
1. Create a new connection with a non-standard port under MySQL (global:3307).
2. Edit the connection and change the name.
3. The port defaults back to 3306 and the connection doesn't work. A new connection with the old name appears when you double-click the new connection name.
4. Reboot VSCode and the connection works, but editing the connection shows the wrong port (3306).

**Expected behavior**
I expected that when I edit the connection, no defaults are used but the actual settings are displayed. When updating the port, the old connection re-appears when trying to reconnect - this is a confusing bug.

**Desktop (please complete the following information):**
 - SQLTools Version: 0.18.2
 - VSCode Version: 1.33.1
 - Dialect Used: MySQL
 - OS: Linux

**Comment by mtxr** [comment]
Hi @shyce !

How is it going with the extension? Is it working as expected now? Hope so!

Just came to remember, if you like the project, please consider a donation or reviewing it on VSCode marketplace. That you help it to keep evolving.

Thanks!
