### ISSUE TITLE
Add support for instanceName option for MSSQL

### ISSUE THREAD

**Issue by SpudNyk** [mtxr/vscode-sqltools#225]
**Is your feature request related to a problem? Please describe.**
I cannot connect to a sql server configured with instances as I cannot specify an instance name.

**Describe the solution you'd like**
Add support for the [instanceName](https://github.com/tediousjs/node-mssql/tree/v4.3.1#tedious) attribute in the connection options for MSSQL.

**Comment by mtxr** [comment]
This is already supported.

Reference: https://github.com/tediousjs/node-mssql/tree/v4.3.1#config

![image](https://user-images.githubusercontent.com/707561/58142129-40d2dc00-7c1c-11e9-87e7-82bfe515242f.png)

**Comment by SpudNyk** [comment]
Yes the tedious driver supports it but the extension filters out “unknown” options, so it is not passed through to mssql/tedious.

**Comment by mtxr** [comment]
I know, but if you add that to your server address, it should work for sure

**Comment by mtxr** [comment]
```json
{
  "name": "MSSQL",
  "server": "localhost\\instance",
  "dialect": "MSSQL",
  "port": 1433,
  "database": "test_db",
  "username": "sa",
  "askForPassword": false,
  "password": "root(!)Password",
  "connectionTimeout": 15,
  "mssqlOptions": {
    ... // options
  }
}
```
@SpudNyk isn't it working like this?

**Comment by SpudNyk** [comment]
Ok thanks I’ll give that a try tomorrow!

**Comment by mtxr** [comment]
Ok, let me know how it goes and if needed you can always re-open the issue.

Keep me posted

**Comment by SpudNyk** [comment]
Following up, that worked perfectly, though I could have sworn I had tried that method earlier.
My mistake and thank you for the help.
