### ISSUE TITLE
A complete SQL statement will be truncated at a location that may be a keyword

### ISSUE THREAD

**Issue by Drogon1573** [mtxr/vscode-sqltools#226]
**Bug information**
If your SQL statement exists as part of the SQL keyword, SQLTools will truncate here. 

**How to make this bug shows up**
1. Create a table in `SQL Server Express 2017`, which the table name is called `[Market].[dbo].[Goods]`. The table has 5 columns. They are `[Name]`, `[Series]`, `[TradeMark]`, `[MadeIn]` and `[Price]`. 
2. Connect to database `[Market]` with SQLTools. 
3. Show table records of `[Market].[dbo].[Goods]` using keyboard shortcuts `Ctrl+E Ctrl+S`. 
4. Bug has appeared! In `SQLTools Results` window, there are label `Showing 1 [Market].[dbo].[Goods] records` - which is expected - and `ods]` - which is unexpected. 
5. The first label shows results exactly what I want, but the second label returns nothing and its query statement is also a mess. 

**Expected behavior**
I hope that SQLTools can ignore keywords `GO` in word `Goods` and do not truncate it. 

**Screenshots**
![Database Details](https://user-images.githubusercontent.com/49941141/57567072-89adb800-7406-11e9-8315-e84782bb9ac3.png)
![Reproduce Guide 1](https://user-images.githubusercontent.com/49941141/57567208-61bf5400-7408-11e9-9190-d7f70fe8fed4.png)
![image](https://user-images.githubusercontent.com/49941141/57567238-d5616100-7408-11e9-9050-ccd7238eb97f.png)
![image](https://user-images.githubusercontent.com/49941141/57567307-967fdb00-7409-11e9-96e1-7ac67a4b9a4e.png)
![image](https://user-images.githubusercontent.com/49941141/57567328-f9717200-7409-11e9-9182-23acbd4518aa.png)

**Desktop (please complete the following information):**
 - SQLTools Version: 0.18.2
 - VSCode Version: 1.33.1 (system setup)
 - Dialect Used: MSSQL, with SQL Server Express 2017
 - OS: Windows 10 Home China 1809 17763.475

**Additional context**
I am a Simplified Chinese user and this is my first time to report an issue on GitHub. Due to the use of the Simplified Chinese system, the menu buttons and prompts in the screenshot are all in Chinese, please forgive me.

**Comment by ransagy** [comment]
I've noticed this too; I believe this is the `GO` keyword being identified in the middle of such queries/names and interpreted as a split in the queries.

**Comment by Drogon1573** [comment]
The Following advice was suggested by my classmate. Is it easy to realize? 

> Use full word matching to solve this problem.
>
> If the GO or other keyword is surrounded by only whitespace characters `\s`, newline characters (`\r`, `\n`), or on a separate line, then these words are recognized as keywords; otherwise, they are associated with adjacent characters (strings) and treated as a whole, not identified as a keyword.

**Comment by ransagy** [comment]
I haven't looked through the codebase, so only @mtxr can say better, but i assume it's a case of just correcting a regex in a similar manner to what your classmate suggested, yeah.

**Comment by mtxr** [comment]
Hey guys, I'll take a look at this today and release it in the next release as well.

The parser is a third-party based code, so I'll need to dig a bit deeper to fix and write tests to avoid this from happening in the future.

**Comment by Drogon1573** [comment]
I received an e-mail from GitHub that you fixed this bug and closed the issue. I can't wait reciving the new release and update to it! Thanks @mtxr 🎉🎉🎉

**Comment by mtxr** [comment]
Hi @Drogon1573!

How is it going with the extension? Is it working as expected now? Hope so!

Just came to remember, if you like the project, please consider a donation or reviewing it on VSCode marketplace. That you help it to keep evolving.

Thanks!

**Comment by Drogon1573** [comment]
@mtxr 

I have received your comment. Thank you very much for your ability to fix the bug in time. Now it can work correctly. 

![image](https://user-images.githubusercontent.com/49941141/58758371-23bbd880-854d-11e9-977d-ab967b6266fd.png)

![image](https://user-images.githubusercontent.com/49941141/58758479-2ff46580-854e-11e9-9e60-055d9207729d.png)

I want to donate to your project. But I have no credit cards to donate in another currency. Sorry for that. 😭

**Comment by mtxr** [comment]
@Drogon1573 nice!

No problem, just please, take a few minutes to review it at https://marketplace.visualstudio.com/items?itemName=mtxr.sqltools

That will help more people find the extension as well. More people using, more feedbacks, more improvements, more donations :smiley: 

Thanks!
