### ISSUE TITLE
Connection indicator/progress

### ISSUE THREAD

**Issue by ransagy** [mtxr/vscode-sqltools#229]
I think it would be a better and more useful user experience if there was some UI element that shows a connection is in progress.

Right now, After connecting, Seemingly "nothing" happens. If we connected, At some point the connection name in the left bottom status bar would change to the connection name. If it failed, We would get a notification, but either might take quite a few seconds where the user has no idea what's going on.

Perhaps add some indication/text to the status bar, possibly a loading animation of some kind, to let the user know a connection attempt is in progress.

**Comment by mtxr** [comment]
There is a new api for progress exchange between the language server and the UI about to be release by vscode team.

I plan to take a look at this once they release it, ok?

But definitely would be great to have a better indicator for that.

**Comment by mtxr** [comment]
It uses the withProgress api defined here: https://code.visualstudio.com/api/references/vscode-api#window

But it's controled by the language-server instead of the window instance

**Comment by ransagy** [comment]
Yeah, definitely, let's take advantage of prior work done by the VSCode team when it's available.

**Comment by mtxr** [comment]
VSCode's June release will bring this to stable channel!

**Comment by ransagy** [comment]
Nice! Looking forward to it :]
