### ISSUE TITLE
Connection via SSH

### ISSUE THREAD

**Issue by sideshow-systems** [mtxr/vscode-sqltools#230]
Right now I'm using Sequel Pro on my mac to connect to MySQL databases. Here I do the connection via SSH. A configuration looks like this:

`
MySQL-Host: localhost
User: dbuser
Pass: dbpass
Database: dbname
Port: 3306 (optional)

SSH-Host: projectname.vagrant
SSH-User: vagrant
SSH-Key: path/to/key
SSH-Port: 22 (optional)
`

It would be great if this would be implemented so I could use the same configuration in the sqltools.

The only alternative I can think of is to tweak my VM or to do a port-tunnel via ssh in the terminal to make this work.

**Comment by jeremypoulter** [comment]
Would this help: https://www.npmjs.com/package/ssh2 ?

Used by https://github.com/liximomo/vscode-sftp/ whick works really well in VSCode on both Linux and Windows (not tried Mac OS)

**Comment by mtxr** [comment]
Yeah, that would be cool.

I'm a bit in a hurry now, but I'll give it a try as soon as possible.

Right now you can do the tunneling using `ssh` command as seen here: 
https://www.ssh.com/ssh/tunneling/example

If any of you guys want to try to develop it, I'll be very thankful!

**Comment by sideshow-systems** [comment]
Yup, no problem there with an ssh tunnel. I'll try to implement this feature when I have some time for that.

**Comment by mtxr** [comment]
Thanks! 

I'll close this for now since we have an working option.
