### ISSUE TITLE
"SQLTools Results" converts values of "timestamp" to a local time

### ISSUE THREAD

**Issue by KorneiDontsov** [mtxr/vscode-sqltools#231]
**Describe the bug**
"SQLTools Results" converts values of type "timestamp without timezone"(same as just "timestamp") to a local time like they're of UTC time zone.

**To Reproduce**
1. Run query
```sql
SELECT timestamp '1970-01-01 00:00:00'
```
2. Look at result in "SQLTools Results": it has an offset corresponded to your local time zone.

For example, I'm in GMT 3, so I get the result `1969-12-31T21:00:00.000Z`.

**Expected behavior**
Timestamps without time zone must remain unchanged.

**Screenshots**
![image](https://user-images.githubusercontent.com/18506086/57778530-ea9dfe80-772c-11e9-94d8-0ec844a5ad2b.png)
![image](https://user-images.githubusercontent.com/18506086/57778543-f12c7600-772c-11e9-9de7-1de2bded1e5e.png)

**Desktop (please complete the following information):**
 - SQLTools v0.18.2
 - VSCode 1.33.1
 - OS: Windows Version 1809 (OS Build 17763.253)

**Comment by keepscoding** [comment]
Is it the same problem when i'm using date type in **postgres** and it'll show date+time with timezone offset?
