### ISSUE TITLE
Support dialect libs extra options without filtering

### ISSUE THREAD

**Issue by mrchypark** [mtxr/vscode-sqltools#235]
plz let me know how to set path

Thank you in advance.

**Comment by mrchypark** [comment]
I tried link below `Additional security options` section.


https://dev.mysql.com/doc/dev/connector-nodejs/8.0/tutorial-Secure_Sessions.html

**Comment by mtxr** [comment]
We need to develop this feature.

By the link you sent, I believe you are using xprotocol, right?

**Comment by mrchypark** [comment]
Oh, I just fallow you guys docs like below.

https://vscode-sqltools.mteixeira.dev/connections/mysql

**Comment by mtxr** [comment]
@mrchypark next release will allow you to set ssl ca.

If you are using MySQL default protocol, just to like this:
```json
{
  "host": "localhost",
  "dialect": "MySQL",
  ...,
  "mysqlOptions": {
    "ssl": true,
    "sslOptions": {
      "ca": "/path/to/ca.pem", // Should be a filename. It will be automatically read and used.
      "crl": "/path/to/crl.pem" // Should be a filename. It will be automatically read and used.
    }
  }
}
```

If you are using MySQL xprotocol protocol, just to like this:
```json
{
  "host": "localhost",
  "dialect": "MySQL",
  ...,
  "mysqlOptions": {
    "ssl": true,
    "sslOptions": {
      "ca": "/path/to/ca.pem",
      "crl": "/path/to/crl.pem"
    }
  }
}
```

**Comment by mtxr** [comment]
@mrchypark How is it going with the extension? Is it working as expected now? Hope so!

Just came to remember, if you like the project, please consider a donation or reviewing it on VSCode marketplace. That you help it to keep evolving.

Thanks!

**Comment by dfdgsdfg** [comment]
> I have `ca-cert.pem`, `client-key.pem` and `client-cert.pem` in my ssl connection but I don't find any documentation of `sslOptions` I can use. I tried
> 
> ```json
> "mysqlOptions": {
>                 "ssl": true,
>                 "sslOptions": {
>                     "ca-cert": "/path/to/ssl/ca-cert.pem",
>                     "client-key": "/path/to/ssl/client-key.pem",
>                     "client-cert": "/path/to/ssl/client-cert.pem"
>                 }
>             }
> ```
> 
> and this does not work.

sslOptions key should be 'ca', 'cert', 'crl', 'key', 'pfx'.

**Comment by renkun-ken** [comment]
I tried the following config but still access denied. I'm not sure if the entries are corresponding ones:

```json
"mysqlOptions": {
                "ssl": true,
                "sslOptions": {
                    "ca": "/path/to/ssl/ca-cert.pem",
                    "key": "/path/to/ssl/client-key.pem",
                    "cert": "/path/to/ssl/client-cert.pem"
                }
            }
```

**Comment by renkun-ken** [comment]
I alter user from `REQUIRE X509` to `REQUIRE SSL` and connect with the above ssl settings, and the following error occurs:

```
Error while preparing columns completions for connection jason@july ER_COL_COUNT_DOESNT_MATCH_PLEASE_UPDATE: Column count of mysql.proc is wrong. Expected 21, found 20. Created with MariaDB 100038, now running 100408. Please use mysql_upgrade to fix this error
```

**Comment by renkun-ken** [comment]
I alter user from `REQUIRE X509` to `REQUIRE SSL` and connect with the above ssl settings, and the following error occurs:

```
Error while preparing columns completions for connection user@host ER_COL_COUNT_DOESNT_MATCH_PLEASE_UPDATE: Column count of mysql.proc is wrong. Expected 21, found 20. Created with MariaDB 100038, now running 100408. Please use mysql_upgrade to fix this error
```
