### ISSUE TITLE
Incompatible with VSCode Remote Container

### ISSUE THREAD

**Issue by lando-cal** [mtxr/vscode-sqltools#239]
**Describe the bug**
While working in a the new Remote Container environment, connecting to a (container local) PGSQL server works, but any loaded tabs don't display.

**To Reproduce**
1. Create a remote container environment
2. Add a PGSQL container to the docker-compose
3. Use normal extension settings to connect to the container
4. Connection will work in tree, but when opening a table there will be no output.

**Expected behavior**
Tabs spawned from the extension should show data

**Desktop (please complete the following information):**
 - SQLTools Version: 0.19.1
 - VSCode Version: 1.35.0-insider
 - Dialect Used: PostgreSQL
 - OS: Windows VSCode client, deploying VSCode server into a Debian Stretch container

**Additional context**

>>Edit: I found [this link](https://code.visualstudio.com/api/advanced-topics/remote-extensions#using-the-webview-api) that covers some basics on WebView over the remote protocol.

Connection settings:
```json
    "sqltools.useNodeRuntime": false,
    "sqltools.connections": [
        {
            "name": "PGSQL",
            "server": "postgres",
            "dialect": "PostgreSQL",
            "port": 5432,
            "database": "postgres",
            "username": "postgres",
            "askForPassword": false,
            "password": "<REDACTED>",
            "connectionTimeout": 15
        }
    ],
    "sqltools.autoConnectTo": ["PGSQL"],
    "sqltools.flattenGroupsIfOne": true,
    "sqltools.autoOpenSessionFiles": false,
```

**Comment by mtxr** [comment]
Hi @lando-cal!

Glad you are trying the new VSCode feature!

I need to take some time to check this. This new remote environment feature is pretty new and I didn't had time to dig into that yet, ok?

If you want to take a shot and contribute you can always count on me too.

**Comment by lando-cal** [comment]
Understandable!
I'm a bit busy this week, but I already planned on taking a shot at it when
I get a break in the workflow.
I just figured I'd put the issue in, in case anyone else comes looking for
it.
Thanks!

**Comment by mtxr** [comment]
Awesome! thanks @lando-cal !

**Comment by mtxr** [comment]
is it ok assign this issue to you, @lando-cal ?

take your time, you don't need to hurry with that because it's very new so we have time to work on that before a huge adoption.

**Comment by lando-cal** [comment]
Yep, totally fine!
I'll keep ya posted.

**Comment by mtxr** [comment]
@lando-cal any updates on this?

**Comment by lando-cal** [comment]
Not at the moment. I've been in the middle of a move. Should have my rig back up by end of next week though, this is top of my list if it hasn't been tackled by then.

⁣Get BlueMail for Android ​

**Comment by mtxr** [comment]
@lando-cal any updates on this?

**Comment by lando-cal** [comment]
I loaded it up in remote WSL, and it works fine.
Then I realized that the issue was about web view proxy-ing, which would in fact need a remote host to test properly..
Unfortunately, I don't have a container infrastructure up at the moment, so I'll have to circle back this afternoon.

**Comment by mtxr** [comment]
Ok, thanks @lando-cal. Keep us posted please
