### ISSUE TITLE
Connection use relative path of workspace

### ISSUE THREAD

**Issue by mitchellsimoens** [mtxr/vscode-sqltools#241]
**Is your feature request related to a problem? Please describe.**
I am using a sqlite connection, the path to the database file is the full, resolved path.

**Describe the solution you'd like**
Instead of a full path, use a relative path to the workspace. For example, it saved this to `.vscode/settings.json`:

```json
{
  "sqltools.connections": [
    {
      "database": "/Users/my-user/my-project/nested/dir/mydatabase.db",
      "dialect": "SQLite",
      "name": "my project database"
    }
  ]
}
```

If my workspace is opened up at the `/Users/my-user/my-project`, then I'd rather have this:

```json
{
  "sqltools.connections": [
    {
      "database": "./nested/dir/mydatabase.db",
      "dialect": "SQLite",
      "name": "my project database"
    }
  ]
}
```

The reason being, if I check in this `.vscode/settings.json`, my full path is likely not going to match anyone else's full path. The good news is, if I change the path manually, it will actually work just fine, I can connect to the sqlite database file and see the tables. So this is just about what is saved to `.vscode/settings.json`.

Maybe something like this:

```javascript
const path = require('path');
const databasePath = '/Users/my-user/my-project/nested/dir/mydatabase.db';
const database = path.relative(vscode.workspace.rootPath, databasePath);
// database should be "./nested/dir/mydatabase.db"
```

**Comment by mitchellsimoens** [comment]
Forgot to also mention that this full path was created when I used the connection wizard and used the picker to choose the file.

**Comment by mtxr** [comment]
You are right! If the file is inside of a workspace, it should be relative.

Would you mind submitting a PR? Your solution is half way there.

https://github.com/mtxr/vscode-sqltools/blob/05ebdc6080c6b588c91a1015c7f8d1ad3ff01476/packages/plugins/connection-manager/screens/settings.ts#L42-L52

We should basically do what you said before `commands.executeCommand` if the dialect is SQLite and the file is within a workspace folder.

I'm trying to go back and finish intellisense, so if you can help on this one, I would be very thankful!

**Comment by mitchellsimoens** [comment]
PR #255

**Comment by mtxr** [comment]
Hi @mitchellsimoens!

Just came to remember, if you like the project, please consider reviewing it on VSCode marketplace. That you help it to keep evolving.

Thanks!
