### ISSUE TITLE
TypeError: Cannot read property 'addItem' of undefined

### ISSUE THREAD

**Issue by saulfautley** [mtxr/vscode-sqltools#242]
**Describe the bug**
Just installed SQLTools for the first time and can't seem to get past this error after adding a new connection:
`Error while trying to create columns tree for MySQL Cannot read property 'addItem' of undefined`

**Screenshots**
![image](https://user-images.githubusercontent.com/2036475/58202775-b7cdaa80-7cd8-11e9-8a83-c1732c9ec507.png)
![image](https://user-images.githubusercontent.com/2036475/58202818-d92e9680-7cd8-11e9-9236-d970fc182eb9.png)
![image](https://user-images.githubusercontent.com/2036475/58202876-ff543680-7cd8-11e9-8379-aa879b91941a.png)

**Desktop (please complete the following information):**
 - SQLTools Version: 0.19.1
 - VSCode Version: 1.34.0
 - Dialect Used: MySQL
 - OS: Windows

**Additional context**
Using MySQL docker container as server. Databases show in the Connections pane, but they are a bit messed up and don't show all tables, etc.

**Comment by mtxr** [comment]
@saulfautley would you mind sharing the result of this query? Even with the explorer tree not working you should be able to run queries.

```SQL
SELECT
  C.TABLE_NAME AS tableName,
  C.COLUMN_NAME AS columnName,
  C.DATA_TYPE AS type,
  C.CHARACTER_MAXIMUM_LENGTH AS size,
  C.TABLE_SCHEMA as tableSchema,
  C.TABLE_CATALOG AS tableCatalog,
  C.TABLE_SCHEMA as tableDatabase,
  C.COLUMN_DEFAULT as defaultValue,
  C.IS_NULLABLE as isNullable,
  C.ORDINAL_POSITION,
  (
    CASE
      WHEN C.COLUMN_KEY = 'PRI' THEN TRUE
      ELSE FALSE
    END
  ) as isPk,
  (
    CASE
      WHEN KCU.REFERENCED_COLUMN_NAME IS NULL THEN FALSE
      ELSE TRUE
    END
  ) as isFk,
  CONCAT(
    C.TABLE_SCHEMA,
    '//SEP//',
    (
      CASE
        WHEN T.TABLE_TYPE = 'VIEW' THEN 'views'
        ELSE 'tables'
      END
    ),
    '//SEP//',
    C.TABLE_name,
    '//SEP//',
    C.COLUMN_NAME
  ) AS tree
FROM
  INFORMATION_SCHEMA.COLUMNS AS C
  LEFT JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE AS KCU ON (
    C.TABLE_CATALOG = KCU.TABLE_CATALOG
    AND C.TABLE_NAME = KCU.TABLE_NAME
    AND C.TABLE_SCHEMA = KCU.TABLE_SCHEMA
    AND C.TABLE_CATALOG = KCU.TABLE_CATALOG
    AND C.COLUMN_NAME = KCU.COLUMN_NAME
  )
  JOIN INFORMATION_SCHEMA.TABLES AS T ON C.TABLE_NAME = T.TABLE_NAME
  AND C.TABLE_SCHEMA = T.TABLE_SCHEMA
  AND C.TABLE_CATALOG = T.TABLE_CATALOG
WHERE
  C.TABLE_SCHEMA NOT IN ('information_schema', 'performance_schema', 'mysql', 'sys')
ORDER BY
  C.TABLE_NAME,
  C.ORDINAL_POSITION
```

If you prefer, you can send it to me via email: matheus@mteixeira.dev

What is happening is that somewhere in the tree we might have found a char that is breaking the tree creator, so I will need to now if we have an invalid char in the `tree` prop this query returns.

If you want to try to debug it and submit a PR, here is where it's breaking:

https://github.com/mtxr/vscode-sqltools/blob/05ebdc6080c6b588c91a1015c7f8d1ad3ff01476/packages/plugins/connection-manager/explorer/index.ts#L154

**Comment by saulfautley** [comment]
Looks like the issue is due to one of my databases having a `.` in its name. Tested with a fresh container, created a new database `test_1`, worked fine in SQLTools. Copied the database to `test_2.0`, refreshed SQLTools and immediately got the same error.

**Comment by mtxr** [comment]
Got it! Thanks! I'll fix that tonight

**Comment by mtxr** [comment]
Hi @saulfautley!

How is it going with the extension? Is it working as expected now? Hope so!

Just came to remember, if you like the project, please consider a donation or reviewing it on VSCode marketplace. That you help it to keep evolving.

Thanks!
