### ISSUE TITLE
command 'mysql.runQuery' not found

### ISSUE THREAD

**Issue by ZgrK** [mtxr/vscode-sqltools#247]
**Describe the bug**
**command 'mysql.runQuery' not found** This error showing when trying to run the query

**Screenshot**
[https://i.ibb.co/S7McLWp/Screen-Shot-2019-05-24-at-14-42-29.png](url)

**Desktop :**
 - SQLTools Version 0.19.1
 - VSCode Version:  1.34.0 (1.34.0)
 - Dialect Used: Mysql
 - OS: Mac

**Comment by mtxr** [comment]
Hi @ZgrK 

I believe we have a misunderstanding here. This command is from another extension, the MySQL extension, look:

https://github.com/formulahendry/vscode-mysql/blob/af46548fa0190ab4c6ab360aecbdedefcae3120a/package.json#L66-L70

I believe you have both extensions installed.

To run the query using SQLTools, you  need to setup a connection and use the command `CMD+e CMD+e` (or `SQLTools Connection: Run Query on command palette`), ok?

**Comment by ZgrK** [comment]
oo sorry :) I see my mistake everything working well now 👍
