### ISSUE TITLE
Failed to install dependencies for SAPHana Request 

### ISSUE THREAD

**Issue by dik111** [mtxr/vscode-sqltools#252]
OS:WIN10
VSCODE version ：1.33
SQLTools version: 0.19.1
When I try to install dependencies for SAP Hana , It reported the following error:

INFO: Executing SQLTools.selectConnection
INFO: Executing SQLTools.selectConnection
ERROR: Error:  { [Error: Request DependencyInstaller/install failed unexpectedly without providing any details.
	at handleResponse (C:\Users\11007166\.vscode\extensions\mtxr.sqltools-0.19.1\extension.js:919:48)
	at processMessageQueue (C:\Users\11007166\.vscode\extensions\mtxr.sqltools-0.19.1\extension.js:746:17)
	at Immediate.module.exports.setImmediate (C:\Users\11007166\.vscode\extensions\mtxr.sqltools-0.19.1\extension.js:730:13)
	at runCallback (timers.js:696:18)
	at tryOnImmediate (timers.js:667:5)
	at processImmediate (timers.js:649:5)] code: -32603, data: undefined }

Can somebody help me? 
Many thanks

**Comment by mtxr** [comment]
@ariel-bentu can you give a hand here?

**Comment by ariel-bentu** [comment]
Eventually, what runs under the hoods, is:
 
npm install @sap/hana-client@2.4.126 --@sap:registry=https://npm.sap.com

@dik111, Can you try run it directly in the command-line?

**Comment by dik111** [comment]
> Eventually, what runs under the hoods, is:
> 
> npm install @sap/hana-client@2.4.126 --@SAP:registry=https://npm.sap.com
> 
> @dik111, Can you try run it directly in the command-line?

HI @ariel-bentu,it got an error,here is the log:

verbose argv "E:\\Blog\\node.exe" "E:\\Blog\\node_modules\\npm\\bin\\npm-cli.js" "install" "@sap/hana-client@2.4.126" "--@SAP:registry=https://npm.sap.com"
verbose node v8.11.4
verbose npm  v5.6.0
error code E404
error 404 Not Found: @sap/hana-client@2.4.126

**Comment by ariel-bentu** [comment]
My mistake, the @SAP should be @sap (as it is in the code. try running this:
`npm install @sap/hana-client@2.4.126 --@sap:registry=https://npm.sap.com`

**Comment by dik111** [comment]
> My mistake, the @SAP should be @SAP (as it is in the code. try running this:
> `npm install @sap/hana-client@2.4.126 --@sap:registry=https://npm.sap.com`

it work!
thanks a lot @ariel-bentu

**Comment by vsshailesh** [comment]
this fails now @ariel-bentu ?
` npm install @sap/hana-client@2.4.126 --@sap:registry=https://npm.sap.com `

 node build.js

Error: Command failed: node-gyp build
In file included from ../src/hana.cpp:5:
../src/h/hana_utils.h:308:11: error: no template named 'Handle'
                        Handle<Value>                           arg,
                        ^
../src/h/hana_utils.h:311:6: error: redefinition of 'getBindParameters' as different kind of symbol
bool getBindParameters( Handle<Value>                           arg,
     ^
../src/h/hana_utils.h:304:6: note: previous definition is here
bool getBindParameters( std::vector<char*>                      &string_params,
     ^
../src/h/hana_utils.h:311:25: error: use of undeclared identifier 'Handle'
bool getBindParameters( Handle<Value>                           arg,
                        ^
../src/h/hana_utils.h:311:32: error: 'Value' does not refer to a value
bool getBindParameters( Handle<Value>                           arg,
                               ^
/Users/i039840/Library/Caches/node-gyp/12.13.1/include/node/v8.h:2284:17: note: declared here
class V8_EXPORT Value : public Data {
                ^
In file included from ../src/hana.cpp:5:
../src/h/hana_utils.h:311:43: error: use of undeclared identifier 'arg'
bool getBindParameters( Handle<Value>                           arg,
                                                                ^
../src/h/hana_utils.h:312:65: error: expected '(' for function-style cast or type construction
                        int                                     row_param_count,
                        ~~~                                     ^
../src/h/hana_utils.h:313:65: error: expected '(' for function-style cast or type construction
                        std::vector<dbcapi_bind_data*>          &params,
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~          ^
../src/h/hana_utils.h:313:66: error: use of undeclared identifier 'params'
                        std::vector<dbcapi_bind_data*>          &params,
                                                                 ^
../src/h/hana_utils.h:314:45: error: expected '(' for function-style cast or type construction
                        std::vector<size_t> &                   buffer_size,
                        ~~~~~~~~~~~~~~~~~~~ ^
../src/h/hana_utils.h:314:63: error: use of undeclared identifier 'buffer_size'
                        std::vector<size_t> &                   buffer_size,
                                                                ^
../src/h/hana_utils.h:315:51: error: expected '(' for function-style cast or type construction
                        std::vector<unsigned int> &             param_types );
                        ~~~~~~~~~~~~~~~~~~~~~~~~~ ^
../src/h/hana_utils.h:315:65: error: use of undeclared identifier 'param_types'
                        std::vector<unsigned int> &             param_types );
                                                                ^
../src/h/hana_utils.h:321:26: error: use of undeclared identifier 'Handle'
bool getInputParameters( Handle<Value>                      arg,
                         ^
../src/h/hana_utils.h:321:33: error: 'Value' does not refer to a value
bool getInputParameters( Handle<Value>                      arg,
                                ^
/Users/i039840/Library/Caches/node-gyp/12.13.1/include/node/v8.h:2284:17: note: declared here
class V8_EXPORT Value : public Data {
                ^
In file included from ../src/hana.cpp:5:
../src/h/hana_utils.h:321:61: error: use of undeclared identifier 'arg'
bool getInputParameters( Handle<Value>                      arg,
                                                            ^
../src/h/hana_utils.h:322:57: error: expected '(' for function-style cast or type construction
                         std::vector<dbcapi_bind_data*> &   params,
                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
../src/h/hana_utils.h:322:61: error: use of undeclared identifier 'params'
                         std::vector<dbcapi_bind_data*> &   params,
                                                            ^
../src/h/hana_utils.h:323:26: error: unexpected type name 'dbcapi_stmt': expected expression
                         dbcapi_stmt *                      stmt,
                         ^
../src/h/hana_utils.h:323:61: error: use of undeclared identifier 'stmt'; did you mean 'stat'?
                         dbcapi_stmt *                      stmt,
                                                            ^~~~
                                                            stat
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/sys/stat.h:361:9: note: 'stat' declared here
int     stat(const char *, struct stat *) __DARWIN_INODE64(stat);
        ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/hana-client/src/hana.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build"
gyp ERR! cwd /Users/i039840/.kube/node_modules/@sap/hana-client
gyp ERR! node -v v12.13.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 

But this command works:
`npm install @sap/hana-client --@sap:registry=https://npm.sap.com`

but that does not allow the tool to work.

**Comment by ariel-bentu** [comment]
I suppose locking to a specific version of the driver is a receipe for
ocasionalnfailures like this.
I suggest changing the code to refer to latest version. Matheis, what do
you say?


בתאריך יום א׳, 24 בנוב׳ 2019, 06:02, מאת vsshailesh ‏<
notifications@github.com>:

**Comment by mtxr** [comment]
Go for it @ariel-bentu.

Just please use v0.21 branch
