### ISSUE TITLE
Support MSSQL LocalDB

### ISSUE THREAD

**Issue by paultissue** [mtxr/vscode-sqltools#253]
MSSQL LocalDB is not supported.  Please support this.

To Reproduce:

Try Connection string setting.
{
    "sqltools.connections": [
        {
            "name": "LocalDB",
            "dialect": "MSSQL",
            "connectString": "Server=(LocalDB)\\MSSQLLocalDB;Database=master",
            "connectionTimeout": 30
        }
    ]
}
Error opening connection The "config.server" property is required and must be of type string.
Try adding "server" setting.
{
    "sqltools.connections": [
        {
            "name": "LocalDB",
            "dialect": "MSSQL",
            "server" : "(LocalDB)\\MSSQLLocalDB", 
            "connectString": "Server=(LocalDB)\\MSSQLLocalDB;Database=master",
            "connectionTimeout": 30
        }
    ]
}
Error opening connection Failed to lookup instance on (LocalDB) - getaddrinfo ENOTFOUND (LocalDB)

**Comment by ransagy** [comment]
see #61 #129 #214

**Comment by mtxr** [comment]
@paultissue try to take a look in those issues @ransagy aforementioned.

**Comment by mtxr** [comment]
Closing due lack of response.
