### ISSUE TITLE
Running a selected query changes the keyboard focus to the results panel

### ISSUE THREAD

**Issue by ransagy** [mtxr/vscode-sqltools#254]
**Describe the bug**
Running a selected query moves the keyboard focus to the results panel from the SQL tab. This worked before as far as i remember and allowed for a more streamlined workflow - For example, I could re-run the query again and again with a keyboard shortcut to see progress.

**To Reproduce**
1. Open a new SQL tab and connect to a DB.
2. Run the query either via keyboard shortcut or the command palette.
3. Try using said keyboard shortcut or command palette again.
4. Get error about having no query selected because the focus has moved.

**Expected behavior**
Keyboard focus should remain on the selected query in the tab while the results panel is opened/updated.

**Desktop (please complete the following information):**
 - SQLTools v0.19.2
 - VSCode 1.34.0
 - Dialect Used: MSSQL + Azure SQL
 - OS: Windows 10 x64

**Comment by mtxr** [comment]
Thanks @ransagy .

I can't remember why I changed it, but taking focus is very obtrusive.
