### ISSUE TITLE
Cannot destructure property `connId` of 'undefined' or 'null'.

### ISSUE THREAD

**Issue by OmarMAbbasi** [mtxr/vscode-sqltools#257]
**Describe the bug**
Trying to save a PostgreSQL to JSON or CSV

**To Reproduce**
1. Run any Query 
2. Try to save as JSON/CSV
3. Cannot destructure property `connId` of 'undefined' or 'null'.

**Expected behavior**
Expected to save.... 

**Screenshots**

**Desktop (please complete the following information):**
- SQLTools Version: v0.19
- VSCode Version: 1.34.0
- Dialect Used: SQLite
- OS: Linux Ubuntu

**Additional context**
Any queries I try to run as well seem to bug out and fail. I've tried some of the fixes in here including checking for "." somewhere in the name...

**Comment by mtxr** [comment]
Close in favor of #259.

It's the same issue.
