### ISSUE TITLE
Bookmarks getting wrong CodeLens comments

### ISSUE THREAD

**Issue by Eggybread610** [mtxr/vscode-sqltools#258]
**Describe the bug**
Nothing severe. If I make a bookmark, give it a name and a group. Then I edit that bookmark, it opens a new page with the query and some codelens comments. However it states the the @group is the query name and the @name is the query group.

**To Reproduce**
1. Create a bookmark, give it a name and group
2. Edit the same bookmark (ctrl+shift+p Edit Bookmark)

**Expected behavior**
@name saying the query name and @group saying the query group

**Desktop (please complete the following information):**
 - SQLTools Version v0.19.2
 - VSCode Version: v1.33.1
 - Dialect Used: PostgreSQL
 - OS: Windows

**Comment by mtxr** [comment]
Hi @Eggybread610 !

Thanks for reaching us with this issue. This is a good first issue to contribute. Would you like to try to fix it?
