### ISSUE TITLE
Button to write query results to csv temp file and open with Excel

### ISSUE THREAD

**Issue by shemco** [mtxr/vscode-sqltools#259]
**Is your feature request related to a problem? Please describe.**
Exporting query results to csv then opening the file is slow, and messy from a UX perspective.

**Describe the solution you'd like**
Add a button that causes a csv file to be written to a Temporary folder and opened with the default program. 

**Describe alternatives you've considered**
n/a

**Additional context**
SQLTools SQL client has this functionality, works well.

**Comment by mtxr** [comment]
This is definitely a good first issue.

If anyone want to take a shot, here is a quick guidance:
- we could use https://www.npmjs.com/package/tempfile to create a tmp file
- we already have a function that open files externally (core/utils/vscode.ts -> openExternal), just reuse
- add a setting to allow user to open file in VSCode or externally, can be a simple boolean I guess

@shemco any thoughts on this?

Also, if you want to take a shot at this issue, feel welcomed aboard! Just submit a PR, I'll be glad to review and merge it :smile:

**Comment by mubaidr** [comment]
@mtxr I am going to try this one.

**Comment by mtxr** [comment]
Awesome! Thanks! Go for it

**Comment by mubaidr** [comment]
Looks like contributing guide is incomplete/obsolete, can you please guide me? 
https://vscode-sqltools.mteixeira.dev/contributing/building

**Comment by mtxr** [comment]
I'll update the guide tonight. Thanks @mubaidr

**Comment by mtxr** [comment]
@mubaidr docs updated! let me know if you still have issues.

**Comment by mubaidr** [comment]
Looks good now. I will try to implement this.

**Comment by mtxr** [comment]
closed by #670
