### ISSUE TITLE
BUG: Keyboard Shortcut for Bookmark Query on MacOS closes VS Code

### ISSUE THREAD

**Issue by MurphysChaos** [mtxr/vscode-sqltools#26]
### Issue Type

* [X] Bugfix/Errors

### Prerequisites (For bugfixes)

* [X] Are you running the latest version?
* [N/A] Did you check the logs?
* [N/A] Did you check the Setup?

### Description

```⌘Q``` on the Mac is the global command to close the current application. Using the configured **Bookmark create** keyboard shortcut results in VS Code closing.

### Steps to Reproduce (For bugfixes)

1. Press ```[command]E``` ```[command]Q``` 

**Expected behavior:** Perform the Bookmark Query function

**Actual behavior:** Exits the application

**Workaround:** ```[shift][command]P``` → Type: "book" → Click "SQLTools Bookmarks: Create from selection"

**Requested fix:** Exclude ```[command]``` on the second keypress (```[command]E``` ```Q```)

**Comment by mtxr** [comment]
Will be fixed on next release.

**Comment by mtxr** [comment]
FIxed
