### ISSUE TITLE
Oracle - Timeout

### ISSUE THREAD

**Issue by mcardia** [mtxr/vscode-sqltools#261]
Oracle connection takes to long to load and most of the time it raises timeout.

I think it's related with oracle owner with a big dictonary.

I don´t know how the extension load the list of table/objects for the explorer/navigator, but,
if it´s using dba_* or all_* views, i would suggest to use user_* views and ignore public synonyms.

![image](https://user-images.githubusercontent.com/11967511/58644240-41800800-82d7-11e9-9fce-3587ba3c7b6e.png)

 - SQLTools Version 0.19.3
 - VSCode Version: 1.33.1
 - OS: Windows

**Comment by mickeypearce** [comment]
hey @mcardia ,

extension uses queries from https://github.com/mtxr/vscodesqltools/blob/master/packages/core/dialect/oracle/queries.ts file to load tables: `fetchTables`, columns in tables `fetchColumns`, functions `fetchFunctions`, etc...

**Comment by mtxr** [comment]
I must take a look on #218.

I think we are having a feel issues because of loading all data after connecting

**Comment by mtxr** [comment]
Not supported within this repository anymore.
