### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by mehmeteminisik** [mtxr/vscode-sqltools#265]
- Issue Type: `Performance`
- Extension Name: `sqltools`
- Extension Version: `0.15.0`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.32.1`

:warning: Make sure to **attach** this file from your *home*-directory: `C:\Users\mei_g\mtxr.sqltools-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by mtxr** [comment]
Hi, 

sorry for the late reply, I had to deal with some stuff here in the past week, I'll take a look at this within this week.

Thanks!

**Comment by mtxr** [comment]
Closing in favor of #322.
