### ISSUE TITLE
SQLTools.Selectconnection not foud

### ISSUE THREAD

**Issue by ilnerdchuck** [mtxr/vscode-sqltools#268]
**Describe the bug**
Hi i'm trying to oper a new connection but VS shows an error message command "SQLTools.Selectconnection" not foud

**To Reproduce**
Just run the command to open a MySQL connection

**Expected behavior**
Shoud open the connection congif file

**Screenshots**

![Capture](https://user-images.githubusercontent.com/13486351/59293152-e3f89d80-8c7e-11e9-89a6-87cf69ff8bdc.PNG)

**Desktop (please complete the following information):**
 - SQLTools Version v0.15.1
 - VSCode Version: v1.33.1
 - Dialect Used: MySQL
 - OS: Debian

**Comment by benyaminl** [comment]
> **Describe the bug**
> Hi i'm trying to oper a new connection but VS shows an error message command "SQLTools.Selectconnection" not foud
> 
> **To Reproduce**
> Just run the command to open a MySQL connection
> 
> **Expected behavior**
> Shoud open the connection congif file
> 
> **Screenshots**
> 
> ![Capture](https://user-images.githubusercontent.com/13486351/59293152-e3f89d80-8c7e-11e9-89a6-87cf69ff8bdc.PNG)
> 
> **Desktop (please complete the following information):**
> 
> * SQLTools Version v0.15.1
> * VSCode Version: v1.33.1
> * Dialect Used: MySQL
> * OS: Debian

Do you use the global or project based connection?

**Comment by ilnerdchuck** [comment]
Global based

Francesco Mignone

**Comment by mtxr** [comment]
Hi, 

sorry for the late reply, I had to deal with some stuff here in the past week, I'll take a look at this within this week.

Thanks!

**Comment by ilnerdchuck** [comment]
No problem XD
Francesco Mignone


Il giorno mer 19 giu 2019 alle ore 14:34 Matheus Teixeira <
notifications@github.com> ha scritto:

**Comment by mtxr** [comment]
@ilnerdchuck do you still face this problems?

I could't reproduce it. Can you share the logs of `SQLTools` output channel and `SQLTools Language Server` output channel? That will help a lot! You can mask any private info, eg. paths.

Thanks!

**Comment by mtxr** [comment]
@ilnerdchuck any updates on this?

**Comment by mtxr** [comment]
I tried to reproduce it a lot, but I've never get this bug. Closing due lack of response.

@ilnerdchuck if you are still facing this issue, please, let me know and reopen it.
