### ISSUE TITLE
ORA-24415: Missing or null username on LDAP connection for OracleDB

### ISSUE THREAD

**Issue by zyxifrash** [mtxr/vscode-sqltools#269]
**Describe the bug**
Connecting to an Oracle DB using LDAP does not send the username/password, even when manually forced in the settings.json file.

**To Reproduce**

- SQLTools->Connections->Add New Connection
  - Change Dialects to `OracleDB (Node Native)`
  - Change Connection Method to `Connection String`
  - Note the Username/Password fields disappear
  - Enter the Oracle Net Service Names in the connection string (as per https://github.com/oracle/node-oracledb/blob/master/doc/api.md#-1222-net-service-names-for-connection-strings)
  - Create the connection
- Open the user settings.json file - observe the config contains no username/password keys
- Try to connect to the database
- Observe the `ORA-24415 Missing or null username` error
- Modify the connection settings as per https://vscode-sqltools.mteixeira.dev/connections/oracledb#2-2-alternative-connection-strings
  - Paste exact configuration from documentation
  - Modify connection string, username and password to match local requirements
  - Note: no change in results when removing password and setting `askForPassword` to true
  - Save settings.json file
- Try to connect to the database
- Observe the same error

Error Log:
```
INFO: Executing SQLTools.addConnection
DEBUG: Configs reloaded!
INFO: Executing SQLTools.selectConnection
ERROR: Error:  { [Error: ORA-24415: Missing or null username.
	at handleResponse (C:\Users\user\.vscode\extensions\mtxr.sqltools-0.19.5\extension.js:919:48)
	at processMessageQueue (C:\Users\user\.vscode\extensions\mtxr.sqltools-0.19.5\extension.js:746:17)
	at Immediate.module.exports.setImmediate (C:\Users\user\.vscode\extensions\mtxr.sqltools-0.19.5\extension.js:730:13)
	at runCallback (timers.js:696:18)
	at tryOnImmediate (timers.js:667:5)
	at processImmediate (timers.js:649:5)] code: -1, data: { dialect: 'OracleDB', dialectOptions: {} } }
```
**Expected behavior**
1. The expected value for connection string In the node-oracledb documentation does not contain the username/password values - those are set as part of the getConnection call:
```
oracledb.getConnection(
  {
    user          : "hr",
    password      : mypw,  // mypw contains the hr schema password
    connectString : "sales"
  }
```
The username/password fields should not disappear when choosing `Connection String`

2. The connection should use the username/password (or askPassword input) when connecting to the database server.

**Desktop (please complete the following information):**
 - SQLTools Version: v0.19.5
 - VSCode Version: 
    - Version: 1.35.0 (system setup)
    - Commit: 553cfb2c2205db5f15f3ee8395bbd5cf066d357d
    - Date: 2019-06-04T01:18:19.664Z
    - Electron: 3.1.8
    - Chrome: 66.0.3359.181
    - Node.js: 10.2.0
    - V8: 6.6.346.32
    - OS: Windows_NT ia32 10.0.17134
 - Dialect Used: OracleDB
 - OS: Win10 x64 (running vscode x32)

**Additional context**
On a side note, I tried connecting directly to the database server using the address/port combo, that did include the username/password fields - but I just got an ORA-12154: TNS could not resolve the connect identifier. That's likely to be some kind of configuration problem on my side, though.

However...I started modifying the second settings.json connection object to recreate the first object (which is still throwing the null username error) - the two are now identical, except the second connection works.

I'm guessing that the username/password are being set in the code flow called when host/port is set, then cached on the connection object - so when I reuse that same object with the connection string, all is good? 

UPDATE: Confirmed - just adding the username/askForPassword settings to the json wasn't enough. I had to change the name field to force a reload - then that connection object started working too. Creating a brand new connect using the config.json also worked as expected. Using the "Edit Connection" option on any of the now working connections breaks them and reverts back to the null username error.

**Comment by mtxr** [comment]
Hi, 

sorry for the late reply, I had to deal with some stuff here in the past week, I'll take a look at this within this week.

Thanks!

**Comment by mickeypearce** [comment]
Hi @zyxifrash ,
can you please confirm If I understand you problem correctly. 
- If you insert settings direclty into `settings.json` from the start (after vscode reload) it now works as you expected?
- Can you please post your DB confuguration settings (`settings.json`) for future reference?
Thanks for now. :)

**Comment by luigicpereira** [comment]
Hi, i am also having the problem as @zyxifrash that it is throwing ORA-24415 when trying to connect even after adding username and password in the settings.json. It seems like that even after modifying the settings.json it is still using the configuration that it was set when the connection was created. After a few resets on vscode it finally worked, all the modifications made on settings.json was reflecting on the connection list in the extension "tab".

**Comment by mtxr** [comment]
Closing due lack of response
