### ISSUE TITLE
codelens/query problem

### ISSUE THREAD

**Issue by skotlex** [mtxr/vscode-sqltools#270]
**Describe the bug**
1. -- @conn function does not work as expected
2. desc(describe) [table_name] not work

**To Reproduce**
*db: oracleDB
1. Add connections. ex. PGSQL1 and PGSQL2
2. Create sql file 
3. Screen shown after coding
Run query block on active connection
-- @block select
-- @conn PGSQL1
select * from [table_name]

Run query block on active connection
-- @block select
-- @conn PGSQL2
select * from [table_name]

**Expected behavior**
Q1. Unlike the guide (https://vscode-sqltools.mteixeira.dev/codelens), each block looks at only the currently connected db, not the connection I want. 
ex. 
guide screenshot text:  Run query block on PGSQL
current my sql text: Run query block on active connection

Am I doing something wrong?

Q2. "desc [table_name]" query on oracle does not work.

**Desktop (please complete the following information):**
 - SQLTools Version: 0.19.5
 - VSCode Version: 1.35.0-exploration
 - Dialect Used: Oracle
 - OS: Windows

**Comment by mickeypearce** [comment]
@skotlex, Q2: no, oracledb-node driver unfortunatelly does not support script execution (SQL*Plus commands).

**Comment by zyxifrash** [comment]
I'm not sure I follow, how is this a SQLPlus/oracledb-node issue?

According to /packages/plugins/codelens/provider.ts, it's specifically looking for a @conn statement at the top of the block, then at the top of the file - only using the active connection if neither were found. It's not specific to oracle in any way.

https://vscode-sqltools.mteixeira.dev/executing-queries also states that you're supposed to be able to use @conn at the top of a file, which will define the connection used for any queries executed in that file.  This is not working as described either.

There's something wrong with the code that finds those @conn statements.

**Comment by mickeypearce** [comment]
> Q2. "desc [table_name]" query on oracle does not work

I was referring to Q2. Describe is a sql*plus cmd, isn't it?

**Comment by skotlex** [comment]
> > Q2. "desc [table_name]" query on oracle does not work
> 
> I was referring to Q2. Describe is a sql*plus cmd, isn't it?

**Comment by skotlex** [comment]
I understand if it's not for support. Can I hear the answer to Q1?

**Comment by mtxr** [comment]
Hi, 

sorry for the late reply, I had to deal with some stuff here in the past week, I'll take a look at this within this week.

Thanks!
