### ISSUE TITLE
Test output was be blocked and no longer display to debug console when testing extension

### ISSUE THREAD

**Issue by qwas368** [mtxr/vscode-sqltools#273]
**Describe the bug**
As title. I developed my vs code extension and found that test output was blocked by SQLTools extension.

**To Reproduce**
1. Install SQLTools extension
2. create any extension by `yo code` (ref: https://code.visualstudio.com/api/get-started/your-first-extension)
3. Testing Extension (ref: https://code.visualstudio.com/api/working-with-extensions/testing-extension)
4. Debug console can't print any message.

**Expected behavior**
![image](https://user-images.githubusercontent.com/26789196/59476784-e75d7600-8e84-11e9-9135-596e0d562afe.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/26789196/59476775-da408700-8e84-11e9-8c49-b7ee57329994.png)

**Desktop (please complete the following information):**
 - SQLTools Version v0.19.5
 - VSCode Version: 1.35.0
 - Dialect Used: n/a
 - OS: Windows 10

**Additional context**
No

**Comment by mtxr** [comment]
Hi, 

sorry for the late reply, I had to deal with some stuff here in the past week, I'll take a look at this within this week.

Thanks!
