### ISSUE TITLE
oracle db connection problem

### ISSUE THREAD

**Issue by skotlex** [mtxr/vscode-sqltools#276]
**Describe the bug**
Connection issue of oracle db automatically disconnected after a certain period of time.

**To Reproduce**
> ※ An oracle db environment that automatically session down in 10 minutes if nothing is done
1. Connect oracle db
2. 10 minutes elapsed without any DB related work
3. DB search
4. _**Failed to search and timeout: (NJS-040: connection request timeout)**_
5. Disconnect current db for re-connection
6. Attempt to connect to DB
7. **_Popup error: (NJS-064: connection pool is closing)_**
8. **_Outputs the following error after a long period of time: (Error: ORA-12547: TNS: lost connect)_**

**Expected behavior**
If lose connection automatically, I hope can re-connect it automatically when search for a query after that way. If this is difficult, I hope that the connection pool will be initialized when the user push disconnect button

**Desktop (please complete the following information):**
 - SQLTools Version 0.19.5
 - VSCode Version: 1.35.0-exploration
 - Dialect Used: Oracle
 - OS: Windows

**Comment by skotlex** [comment]
I solved it using "oracleOptions" "poolMax","poolMin","poolIncrement"
In case of the same problem, I'll ask you again.
Thank you

**Comment by mickeypearce** [comment]
Could you please share your settings?

**Comment by skotlex** [comment]
"oracleOptions": {
  "poolMax": 1,
  "poolMin": 1,
  "poolIncrement": 0
}

But it's not clear if this is the perfect solution. I will test in my company's Oracle environment for a few days, and if there is a problem, I will write the issue again.
