### ISSUE TITLE
Run query under cursor position

### ISSUE THREAD

**Issue by pkkid** [mtxr/vscode-sqltools#277]
**Request Description**
I'd like to set a hotkey to run the query under the current cursor position without having to select all the text. Currently I need to keep highlighting the full query and executing "Run Selected Query". It would be very convenient if I could just place my cursor anywhere in that query and execute "Run Query Under Cursor" or similar.  It's a bit tedious to keep highlighting the query I want to run.

Most of the time executing the full file is overkill on my large database because I use the sql file as a scratchpad to build complex queries and try many different things.

I understand looking for the beginning and end of the query may be difficult to get right. Maybe for starters something as simple as looking for the previous semicolon or beginning of file and the next semicolon or eof.

**Describe alternatives you've considered**
It looks like there are currently three ways to run a query (unless I'm mistaken)..
* The full file (opens tab for every query in the file).
* Selected query (runs a single query, but you need to highlight it).
* Input box (you need to enter it in).
* _I'm suggesting a 4th option._

---
Related or merged into:
https://github.com/mtxr/vscode-sqltools/issues/363
https://github.com/mtxr/vscode-sqltools/issues/354

**Comment by vrokolos** [comment]
What toad for oracle does is figuring out the current query by looking at blank lines. It gets your cursor position, finds the previous blank line, next blank line and everything between those is the current query. That would be fairly easy to implement I guess

**Comment by vrokolos** [comment]
So I implemented this and a bunch of other stuff. Please see my pull request

**Comment by johndevedu** [comment]
@mtxr would love to see this implemented. Looking at #293 it looks like the contributor stopped responding to your questions, so the PR was closed. Can I take a crack at it? Was thinking of just adding the "Run Current Query" part out of that PR since the PR was so large.

**Comment by mtxr** [comment]
@johndevedu please go ahead! I'll be happy to accept your PR.

Just giving you more tools to work, @dnlw07 send me some instructions he thought could be useful.

Regarding the ‘Run query under cursor’ I have a regex script which can help you with that.

> It’s JavaScript regex flavor:
>
> ((.*\n)|.*)+?;|(?<=;)((.*\n)|.*)+
>
> It is multiline script, so if you paste this script directly into VSCode, it will select all SQL scripts separated by semicolon (including boundaries).

Let me know if you need any help, I'll be happy assisting you

**Comment by mtxr** [comment]
@johndevedu any luck?

**Comment by steg0** [comment]
I'm interested in this as well. I support the idea of splitting on semicolons with a regex. I've extracted the Run Current Query command out of the original branch by @vrokolos and tried changing it, starting with b3d0110e747280d8ac74d6b68c8de06b0da8c750. I'm going to test it over the next couple of weeks and open PR if successful.

**Comment by mtxr** [comment]
Thanks @steg0

**Comment by steg0** [comment]
My current approach is https://github.com/mtxr/vscode-sqltools/pull/481. (I opened it against v0.21.x -- sorry for that -- haven't caught up with master yet.)

**Comment by steg0** [comment]
I opened https://github.com/mtxr/vscode-sqltools/pull/482 against master now and closed the other one. v0.21.x is for bugfixing I guess after all. Sorry for the noise.

**Comment by mtxr** [comment]
added some extra feature to your PR @steg0!

![](https://user-images.githubusercontent.com/707561/72664290-d5275580-39da-11ea-88ec-4670f7506de8.gif)

Thanks to you and to @vrokolos it's being closed.

**Comment by steg0** [comment]
Oh wow just tried it, that's definitely nifty. (Let's hope the splitter is fast enough to not cause lag in larger files :-P )

**Comment by vinclei** [comment]
Hey @mtxr , @steg0 , can you please guide how to get these 2 features work?

**Comment by pkkid** [comment]
I haven't figured out how to run this either. Not sure what I am missing.

**Comment by steg0** [comment]
you're right, it's not released and only in master. I would hope it gets released with the next major upgrade.
