### ISSUE TITLE
Open results window in same grouping as focused window

### ISSUE THREAD

**Issue by tripl3dogdare** [mtxr/vscode-sqltools#28]
### Issue Type

* [x] Feature Request
* [x] Bugfix/Errors
* [ ] Questions
* [ ] Other

(Not really sure which to classify this as, I'd assume feature request but it may be a bug)

### Description

Currently, when you execute a SQL query, the results window automatically opens in the first tab group (top/left). I believe it would make more sense (if possible) to have it open in the same tab group as the focused window, in order to avoid having to constantly move the results window around.

Example: given a setup like this (code on the left, utility queries on the right), I execute the query in the right-hand window.

![](https://user-images.githubusercontent.com/8225036/29238209-13f144e8-7eed-11e7-8666-f370039cae30.png)

I would prefer to be able to have the results window open on the right, like this (actual data blurred out for privacy reasons):

![image](https://user-images.githubusercontent.com/8225036/29238228-a83181e0-7eed-11e7-9efc-3e328a243ccd.png)

However, what actually happens is that the results window opens on the left, like this:

![](https://user-images.githubusercontent.com/8225036/29238227-8657726e-7eed-11e7-926d-349f9e2e22cb.png)

I believe it would make for a more streamlined and intuitive experience for the results tab to automatically open in the same tab group as the query that was executed, rather than having to move it every time to produce the desired layout. This could theoretically be made into a config option as well, to allow for either behavior depending on user preference.

**Comment by sluongng** [comment]
I would like to further adding that there should be options for user to customize the window location. And if there is already a result window open, may be reuse it instead of opening a new one(with scrolling through multiple results).

**Comment by tmastny** [comment]
I actually prefer it the other way: having the results open in a new column, so I can see the query and results side by side.

I second @sluongng's request: can we customize the window location so it can either open in the current column, or move to the next one?

**Comment by jdobruchowski** [comment]
Yes please , as per @tmastny  , can we have a config for it ? because i would prefer  having it in original behaviour . I'm coming from sql developer and there you have static query output window.

**Comment by mtxr** [comment]
Yeah, it was added on latest releases.

Please, take a look at https://mtxr.gitbook.io/vscode-sqltools/changelog#v-0-17-7
