### ISSUE TITLE
Add option to force the path to the Oracle client

### ISSUE THREAD

**Issue by bergamin** [mtxr/vscode-sqltools#281]
**Is your feature request related to a problem? Please describe.**

At work I normally use a 32 bits Oracle (I don't know why. The environment comes ready for every new employee and it targets a shared drive), but SQLTools requires 64 bits, giving me the following error when I try to connect:

![image](https://user-images.githubusercontent.com/14339291/60200119-d8c77500-981b-11e9-9ca9-2f870eb6aa11.png)

**Describe the solution you'd like**

it would be great to have a setting to override the environment variable and set it like this:

`"sqltools.oracle_home": "Path I want SQLTools to use instead of the default environment variable"`

**Describe alternatives you've considered**

I have both changed the path and oracle_home variables and the message keeps being shown with the wrong path in it. It is still trying to connect to the old path, so may be a bug as well?

**Additional context**

### EDIT

I found out why it wasn't working. I had two environment variables called Path. My suggestion for overriding though, is still valid.

**Comment by mickeypearce** [comment]
Node-oracledb driver used in extension doesn't include pre-built 32-bit binaries at the moment unfortunatelly. https://github.com/oracle/node-oracledb/releases/tag/v3.1.0 and https://github.com/oracle/node-oracledb/issues/923

**Comment by mtxr** [comment]
Just added a config that allows you to achieve this.

This is the text added to the docs:

If you want to use 32bits drivers or set a different ORACLE_HOME to be used with the node driver, you can achieve this using the `sqltools.languageServerEnv`.


```json
{
  ...
  "sqltools.languageServerEnv": {
    "ORACLE_HOME": "YOUR PATH HERE"
  },
  ...
}
```

**Comment by ira-gordin-sap** [comment]
Thank you so much.
It helps me to fix another issue with another database.
