### ISSUE TITLE
Support MySQL defaults option file and group suffix

### ISSUE THREAD

**Issue by renkun-ken** [mtxr/vscode-sqltools#282]
**Is your feature request related to a problem? Please describe.**
I cannot connect to MySQL server that `REQUIRE SSL` using local `~/.my.cnf` file that specifies `ca-cert`, `client-cert`, `client-key` file in a group like `[client-ssl]` like the following:

```ini
[client-ssl]
ssl-ca=/etc/mysql/ssl/ca-cert.pem
ssl-cert=/etc/mysql/ssl/client-cert.pem
ssl-key=/etc/mysql/ssl/client-key.pem
```

**Describe the solution you'd like**

More options should be supported in `mysqlOptions`: 

1. `defaults-file`: https://dev.mysql.com/doc/refman/8.0/en/option-file-options.html#option_general_defaults-file
2. `defaults-group-suffix`: https://dev.mysql.com/doc/refman/8.0/en/option-file-options.html#option_general_defaults-group-suffix

**Comment by mtxr** [comment]
I believe this was fixed on #263 .

Related to #235.

Closing.
