### ISSUE TITLE
Newly created Oracle connection not being shown on sidebar (and not able to connect to it for possibly the same reason), but it is shown in the settings.json

### ISSUE THREAD

**Issue by bergamin** [mtxr/vscode-sqltools#284]
**Describe the bug**

![image](https://user-images.githubusercontent.com/14339291/60359102-6aff8280-99ae-11e9-8145-003f953969b1.png)

**To Reproduce**

- Created a new connection to Oracle
- Commanded it to connect just after creation in the confirmation message.
- It didn't connect and it is not shown in the connection lists
- It is still available in the settings.json

**Expected behavior**

All connections from the settings available for connection (or updating through the interface when having problems or incomplete)

**Desktop (please complete the following information):**

 - SQLTools Version 0.19.6
 - VSCode Version: 1.35.1
 - Dialect Used: Oracle
 - OS: Windows 10

**Additional context**

Not sure if this could be related, but the previous connection I created, I created with some wrong information, so I tried updating it. It didn't update the information after I commanded it to save the update, so I manually changed the settings.json and it worked well.

### EDIT

Found out when the problem occurs: it seems it only looks at the workspace settings instead of always showing the global connections **plus** the current workspace

**Comment by josecanciani** [comment]
Same here with Mysql. I'm trying to add connections using the user settings json, and it's ignored.
It seems when you also have workspace settings, the connection list is not merged, but rather overwritten and only the workspace is taken into consideration. Even if you have an empty list, just having the "sqltools.connections" defined, then the user setting's "sqltools.connections" is ignored.

**Comment by mtxr** [comment]
@bergamin @josecanciani do you still have this issue on v0.21.x?

**Comment by mtxr** [comment]
Let me know if this issue persists. Closing for now

**Comment by josecanciani** [comment]
Yes, it appears to be fixed, thanks!
