### ISSUE TITLE
Add support for Teradata

### ISSUE THREAD

**Issue by C1ARKGABLE** [mtxr/vscode-sqltools#285]
Teradata has developer tools for Visual Studio, but they’re showing no love to VS Code. 

The ability to connect using LDAP would be amazing!

**Comment by mtxr** [comment]
Hi @C1ARKGABLE , I don't have time to work on this right now.

But if you want to try to develop this, we have a guide for new dialects.

Would you like to try?

Take a look here: #219

**Comment by C1ARKGABLE** [comment]
Sure @mtxr! I’ll dip my feet in tomorrow. Will you be around if I have questions at this same time?

**Comment by mtxr** [comment]
Can't promise this, I have a lot of work for tomorrow since it's a holiday in US on Thursday. But you can always drop your message and I'll reply as fast as I can.

I really appreciate you working on this since I have no experience with Teradata
Thanks!

**Comment by mtxr** [comment]
@C1ARKGABLE any updates on this?

**Comment by C1ARKGABLE** [comment]
Haven’t had much luck. I’d have to make calls to Python or Java because there aren’t any JS drivers. I don’t want to jank it together. @mtxr

**Comment by mtxr** [comment]
Got it.

That's sad. It will be a bit hard to do this kind of integration for now.

I'll close this ticket since we don't have real plans for this soon, ok?

I'll tag it as a `third-party-blocking` to revisit it in the future.

Thanks for your effort @C1ARKGABLE

**Comment by ScriptPup** [comment]
Hey there, is there still an issue with teradata not having a JS driver? I found this https://github.com/Teradata/nodejs-driver, but wasn't sure if that was something you'd already looked into. Just tossing it out there since I stumbled on this while looking for a decent non-1900's themed teradata IDE.
