### ISSUE TITLE
Create Connection Button Issue

### ISSUE THREAD

**Issue by JRAVILES** [mtxr/vscode-sqltools#286]
Hello when the VsCode Theme is setted to High Contrast, the create button on new connection wizard does not display properly. Tks

**Comment by mtxr** [comment]
Hello @JRAVILES and thanks!

Can you send me a screenshot of the bug?

That would help to fix it. There are some themes that it work, so I need to see how is it being displayed for you

**Comment by JRAVILES** [comment]
![image](https://user-images.githubusercontent.com/5407512/60756022-9ac21200-9fce-11e9-81ff-a4dea863ad4b.png)

**Comment by mtxr** [comment]
Thanks!
