### ISSUE TITLE
ATTENTION! Sorry guys! I'm in a hurry now :(

### ISSUE THREAD

**Issue by mtxr** [mtxr/vscode-sqltools#290]
Hi everyone,

First of all, I'm sorry I've been a bit far from the project this month. 

I'm having a lot of stuff to deal with in my free time, my kid is on vacation so the project is a bit stuck for now.

I'll try my best to keep things going, but please, don't expect releases in the same pace like we had before June for the next 3 weeks.

If you have the possibility to work in some issues, please, just mention me in the issues, I'll be glad to provide some assistance, but for the next weeks I'll try to focus only on high priority bugs

**Comment by JimFung** [comment]
Take some time for yourself man 👍

**Comment by BrettMoan** [comment]
Enjoy your holiday! It's important to not work all the time. :)

**Comment by mtxr** [comment]
Kid is back to school next week. Let's fix some issues!
