### ISSUE TITLE
Change the keyboard shortcuts to use a non-otherwise functional key

### ISSUE THREAD

**Issue by katzelad** [mtxr/vscode-sqltools#299]
**Is your feature request related to a problem? Please describe.**
The keyboard shortcuts currently use CTRL+E, overriding one of the most useful keyboard shortcuts in VS Code.

**Describe the solution you'd like**
Use an otherwise unused key combination instead, such as CTRL+SHIFT+Q (which also intuitively matches the extension name).

**Describe alternatives you've considered**
CTRL+Q is also possible (rarely used).

**Comment by mtxr** [comment]
@katzelad, thanks for reaching us.

About the hotkeys, users can change it whenever they want using vscode keyboard shortcuts editor. The project is now 2 years old with a lot of installs, it's hard to do this kind of change. I believe you are the second one to suggest this kind of change, so I believe it's working for the other users.

In the very beginning of vscode, CTRL+Q was used and CMD+Q is quit on MacOS. So I thinks it's an important key combination.

Sorry to say that, but I believe it's better to keep it as-is for now.
