### ISSUE TITLE
Drag & Drop from connection panel

### ISSUE THREAD

**Issue by ilmam** [mtxr/vscode-sqltools#30]
* [x] Feature Request

Would love to be able to drag and drop a table or a column from SQL Connections panel on the left, to the editor window. It would makes Writing a query much easier.

**Comment by mtxr** [comment]
I will study to check how to do that. It's very useful!

**Comment by mtxr** [comment]
Currently that's not possible. Vscode doesn't have support for drag from side explorer for custom plugins. Anyway I'll add a feature that adds the selected node to the current cursor place on click, ok?

**Comment by ilmam** [comment]
Thanks for looking into this, appreciate the efforts. I like your suggestion, but maybe it would be better if that works either as right click, or double click rather than just a normal left click.
Thanks again for the awesome work!

**Comment by mtxr** [comment]
Feature added. WIll be release in this next release.
