### ISSUE TITLE
MySQL Database Filter (Filtro de banco de dados no MySQL)

### ISSUE THREAD

**Issue by profbaco** [mtxr/vscode-sqltools#300]
When connecting to a MySQL database the system is loading all the databases, not just the one I put in the connection. With the PostrgreSQL database it works fine, but not in MySQL.

(Ao fazer a conexão com um banco MySQL o sistema esta carregando todas as bases de dados, e não somente a que eu coloquei na conexão. Com o banco PostrgreSQL funciona certinho, mas no MySQL não.)

**Comment by mtxr** [comment]
@profbaco there's a PR that fixes this for Oracle. I'll extend this PR to have the same behavior for other dialects. It will allow user to have an array of DB's to show for the same connection.

**Comment by profbaco** [comment]
Yeah @mtxr , but if I determined which DB to use in the settings, shouldn't it respect what is in the configuration file?
---------------------
Pois é, mas se eu determinei qual o DB que é para usar, nas configurações, ele não deveria respeitar o que esta no arquivo de configuração?

**Comment by mtxr** [comment]
Closing in favor of #322.

**Comment by mtxr** [comment]
To be released

**Comment by profbaco** [comment]
Hi @mtxr is scheduled to release the new version?

Olá @mtxr tem previsão de lançamento da nova versão?
