### ISSUE TITLE
SQLTools table view window crashes when typing `[` in a _Filter By ..._ field

### ISSUE THREAD

**Issue by lmichelin** [mtxr/vscode-sqltools#302]
**Describe the bug**
When I type `[` in a _Filter By ..._ field, the SQLTools table view window crashes. The following error in logged in the developer console: `[Embedded Page] Uncaught SyntaxError: Invalid regular expression: /[/: Unterminated character class`

**To Reproduce**
1. Go to the SQLTools panel
2. Click on the _Show Table Records_ button on a table
3. Type _[_ in a _Filter By ..._ field
4. The window crashes. See the error in the developer console

**Expected behavior**
Show elements filtered by `[` without crashing

**Screenshots**
![Peek 2019-07-26 11-06](https://user-images.githubusercontent.com/33673240/61940360-8fdb1b80-af95-11e9-8851-40ac09b56f3c.gif)

**Desktop:**
 - SQLTools Version 1.36.1
 - VSCode Version: 0.19.7
 - Dialect Used/Version: MySQL 5.6
 - OS: Linux Ubuntu 18.04

**Comment by mtxr** [comment]
@lmichelin thanks!
