### ISSUE TITLE
SQLTools is asking for oracledb once again

### ISSUE THREAD

**Issue by bergamin** [mtxr/vscode-sqltools#303]
**Describe the bug**
SQLTools started asking me to install oracledb once again.

**To Reproduce**
I'm not sure if could be related, but I had to scrap my workspace because VSCode thought it would be a good idea to rebuild all applications I have in it after an update when I didn't configure it to do so (I mostly just use it as a text editor, with some limited IDE functionality).

So there were two things meanwhile. I reopened VSCode without opening a folder and there was also SQLTools last update.

**Expected behavior**
Install stuff once

**Screenshots**
![image](https://user-images.githubusercontent.com/14339291/61951382-3cfa6780-af87-11e9-9a49-6ee5cf69ad37.png)

**Desktop (please complete the following information):**
 - SQLTools Version [e.g. v0.19.7]
 - VSCode Version: [e.g 1.36.1]
 - Dialect Used/Version: [Oracle]
 - OS: [Windows 10]

**Comment by mtxr** [comment]
@bergamin if you deleted VScode config folder, you will need to reinstall it for sure. Check if it's one of this places you had a reset: https://code.visualstudio.com/docs/getstarted/settings#_settings-file-locations

The driver is installed there. Please keep me posted. That's the only situation expected this to happen (except driver updates).

**Comment by mtxr** [comment]
@bergamin I'll close it since reinstalling is expected (for now). Please, feel free to re-open if you believe we still need to investigate it.
