### ISSUE TITLE
The connection list refresh button does not work.

### ISSUE THREAD

**Issue by skamansam** [mtxr/vscode-sqltools#308]
**Describe the bug**
The connection list refresh button does not work.

**To Reproduce**
1. Add a new connection via the new connection panel or by editing the settings.json file.
2. Click on the refresh button on the connections list panel.

**Expected behavior**
The new connection(s) should show up in the list of connections.

**Screenshots**
![vscode-sqltools-refresh-attmept](https://user-images.githubusercontent.com/102971/62235912-f5ffde00-b39b-11e9-85d9-2801b3e0ae39.png)

**Desktop (please complete the following information):**
 - SQLTools Version: 0.19.7
 - Dialect Used/Version: PostgreSQL
 - VSCode Version: 1.37.0-insider
 - VSCode Commit: d5900c642b359fe7a9eb1e3f9e2d0977f6e0905c
 - VSCode Date: 2019-07-31T05:23:42.978Z
 - VSCode Electron: 4.2.7
 - VSCode Chrome: 69.0.3497.128
 - VSCode Node.js: 10.11.0
 - VSCode V8: 6.9.427.31-electron.0
 - VSCode OS: Linux x64 5.1.5-300.fc30.x86_64

**Additional context**
The list is successfully refreshed when I reload VSCode, but not when clicking the refresh button. When clicking the button, the SQLTools Language Server logs the following message:
```
Request connection/RefreshAllRequest received
```
The SQLTools log gives:
```
INFO: Executing SQLTools.refreshAll
```

**Comment by mtxr** [comment]
@skamansam I see you are using insiders. Can you confirm it still happening? I've just tested it and it worked pretty well here both Insiders and Stable.

The logs are fine. That's all supposed to be written. But I'm adding new logs to show that it was updated.

**Comment by mtxr** [comment]
Closing due lack of response

**Comment by bonohemi** [comment]
hi 
What is the vscode theme you used?
