### ISSUE TITLE
SQLite syntax error during connection initialization

### ISSUE THREAD

**Issue by MLutt** [mtxr/vscode-sqltools#309]
New issue requested by @mtxr in #307 

@mtxr I can do better than just sending over the logs.... Try opening this SQLite database in SQLTools :stuck_out_tongue: 

[X Series.sqlite.zip](https://github.com/mtxr/vscode-sqltools/files/3464820/X.Series.sqlite.zip)

Result should be:

![Screenshot from 2019-08-04 12-52-05](https://user-images.githubusercontent.com/12535109/62422685-bb0ceb80-b6b6-11e9-9db7-f4d355ee7575.png)

Logs:

[20190804T124922.zip](https://github.com/mtxr/vscode-sqltools/files/3464821/20190804T124922.zip)

**Comment by mtxr** [comment]
Whats the name of this Ships table? is it just Ships or is it something llike "Ships whatever"? It looks like a escaping issue

**Comment by mtxr** [comment]
Confirmed and fixed
