### ISSUE TITLE
Date result formatting

### ISSUE THREAD

**Issue by Joascode** [mtxr/vscode-sqltools#315]
First of: I'm pretty new to the package, so I might be missing something obvious. If that's the case, I'm incredibly sorry for the trouble I cause. I totally enjoy the package and love what's been done so far (keep it up! 👏)

**Is your feature request related to a problem? Please describe.**
It's a pretty minor inconvenience: Currently when querying for date values in Postgres, the result is always a DateTime object which also isn't totally correct either (there seemed to be some time/day difference).

**Describe the solution you'd like**
Would prefer the possibility of formatting the date result. Having default behaviour being DateTime isn't bad, but it seems I'm not able to format the date into something I want/need. Having the full DateTime object fills up the screen quickly and that way it can be hard to distinguish certain values.

**Describe alternatives you've considered**
I tried adding DATE(date_field) and other query options, but that didn't change the output in the results window.

**Additional context**
Current behaviour:
![sql-tools-dates](https://user-images.githubusercontent.com/21367291/62653612-27f5df00-b95e-11e9-8fba-84f315a7398f.png)

Expected behaviour (same query in pgAdmin):
![pgadmin-dates](https://user-images.githubusercontent.com/21367291/62653624-317f4700-b95e-11e9-8e92-f055fe2e9103.png)

**Comment by mtxr** [comment]
Hi @Joascode 

This was fixed in the last commit here. I didn't see the issue in time, otherwise I would have linked it here, but here is the commit hash: https://github.com/mtxr/vscode-sqltools/commit/f36dfb6605a1db8845a6e109f6af1d3f34ea4ef0

It's about to be released together with the new UI.

**Comment by Joascode** [comment]
Awesome! Thanks alot for the update :) Looking forward to the new release!

**Comment by fredaczz** [comment]
it seems that the same problem exists in the newest version(0.28.3)?

**Comment by gjsjohnmurray** [comment]
@fredaczz please open a new issue with full details of which driver you are using and how to reproduce the issue from scratch.
