### ISSUE TITLE
Endless loop connectiong to Oracle

### ISSUE THREAD

**Issue by ghLoser** [mtxr/vscode-sqltools#318]
When trying to connect to an Oracle DB i get the following message:

> You need to install "oracledb@3.1.1" to connect to $DBName.

Clicking on Install, i get:

> "oracledb@3.1.1" installed! Go ahead and connect!

Clicking on Connect I get again:

>You need to install "oracledb@3.1.1" to connect to $DBName.

And this keeps going on and on and on and on...

OS: Win10 Pro

**Comment by mtxr** [comment]
@ghLoser HI,

Hey, do you have all pre requisites? Check here: https://vscode-sqltools.mteixeira.dev/connections/oracledb#1-prerequisites

I think maybe `sqltools.useNodeRuntime` is not enabled or you have a different node version.

Can you check it and reach me back?

**Comment by mtxr** [comment]
Actually you are right.

I've tried it and since VScode update electron version, the checking for node runtime was broken.

Just fixed.
