### ISSUE TITLE
Error opening connection Received packet in the wrong sequence.

### ISSUE THREAD

**Issue by Lips7** [mtxr/vscode-sqltools#325]
**Describe the bug**

In **remote-wsl**, wsl-version-**2**.
**Error opening connection Received packet in the wrong sequence.**
It worked well yesterday.
And I don't know what exactly trigger this, I can access mysql server with python-pymysql, it works well, but just broken within SQLTool.

**To Reproduce**
I really don't know what happens.

**Expected behavior**
It should works well.

**Screenshots**
![image](https://user-images.githubusercontent.com/51849534/62835489-c9956d00-bc8b-11e9-9fc8-392523ad85b2.png)

**Desktop (please complete the following information):**
 - SQLTools Version [v0.20.0]
 - VSCode Version: [1.37.0]
 - Dialect Used/Version: [MySQL-server 5.7]
 - OS: [WSL]

**Additional context**

**Comment by carsalgl** [comment]
I just loaded this extension for the first time and am having the same issue.

**Comment by klukiyan** [comment]
same issue here. Any workaround for it?

**Comment by MrLexJR** [comment]
Apparently the problem is with MySQL, because if it allows me to connect to a PostgreSQL database

**Comment by lesfen** [comment]
I am having the exact same problem.  This extension worked perfectly until the last update that was dated today 8/11/1019.   The update broke it.

Received packet in the wrong sequence.

**Comment by PapsOu** [comment]
I can confirm that `v0.20.0` introduces this bug for MySQL existing and new connections.

**Comment by mtxr** [comment]
Fixed and released. Soon you can update

**Comment by mtxr** [comment]
It was a packing issue while doing the minification of the files ti publish

**Comment by PapsOu** [comment]
`v0.20.1` fixes the issue. Thanks @mtxr !
