### ISSUE TITLE
connection oracle (ERROR: Error:  { [Error: Cannot find module 'oracledb')

### ISSUE THREAD

**Issue by Joca9227** [mtxr/vscode-sqltools#326]
ERROR: Error:  { [Error: Cannot find module 'oracledb'
	at C:\Users\Joca\.vscode\extensions\mtxr.sqltools-0.20.0\extension.js:1:14086
	at C:\Users\Joca\.vscode\extensions\mtxr.sqltools-0.20.0\extension.js:1:14380
	at Immediate.module.exports.W.R.size.setImmediate (C:\Users\Joca\.vscode\extensions\mtxr.sqltools-0.20.0\extension.js:1:14741)
	at runCallback (timers.js:694:18)
	at tryOnImmediate (timers.js:665:5)
	at processImmediate (timers.js:647:5)]
  code: -32001,
  data: { dialect: 'OracleDB', dialectOptions: {} } }
INFO: Executing SQLTools.showOutputChannel

**Comment by a-m-dev** [comment]
me too

**Comment by mtxr** [comment]
Can you guys upgrade to the new version and try again? We had an issue because of the VSCode migrations to new electron version. Also, after updating, we need to reinstall the driver since it's installed inside of the extension folder
