### ISSUE TITLE
cannot install extention in windows 10

### ISSUE THREAD

**Issue by mbaghert** [mtxr/vscode-sqltools#331]
cannot install extension

version Info

Version: 1.37.0 (system setup)
Commit: 036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8
Date: 2019-08-08T02:33:50.993Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17134

ERROR: Error:  { [Error: Request DependencyInstaller/install failed with message: You need to install node@6 or newer and npm first to install dependencies. Install it and restart to continue.
	at C:\Users\tolou-m\.vscode\extensions\mtxr.sqltools-0.20.1\extension.js:1:22983
	at C:\Users\tolou-m\.vscode\extensions\mtxr.sqltools-0.20.1\extension.js:1:23390
	at Immediate.module.exports.messageQueue.size.setImmediate (C:\Users\tolou-m\.vscode\extensions\mtxr.sqltools-0.20.1\extension.js:1:23934)
	at runCallback (timers.js:694:18)
	at tryOnImmediate (timers.js:665:5)
	at processImmediate (timers.js:647:5)] code: -32603, data: undefined }
INFO: Executing SQLTools.showOutputChannel

**Comment by mtxr** [comment]
You just need to install `NodeJS` to get it working. ` You need to install node@6 or newer and npm first to install dependencies. Install it and restart to continue.`

Just download the latest version or anything newer than version 6.
