### ISSUE TITLE
Cannot connect to previously working MariaDB connection (invalid semver)

### ISSUE THREAD

**Issue by nlaplante** [mtxr/vscode-sqltools#332]
**Describe the bug**
When trying to connect to a previously working connection to a MariaDB server, I get the following error message:
```
ERROR: Error:  { Error: Invalid argument not valid semver ('10.4.7-MariaDB-1:10.4.7+maria~bionic' received)
    at C:\Users\****\.vscode\extensions\mtxr.sqltools-0.20.1\extension.js:1:22921
    at C:\Users\****\.vscode\extensions\mtxr.sqltools-0.20.1\extension.js:1:23328
```

**To Reproduce**
1. Open SQL Tools panel
2. Click on connect icon of previously configured connection
3. See error message in notification popup

**Expected behavior**
The connection opens successfully

**Screenshots**
![image](https://user-images.githubusercontent.com/141054/63089495-13997f80-bf26-11e9-9cc5-fcba8e634f9a.png)

**Desktop (please complete the following information):**
 - SQLTools Version v0.20.1
 - VSCode Version: 1.37 (user setup)
 - Dialect Used/Version: MySQL
 - OS: Windows 10 1903

**Additional context**
The connection was setup about a week ago and was working perfectly.

**Comment by Napster2709** [comment]
Got the same Problem. Rolling back to 0.19.7 fixed it for me.

**Comment by mtxr** [comment]
Fixed. Will be visible for you guys to update soon.

Try version 0.20.2.

**Comment by nlaplante** [comment]
I confirm it works with 0.20.2. Thank you for your fast response!
