### ISSUE TITLE
bigint unsigned column display loss of precision

### ISSUE THREAD

**Issue by guerbai** [mtxr/vscode-sqltools#334]
**Describe the bug**
value 6684121293811353602 display in results is 6684121293811354000

**To Reproduce**
1. create a table with bigint unsigned column id
2. insert a row with id 6684121293811353602
3. run `select id from table where id=6684121293811353602`

**Expected behavior**
value 6684121293811353602 display in result is 6684121293811353602

**Screenshots**
![image](https://user-images.githubusercontent.com/17327981/63250745-e7239180-c29e-11e9-8fe9-5372999b2527.png)

**Desktop (please complete the following information):**
 - SQLTools Version: 0.20.2
 - VSCode Version: 1.34.0
 - Dialect Used/Version: Mysql5.7.23
 - OS: Mac

**Comment by mtxr** [comment]
Confirmed. Will be fixed and release in the next version. (~1 day)

**Comment by guerbai** [comment]
Thank you, waiting next version.
