### ISSUE TITLE
Add support for autocommit option

### ISSUE THREAD

**Issue by blassmegod** [mtxr/vscode-sqltools#341]
Please try and add autocommit option, as is very useful when creating a session/connection.
Also support for multiple queries to be sent would be interesting (on same connection), and just display for each the results as plain text.

**Comment by mtxr** [comment]
@blassmegod can you explain a little what you are looking for?

I believe we are already using single connection for all queries.

Which driver/rdbms are you using?

**Comment by blassmegod** [comment]
Hi @mtxr,
I'm using it to connect to an Oracle12c database, and the problem that I have is that even if the update/insert statements work, the changes are not committed in the database, so an option/functionality to choose to start the connection with auto-commit or not would really help. And for example if I'm trying to execute "commit;" after executing the "update table set col=val when blabla=something;" the previous change is not committed. Trying to execute both queries ( update + commit ) in one execution results in error as the extension doesn't support to execute multiple queries in one run.
P.S.: Other than that really nice and helpful extension.

**Comment by mickeypearce** [comment]
We could add `oracledb.autoCommit = true;` for now...

**Comment by blassmegod** [comment]
there is a property called "oracleOptions", which could be used to add extra options in the connection settings, but from what I saw in the code this is used just for pool stuff, so adding something else there is ignored. Maybe this part here could be refactored so that it can handle also other arguments from node-oracledb. If I will have some spare time maybe I can help, but I don't promise anything :)

**Comment by mickeypearce** [comment]
Yes, currently "oracleOptions" gets passed to oracledb.createPool() function (https://github.com/oracle/node-oracledb/blob/master/doc/api.md#-331-oracledbcreatepool). 

But It is not a bad idea to optionalize also the oracledb properties (https://github.com/oracle/node-oracledb/blob/master/doc/api.md#oracledbproperties), as you suggest.

**Comment by mtxr** [comment]
in the open() method:
```ts
	// @ts-ignore
    const { autoCommit, ...oracleOptions } = this.credentials.oracleOptions || {};
    await this.lib.createPool({
      connectString,
      password: this.credentials.password,
      user: this.credentials.username,
      poolAlias: this.poolName,
      ...oracleOptions
    });
```

and then in the query method:
```ts
const { autoCommit } = this.credentials.oracleOptions || {};
let res = await conn.execute(q, [], { outFormat: this.lib.OUT_FORMAT_OBJECT, autoCommit });
```

This is make the flag to be evaluated in query run time instead of globally set.

we just need to add this to the docs.

what do you think @mickeypearce ?

**Comment by mickeypearce** [comment]
Optionalizing the whole global property object would be too much, you think?

**Comment by mickeypearce** [comment]
And I would set also autoCommit to true by default.

**Comment by mtxr** [comment]
@mickeypearce 

> Optionalizing the whole global property object would be too much, you think?
> 
> We would have to set defaults for "fetchAsString" property, but leave an option for the user to change it through oracleOptions, along with other properties.

That's up to you. To be honest I don't have a preference in this case. Whatever works better and brings more value for Oracle users.


> And I would set also autoCommit to true by default.

Maybe this is to risky. We can enable it for sure, but we need to let users know about that. If you approach this default strategy, do you think would be nice to add this to connections assistant? A notice saying something like `by default autoCommit is enabled for this connection` or something like that?

@blassmegod what are your thought on this? Let's all share some thoughts too

**Comment by blassmegod** [comment]
@mtxr, I would say that autoCommit is a general option that should be useful also for other driver providers, not only for Oracle, so it would be nice that the SQLTools API would add it generally so that the rest of database drivers can use it.

P.S.: normally this should not be enabled by default as long as the transaction is not closed, I tried setting "poolMin":1 and "poolMax":1 and  "poolIncrement":0 in oracleOptions, but had no effect on "commit;" command. I think that node-oracledb somehow creates another connection in the pool or it closes the previous transaction when executing a second SQL query, but this is a thing that I still have to look into.

**Comment by mtxr** [comment]
Not supported within this repository anymore.
