### ISSUE TITLE
MSSQL: Display of rowversion columns isn't intuitive

### ISSUE THREAD

**Issue by ransagy** [mtxr/vscode-sqltools#344]
SQL Server has a column type of `rowversion` that keeps an automatically incremented number, mostly used to verify when a row was changed.

Right now it's displayed as raw data (`{"data":[0,0,0,0,124,213,26,20],"type":"Buffer"}`) instead of the actual value (i.e. `0x00000000000007D3`).

The way it is displayed in SQL Tools is different to other DB tools I've used in the past and the inconsistency is not very intuitive. It also causes the row heights to be greater since so far for me by default it's value is always "wrapped" around more than a single row's height.

I think it would be useful to parse this column type as intended.

https://docs.microsoft.com/en-us/sql/t-sql/data-types/rowversion-transact-sql?view=sql-server-2017

**Comment by mtxr** [comment]
Hi @ransagy . I'm trying to figure out how to convert that buffer to the desired value you provided.

To add the support you want, the better place would be here
https://github.com/mtxr/vscode-sqltools/blob/f1f4dd12a0cb7958fd206d3d29037ac40c4cb329/packages/ui/screens/Results/ResultsTable.tsx#L55

But we need to know how to convert it first
