### ISSUE TITLE
You need to install "oracledb@3.1.1" DependencyInstaller/install failed unexpectedly without providing any details

### ISSUE THREAD

**Issue by coldfault** [mtxr/vscode-sqltools#348]
When trying to connect to oracledb i am getting prompted to install above mentioned dependency, which fails with the following error...

Output: 
ERROR: Error:  { [Error: Request DependencyInstaller/install failed unexpectedly without providing any details.
	at C:\Users\username\.vscode\extensions\mtxr.sqltools-0.20.2\extension.js:1:22983
	at C:\Users\username\.vscode\extensions\mtxr.sqltools-0.20.2\extension.js:1:23390
	at Immediate.module.exports.messageQueue.size.setImmediate (C:\Users\username\.vscode\extensions\mtxr.sqltools-0.20.2\extension.js:1:23934)
	at runCallback (timers.js:694:18)
	at tryOnImmediate (timers.js:665:5)
	at processImmediate (timers.js:647:5)] code: -32603, data: undefined }

Same issue as Linh1706 reported in this closed issue... https://github.com/mtxr/vscode-sqltools/issues/137#issuecomment-522212124

Version VSCode 1.37.1 Node version 12.9.1
Btw there should be already Version 4 of oracledb available...

**Comment by mtxr** [comment]
This is already fixed here https://github.com/mtxr/vscode-sqltools/commit/094f7a27c28db5105ab0cfc4b406c9fff643949e. It will be release this weekend. Ok?
