### ISSUE TITLE
Oracle - Schema Browser

### ISSUE THREAD

**Issue by thiago-paz** [mtxr/vscode-sqltools#349]
When I connect an Oracle database, I can't see the database explorer properly. This is because my read-only user needs to switch the schema browser of another user. Is it possible to fill the database explorer using a parameter from settings.json?

For example... I access my oracle read-only user, but I would like to see the schema browser (tables, views) from "services" user:

Setting.json:
"sqltools.connections": [
    {
         "dialect": "OracleDB",
         "name": "My Oracle DB",
         "server": "127.0.0.1",
         "port": 1521,
         "database": "DEV",
         "username": "read_only_user",
         "password": "read_only_user",
         **"schemaBrowser": "services"**
    }
]

And the "database explorer" on vscode, would be filled by the query below, using OWNER described on settings.json:

SELECT owner, table_name FROM all_tables
WHERE **owner = 'SERVICES'**;

Is it possible?

Thanks

**Comment by mtxr** [comment]
Closing. Will be tracked in #322
