### ISSUE TITLE
Unable to run more than 1 query at a time - OracleDB

### ISSUE THREAD

**Issue by MrSnowball-dev** [mtxr/vscode-sqltools#350]
**Describe the bug**
I have a large script of about ~800 'INSERT INTO...' queries which I need to run in OracleDB. It is formatted correctly, and each statement runs fine, showing me a result. But when I select all queries at once and try to run (ctrl+e+e), result window shows me an error 'ORA-00911: Invalid character'.

**To Reproduce**
1. Connect to OracleDB
2. Write 2 simple select statements
3. Select these statements and press 'Run selected query'

**Expected behavior**
Query runs fine 1 statement at a time through ';' delimiters.

**Screenshots**
![image](https://user-images.githubusercontent.com/23441203/64034588-a279df00-cb57-11e9-868c-ac718fa07b54.png)
![image](https://user-images.githubusercontent.com/23441203/64034592-a443a280-cb57-11e9-90c7-826a851ca55d.png)

**Desktop (please complete the following information):**
 - SQLTools Version: 0.20.2
 - VSCode Version: 1.37.1
 - Dialect Used/Version: Oracle CE
 - OS: Windows

**Comment by mtxr** [comment]
Hi @MrSnowball-dev , thanks for reaching us.

Hey @mickeypearce , can you take a look at this later?

**Comment by dnlw07** [comment]
I have same issue. Multiple select scripts also not working.

**Comment by CurrenWong** [comment]
Same issue with mysql.

**Comment by mtxr** [comment]
Not supported within this repository anymore.

**Comment by robertmarkbram** [comment]
> Not supported within this repository anymore.

Can I ask what this means? Won't fix, or won't fix in this extension? Is there a hard limit that means multiple queries cannot be run at once?

**Comment by stevenzlee** [comment]
Would appreciate the capability to run multiple ; separated queries as well... for mysql

**Comment by freddietattersall** [comment]
Hi @mtxr - would it be possible to understand if running multiple queries at once is in the pipeline for this product? This extremely useful and is currently a pretty big limitation on the usefulness of this extension? Thanks, Freddie

**Comment by gjsjohnmurray** [comment]
@freddietattersall which driver extension are you using in conjunction with the SQLTools extension? This issue was originally raised for an OracleDB driver extension.
