### ISSUE TITLE
Database gets disconnected when vim extension changes status bar color

### ISSUE THREAD

**Issue by sshantt** [mtxr/vscode-sqltools#351]
**Describe the bug**
The database gets disconnected whenever the vim extension changes mode with status bar color change turned on. Within the VScode Vim extension, there is the following option 

    "vim.statusBarColorControl": true|false,

When this is set to true, it changes the bottom status bar color depending on the current Vim mode. Whenever this option is turned on and a mode change is invoked, vscode-sqltools disconnects from the current database its connected to. 

**To Reproduce**
1. Download vscode-sqltools and vim extensions
2. set < "vim.statusBarColorControl": true >
3. Connect to a database
4. Execute query 
5. Change Vim mode 
6. Execute query 
7. Wait for vscode-sqltools to reconnect to database
8. etc...

**Expected behavior**
The database should remain connected whenever a mode change occurs in vim with a corresponding status bar color change.

**Desktop (please complete the following information):**
 - SQLTools Version: v0.12
 - Vim Version: 1.10.2
 - VSCode Version: 1.38.0-insider
 - Dialect Used/Version:  Redshift
 - OS: Mac

**Comment by mtxr** [comment]
@sshantt I'll release a new version today and it doesn't seem to be happening anymore.

We had a few enhancements on explorer. It might have fixed this.

Please, let me know if the issue persists
