### ISSUE TITLE
Column suggestions appear from all tables as opposed to mentioned tables

### ISSUE THREAD

**Issue by sshantt** [mtxr/vscode-sqltools#353]
**Describe the bug**
When writing a query, column suggestions appear from all tables in the database as opposed to the ones that have been mentioned in the query. Beyond that, the "." (dot) operator does not invoke suggestions from the table/schema name preceding it. Also, as a side note, suggestions are slow to pop up and sometimes do not end up popping up at all before I finish typing even when I type slowly.

**To Reproduce**
1. Install and configure vscode-sqltools
2. Start typing a query
3. In there where statement, notice columns from all tables show up in the suggestions box
4. Also, in the select statement, type a table name followed by a dot and notice the table columns don't show up in the suggestions 

**Expected behavior**
Only columns from mentioned tables or table names followed by a dot should show up in suggestions. Or they should at least show up first if this behavior is unfavorable to other users.

**Desktop (please complete the following information):**
 - SQLTools Version v0.20.2
 - VSCode Version: 1.38.0-insider
 - Dialect Used/Version: Redshift
 - OS: Mac

**Comment by mtxr** [comment]
dup of #110
