### ISSUE TITLE
Execute region

### ISSUE THREAD

**Issue by sshantt** [mtxr/vscode-sqltools#354]
**Is your feature request related to a problem? Please describe.**
Currently, the only way to execute a query is to use codelens or highlight the query and invoke the execute command. 

**Describe the solution you'd like**
It would make it a lot easier to execute queries by only having to have the cursor in the bounds of the query and having vscode-sqltools recognize the bounds of the query. This usually corresponds to line breaks but a more robust logic can easily be developed based on keywords.

**Describe alternatives you've considered**
I currently click command-open_curly_bracket to jump to the previous line break, then shift-V to enter Vim-line-highlight mode. Followed by command-close_curly_bracket to jump to the next line break. After This is done, I can then proceed to press command-e command-e to run the highlighted query

**Comment by mtxr** [comment]
Dup of https://github.com/mtxr/vscode-sqltools/issues/277. Closing.
