### ISSUE TITLE
Database specific function suggestions 

### ISSUE THREAD

**Issue by sshantt** [mtxr/vscode-sqltools#355]
**Is your feature request related to a problem? Please describe.**
When connected to Redshift, I do not get keyword and function suggestions. 

**Describe the solution you'd like**
Some functions are hard to remember (json_extract_array_element_text, etc...) and it would be useful for the suggestion box to include those somehow.

**Describe alternatives you've considered**
I don't mind populating the functions and keywords myself into a json file but I currently can't figure out a way to do that.

**Comment by mtxr** [comment]
Merging into #110 .
