### ISSUE TITLE
Comments after sql in selection cause an error during running a query 

### ISSUE THREAD

**Issue by dnlw07** [mtxr/vscode-sqltools#359]
**Describe the bug**
Comments after sql in selection cause an error during running a query;
Error: _ORA-00933: SQL command not properly ended_

**To Reproduce**
1. Write a comment after SQL query
2. Select all (Ctrl-A) 
3. Run query

**Expected behavior**
Ignores the comment after the query and return query result

**Screenshots**

![screenshot 23](https://user-images.githubusercontent.com/23562689/64134329-3a3c2f00-cddd-11e9-8079-731204d3f94d.jpg)

**Desktop (please complete the following information):**
    SQLTools Version v0.20.2 (lastest)
    VSCode Version: 1.37.1 (lastest)
    Dialect Used/Version: Oracle 12c
    OS: Windows 10

**Comment by mtxr** [comment]
Not supported within this repository anymore.
