### ISSUE TITLE
Add an option to save only selected part of query results to csv in context menu

### ISSUE THREAD

**Issue by dnlw07** [mtxr/vscode-sqltools#360]
**Is your feature request related to a problem? Please describe.**
Add an option to save only selected part of query results to CSV in context menu. 
If possible please, also include if results should contain headers or not.

**Describe alternatives you've considered**

**Example Screenshot**
![screenshot 24](https://user-images.githubusercontent.com/23562689/64134486-8e93de80-cdde-11e9-9dd5-28cab9f756e0.jpg)

**Comment by mtxr** [comment]
Done in v0.22. You can select the rows you want and save or open editor with those rows
