### ISSUE TITLE
option to show result as backgourd tab

### ISSUE THREAD

**Issue by dnlw07** [mtxr/vscode-sqltools#364]
**Is your feature request related to a problem? Please describe.**
Add an option to choose, if query result tab should appear in background/foreground and in the same or separate tab group as query.

**Comment by mtxr** [comment]
This is not supported by VSCODE. Currently when opening a tab or view, it will show up to the user. The only change possible is if we can focus or not to that tab.

We could do a "hacky" change and switch back to the previous tab/view, but it would cause a glitch in the screen.

To select where it shows, you can use this setting:
https://github.com/mtxr/vscode-sqltools/blob/bb29d5bf8259243d5fab58329a8f5e80599f97eb/.test-database/project.code-workspace#L30
