### ISSUE TITLE
Add option to return next #N rows when showing table records

### ISSUE THREAD

**Issue by dnlw07** [mtxr/vscode-sqltools#365]
**Is your feature request related to a problem? Please describe.**
Add option to return first 50 rows only, and add button in query result **"return next 50 records"**  and **"return all results"**

**Comment by mtxr** [comment]
Hi.

We currently have the option to return just the `#N records`. See: https://github.com/mtxr/vscode-sqltools/blob/bb29d5bf8259243d5fab58329a8f5e80599f97eb/.test-database/project.code-workspace#L29

I like the idea of paginating it. But meanwhile you can show the first `#N` records and if needs more, the query needs to be manually.

**Comment by dnlw07** [comment]
Thanks for feedback,
I have checked that setting, but I am afraid `"limit": 100, ` is not working.

After applying that setting, querying a big table still returns its all results, instead first 100 only.

I need to manually add condition `where rownum >100` to sql to return first 100 only.

**Comment by mickeypearce** [comment]
The limit applies only to "Show table records" command and not when executing a general query ("Run this file | query"), is that correct @mtxr?

With "Show table records" it works in my case. You can see the actual query executed if you click on "QUERY DETALS" at the bottom of the results grid.

**Comment by mtxr** [comment]
That's correct.

We just limit queries we generate. What user type we avoid changing

**Comment by dnlw07** [comment]
Yes, you are right.
However I believe it would be a nice option to add this functionality even for what user is typing. 
Many tools already have it, like SQL Developer or SQuirreL, etc. 
I found myself it's a bit annoying to each time add/remove the additional filter condition `rownum <= 100`, to not "kill" DB.

**Comment by mtxr** [comment]
Since we don't want to change the query without his approval, let's add an alert first.

Requirements:
1. Show an alert `You are running a select query that has no limit clause, would you like to add it before continue?` before changing the query.

**Comment by dnlw07** [comment]
Yeah, good idea!
By default the alert should be always shown.
However, please consider the option to turn off the alert in settings.

**Comment by mtxr** [comment]
You are totally right. Evolving requirements:

Requirements:
1. Show an alert `You are running a select query that has no limit clause, would you like to add it before continue?` before changing the query.
2. Add an option to ignore this alerts

**Comment by mtxr** [comment]
Done on v0.22. Closing

**Comment by johndevedu** [comment]
@mtxr which version of v0.22 has this? Could not find it in the changelog. I'm currently on v0.22.9 and wondering what the syntax is for enabling this feature. Thanks!

**Comment by mtxr** [comment]
Hi @johndevedu , it's the first version, it's enabled by default also so you should be seeing this on any queries resulting in rows number bigger than the limit

**Comment by johndevedu** [comment]
@mtxr I am not getting the alert when doing a select query on 0.22.9. I have the limit set to:

```
  "sqltools.results": {
    "limit": 20
  }
```

**Comment by mathief123** [comment]
Hi! I'm also not getting the alert, is it fixed yet?

**Comment by vibhavagarwal5** [comment]
Is this working? I dont see any alerts. @mtxr  @gjsjohnmurray  how to auto set limits while running query? can the extension auto set limit to queries?

**Comment by gjsjohnmurray** [comment]
My searches of the codebase didn't find this implemented anywhere. @mtxr did I miss something?
