### ISSUE TITLE
Please disable the notification to support this project

### ISSUE THREAD

**Issue by marcocastignoli** [mtxr/vscode-sqltools#37]
Each time I open my editor I get a notification saying "Do you like SQLTools? [...]". I can't find a way in the options to mute this notification. Thanks.

**Comment by mtxr** [comment]
It will be removed this week, but not completely. It will still pop up after some time.

For donators (any amount), it will be removed using a key code provide by email.

Have you consider to support open source projects?

**Comment by moberemk** [comment]
Okay, while I appreciate where you're coming from here and agree that we as a community should try and support open-source projects more, having it only be disabled via a key code provide in exchange for money reminds me of shareware tactics. Honestly, until now I thought it was a bug that was making it appear so much.

**Comment by marcocastignoli** [comment]
@moberemk totally agree with you. I will use my fork of this plugin till the notification will be removed.

**Comment by mtxr** [comment]
You are right, @moberemk . Shareware is not something we would appreciate. But we need to find a way to keep it evolving. It takes me a lot of time to develop, maintain, and look for features. I have a family, a full-time job and I do this in my free time, for free. Also as you can check, I use to contribute to other projects like yarn, vscode, etc. They all are free and receive some resources for the main maintainers to keep it evolving.

@marcocastignoli, feel free to fork and remove the message. I don't think it fits in the open source community if that's you first resource to keep it working.

**Comment by mtxr** [comment]
Enhanced. Closing.
