### ISSUE TITLE
Exporting/Importing connections 

### ISSUE THREAD

**Issue by acumenrev** [mtxr/vscode-sqltools#370]
**Is your feature request related to a problem? Please describe.**
Currently, we manually provide credentials for a connection

**Describe the solution you'd like**
Exporting connections to a config file, then I can import this one in a new machine

**Comment by mtxr** [comment]
Is it really needed?

Currently we have an amazing project called [code-settings-sync](https://github.com/shanalikhan/code-settings-sync) by @shanalikhan. It does exactly what you want but "automagically".

Even if you don't want to use his project, you can just open your `settings.json`/`*.code-workspace` file(s) copy and paste anywhere you want. 

As much as possible, I would like to keep the project as much attached to the Database Management domain as possible. I not against implementing import/export connections, but I don't see a strong reason why developing this right now with such a strong project like https://github.com/shanalikhan/code-settings-sync

Give code-sync a change, I'm 100% sure you won't regret.
