### ISSUE TITLE
Intellisense/Autocomplete returning columns from every single table that is similarly named

### ISSUE THREAD

**Issue by willstocks** [mtxr/vscode-sqltools#371]
**Describe the bug**
Hello!
I've just installed and have noticed that the column autocomplete in some cases can be fairly... difficult to use. 
For instance, I had a query:
```sql
SELECT
  *
FROM
  A
WHERE
  A.Name LIKE '%name%'
```

I was then going to expand this by implementing a simple JOIN:

```sql
SELECT
  *
FROM
  A
INNER JOIN B ON A.ID = B.AID
WHERE
  UserName LIKE '%nando%'
  AND Deleted = 0
```

However the intellisense/column autocomplete on the JOIN pulled back every single ID column from the connected database when I typed `ON A.I` (the database has over 100 tables, most of which have ID column - for some reason the intellisense/autocomplete showed ALL of these ID columns as an available selection?)

**To Reproduce**
1. Create a database connection
2. Connect the connection to a file
3. Create the basic SQL outlined above
4. Start writing a JOIN and see that every related column name from any table is returned in intellisense/autocomplete.

**Expected behavior**
I should only see autocomplete options for the relevant included tables. For instance if I type `A.` I would only expect to see autocomplete columns for those in the `A` table. Likewise, I should only see table autocomplete options for `B` considering that that is the table I am trying to JOIN. It doesn't help me having a full table list to have available in autocomplete when I am trying to simply join B to A.

**Screenshots**
tbc

**Desktop (please complete the following information):**
 - SQLTools Version: 0.20.3
 - VSCode Version: 1.37.1
 - Dialect Used/Version: MSSQL
 - OS: Windows 10 Pro

**Additional context**

**Comment by mtxr** [comment]
Dup of #110. Closing
