### ISSUE TITLE
ORACLE: ORA-00923: FROM keyword not found where expected. When trying to connect.

### ISSUE THREAD

**Issue by GAZ082** [mtxr/vscode-sqltools#372]
**Describe the bug**
Cant connect.

**To Reproduce**
Try to connect to the DB.

Oracle Database 10g Enterprise Edition Release 10.2.0.5.0 - Prod
Windows10
VSCode 1.38.0
SQLTools 0.20.3

![sql](https://user-images.githubusercontent.com/100194/64359977-d9307900-cfdf-11e9-909e-b9a315cfd740.gif)

**Comment by 188008017** [comment]
Function "listagg" in file "/packages/core/dialect/oracle/queries.ts".but is only with oracle 11g.
if you  connect 10g (before oracle 10g) then catch the error

**Comment by mtxr** [comment]
Not supported within this repository anymore.
