### ISSUE TITLE
Support for Azure Active Directory login in MSSQL/Tedious

### ISSUE THREAD

**Issue by ransagy** [mtxr/vscode-sqltools#375]
Would it be possible to support Azure Active Directory (password) logins in the extension?

As per the tediousjs documentation (http://tediousjs.github.io/tedious/api-connection.html), tedious and the version used by node-mssql already supports it.

Where would i look to if i wanted to add a PR for this?

**Comment by mtxr** [comment]
Hey @ransagy is possible for sure.

But I believe we already support this, it's just not documented.

Did you try to add it those options to `mssqlOptions` like this:
```json
"mssqlOptions": {
  ...
  "authentication": {
    "type": "azure-active-directory-password",
    "options": {
      "userName": "<userName>",
      "password": "<password>"
    }
  },
}
```

**Comment by ransagy** [comment]
@mtxr You're right, it does work; but only if the password is embedded in the configuration. if i try to use `"askForPassword": false` and only leave the username part of that, authentication fails.

**Comment by BobbyMcWho** [comment]
@ransagy wouldn't you want "askForPassword" to be true if you're not embedding it in the json?

**Comment by ransagy** [comment]
@BobbyMcWho that's just the problem; it doesn't input the password into the specific aad password field in this case, vut in nto

**Comment by mtxr** [comment]
@ransagy I just did a commit. I don't have a way to test it. Would you mind testing and reaching me back?

**Comment by ransagy** [comment]
@mtxr I'll try grabbing the repo and building to test, will get back to you.

**Comment by ransagy** [comment]
@mtxr confirmed working, thanks!

**Comment by mtxr** [comment]
Awesome!
