### ISSUE TITLE
Vscode-sqltools cannot connect to mysql 8.0.x server

### ISSUE THREAD

**Issue by sundaycat** [mtxr/vscode-sqltools#376]
**Describe the bug**

I installed mysql 8.0.17 on an idle Mac as server and tried to remotely access it with my own computer. Everything works fine in command line. But it doesn't work with Sqltools in VScode. I set up the settings exactly as [#195](https://github.com/mtxr/vscode-sqltools/issues/195) suggested(except the port number was set to 33060) and the x plugins has been installed on MySQL Server and port 33060 is open to mysql. The following is a configuration file fragment generated when I create a mysql connection with vscode-sqltools. The current configuration file is ~/.config/Code/global/settings.json.

```
"sqltools.connections": [
      {
        "askForPassword": false,
        "connectionTimeout": 30,
        "database": "MyDB",
        "dialect": "MySQL",
        "name": "LocalDB",
        "password": "123456",
        "port": 33060,
        "server": "xx.xxx.xx.xx",
        "username": "sundaycat",
        "mysqlOptions": {
          "authProtocol": "xprotocol"
        }
      }
    ]
```

The error message I got is

```
INFO: Executing SQLTools.selectConnection
ERROR: Error:  { [Error: Handshake inactivity timeout
	at /Users/sundaycat/.vscode/extensions/mtxr.sqltools-0.20.3/extension.js:1:22983
	at /Users/sundaycat/.vscode/extensions/mtxr.sqltools-0.20.3/extension.js:1:23390
	at Immediate.module.exports.messageQueue.size.setImmediate (/Users/sundaycat/.vscode/extensions/mtxr.sqltools-0.20.3/extension.js:1:23934)
	at runCallback (timers.js:694:18)
	at tryOnImmediate (timers.js:665:5)
	at processImmediate (timers.js:647:5)] code: -32001, data: { dialect: 'MySQL', dialectOptions: {} } }
```

**Expected behavior**
Successfully connect to MySQL Server via Sql-tools

**Desktop (please complete the following information):**
 - SQLTools Version 0.20.3
 - VSCode Version: 1.38.0
 - Mysql Version: 8.0.7
 - OS: MacOS Mojave 10.14.6

**Additional context**

**Comment by mtxr** [comment]
Please, take a look at this issue on driver's repository: https://github.com/mysqljs/mysql/issues/1616

You might need to allow UDP packages in you network.

**Comment by yanickrochon** [comment]
This issue is cyclical and does not explicitly propose a resolution; how do I enable "UDP packages in [my] network"? Is that some option I set?
