### ISSUE TITLE
Need permissions to push changeset for support DB2

### ISSUE THREAD

**Issue by snyang** [mtxr/vscode-sqltools#380]
**Describe the solution you'd like**
Write an extension via [node ibm_db](https://github.com/ibmdb/node-ibm_db/)

**Describe alternatives you've considered**

**Additional context**
I've implemented the feature, but I need permissions or guide to push my fix.

**Comment by snyang** [comment]
@mtxr may you add me as a contributor? I've implemented 'support DB2', want to create a PR for my changes.

**Comment by mtxr** [comment]
Thanks @snyang !

For sure I'll add. In fact when you open a PR, I'll add you on the change log as I did to other contributors.

And thinking about a long term relationship, would you like to be assigned to new issues opened for DB2?

noite How to merge your changes, just open a PR, I'll review the code and approve the changes. After that I'll merge and update the change log. Ok?

Please see #379 for example

**Comment by snyang** [comment]
@mtxr yes. I'd like to handle new issues for DB2.

**Comment by snyang** [comment]
@mtxr I still cannot push my changes.

**Comment by mtxr** [comment]
Sorry, I didn't have time yesterday to release. I'll try to do it today.

**Comment by mtxr** [comment]
@snyang can you open a PR? everyone should be able to do it.

I believe you've already forked, right?

**Comment by snyang** [comment]
@mtxr oh. I followed process of creating a private branch. I will try to fork and create a PR process soon.
