### ISSUE TITLE
SQLTools keeps connecting to the same database

### ISSUE THREAD

**Issue by jscul** [mtxr/vscode-sqltools#383]
**Describe the bug**
The connections all connect to the same exact database even though they're described as different databases in the settings.

**To Reproduce**
1. Add two connections: 
```
"sqltools.connections": [
		{
			"askForPassword": true,
			"connectionTimeout": 30,
			"database": "dtm-sd",
			"dialect": "MySQL",
			"name": "localhost",
			"port": 3306,
			"server": "127.0.0.1",
			"username": "root"
		},
		{
			"askForPassword": true,
			"connectionTimeout": 30,
			"database": "socka",
			"dialect": "MySQL",
			"name": "socka",
			"port": 3306,
			"server": "127.0.0.1",
			"username": "root"
		}
	]
```
2. Connect to either database, the same database shows up.
3. ![image](https://user-images.githubusercontent.com/22265367/65003648-441a6380-d8ae-11e9-97f4-ccfab81c716c.png)

**Expected behavior**
I expect to connect to different databases if the "database" value in "sqltools.connections" is different.

**Screenshots**
Provided a screenshot above.

**Desktop (please complete the following information):**
 - SQLTools Version 0.20.3
 - VSCode Version: 1.38.0
 - Dialect Used/Version: 5.7.27, for Linux (x86_64)
 - OS: Linux

**Comment by mtxr** [comment]
@jscul  can you try latest version and see if the problem persists?

If error still exists, can you send me a few screenshots or logs of the bug?

Also, do you have a session file open or have you attached a connection to any files?

**Comment by jscul** [comment]
I just installed the latest version (looks great) but the bug continues :(

These are the settings I'm using in the global settings ⬇️
```
{
	"connectionTimeout": 30,
	"database": "dtm-sd",
	"dialect": "MySQL",
	"name": "dtm-sd",
	"password": "***",
	"port": 3306,
	"server": "127.0.0.1",
	"username": "root"
},
{
	"connectionTimeout": 30,
	"database": "test-db",
	"dialect": "MySQL",
	"name": "test-db",
	"password": "***",
	"port": 3306,
	"server": "localhost",
	"username": "root"
}
```

But the problem persists...
![image](https://user-images.githubusercontent.com/22265367/65279298-bd9a9780-dae2-11e9-84ed-728c90083668.png)

I don't see any session files in my editor.

Further the databases are showing up properly in the terminal.
![image](https://user-images.githubusercontent.com/22265367/65279486-2c77f080-dae3-11e9-9116-138a61133d76.png)

**Comment by mtxr** [comment]
Oh! I see what you mean now. 

Well, actually we are showing all DBs if they are in the same MySQL instance, so you don't need 2 connections for now. I'm working on #322 that is more likely what you need. I'll close this issue and add it to #322 list since it will be fixed together, ok?

**Comment by jscul** [comment]
Ah okay - thanks for your help!
