### ISSUE TITLE
Run selected not working

### ISSUE THREAD

**Issue by xgdgsc** [mtxr/vscode-sqltools#386]
**Describe the bug**
run selected not working

**To Reproduce**
1. Go to tab of session.sql
2. select the region you want to query
3. call run selected query
4. error shows you have selected nothing and opens up an untitled tab.

**Expected behavior**
query works.
 

**Desktop (please complete the following information):**
 - SQLTools Version 0.20.3
 - VSCode Version:  1.38.1
 - Dialect Used/Version: MySQL
 - OS: ubuntu 16.04

**Comment by mtxr** [comment]
@xgdgsc can you try latest version and see if the problem persists?

If error still exists, can you send me a few screenshots or logs of the bug?

**Comment by xgdgsc** [comment]
Thanks. After uninstalling https://github.com/Microsoft/vscode-mssql it works.
