### ISSUE TITLE
Timezone is assumed

### ISSUE THREAD

**Issue by vadi2** [mtxr/vscode-sqltools#388]
**Describe the bug**
Timezones in `DateTime` formats are assumed, which is misleading.

**To Reproduce**
1. Run http://docs.simplifier.net/_downloads/86acc454cdad36b5d1ece286b582d9f0/CreateDatabase.sql
4. Observe how plugin assumed the dates are in UTC when they aren't:

![Selection_485](https://user-images.githubusercontent.com/110988/65147057-9332d680-da1d-11e9-8801-a8876a10054c.png)

I was really confused as to why my results were wrong until I figured out that the issue is in the plugins display.

**Expected behavior**
If no timezone is available in the raw data, none should be assumed in the output display.

**Desktop (please complete the following information):**
 - SQLTools Version 0.20.3 
 - VSCode Version: 1.38.1
 - Dialect Used/Version: MS SQL
 - OS: Linux

**Comment by mtxr** [comment]
@vadi2 this is bug is because of MSSQL driver.

For now you can workaround this using this in you settings:
```json
{
        "name": "MSSQL",
        "server": "localhost",
        "dialect": "MSSQL",
        ...
        "mssqlOptions": {
          ...
          // add these lines below
          "options": {
            "useUTC": false
          }
        }
      },
```

**Comment by mtxr** [comment]
This is a driver setting. It will fix you problem for now, but I'm trying new drivers to allow us to display date and times for SQL server like other tools
