### ISSUE TITLE
Postgres materialized views not shown in 

### ISSUE THREAD

**Issue by themightychris** [mtxr/vscode-sqltools#392]
**Describe the bug**

Materialized views in a postgres database do not show up in the connections explorer tree

**To Reproduce**
1. Create a materialized view within a postgres database
2. Connect to the postgres database with SQL Tools
3. Materialized view is not shown under tables or views subtree

**Expected behavior**
Materialized views should show up under a tables or views subtree, whichever is more practical for the current pipeline but they should at least show up

**Screenshots**

**Desktop (please complete the following information):**
 - SQLTools Version: 0.21.0 and earlier
 - VSCode Version: 1.38.1 and earlier
 - Dialect Used/Version: PostgreSQL 11
 - OS: Linux

**Comment by mtxr** [comment]
Merging into #322

**Comment by mtxr** [comment]
Close in previous commit.
