### ISSUE TITLE
Not working for keyboard shortcuts 

### ISSUE THREAD

**Issue by nirzaf** [mtxr/vscode-sqltools#393]
Error Notification "command 'extension.vscode-git-automator.pushLocalCommits' not found"

- Issue Type: `Performance`
- Extension Name: `sqltools`
- Extension Version: `0.21.0`
- OS Version: `Windows_NT x64 10.0.17763`
- VSCode version: `1.38.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\Nirzaf\mtxr.sqltools-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by mtxr** [comment]
@nirzaf  This issue is not from this extension. Closing.
