### ISSUE TITLE
Cannot connect to SQL server using windows authentication.

### ISSUE THREAD

**Issue by cstyve** [mtxr/vscode-sqltools#394]
When attempting to connect to sql server using the following valid connection string as an example
"server=mydbserver;database=mydatabase;Integrated Security=true;"
 sql tools report s the following error

**Login failed for user ''.**

**To Reproduce**
1. Go to "Add New Connection"
2. Click on 'MSSQL' icon
3. Click on "Connection Method" and change to "Connection String"
4. Click on "Connection String" textbox and enter a valid connection string similar to the example above.
4. SQL Tools returns error **Login failed for user ''.**

**Expected behavior**
Connecting to SQL Server using integrated security should connect to the SQL server database using the current windows credentials.

**Desktop (please complete the following information):**
 - SQLTools Version [Latest version]
 - VSCode Version: 1.38.1
 - Dialect Used/Version: MS SQL
 - OS: [Windows]

**Comment by BobbyMcWho** [comment]
You need to add a User ID and password to the connection string:
`server=mydbserver;database=mydatabase;Integrated Security=true;User ID=domain\username;Password=your_pass`

**Comment by mtxr** [comment]
Thanks @BobbyMcWho. Would you mind adding this to the docs as well?

**Comment by cstyve** [comment]
Using integrated security in the connection string allows an app to connect to a server without coding the actual credentials (username/password).  Entering and saving in the configuration file the username and password reveals the domain authentication used to whomever looks at the connection settings.  

I believe this provides a significant vulnerability in the security of the server having usernames and passwords exposed.  Is it possible to either encrypt the password or avoid having the username/password from being entered when using integrated security?

**Comment by Fred-Wu** [comment]
New to dbcode, was trying to find the same answer that if windows authentication is used, why still need to enter username/password?

**Comment by Jomy10** [comment]
Can we consider reopening this? Having to enter User ID and Password in the connection string defeats the purpose of using Windows credentials.

**Comment by gjsjohnmurray** [comment]
@Jomy10 please see #843
