### ISSUE TITLE
Not able to connect to docker mysql8 from sql tools with protocol tcp

### ISSUE THREAD

**Issue by komalbb** [mtxr/vscode-sqltools#402]
**Describe the bug**
I am trying to connect to mysql8 running on docker instance from VSCode sqltools. The error is: 
Connection String: Server=localhost;Database=test;Uid=user;Pwd=user;Protocol=tcp;Port=3307
Docker is running on my localhost on port 3307
1f2898611348        mysql/mysql-server   "/entrypoint.sh mysq…"   6 days ago          Up About an hour (healthy)   33060/tcp, 0.0.0.0:3307->3306/tcp   mysql

ERROR:
INFO: Executing SQLTools.selectConnection
ERROR: Error:  { [Error: ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client
	at /Users/komal/.vscode/extensions/mtxr.sqltools-0.21.0/extension.js:1:22985
	at /Users/komal/.vscode/extensions/mtxr.sqltools-0.21.0/extension.js:1:23392
	at Immediate.module.exports.messageQueue.size.setImmediate (/Users/komal/.vscode/extensions/mtxr.sqltools-0.21.0/extension.js:1:23936)
	at runCallback (timers.js:694:18)
	at tryOnImmediate (timers.js:665:5)
	at processImmediate (timers.js:647:5)] code: -32001, data: { dialect: 'MySQL', dialectOptions: {} } }
INFO: Executing SQLTools.openEditConnectionScreen
INFO: Executing SQLTools.showOutputChannel
INFO: Executing SQLTools.testConnection

Able to connect to the same from command line on vm.
mysql -h localhost -u user -puser -P 3307 --protocol=tcp

**To Reproduce**
1. Go to '...' create a docker instance of mysql8
2. Click on '....' from VSCode connected to VM which is running docker.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - SQLTools Version [e.g. v0.17.x] mysql  Ver 14.14 Distrib 5.7.27, for Linux (x86_64) using  EditLine wrapper
 - VSCode Version: [e.g 1.x.y] 1.38
 - Dialect Used/Version: [e.g PostgreSQL 9, Oracle CE, SQLite, MySQL 6, Redshift..] MYSQL
 - OS: [e.g. Windows, Linux, Mac] Linux.

**Additional context**

**Comment by mtxr** [comment]
This is already described here: https://vscode-sqltools.mteixeira.dev/driver/mysql#mysql-8-and-er_not_supported_auth_mode

**Comment by Maransatto** [comment]
> This is already described here: https://vscode-sqltools.mteixeira.dev/driver/mysql#mysql-8-and-er_not_supported_auth_mode

Hi.
I've tried to follow these instructions, but now I got the following error

Error opening connection Client option 'pooling.maxIdleTime' does not support value 'NaN'.

Note: I'm also using docker but my port is now 3307, so I've tried 33070.

**Comment by danhanson** [comment]
@Maransatto Searching the repo for maxIdleTime, I found [this](https://github.com/mtxr/vscode-sqltools/blob/8f396d61ef8f37517054112573fb778ed054805f/packages/driver.mysql/src/ls/xprotocol.ts#L31).

Not setting a connection timeout results in NaN being computed for pooling.maxIdleTime.

Just setting a timeout in the connection configuration fixes the problem.

**Comment by OzzyTheGiant** [comment]
Followed all instructions above: used xprotocol, defined connection timeout, set up user to connect on localhost with password and all I get at the end is `server has gone away`. Using MySQL 8

**Comment by dugufeiyun** [comment]
> Followed all instructions above: used xprotocol, defined connection timeout, set up user to connect on localhost with password and all I get at the end is `server has gone away`. Using MySQL 8

Me too ... 
How to solve it ??

**Comment by philopian** [comment]
So this is what i did to get it working...

1.  Spin up a docker container
  ```shell
  # Pull the latest image
  $ docker pull mysql/mysql-server:latest

  # Create & run a container
  $ docker run --name some-mysql -p 3306:3306 -p 33060:33060  -e MYSQL_ROOT_PASSWORD=123456789 -d mysql
  $ docker exec -it some-mysql mysql -uroot -p
  # 123456789     <-- (the password)
  mysql> CREATE DATABASE some-db;
  ```

2. Connecting to the `MySQL v8` Database with [`SQLTools` extension](https://marketplace.visualstudio.com/items?itemName=mtxr.sqltools). You will also have to download the Extensions drivers: MySQL
  - *NOTE* we had to make a database `some-db` manually above
    ```json
    {
      "mysqlOptions": {
        "authProtocol": "xprotocol"
      },
      "previewLimit": 50,
      "server": "localhost",
      "port": 33060,
      "driver": "MySQL",
      "name": "MySQL_v8",
      "database": "some-db",
      "username": "root",
      "password": "123456789",
      "connectionTimeout": 15
    }
    ```

**Comment by TravisC671** [comment]
hey, for anyone still on this who has inserted a connection timeout and still getting this  
`Error opening connection Client option 'pooling.maxIdleTime' does not support value 'NaN'`
just close VisualStudio and re-open it. I hope this saves a few people from making my mistake!

**Comment by Sherpard** [comment]
> hey, for anyone still on this who has inserted a connection timeout and still getting this
> `Error opening connection Client option 'pooling.maxIdleTime' does not support value 'NaN'`
> just close VisualStudio and re-open it. I hope this saves a few people from making my mistake!

this shold receive way more thumb ups! it fixed my issue. thanks!

**Comment by spking11** [comment]
> > Followed all instructions above: used xprotocol, defined connection timeout, set up user to connect on localhost with password and all I get at the end is `server has gone away`. Using MySQL 8
> 
> Me too ...
> How to solve it ??

Me too...

> hey, for anyone still on this who has inserted a connection timeout and still getting this
> `Error opening connection Client option 'pooling.maxIdleTime' does not support value 'NaN'`
> just close VisualStudio and re-open it. I hope this saves a few people from making my mistake!

And this method doesn't work.

**Comment by eahanson** [comment]
> Followed all instructions above: used xprotocol, defined connection timeout, set up user to connect on localhost with password and all I get at the end is `server has gone away`. Using MySQL 8

I had this problem and was able to fix it by setting the port to `33060` instead of `3306` as described in the [docs here](https://vscode-sqltools.mteixeira.dev/driver/mysql#know-errors-and-how-to-fix), and then disconnecting and reconnecting. (I might have restarted VSCode too.)

**Comment by Faiamfine** [comment]
I got connect ECONNREFUSED 127.0.0.1:33060

**Comment by gjsjohnmurray** [comment]
> I got connect ECONNREFUSED 127.0.0.1:33060

@Faiamfine are you certain that the config which creates your Docker container connects your host workstation's port 33060 to the same port inside the container? And that MySQL in the container is listening on that port? If you are, please open a fresh issue on GitHub with details of your setup.

**Comment by magician20** [comment]
> > Followed all instructions above: used xprotocol, defined connection timeout, set up user to connect on localhost with password and all I get at the end is `server has gone away`. Using MySQL 8
> 
> I had this problem and was able to fix it by setting the port to `33060` instead of `3306` as described in the [docs here](https://vscode-sqltools.mteixeira.dev/driver/mysql#know-errors-and-how-to-fix), and then disconnecting and reconnecting. (I might have restarted VSCode too.)

Worked for me and I add time connection also. Before worked with 3306  :)

**Comment by jgarciasol** [comment]
> > Followed all instructions above: used xprotocol, defined connection timeout, set up user to connect on localhost with password and all I get at the end is `server has gone away`. Using MySQL 8
> 
> I had this problem and was able to fix it by setting the port to `33060` instead of `3306` as described in the [docs here](https://vscode-sqltools.mteixeira.dev/driver/mysql#know-errors-and-how-to-fix), and then disconnecting and reconnecting. (I might have restarted VSCode too.)

THIS HELPED!!!! I didn't want to create a new user, since it seemed like it was a security vulnerability.

**Comment by r-martins** [comment]
Didn't work for me.. using 3310 or 3306 with or without trailling 0.
```json
{
  "mysqlOptions": {
    "authProtocol": "xprotocol"
  },
  "previewLimit": 50,
  "server": "localhost",
  "port": 33100,
  "driver": "MySQL",
  "name": "woocommerce",
  "group": "docker",
  "database": "woocommerce",
  "username": "woocommerce",
  "password": "woocommerce_pass",
  "connectionTimeout": 15
}

```
> [1687397353895] ERROR (ext): ERROR: Error opening connection connect ECONNREFUSED 127.0.0.1:33100, {"code":-1,"data":{"driver":"MySQL","driverOptions":{"mysqlOptions":{"authProtocol":"xprotocol"}}}}
    ns: "error-handler"


No issues on PhpStorm.
<img width="958" alt="image" src="https://github.com/mtxr/vscode-sqltools/assets/191149/914e8f41-d503-4e2c-a4fd-3b4665771bce">

**Comment by krzysztoffila** [comment]
> This is already described here: https://vscode-sqltools.mteixeira.dev/driver/mysql#mysql-8-and-er_not_supported_auth_mode

Link doesn`t work

**Comment by gjsjohnmurray** [comment]
> Link doesn`t work

Try https://vscode-sqltools.mteixeira.dev/en/drivers/my-sql#mysql-8-and-er_not_supported_auth_mode

**Comment by CrlClgrs** [comment]
OS Linux (host and guest)
MySql v8+ installed on Docker

trying to access from sqltools inside vscode

```
"mysqlOptions": {
					"authProtocol": "xprotocol"
				},
"previewLimit": 50,
"server": "127.0.0.1",
"port": 33060,
```
note the authProtocol and the port (trailing 0)

AND

you need to expose the port from the container, so (I am using docker-compose):
```    
ports:
      - '3306:3306'
      - '33060:33060'
```
