### ISSUE TITLE
New driver please! :)

### ISSUE THREAD

**Issue by NEgorE** [mtxr/vscode-sqltools#403]
Hey, dear developers of this tool.

Thanks a lot for this tool. It's nice for all db-developers.

1 question: can u add driver for connect to TERADATA DB? and how mach of time need for to do  this?

Neliubin Egor
Teradata developer
A1 Belarus
neo.8318731@gmail.com

**Comment by benyaminl** [comment]
> Hey, dear developers of this tool.
> 
> Thanks a lot for this tool. It's nice for all db-developers.
> 
> 1 question: can u add driver for connect to TERADATA DB? and how mach of time need for to do this?
> 
> Neliubin Egor
> Teradata developer
> A1 Belarus
> [neo.8318731@gmail.com](mailto:neo.8318731@gmail.com)

Hello, @mtxr hand is full now, maybe if you can create a connector for this plug in then it will be a great help for SQLTools and Teradata itself. Cheers!

**Comment by mtxr** [comment]
@NEgorE so far I've been trying not to add new drivers to enhance the currently existing ones. The project is growing a lot, and that's awesome, but the worklaod has increased a lot for me to take over all issues.

But I've developed a tool to help developers to quick start in a new drivers. This tool generates some boiler plates stuff where you can start on.

I'll close this issue for to to keep track for the enhancements and bugs.

I'll be glad to merge a PR with this new driver if you are able to work on it. Reach me out if you need any help, I'll be happy to assist.
