### ISSUE TITLE
If executing command than DQL, return result instead of no data prompt

### ISSUE THREAD

**Issue by dnlw07** [mtxr/vscode-sqltools#404]
**Is your feature request related to a problem? Please describe.**
While executing command other than **DQL**, **no data** prompt is shown. As instead **success** or **failure** result should be shown.

For example:
`GRANT SELECT ON OWNER.TABLE TO ANOTHER_OWNER;`

DML script returns **query** output:
![screenshot 26](https://user-images.githubusercontent.com/23562689/68085182-7f60f980-fe3e-11e9-960d-99700c52f128.jpg)

As instead DML script should return output like: `Script executed successfully`

**Comment by mtxr** [comment]
@dnlw07  Can you provide more details about this?

Examples, screenshots and an expected behavior?

Which driver are you using?

**Comment by dnlw07** [comment]
comment updated

**Comment by mtxr** [comment]
Hmm, I see. That's something very annoying. The message is there, but hidden in the message panel ;p

**Comment by dnlw07** [comment]
Oh good to know! ;)

It's not that much annoying, but in the beginning when I started working with the extension, I got an impression that scripts other than DQL are not executing properly.
