### ISSUE TITLE
Connection tree at table level expands also table columns

### ISSUE THREAD

**Issue by dnlw07** [mtxr/vscode-sqltools#407]
**Is your feature request related to a problem? Please describe.**
Connection tree at table level expands also table columns. 

**Describe the solution you'd like**
As instead it would be more convenient to list only tables and expand particular table to see its columns.

**Comment by mtxr** [comment]
@dnlw07 I don't think I completely understand your issue. Could you elaborate a bit more?

I thought you said when connecting we were expanding all the tree, that includes columns, but I've just tested here and we expand just the connection.

![image](https://user-images.githubusercontent.com/707561/68084952-5dee1680-fe1a-11e9-97ff-75fd28415bac.png)

**Comment by dnlw07** [comment]
I just have checked and the issue seems to be already solved with 0.21 release.

**Comment by mtxr** [comment]
Thanks @dnlw07 <dnlw07@gmail.com>
