### ISSUE TITLE
Show database driver in CONNECTIONS panel

### ISSUE THREAD

**Issue by psychelzh** [mtxr/vscode-sqltools#410]
**Is your feature request related to a problem? Please describe.**
The connections on the CONNECTIONS panel are only listed with name and server, but it is very inconvenient to see the driver behind each connection.

**Describe the solution you'd like**
E.g., use the database driver logo as the icon of each connection.

**Comment by mtxr** [comment]
I like your Idea. But How would I show which database is connected and which one is active?

**Comment by mtxr** [comment]
Hey, got and idea.

![image](https://user-images.githubusercontent.com/707561/67614901-21c41180-f79b-11e9-935c-22bb7e185c45.png)


This is done in `vnext` branch. Will be release with v0.22 but I still don't have a date for it yet
