### ISSUE TITLE
Connecting to MySQL Database is incredibly slow

### ISSUE THREAD

**Issue by miversen33** [mtxr/vscode-sqltools#411]
**Describe the bug**
When I try to connect to a MySQL database, it takes upwards of 5 minutes to actually open the connection. It takes less than a second to confirm my credentials and test the connection, however opening the database so I can execute SQL commands and view the database tables takes far too long. I can open my databases with other VS code extensions [Such As MySQL](https://github.com/formulahendry/vscode-mysql) and it takes less than a few seconds to connect. Connecting via external tools (Such As [DB Vis](https://dbvis.com/)) work fine as well.

**To Reproduce**
1. Create Connection Setting
2. Test Connection Setting
3. Save Connection Setting
4. Attempt to open new connection

**Expected behavior**
It is not fair to set a time expectation on how long a connection should take, as there are numerous things that could affect it. However, it should respond in about the same time as any other connection method used.

**Screenshots**

**Desktop (please complete the following information):**
 - SQLTools Version 0.21.0
 - VSCode Version: 1.39.2
 - Dialect Used/Version: MySQL 5.5.5 v15.1
 - OS: Windows 10

**Comment by miversen33** [comment]
This will be edited after my connection is finished. I will replace this with the current log from SQLTools

**Comment by miversen33** [comment]
Is there anything else I can provide for this? SQLTools was just updated and this issue is not any better.

**Comment by mtxr** [comment]
There is some on going effort on that. But it's not about mysql only, we need to keep standards against all drivers.

I'll merge this issue into #322 since that's the root cause of slowness when connecting.

**Comment by mtxr** [comment]
This will be released on v0.22

**Comment by josecanciani** [comment]
Can't wait for v0.22 to be available!
Does this fix avoids/limits the information_schema traversing in any way? Or is it just loading it in a separate connection or something like that?

**Comment by repellentrian7** [comment]
@josecanciani https://sublimetext3ever-present.github.io/catechism/
