### ISSUE TITLE
how to edit connection json manually?

### ISSUE THREAD

**Issue by sstirlin** [mtxr/vscode-sqltools#412]
The docs suggest that to add any extra pgOptions (e.g. setting ssl to true) we should manually edit the connection json

https://vscode-sqltools.mteixeira.dev/connections/aws-redshift

How do we do this?  There doesn't appear to be any way to modify the json from the Connection Assistant.

Thanks!

**Comment by Jakob-Winkler** [comment]
C:\Users\<name>\AppData\Roaming\Code\User\settings.json
Took me a while hope it helps

**Comment by sstirlin** [comment]
Thanks!  I ended up doing the same thing you probably did (putting a file change monitor on my laptop, saving the file, and locating it that way).

@maintainers it would be super helpful to show the location of settings.json in the Connection Assistant.

Also recommend explicitly showing ssl example in the docs, e.g.

"pgOptions": {
    "ssl": true
}

Since that's a VERY common option (probably needed for the majority of connections, especially to things like Redshift).  Great work on this extension BTW.

**Comment by mtxr** [comment]
Thanks @sstirlin .

I've s tarted working on this, see: https://github.com/mtxr/vscode-sqltools/compare/open-settings

About ssl options, it already existis in the docs.

This open settings will be release in a few days after testing, ok?

**Comment by sstirlin** [comment]
Sounds great!  I'll let you close the issue.  Thanks

**Comment by mtxr** [comment]
Useful info: https://code.visualstudio.com/docs/getstarted/settings#_settings-file-locations

**Comment by mtxr** [comment]
Found a temporary solution. We still can't got directly to the file, but we take user to vscode settings screen, from there we can go to the correct file..
