### ISSUE TITLE
Result limiter

### ISSUE THREAD

**Issue by CharlesSQL** [mtxr/vscode-sqltools#413]
Really love your extension! But I might have found a feature to make it into THE Extension of the decade!

It seems that out of the box a "SELECT * FROM TABLE" query retrieves all rows. And I find no easy way to limit the result-set without going to write the limit statement in the SQL query itself.

It would be super good to ju being able to browse a limited set of rows for a query. Maybe from a drop down menue with standard limiting numbers.  

Pagination is good, but when your query retrieves hundred thousand or millions of rows it is not very practical. And if one always need to write LIMIT in code it increases risk of limit command being left by mistake when creating tables with "create table as select ..." command.

Hopefully I just missed this already existing feature, otherwise I hope it gets added soon.

**Comment by mtxr** [comment]
This is a tricky question. I don't really want to change user's query, but I do see some benefits on having that.

I would say that's I'ld approach it with an alert like `This query doesn't have limit clause, would you like to add it?` before changing the query.

**Comment by mtxr** [comment]
Closing this issue in favor of #365.
