### ISSUE TITLE
sqlite  always fails to install

### ISSUE THREAD

**Issue by etimes2008** [mtxr/vscode-sqltools#414]
**Describe the bug**
can you https://github.com/kripken/sql.js/ replace  https://github.com/mapbox/node-sqlite3

**Comment by Dragon1573** [comment]
# Environments

- Microsoft Visual Studio Code: v1.39.2 (system setup)
- Node.js: v12.11.1
- SQLToos Extensions: v0.21.0
- Operating System: Windows 10 x64 Home China
- Location: Guangdong, People's Republic of China

# What had happened?

For several reasons, I can't access to the original `npm` mirror. So I used `cnpm` from <https://npm.taobao.org> instead and installed `sqlite3@4.0.8` by using command:
```text
cnpm install -g sqlite3@4.0.8
```

![image](https://user-images.githubusercontent.com/49941141/67142720-814f8800-f296-11e9-962a-411f9383f9e3.png)

Accroding to the screenshot, the package was successfully installed.

But it seems that SQLTools in VSCode can't detect this package and remind me that I haven't installed `sqlite3@4.0.8`. If I click `Install Now` button in VSCode, it will try to download all required packages through `npm`, which has been blocked. And of course, unable to install. 

![image](https://user-images.githubusercontent.com/49941141/67142762-0470de00-f297-11e9-823f-0ae9de5d57e7.png)

![image](https://user-images.githubusercontent.com/49941141/67142811-5fa2d080-f297-11e9-8e0c-20670125810b.png)

The progress bar at the right bottom keep rolling from left to right, but have to chance to finish the task. 

****

Is there any other method to solve this question? Could you do me a favour? Thank you! @mtxr

**Comment by Dragon1573** [comment]
@mtxr 

I have no idea how to alias `npm` to `cnpm`, and [Taobao NPM Mirror](https://npm.taobao.org/) told me that `cnpm` is an alias of

```bash
npm --registry=https://registry.npm.taobao.org --cache=$HOME/.npm/.cache/cnpm --disturl=https://npm.taobao.org/dist --userconfig=$HOME/.cnpmrc
```

If I alias `npm` to `cnpm`, this operation may create an **Alias Loop** and cause unexpected problems.

There's my suggestions:
1. Move all equirements of *SQLTools* from `%USER_HOME%/.vscode/extensions/mtxr.sqltools-<version>/node_modules` to the global environment `%NODE_HOME%/node_modules`, so we can install those requirements through another package manager if packages are unavailable.
2. Apply choices to us so we can use our preferred package manager to install requirements.
3. Change a method of requirements installation, from binary installation (install requirements binary files through package manager) to source code installation (download souce codes from their repository and install locally).

**Comment by MBetters** [comment]
I'm getting a similar error on Windows 10:

```
DEBUG: Settings updated!
INFO: Telemetry enabled!
DEBUG: Event: sessionStarted:extension 
DEBUG: Activation time: 364.5388ms
INFO: Executing SQLTools.getConnectionStatus
INFO: Executing SQLTools.getConnectionStatus
INFO: Executing SQLTools.getConnectionStatus
INFO: Executing SQLTools.getConnectionStatus
INFO: Executing SQLTools.getConnectionStatus
INFO: Executing SQLTools.getConnectionStatus
INFO: Executing SQLTools.openAddConnectionScreen
INFO: Executing SQLTools.testConnection
ERROR: Error:  [ResponseError: Request DependencyInstaller/install failed with message: Nothing to install. Request is invalid.
	at c:\Users\mark.betters\.vscode-insiders\extensions\mtxr.sqltools-0.21.1\extension.js:1:22892
	at c:\Users\mark.betters\.vscode-insiders\extensions\mtxr.sqltools-0.21.1\extension.js:1:23299
	at Immediate.<anonymous> (c:\Users\mark.betters\.vscode-insiders\extensions\mtxr.sqltools-0.21.1\extension.js:1:23843)
	at processImmediate (internal/timers.js:439:21)] {
  code: -32603,
  data: undefined
}
INFO: Executing SQLTools.showOutputChannel
```

**Comment by mtxr** [comment]
I'm adding options to select which package manager user wants to use.

Having the requirements in a global folder is something I've tried, but that can lead us to a variety of bug because of wrong package versions. So I'll keep it the `node way`, managing all deps in the app folder.

About 3, we can certainly improve the dependency installer to add this feature. It shouldn't be difficult, but so far I think 2 is faster and covers most of situations we have.

Thanks @etimes2008
