### ISSUE TITLE
yarn run add-driver fails to run

### ISSUE THREAD

**Issue by dev-moonduck** [mtxr/vscode-sqltools#416]
**Describe the bug**
I try to start to develop new driver, but the command(yarn run add-driver) shows me error. Not sure this is bug or just my mistake.
The full log is like this
```
yarn run v1.16.0
warning sqltools@0.21.0: The engine "vscode" appears to be invalid.
$ node ./tools/add-driver.js --name impala
error: docs/Connections.md: No such file or directory
error: docs/SUMMARY.md: No such file or directory
error: patch failed: packages/core/dialect/index.ts:5
error: packages/core/dialect/index.ts: patch does not apply
error: patch failed: packages/ui/screens/Settings/Drivers/index.tsx:5
error: packages/ui/screens/Settings/Drivers/index.tsx: patch does not apply
error: patch failed: packages/ui/screens/Settings/lib/availableDialects.ts:7
error: packages/ui/screens/Settings/lib/availableDialects.ts: patch does not apply

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Any idea?

**To Reproduce**
1. Git clone 'vscode-sqltools' repo
2. cd vscode-sqltools
3. yarn 
4. yarn run add-driver

**Expected behavior**
Initial files are created

**Screenshots**

**Desktop (please complete the following information):**
 - SQLTools Version 0.21.0
 - VSCode Version: 1.38.1
 - Dialect Used/Version: -
 - OS: Mac

**Additional context**

**Comment by dev-moonduck** [comment]
It is because merge conflict.
docs/Connections.md, docs/SUMMARY.md is not in there in master branch
and there is conflict between master and add-driver-example with availableDialects.ts

**Comment by C1ARKGABLE** [comment]
Bumping for visibility. I’ve had the same issue on Ubuntu 19.04.

**Comment by mtxr** [comment]
@C1ARKGABLE @dev-moonduck I'm sorry, I'm still writing the docs for that.

But you can quickly fix this by running `yarn run add-driver:refresh && yarn run add-driver`

**Comment by mtxr** [comment]
just updated the branch. should be working now. thanks

**Comment by C1ARKGABLE** [comment]
Thanks! @mtxr

**Comment by mtxr** [comment]
I've added a Github Action to auto update that branch.
Also update the script to generate the patch in run time to avoid conflicts
