### ISSUE TITLE
No way to see RAISE notices in Postgres

### ISSUE THREAD

**Issue by Fmstrat** [mtxr/vscode-sqltools#417]
**Is your feature request related to a problem? Please describe.**
In Postgres, you can raise notices, such as:
```
raise notice '%',now();
```
Currently there is no way to view this output like there is using the Microsoft Postgres plugin.

**Describe the solution you'd like**
A way to view notices.

**Comment by mtxr** [comment]
You wanted to see it like this?

![image](https://user-images.githubusercontent.com/707561/68085201-2e8cd900-fe1d-11e9-9959-04c633cc4562.png)


We also show the message...

![image](https://user-images.githubusercontent.com/707561/68085211-44020300-fe1d-11e9-8e1e-21c88f16af4f.png)

**Comment by mtxr** [comment]
Nvm, I see what you are looking for.

Feature Requirements:
1. list all notices and raises when running queries.

More info: https://node-postgres.com/api/client
