### ISSUE TITLE
Is there a proper installation guide available? I'm not able to get it working in VS Code

### ISSUE THREAD

**Issue by aditya43** [mtxr/vscode-sqltools#42]
### Issue Type
* [ ] Questions
* [ ] Other

### Description

I'm not able to get SQL tools working in VS Code. Following is the output I'm seeing when I execute a query.

![2017-12-06_211031](https://user-images.githubusercontent.com/25119995/33670078-2620cc9a-daca-11e7-8b29-d844111f2786.png)

SQLTools  works fine on Sublime Text-3. Is there a setting where I need to specify path to mysql executable?

Is there a proper installation guide for VS Code?

Thank You

**Comment by mtxr** [comment]
Well, no. Not yet at least.

Usually people update their settings reading the "settings" through VSCode Settings tool.

But you are completely right. We should write our own doc.

It will be done in a few days ok?

**Comment by mtxr** [comment]
/remind me to create the docs in 5 days

**Comment by aditya43** [comment]
@mtxr Thank you
