### ISSUE TITLE
Can't create a SQLite connection using the connection assistant in remote development  

### ISSUE THREAD

**Issue by liatbor** [mtxr/vscode-sqltools#421]
When creating a new SQLite connection using the connection assistant I need to provide a database file. Currently the way to choose the file is to click on the "Database file" field which opens a browse window to select the file from my local machine. However in a remote development scenario the file is not located on my local machine but reside in remote workspace

It should be allowed to provide the path to the file as text or to browse the remote workspace.

![Sqltools](https://user-images.githubusercontent.com/1785337/67479821-90a04e00-f667-11e9-8651-f481cdf36cf3.png)

 - SQLTools Version  v0.21
 - VSCode Version: 1.37.1
 - Dialect Used/Version:  SQLite
 - OS:  Mac

Thanks!

**Comment by liatbor** [comment]
@mtxr you're too quick for me :)

**Comment by majordoobie** [comment]
I see the commit was made - but how do I specify a remote path? =o

**Comment by GeorgFoc** [comment]
Just in case anyone winds up here, here's the solution:

You have to wright the path in relative form from your workspace. So something like:
`./instance/db.sqlite`
