### ISSUE TITLE
Add new MSSQL driver to support Windows Integrated Security

### ISSUE THREAD

**Issue by tmknight** [mtxr/vscode-sqltools#424]
**Describe the bug**
Trying to leverage integrated domain security to avoid hard-coded passwords.  The following connection has been created though results in untrusted domain with integrated security" error.
Similar, though different, to: #70

```
"name": "the-name",
"server": "the-server",
"dialect": "MSSQL",
"port": 1433,
"database": "the-db",
"username": "the-user",
"askForPassword": false,
"password": "",
"domain": "the-domain",
"connectionTimeout": 15
```

`Error opening connection Login failed. The login is from an untrusted domain and cannot be used with Integrated authentication.`

`INFO: Executing SQLTools.selectConnection
ERROR: Error:  { [Error: Login failed. The login is from an untrusted domain and cannot be used with Integrated authentication.
	at c:\Users\user\.vscode\extensions\mtxr.sqltools-0.21.0\extension.js:1:22985
	at c:\Users\user\.vscode\extensions\mtxr.sqltools-0.21.0\extension.js:1:23392
	at Immediate.messageQueue.size.setImmediate (c:\Users\user\.vscode\extensions\mtxr.sqltools-0.21.0\extension.js:1:23936)
	at runCallback (timers.js:694:18)
	at tryOnImmediate (timers.js:665:5)
	at processImmediate (timers.js:647:5)] code: -32001, data: { dialect: 'MSSQL', dialectOptions: {} } }`

Tried adding the domain to trusted domains JSON, to no avail.

**Expected behavior**
Connect to DB without hard-coded credentials

**Desktop (please complete the following information):**
- SQLTools: 0.21
- VSCode: 1.39.2
- Dialect: MSSQL
- OS: Windows 10 x64 1903

**Comment by mtxr** [comment]
@tmknight  I'll release a new version with some MSSQL updates tonight.

Try to take a look at http://tediousjs.github.io/tedious/api-connection.html and also https://github.com/mtxr/vscode-sqltools/issues/375

I believe you can achieve this with similar settings.

Problem is I can't test this scenario right now, but I'll try to find a way to reproduce it, ok?

**Comment by tmknight** [comment]
Thanks for digging into the problem.  
Tried adding "type": "ntlm", though still no joy unless I populate a username and password.
FWIW, Microsoft's SQL extension is handling integrated auth without issue.

**Comment by jbunselmeyer** [comment]
@tmknight You mention the Microsoft SQL extension is handling integrated auth without issue. I'm needing to try to utilize it to use my domain account for some of my server connections for audit reasons. 

Is there a specific section you add in the config to make it work or is it a specific syntax in the mssql.connections section of the config that that specifies additional values?

Thanks!

**Comment by tmknight** [comment]
The selection is simply "integrated" as you step through establishing a new connection.  This is what the end result looks like in the JSON:
`    "mssql.connections": [
        {
            "server": "the_server",
            "database": "the_db",
            "authenticationType": "Integrated",
            "password": ""
        }
    ]
`
Thanks for continuing to look into this...

**Comment by jbunselmeyer** [comment]
@tmknight Does it then prompt you for the domain at some point when you connect?

**Comment by tmknight** [comment]
It does not.  These are the server specific prompts:
![image](https://user-images.githubusercontent.com/548588/68026920-695d0880-fc87-11e9-923f-c6fa550b9497.png)
![image](https://user-images.githubusercontent.com/548588/68026933-711cad00-fc87-11e9-9a7c-1a00356b1347.png)
![image](https://user-images.githubusercontent.com/548588/68026937-74b03400-fc87-11e9-8d83-999c9662ca91.png)

**Comment by jbunselmeyer** [comment]
How are you logging in with a domain account then? That's where I'm confused. I want to connect via a domain account. When I use SSMS I have a RunAs shortcut that specifies the domain credentials to use. I'm trying to figure out how accomplish the same thing using these SQL Server extensions.

**Comment by tmknight** [comment]
Integrated authentication is predicated on the user being logged onto a domain joined device with a domain account.  Also the SQL server is domain joined and permissions are set leveraging Active Directory Users/Groups.

Thus no user information is required when setting up a connection with integrated authentication.

Hope that makes sense.

**Comment by tmknight** [comment]
I'm joined to a Windows Active Directory domain.  To logon to my Windows PC, I authenticate with my domain user account.  From there kerberos tokens and ntlm take care of any other authentications on other domain joined resources.  Not sure how else to describe it.

**Comment by jbunselmeyer** [comment]
Yeah, I follow what you are saying, I'm thinking for my situation I just may not be able to do it. 
I log in to my Windows PC with an AD account as well, but the databases I'm connecting to are in two other domains and there is no domain trust between the domains. 

Even to use SQL Server Management Studio to access those databases I have to have shortcuts that basically do this...

%windir%\system32\runas.exe /user:<domain>\<account> /netonly ssms.exe

And then I get prompted for the password each time and have to enter in the appropriate domain password based on which database to which I need to connect. It's a real pain.

**Comment by tmknight** [comment]
Are you able to RDP to a machine on one of the other domains then connect
to SQL?

**Comment by mtxr** [comment]
> Thanks for digging into the problem.
> Tried adding "type": "ntlm", though still no joy unless I populate a username and password.
> FWIW, Microsoft's SQL extension is handling integrated auth without issue.
> 
> To add, I also had earlier tried a connection string and that too resulted in error.
> 
> Thanks, again for delving into a solution.

So if you fill username and password it does work? It does look with a similar issue we've got before. Let me see if I can find it.

Also, @ransagy do you think this is somehow similar to what you've got in your setup?

**Comment by mtxr** [comment]
Actually the driver we are using (`tedious`) doesnt support integrated security as we have seem in other tools. See https://github.com/tediousjs/tedious/issues/836
I've found another driver that supports, it's https://www.npmjs.com/package/msnodesqlv8, but we would need to add that new driver to SQLTools.

We have a tool to add new drivers, also the docs, would you like to add it? would require you to work in the queries to fetch databases and columns, but I'm pretty sure we could use the same queries from the other driver.

**Comment by jbunselmeyer** [comment]
> Are you able to RDP to a machine on one of the other domains then connect to SQL?
> […](#)

That doesn't seem to make any difference. I RDP into one of the actual database servers I'm trying to connect to with the appropriate domain account and then try to add the connection in Visual Studio Code, selecting integrated, and it returns...

mssql: Failed to connect: Microsoft.Data.SqlClient.SqlException (0x80131904): Failed to generate SSPI context.

**Comment by jbunselmeyer** [comment]
@tmknight Totally off-topic to this thread but didn't know how else to contact you to ask...

Does the mssql extension just not show record counts in it's message or results pane or am I missing/mis-configuring something?

**Comment by tmknight** [comment]
It does not show results count.  An oversight, IMO.  Hoping they add it
soon.

**Comment by jbunselmeyer** [comment]
Thanks for the quick reply. It's the one thing I'm really missing from SSMS based on some tasks I have to do daily. Easy enough to scroll to the bottom of the results or do a quick count query but so weird it isn't there.

**Comment by tmknight** [comment]
https://github.com/microsoft/vscode-mssql/issues/1462

**Comment by mtxr** [comment]
@tmknight @jbunselmeyer could you please move this to a different thread inside of the correct repository? With the exception of the first comments, everything else is all about vscode-mssql. They use proprietary driver/tools to achieve what you are looking for, something we currently not support. Let's try to keep this thread useful for adding this feature to SQLTools.

Don't get me wrong, it's just hard to keep track of everything and having to filter unrelated comments when working on feature requests

**Comment by jbunselmeyer** [comment]
Absolutely @mxtr, totally understand. I take responsibility for taking it off-topic, sorry about that.

**Comment by mtxr** [comment]
If anyone else want to try to integrate this with the extension, here is the guide to achieve that: https://vscode-sqltools.mteixeira.dev/contributing/support-new-drivers

I'll close this issue for now
