### ISSUE TITLE
SQLite Driver Fails to Install for "VS Code - Insiders" with "data: undefined"

### ISSUE THREAD

**Issue by MBetters** [mtxr/vscode-sqltools#428]
**Describe the bug**

In "VS Code - Insiders", SQLite driver fails to install for "VS Code - Insiders" with "data: undefined"

**To Reproduce**

In "VS Code - Insiders" I try to add a new SQLite connection. I select the file then click Test Connection. It prompts me to install the SQLite driver. The install fails with this:

```
DEBUG: Settings updated!
INFO: Telemetry enabled!
DEBUG: Event: sessionStarted:extension 
DEBUG: Activation time: 364.5388ms
INFO: Executing SQLTools.getConnectionStatus
INFO: Executing SQLTools.getConnectionStatus
INFO: Executing SQLTools.getConnectionStatus
INFO: Executing SQLTools.getConnectionStatus
INFO: Executing SQLTools.getConnectionStatus
INFO: Executing SQLTools.getConnectionStatus
INFO: Executing SQLTools.openAddConnectionScreen
INFO: Executing SQLTools.testConnection
ERROR: Error:  [ResponseError: Request DependencyInstaller/install failed with message: Nothing to install. Request is invalid.
	at c:\Users\mark.betters\.vscode-insiders\extensions\mtxr.sqltools-0.21.1\extension.js:1:22892
	at c:\Users\mark.betters\.vscode-insiders\extensions\mtxr.sqltools-0.21.1\extension.js:1:23299
	at Immediate.<anonymous> (c:\Users\mark.betters\.vscode-insiders\extensions\mtxr.sqltools-0.21.1\extension.js:1:23843)
	at processImmediate (internal/timers.js:439:21)] {
  code: -32603,
  data: undefined
}
INFO: Executing SQLTools.showOutputChannel
```

**Expected behavior**

For the SQLite driver to install successfully on "VS Code - Insiders"

**Screenshots**

N/A

**Desktop (please complete the following information):**

- SQLTools Version: 0.21.1
- VSCode Version: 1.40.0-insider
- Dialect Used/Version: SQLite
- OS: Windows 10

**Additional context**

N/A

**Comment by mtxr** [comment]
Can you send `SQLTools Language Server` output logs as well?

This message by itself suggests the drier is installed, so do problem would be somewhere else.

![image](https://user-images.githubusercontent.com/707561/67634850-8799c180-f89f-11e9-80ba-243ce8e697bd.png)

**Comment by drk-mtr** [comment]
I have the same issue in vscode 1.39.2. SQLTools Language Server output is:

```
===============================
SQLTools Server started!
Using node runtime?: true
ExecPath: C:\Program Files\nodejs\node.exe
===============================

Telemetry enabled!
Event: sessionStarted:language-server 
Message: Initialized with node version:v10.16.0
Request connection/GetConnectionsRequest received
Request connection/GetConnectionsRequest received
Request connection/GetConnectionsRequest received
Request connection/TestConnectionRequest received
Request DependencyInstaller/install received
Request connection/TestConnectionRequest received
Request DependencyInstaller/install received
Request connection/TestConnectionRequest received
Request DependencyInstaller/install received
Request connection/TestConnectionRequest received
Request connection/TestConnectionRequest received
Request DependencyInstaller/install received
Request connection/TestConnectionRequest received
```

**Comment by sapiens-sapide** [comment]
Same error with vscode 1.39.2. SQLTools Language Server output is :  
```

===============================
SQLTools Server started!
Using node runtime?: true
ExecPath: /home/stan/.nvm/versions/node/v10.15.3/bin/node
===============================

Telemetry enabled!
Event: sessionStarted:language-server 
Message: Initialized with node version:v10.15.3
Request connection/GetConnectionsRequest received
Request connection/ConnectRequest received
Request connection/GetConnectionsRequest received
Request connection/TestConnectionRequest received
Request DependencyInstaller/install received
Request connection/GetConnectionsRequest received
```

**Comment by mtxr** [comment]
Hey Guys, I've added more logs and I'm releasing a new version.

But can you guys test something? Try to:
1. uninstall the extension
2. delete extension directory.
> You can find it using this guide from MS: https://code.visualstudio.com/docs/editor/extension-gallery#_where-are-extensions-installed	
3. Reinstall the new version

**Comment by sapiens-sapide** [comment]
didn't work for me, after uninstalling the extension, deleting extension directory and reinstalling.  
Same error.

**Comment by mtxr** [comment]
@MBetters @sapiens-sapide @drk-mtr please, let me now if the issue persists on v0.21.2

We've introduced new settings that can tweak dependency installing.

Keep me posted

**Comment by sapiens-sapide** [comment]
It fixed the issue for me. Thanks @mtxr for your job !

**Comment by ZakariyeAden** [comment]
Hello jt doesnt work.

**Comment by gjsjohnmurray** [comment]
@ZakariyeAden if you still have this issue after updating with today's releases please open a new GH issue with plenty of information.
