### ISSUE TITLE
How to turn off plugin notifications?

### ISSUE THREAD

**Issue by rvong** [mtxr/vscode-sqltools#43]
Hello,

How do I turn off Donation request notification?

I found the issue in this file: https://github.com/mtxr/vscode-sqltools/blob/673ad277937cd592801c7cb56bb1c9ebc66e98d9/src/sqltools.ts

It shows:

      if (last.getTime() >= new Date().setHours(0, 0, 0, 0)) {
        return;
      }

Instead, the condition should be removed and it should always return so the code should not execute the Popup notification.

Thanks!

**Comment by rvong** [comment]
For those that do not plan to donate and have not used the tool extensively, they should have the option to not be bombarded with requests.  Otherwise, I'll uninstall/install when needed.

**Comment by mtxr** [comment]
This "feature" is being developed.

The idea is to show message just to the ones that use it extensively. Can you please wait 1~2 days?

Anyway, the message is show once per day.

Hope you understand.

Thanks!
