### ISSUE TITLE
SQLite Selected DB Path includes current folder

### ISSUE THREAD

**Issue by bricakeld** [mtxr/vscode-sqltools#430]
**Describe the bug**
When I select an sqlite file, the current folder is included in the path, resulting in an error that says the database file cannot be opened. It can be fixed manually by changing the file path in the connections json setting, but by default, I'm guessing the file selector should result in a correct path added to the json.

**To Reproduce**
Example project dir:
```
|--Project
  |--src
  |--db
    |--test.sqlite
```
1. Open SQLTools extension
2. Click on 'Add New Connection'
3. Select SQLite (Node Native) in the Connection Assistant
4. Enter connection name and select file
5. Save connection
6. Error can be seen here where the file to the database file is saved in the resulting json as `.\\<current_folder>/path/to/db.sqlite` or as in example, `.\\Project/db/test.sqlite`
7. When testing or opening the connection, an error is thrown saying the file cannot be found

**Expected behavior**
The correct file path should exclude the current folder, and be saved directly as `./path/to/db.sqlite` or as in example, `./db/test.sqlite` 
Using the full file path of the sqlite file works too.

**Desktop (please complete the following information):**
 - SQLTools Version v0.21.1
 - VSCode Version: v1.39.2
 - Dialect Used/Version: SQLite
 - OS: Windows 10

**Comment by mtxr** [comment]
are you using settings.json or vscode workspace files?

**Comment by mtxr** [comment]
I'll make SQLite relative to settings file or workspace file. We've already had a lot of similar issues, that's very opinionated because which user has an understanding about this path. I'll use vscode standard, relative to current setting file dir.

**Comment by gogobook** [comment]
The same issue in ubuntu, can fix `.vscode\settings.json` directly.

**Comment by bricakeld** [comment]
> 
> 
> are you using settings.json or vscode workspace files?

I'm using vs code workspace files but regardless, I'm guessing the file path to be inserted should be relative to the current vs code project directory. 

If it's global in settings.json perhaps using the full file path would be better? I've tried pasting the full file path into my workspace json and it is working.

**Comment by mtxr** [comment]
Closed by mistake

**Comment by mtxr** [comment]
I've fixed this using vscode guides for workspaces. See: https://code.visualstudio.com/docs/editor/variables-reference#_variables-scoped-per-workspace-folder

Now files will be saved with `${workspaceFolder:<workspace name>}` if it's an saved workspace or `${workspaceFolder}` if it's just open folder(s).

We can still use dot syntax `.`, but that will make connections to be relative to the first opened folder.

This solution covers all 3 supported kinds of workspaces by vscode.

**Comment by mtxr** [comment]
@bricakeld this will be released tonight, so if will still face problems with paths, just edit you connection, select the file and save it again. It will update to new standard.

**Comment by bricakeld** [comment]
Thanks for the fix! I'll try it out next couple days and update again if needed

**Comment by mtxr** [comment]
:metal:
