### ISSUE TITLE
Request connection/TestConnectionRequest failed with message: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by ManPython** [mtxr/vscode-sqltools#431]
**Describe the bug**
`Request connection/TestConnectionRequest failed with message: Cannot convert undefined or null to object`

**To Reproduce**
1. Trying open any .sqlite3 and test connection
2. After save of connection the `Unable to write into workspace settings. Please open the workspace settings to correct errors/warnings in the file and try again.` - we often need use this tool in django, but file is used...so connections settings should offer save profile in any case of failed test

**Expected behavior**
See some data

 

**Desktop (please complete the following information):**
ext v0.21
Version: 1.39.2
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:35:18.241Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 6.1.7601

**Comment by mtxr** [comment]
What happens if you try to update workspace settings manually?
This is a VSCode error. VScode is unable to save settings in your workspace.

Since we completely rely on VSCode settings API and it looks like a file permissions error, I'll close it for now. But please, keep me updated.

If you have any suggestions on how to do this, let me know.

**Comment by ManPython** [comment]
When trying change in profile then
`You need to fix some issues in your machine first. Check the notifications on bottom-right before moving forward.`
When trying select the profile of connection then I see on notification:
`You need to install sqlite3@4.0.8 to connect test` source: sqltools... 
When trying install by "install now" then:

```
Failed to install dependencies for SQLite: Request DependencyInstaller/install failed with message: 
You need to install node@6 or newer and npm first to install dependencies. Install it and restart to continue.
```

details:
```
DEBUG: Settings updated!
INFO: Telemetry enabled!
DEBUG: Event: sessionStarted:extension 
DEBUG: Activation time: 1092.05243ms
INFO: Executing SQLTools.getConnectionStatus
DEBUG: Connection explorer updated.
INFO: Executing SQLTools.selectConnection
INFO: Executing SQLTools.selectConnection
ERROR: Error:  { Error: Request DependencyInstaller/install failed with message: You need to install node@6 or newer and npm first to install dependencies. Install it and restart to continue.
    at e:\Microsoft\.vscode\extensions\mtxr.sqltools-0.21.1\extension.js:1:22985
    at e:\Microsoft\.vscode\extensions\mtxr.sqltools-0.21.1\extension.js:1:23392
    at Immediate.messageQueue.size.setImmediate (e:\Microsoft\.vscode\extensions\mtxr.sqltools-0.21.1\extension.js:1:23936)
    at runCallback (timers.js:694:18)
    at tryOnImmediate (timers.js:665:5)
    at processImmediate (timers.js:647:5)
    at process.topLevelDomainCallback (domain.js:121:23)
 code: -32603, data: undefined }
INFO: Executing SQLTools.showOutputChannel

```

**Comment by mtxr** [comment]
Just checking, did you enable setting `"sqltools.useNodeRuntime": true,` as in https://vscode-sqltools.mteixeira.dev/driver/sqlite#1-prerequisites?

Check here an working example: https://github.com/mtxr/vscode-sqltools/blob/master/.test-database/project.code-workspace#L31

I see you have `node 10.11.0` installed, so it's probably just a matter of enabling node binary.

**Comment by ManPython** [comment]
`"sqltools.useNodeRuntime": true,` exist.
But I not instaled node manualy or not do anything with this env. I belive that VSC do this or this ext. Should I do here something? There is no instruction or information that is required to do.

**Comment by ManPython** [comment]
Looks that problems exist with sqlite. The test with mysql was ok. HVR I uninstaled this ext due that not speending my needs - I expect some option to write scripts, save these as files in dir and run if required to see data.
