### ISSUE TITLE
SQLite - prevent "install sqlite" notification

### ISSUE THREAD

**Issue by TomHermanSAP** [mtxr/vscode-sqltools#434]
**Describe the bug**
When applying first connection to SQLite DB using sqltools extension, a notification pops-up and the user is requested to install sqlite:
"You need "sqlite3@4.0.6" to connect to sqlite."

**To Reproduce**
Follow the instructions at:
1. https://github.com/SAP-samples/cloud-cap-walkthroughs/tree/master/exercises-java/exercise1
2. https://github.com/SAP-samples/cloud-cap-walkthroughs/tree/master/exercises-java/exercise2
3. https://github.com/SAP-samples/cloud-cap-walkthroughs/tree/master/exercises-java/exercise3:
    Connect to sqlite DB:
    https://github.com/SAP-samples/cloud-cap-walkthroughs/blob/master/exercises-java/exercise3/images/connect_power_icon.png

**Expected behavior**
Having instructions explaining how to install **manually** sqlite package beforehand so the described above notification will **not** pop-up.

**Screenshots**
![image](https://user-images.githubusercontent.com/54273024/68081675-a3aadf00-fe1a-11e9-8482-7f66170adac8.png)

**Desktop (please complete the following information):**
 - SQLTools Version 0.21.0
 - VSCode Version: Theia 0.10.0
 - Dialect Used/Version: SQLite
 - OS: Linux

**Additional context**
Thank you!

**Comment by mtxr** [comment]
@TomHermanSAP  Why would we need to install manually?
If you have node installed, it will just install it for you..

**Comment by TomHermanSAP** [comment]
Hi @mtxr ,
1. We want to provide to the users a "**ready**" environment, and not ask them to install more dependencies by themselves, for more smooth experience.
2. If "SQLite" is one of the dependencies of sqltools, can't it be already packed as part of the extension?

Thank you!

**Comment by mtxr** [comment]
Hi Tom,

Not really, SQLite package includes some binary files platform attached, so
it's better to allow user to install that manually or having the dependency
manager. See https://www.npmjs.com/package/sqlite3#installing

Currently for any development project or some tools like DBeaver, DataGrip
etc, we need to install dependencies. it's hard to ship all drivers in the
code, This requires to create platform specific packages we want to
support, so it's easier adding a dependency manager, so if the user needs
an specify driver, it will be installed on first use. That looks smooth to
me.

I'm open to suggestions, but so far that's what I've could got so far.

**Comment by mtxr** [comment]
I've added an option to bypass that message. But still can't completely remove that popup
