### ISSUE TITLE
Add fuzzy search during connection selection

### ISSUE THREAD

**Issue by dnlw07** [mtxr/vscode-sqltools#435]
**Is your feature request related to a problem? Please describe.**
Fuzzy search during connection selection is not enabled. 
In VSCode, fuzzy search is enabled by default in command palette.

**Describe the solution you'd like**
While typing connection name, fuzzy search should be performed.

**Comment by mtxr** [comment]
Currently not supported on extensions api.

See: https://github.com/microsoft/vscode/issues/34088

Will revisit this `3rd party blocked` stuff monthly. Closing for now
