### ISSUE TITLE
Add option to exectue mutlitple commands

### ISSUE THREAD

**Issue by dnlw07** [mtxr/vscode-sqltools#436]
**Is your feature request related to a problem? Please describe.**
Extension does not allow to execute multiple INSERT scripts at once.

**Describe the solution you'd like**
Please add an option to execute all scripts in file or only selected ones.

**Comment by mtxr** [comment]
this is already supported. 

just tested with this query.

The only problem is the messages not being displayed.

```sql
INSERT INTO "test_db"."public"."department" (id, dept, emp_id) VALUES (1, 'first item', 1);
INSERT INTO "test_db"."public"."department" (id, dept, emp_id) VALUES (2, 'second item', 2);
INSERT INTO "test_db"."public"."department" (id, dept, emp_id) VALUES (3, 'third item', 3), (4, 'fourth item', 4);

SELECT * from department;
```

![Peek 2019-11-04 14-54](https://user-images.githubusercontent.com/707561/68144712-01baed80-ff13-11e9-8156-42cf7ad1a898.gif)

**Comment by dnlw07** [comment]
Hello, 
could you please reopen the issue again?
I have noticed that multiple selection is working fine for SQLite, however **for Oracle** it is still problematic.

The query I am trying to execute:
```sql
select '1' AS COST_CENTER_CODE, 'HCPERM' AS SKF_NAME from dual;
select '2' AS COST_CENTER_CODE, 'EHPERM' AS SKF_NAME from dual;
```

The error I receive:
`ORA-00933: SQL command not properly ended`
