### ISSUE TITLE
BasicClientLite Package .  ORA-01804 errors . vs. BasicClient Package

### ISSUE THREAD

**Issue by bkbonner** [mtxr/vscode-sqltools#438]
This isn't a bug per se, but more of a write-up on the steps I had to take to get sqltools working on catalina (I was installing it on OSX Catalina 10.15.1) with oracle.  

I initially install oracledb@4.0.0 but it required upgrading from v10.15.3 . -> v10.16.1.  I upgraded to v10.17.0 

After this I downloaded: https://download.oracle.com/otn_software/mac/instantclient/193000/instantclient-basiclite-macos.x64-19.3.0.0.0dbru.zip and unzipped it into my tools directory.

I copied the libclntsh.dylib to the /usr/local/lib as suggested.   And I was getting errors like:

> DPI-1047: Cannot locate a 64-bit Oracle Client library: "dlopen(libclntsh.dylib, 1): image not found" #1165

So I created the ~/lib directory and I copied lib* from the instantclient_19_3 directory to ~/lib as suggested.

I then started getting errors like:
> libclntsh.dylib cannot be opened because the developer cannot be verified catalina

I enabled access via Gatekeeper in System Settings and clicking 'Allow Anyway' in the dialog.

After doing this I started getting:

> Error while trying to retrieve text for error ORA-01804

Upgrading to the full basic_package vs. basic_lite package https://download.oracle.com/otn_software/mac/instantclient/193000/instantclient-basic-macos.x64-19.3.0.0.0dbru.zip    Allowed it to connect correctly.

I hope this helps someone going forward.

**Comment by mtxr** [comment]
@bkbonner awesome! Great job!

Hey @bkbonner, would you mind adding this to the docs?

I'll be happy to merge your pull request.

Users usually look there first, so might be better to put this guide there than here.

Here is the file for Oracle: https://github.com/mtxr/vscode-sqltools/blob/master/docs/src/pages/driver/oracledb.mdx
