### ISSUE TITLE
Can't execute sql in mssql and alert Connection is closed

### ISSUE THREAD

**Issue by zhutoutou** [mtxr/vscode-sqltools#443]
**Describe the bug**
Recently I found that i can't execute mssql sql by using the tool any more And alert message connection is closed,by the way, the same sql use microsoft mssql tool with no problem.i have test the connection correctly. 

**To Reproduce**
1. create a connection to mssql 2008 R2
2. choose the sql
3. Ctrl+E Ctrl+E
4. Use another computer repeat the operation

**Expected behavior**
execute success like before

**Screenshots**
![image](https://user-images.githubusercontent.com/30338453/68665403-f30cb000-057c-11ea-88dd-4a0f9c389aa3.png)

**Desktop (please complete the following information):**
 - SQLTools Version:0.21.2
 - VSCode Version: 1.40.0
 - Dialect Used/Version:MSSQL 2008 R2
 - OS: Windows 10

**Additional context**
the mysql connection is well and can unfold the database
![image](https://user-images.githubusercontent.com/30338453/68665755-94940180-057d-11ea-81e0-df208b188622.png)

**Comment by wjfang90** [comment]
I have the same problem, but I have not found a message supported by the MSSQL version.

**Comment by mtxr** [comment]
@zhutoutou @wjfang90 Does your connection need encryption?

**Comment by wjfang90** [comment]
> @zhutoutou @wjfang90 Does your connection need encryption?

No,I connected direct

**Comment by zhutoutou** [comment]
> > @zhutoutou @wjfang90 Does your connection need encryption?
> 
> No,I connected direct

Me too

**Comment by boukisny** [comment]
Did anyone find a solution to this issue?

**Comment by Artur-nav** [comment]
Looks like this bug concerns version 2008 only. I had same alert "Connection is closed" without displaying a result for simplest "select getdate()" query, when sqltools connected to MSSQL Express 2008. It  didn't create tree of schemas and their objects too.

I installed MSSQL Express 2019, vscode works fine with this version of database.

**Comment by mtxr** [comment]
This was fixed on newer versions.
