### ISSUE TITLE
Error when starting a connection to an sqlite database

### ISSUE THREAD

**Issue by wesleydean** [mtxr/vscode-sqltools#444]
**Describe the bug**
Getting a red error banner when trying to connet to an sqlite.db

**To Reproduce**
1.Go to Connection Assistant. Fill out connection name and attach .db file.
2.Click on test connection.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/6432980/68775132-54d92280-062e-11ea-9e40-c2fd0e9bf562.png)

**Desktop (please complete the following information):**
 - SQLTools Version 0.21.3
 - VSCode Version: 1.40.0
 - Dialect Used/Version: [SQLite]
 - OS: [Mac]

**Comment by mtxr** [comment]
@wesleydean can you paste the logs of SQLTools (and Language Server) output channel as well?

**Comment by kasanitej** [comment]
I too cannot able to connect. But my OS is windows. my file extension is ".sqlite3" not ".db"

**Comment by mtxr** [comment]
do you still have problems?
