### ISSUE TITLE
Move postgres messages above query in output.

### ISSUE THREAD

**Issue by Fmstrat** [mtxr/vscode-sqltools#446]
**Is your feature request related to a problem? Please describe.**
Potentially related to: https://github.com/mtxr/vscode-sqltools/issues/437 and https://github.com/mtxr/vscode-sqltools/issues/417 which you fixed awesomely.

In the latest version of SQL Tools, If I run a very long query, such as adding a function, it used to show a blank result to let you know there was a success. However, now it shows the slide-out from the side overlapping results with a `DO successfully executed.`

Could we consider moving `MESSAGES` up above `QUERY`? In most cases, the message is what is important, vs having to scroll through the entire query.

**Describe the solution you'd like**
Move `MESSAGES` up above `QUERY`.

**Describe alternatives you've considered**
A lot of scrolling.

**Additional context**
![query](https://user-images.githubusercontent.com/971474/68886568-79440600-06e5-11ea-8a86-1cdb6212bc20.png)

**Comment by mtxr** [comment]
Thanks @Fmstrat. Messages were moved to another place in `vnext` branch.

Keep following the project to get updates on that, ok?

Thanks.
