### ISSUE TITLE
Jump server / multiple servers

### ISSUE THREAD

**Issue by flight505** [mtxr/vscode-sqltools#450]
Is it possible to use SQLtools when you have multiple login points? 
One of the servers I need to query, requires me to initially log in to a Mysql server then a second login is required to get to a MariaDB. 

Usually, I connect via SSH or Sequel Pro - but it would be a very nice feature if it is/was possible directly from VScode.  

Thanks

**Comment by mtxr** [comment]
Can you explain it a bit? I'm not picturing it yet. Or if possible, instructions on how can I reproduce this here.

Thanks!

**Comment by xgdgsc** [comment]
I' ve used vscode remote (with ~/.ssh/config edited with ProxyCommand) and install sqltools on remote with success.

**Comment by gjsjohnmurray** [comment]
Closing because no response to request for more information.
