### ISSUE TITLE
MySQL auto-formatting breaks block execution

### ISSUE THREAD

**Issue by cscholle1** [mtxr/vscode-sqltools#451]
**Describe the bug**
Autoformat results in queries not running correctly

**To Reproduce**
1. Create a new .sql file with 2 blocks
2. Save file with auto-formatting
3. Notice no extra line spacing between blocks
4. Run first block (it fails)

**Expected behavior**
All blocks should be able to be run successfully.

**Screenshots**
Only the last block can be run successfully. First block and all blocks previous to the last are not run successfully. Received error: `ER_NO_TABLES_USED: No tables used`

![image](https://user-images.githubusercontent.com/47984872/69436468-6b0e6f00-0d0f-11ea-9886-5c1a38e39f38.png)

**Desktop (please complete the following information):**
 - SQLTools Version 0.21.3
 - VSCode Version: 1.40.1
 - Driver Used/Version: MySQL 6
 - OS: Windows 10 Pro Version 10.0.18362 Build 18362

**Additional context**
It appears that the  block is not parsed properly and only `SELECT *` is run, resulting in the "no table error". If I add an empty newline between blocks and saving without auto formatting, the blocks run successfully and correct results returned.

**Comment by mtxr** [comment]
Yeah, that's annoying. If we add one line before the 2nd `-- @BLOCK` it works. I'll fix this today.

**Comment by mtxr** [comment]
Fixed
