### ISSUE TITLE
store passwords in env vars

### ISSUE THREAD

**Issue by two-bridges** [mtxr/vscode-sqltools#452]
First off, SQLTools is great.  Thanks for the extension.  

One gripe is that it looks like passwords can only be stored in plain text in the settings.  This is unfortunate as you generally wouldn't want to send passwords to git.  

Instead, it would be good if you can use environment variable substitution.  Eg. passwords are in stored in environment variables and then only environment variable names are referenced in the SQLTools settings.  

È possibile?

**Comment by two-bridges** [comment]
> what about the "Save To Global Settings?" option 

Ah great, I will try that - thanks.  Sounds like it will do the trick actually.  Could even be exactly what I need.  Environment variables are available everywhere not just when running from a cli, ASAIK.  

If `${env:ENVVARNAME}` works then there's no need to change the extension at all (perhaps you could document in the README.md for best practices with password handling).  

I'll test it out once I restart my workspaces tonight (as VSCode only takes the env vars on process start).  

> I'm not sure where you would read envvars from

Incidentally, since it's electron, based on nodeJs, I believe you access environment variables using `process.env`.  eg. `console.log(process.env.PATH);`.

**Comment by two-bridges** [comment]
> In that case, you could use "${env:ENVVARNAME}" [as seen here](https://code.visualstudio.com/docs/editor/variables-reference#_environment-variables).

I've just tried that but it's not working.  Apparently VSCode's variable substitution is not yet implemented for general use settings.json (only works in limited places like debugging, tasks and a few particular settings).  

I'll go with the Global Settings solution you suggested, I think that's adequate for now.  I cut-paste my existing connection settings from .vscode/settings.json into the global settings file, restarted VSCode and it worked.  

It's not perfect as those wishing to sync their settings between machines now have to worry about their settings containing secrets.  

I'm watching this VSCode feature request for an env-var solution, as I reckon variable substitution should be provided by VSCode rather than every single extension author:  https://github.com/microsoft/vscode/issues/2809 

Feel free to close this.

**Comment by bagong** [comment]
When I store the access data in User-settings, authentication fails for me (it works with settings stored in the project, so it's not an mysql-version related problem, I set mysql back to the old authentication method). As a workaround for the git-problem: I think you want to add settings.json to .gitignore anyways).

**Comment by lnxbil** [comment]
I tried the extension in `code-server` and it works great if I store the plaintext password in the configuration. The environment substitution however, does not work. As @two-bridges already pointed out, it would be great if vscode would have such a method, but for the last 1+ years, there was no such thing.

Maybe we could try to solve it in the extension until it is mainstream vscode?

**Comment by gjsjohnmurray** [comment]
Closing in favour of #927
