### ISSUE TITLE
Problem connecting to IBM DB2

### ISSUE THREAD

**Issue by fkita** [mtxr/vscode-sqltools#454]
When trying to access IBM DB2, I'm reaching the following error message.

Error opening connection [IBM][CLI Driver][DB2] SQL0204N  "SYSIBM.TABLES" is an undefined name.  SQLSTATE=42704

I checked our DB2 and in fact I can't see the table/view named "TABLES" at SYSIBM Schemes, is there a way to workaround this step while trying to access IBM DB2?

ps.: I'm not sure if it's related to RACF access and it can limit the number of tables that I can see for SYSIBM schemes. Also we do have SYSIBM.SYSTABLES, but since I'm not a DBA I can't say for sure if it's the same table as expected for your plugin.

**Comment by mtxr** [comment]
@snyang can you give a hand here?

**Comment by snyang** [comment]
@mtxr The issue is probably a permission issue, so the user cannot access database schema tables.
An idea is that we  catch the error in `dialect\generic.ts`.
Any opinions?

**Comment by mtxr** [comment]
Go for it. I'm really blind on IBM DB2. You are the master here :D

**Comment by mtxr** [comment]
Not supported within this repository anymore.

**Comment by GitMensch** [comment]
Why was DB2 removed? Can you please share some links to read about that?

Background: Someone demo'd connecting to different DBs starting with DB2 lately and I've thought "that's possible with the extension I've heard of", now checking back: all DBs work - but DB2 - but it seems that _was_ in someday, so I'm even more confused.

**Comment by gjsjohnmurray** [comment]
GH history indicates DB2 support got added in September 2019 by PR https://github.com/mtxr/vscode-sqltools/pull/391 from @snyang 

Apparently the project owner @mtxr didn't have access to a DB2 system, and later (v0.22) when the architecture was revised to separate drivers into individual extensions no-one created one for DB2.

@GitMensch maybe you could use the info in the original PR plus the documentation at https://vscode-sqltools.mteixeira.dev/en/contributing/support-new-drivers/ to create a DB2 driver extension.
