### ISSUE TITLE
Use sqlfmt

### ISSUE THREAD

**Issue by brandonkal** [mtxr/vscode-sqltools#463]
**Is your feature request related to a problem? Please describe.**
The bundled formatter works decently but it would be nice to have something that is more aware of line length, as is common with Prettier.

Example input:
input:
```sql
SELECT change_id from changes;
```
vscode-sqltools output:
```
SELECT
  change_id
from
  changes;
```
Things I note are, no standardization on capitalization of keywords and the unnecessary extra lines that detracts from readability.

**Describe the solution you'd like**
Would you consider a PR for running sqlfmt on save? This would be one less thing to maintain.
ref:
https://www.cockroachlabs.com/blog/sql-fmt-online-sql-formatter/
https://sqlfum.pt/
https://github.com/mjibson/sqlfmt/tree/master

input:
```sql
SELECT count(*) count, winner, counter * (60 * 5) as counter FROM (SELECT winner, round(length / (60 * 5)) as counter FROM players WHERE build = $1 AND (hero = $2 OR region = $3)) GROUP BY winner, counter;
INSERT INTO players(build, hero, region, winner, length) VALUES ($1, $2, $3, $4, $5);
INSERT INTO players SELECT players_copy ORDER BY length;
UPDATE players SET count = 0 WHERE build = $1 AND (hero = $2 OR region = $3) LIMIT 1;
```
sqlfmt output:
```sql
SELECT count(*) AS count,
         winner,
         counter * 60 * 5 AS counter
    FROM (
            SELECT winner,
                   round(length / (60 * 5)) AS counter
              FROM players
             WHERE build = $1 AND (hero = $2 OR region = $3)
         )
GROUP BY winner, counter;

INSERT
  INTO players (build, hero, region, winner, length)
VALUES ($1, $2, $3, $4, $5);

INSERT INTO players SELECT players_copy ORDER BY length;

UPDATE players
   SET count = 0
 WHERE build = $1 AND (hero = $2 OR region = $3)
 LIMIT 1;
```

**Comment by mtxr** [comment]
I've been improving our current formatter, I believe won't be moving to a different formatter soon, so I'm closing this one.
