### ISSUE TITLE
Return results like cells in excel instead of plain text

### ISSUE THREAD

**Issue by dnlw07** [mtxr/vscode-sqltools#465]
Currently returned results are represented as plain text. 
When query results are selected and copied, then all NULL values are copied as "NULL" text instead of empty string.

Is it possible that returned results will behave more less like an excel sheet (ex. Excel Viewer by GrapeCity VSC extension). 
Returned results records could be treated like cells not like plain text. Thanks that records could be easily copied and nulls would be copied as and empty string.

Screen example:
![screenshot 198](https://user-images.githubusercontent.com/23562689/70809181-88d86c80-1dc1-11ea-8235-6f16f5d8a86b.jpg)

**Comment by gjsjohnmurray** [comment]
CSV and JSON formats are already available.
