### ISSUE TITLE
Snowflake Support

### ISSUE THREAD

**Issue by Bryan-Meier** [mtxr/vscode-sqltools#466]
**Is your feature request related to a problem? Please describe.**
We have a need to connect to and write code against Snowflake which is currently not supported in SQL Tools

**Describe the solution you'd like**
Add driver support for Snowflake

**Describe alternatives you've considered**
Using other tools like DBeaver which only gets part of the way there.

**Additional context**
NA

**Comment by eciccarone** [comment]
Has anyone started working on a driver for Snowflake?  If not, I may take a crack at it.

**Comment by Bryan-Meier** [comment]
As far I a know, I have been the only one interested in adding a Snowflake driver. I had issues getting my environment to build for the SQL Tools. I may be willing to help if I can get a clean build.

**Comment by tomsej** [comment]
Any progress with this? Unfortunately, I am not really good at TS so it is hard for me to contribute.

**Comment by Bryan-Meier** [comment]
> Any progress with this? Unfortunately, I am not really good at TS so it is hard for me to contribute.

No progress yet as far as I know.

**Comment by mtxr** [comment]
I need help with this. I dont know this dialect.

**Comment by BrettMoan** [comment]
I could definitely help with the syntax of snowflake. 

I was interested in also making a jdbc port, since while getting the package to build may be complex, it would immediately allow for 40+ languages with a single code base (jdbc has an api call instead of a sql query for each of the defined methods which works for literally every language that follows the jdbc spec and makes an jdbc jar)

**Comment by BNMeier** [comment]
> I need help with this. I dont know this dialect.

I can help. I was going to get started on it but had issues adding a driver. It seems the "yarn run add-driver" is broken in the current build.

**Comment by mtxr** [comment]
@Bryan-Meier please take a look at https://vscode-sqltools.mteixeira.dev/contributing/support-new-drivers

you should be able to integrate it now.

**Comment by koszti** [comment]
related PR, waiting for approval to get merged: https://github.com/mtxr/vscode-sqltools/issues/713 . Snowflake driver can now be installed directly from the vscode extension menu:

Github source code: https://github.com/koszti/sqltools-snowflake-driver.
VS Marketplace: https://marketplace.visualstudio.com/items?itemName=koszti.snowflake-driver-for-sqltools
