### ISSUE TITLE
need to upgrade required sqlite3 driver version?

### ISSUE THREAD

**Issue by zombie110year** [mtxr/vscode-sqltools#467]
**Describe the bug**
`npm i -g sqlite3@4.0.8` will raise a 403 error, so I execute `npm i -g sqlite3` and installed sqlite3@4.1.1. However, extension still requires sqlite3@4.0.8.

**To Reproduce**
1. create a connection profile, connecting to my firefox cookies.sqlite file.
2. Connect.

**Expected behavior**
commonly run...

**Screenshots**
![图片](https://user-images.githubusercontent.com/36528430/70860582-77789700-1f5e-11ea-9835-7138d8721070.png)

**Desktop (please complete the following information):**
 - [x] SQLTools Version: 0.21.5
 - [x] VSCode Version: 1.41.0
 - [x] Driver Used/Version: SQLite3/?
 - [x] OS: Windows_NT x64 10.0.18363

**Comment by Rossosaurus** [comment]
I'm having the same issue. I'm guessing it's because in [this file](https://github.com/mtxr/vscode-sqltools/blob/master/packages/drivers/src/driver/sqlite/index.ts) they have this line requiring a specific version of SQLite3:

`const SQLite3Version = '4.0.8';`

**Comment by mtxr** [comment]
I'll upgrade the version.
@zombie110year install it globally doesn't work. The extension is a package and all its dependencies are installed in the extension folder. You can try installing the driver in the extension folder if you want

**Comment by mtxr** [comment]
fixed
