### ISSUE TITLE
Connection via SSH keyfile possible?

### ISSUE THREAD

**Issue by SmokinB** [mtxr/vscode-sqltools#475]
Hello,

is it possible to connect via SSH and keyfile to a remote MySql-DB?

Best regards, 
Benjamin

**Comment by mrk-n** [comment]
Hi, this was already discussed in #230 and #395 . For now you can open up a native ssh tunnel.

What I did: I created an AppleScript which opens a tunnel for me and creates a small window with a close button. Easier for me to handle/close open tunnels.

**Comment by mtxr** [comment]
Dup of #395
