### ISSUE TITLE
Error opening connection DPI-1050: Oracle Client library is at version 11.1 but version 11.2 or higher is needed

### ISSUE THREAD

**Issue by doberkofler** [mtxr/vscode-sqltools#480]
When trying to connect to a local Oracle database the driver reports the following error:
`Error opening connection DPI-1050: Oracle Client library is at version 11.1 but version 11.2 or higher is needed`

The configuration is as follows:
```
{
	"sqltools.connections": [
		{
			"connectionTimeout": 30,
			"database": "TEST",
			"dialect": "OracleDB",
			"name": "LJ_UNITTEST",
			"password": "***",
			"port": 1521,
			"server": "localhost",
			"username": "LJ_UNITTEST"
		}
	],
	"sqltools.useNodeRuntime": true,
	"sqltools.languageServerEnv": {
		"ORACLE_HOME": "C:\\oracle\\product\\12.2.0\\dbhome_1"
	}
}
```

**Comment by mickeypearce** [comment]
What is your OS version? 
Do you have a ORACLE_HOME defined in system variables?

**Comment by mickeypearce** [comment]
Take a look at this: https://github.com/oracle/python-cx_Oracle/issues/351#issuecomment-538785431
> Oracle client 12.1 requires the Visual Studio 2010 Redistributable.

**Comment by mickeypearce** [comment]
@doberkofler did you solve the problem? Can you please provide details...

**Comment by doberkofler** [comment]
Sorry for just closing without commenting. I just wanted not to use more of your time. After having tried to install on another Workstation it worked as expected, so I concluded that something was just messed up and I need to sort this out by reinstalling everything from scratch.

**Comment by mickeypearce** [comment]
No problem. Good luck. 😄
