### ISSUE TITLE
Support for Old 10g Oracle 

### ISSUE THREAD

**Issue by auphali** [mtxr/vscode-sqltools#487]
**Describe the bug**
My company still uses the old 10g for database, so when I tried to connect, it failed to get list of functions. As I see from how you retrieve the list. It is the function **LISTAGG** that makes it failed.
My suggestion is that you replace it with something that even older version of Oracle can understand like **WM_CONCAT**

**Comment by auphali** [comment]
It is this part of SQL that failed to execute on older version of oracle
`select
  nvl(procedure_name, object_name) as name,
  owner as dbschema,
  sys_context ('USERENV', 'DB_NAME') as dbname,
  owner ||'.'||object_name || case when procedure_name is not null then '.'||procedure_name else null end as signature,
  replace(
  rtrim(xmlagg(case when argument_name is null then null else xmlelement(a, argument_name || '=>' || ora_type, ','
  ).extract('//text()') end order by position).getclobval(), ',' ),
  '=&gt;', '=>') as args,`
**`listagg(case when argument_name is null then ora_type else null end, ',') within group (order by position) as resulttype,`**
`  sys_context ('USERENV', 'DB_NAME') || '${TREE_SEP}' || owner || '${TREE_SEP}'
    || decode(object_type, 'PACKAGE', 'packages', 'FUNCTION', 'functions', 'PROCEDURE', 'procedures')
    || '${TREE_SEP}' || object_name 
    || case when procedure_name is not null then '${TREE_SEP}' || procedure_name  else null end
  as tree,
  '' as source
from (
  select p.procedure_name, p.object_name, p.owner, p.object_type,
  sys_context ('USERENV', 'DB_NAME') as dbname,
  a.data_type, a.argument_name, a.position,
  case when a.type_name is not null 
    then a.type_owner || '.' || a.type_name 
    || case when a.type_subname is not null
      then '.' || a.type_subname
      end
    when a.pls_type is not null 
      then a.pls_type
    else a.data_type 
  end ora_type  
  from all_procedures p
  join all_arguments a on (a.owner = p.owner and ((a.object_name = p.object_name) or (p.procedure_name = a.object_name and p.object_name = a.package_name)))
  where p.object_type in ('FUNCTION','PROCEDURE','PACKAGE') 
  and not (p.object_type = 'PACKAGE' and p.procedure_name is null) 
  and p.owner = user
)
group by
  owner,
  object_type,
  object_name,
  procedure_name`

As I mentioned above, it was due to **LISTAGG** function being unsupported. As a way around, i simply use **WM_CONCAT** only to make the query successful, since i do not really use function list.
To mitigate, i replaced the bold script above with
**`WM_CONCAT(CASE WHEN ARGUMENT_NAME IS NULL THEN ORA_TYPE ELSE NULL END || ',')`**
But you might want to fix this issue for real as the code i use may not show the result you actually want

**Comment by mtxr** [comment]
@auphali  Do you believe you can work on a PR to fit both versions?

**Comment by auphali** [comment]
@mtxr I am ashamed i cannot. I appreciate you created the plugin (even though i cannot appreciate enough), but i cannot really involved in working on fixing this issue. Sorry

**Comment by mtxr** [comment]
I'll close this issue for now. 

If anyone else is interested on this integration and wants to try it out, here is the docs to achieve that: https://vscode-sqltools.mteixeira.dev/contributing/support-new-drivers
