### ISSUE TITLE
error listen EADDRINUSE: address already in use :::8080

### ISSUE THREAD

**Issue by cdisk** [mtxr/vscode-sqltools#493]
When I use code-server to install the VSIX file.
and after restart browser, IDE alert message say : The SQLTools Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted.

The logs output:
Option 'node-ipc' is unknown. Ignoring.
Option 'clientProcessId' is unknown. Ignoring.
Option 'node-ipc' is unknown. Ignoring.
Option 'clientProcessId' is unknown. Ignoring.
error listen EADDRINUSE: address already in use :::8080
[Info  - 4:28:05 AM] Connection to server got closed. Server will restart.
Option 'node-ipc' is unknown. Ignoring.
Option 'clientProcessId' is unknown. Ignoring.
Option 'node-ipc' is unknown. Ignoring.
Option 'clientProcessId' is unknown. Ignoring.
error listen EADDRINUSE: address already in use :::8080
[Info  - 4:28:06 AM] Connection to server got closed. Server will restart.
Option 'node-ipc' is unknown. Ignoring.
Option 'clientProcessId' is unknown. Ignoring.
Option 'node-ipc' is unknown. Ignoring.
Option 'clientProcessId' is unknown. Ignoring.
error listen EADDRINUSE: address already in use :::8080
[Info  - 4:28:06 AM] Connection to server got closed. Server will restart.
Option 'node-ipc' is unknown. Ignoring.
Option 'clientProcessId' is unknown. Ignoring.
Option 'node-ipc' is unknown. Ignoring.
Option 'clientProcessId' is unknown. Ignoring.
error listen EADDRINUSE: address already in use :::8080
[Info  - 4:28:07 AM] Connection to server got closed. Server will restart.
Option 'node-ipc' is unknown. Ignoring.
Option 'clientProcessId' is unknown. Ignoring.
Option 'node-ipc' is unknown. Ignoring.
Option 'clientProcessId' is unknown. Ignoring.
error listen EADDRINUSE: address already in use :::8080
[Error - 4:28:08 AM] Connection to server got closed. Server will not be restarted.

another my code-server run as docker image.  default port is 8080.

I enter this container, run "ps" command, found the following command: 
/usr/local/bin/code-server /home/coder/.local/share/code-server/extensions/mtxr.sqltools-0.21.6/languageserver.js --node-ipc --clientProcessId=1050 

I think, The correct command should be:
node /home/coder/.local/share/code-server/extensions/mtxr.sqltools-0.21.6/languageserver.js --node-ipc --clientProcessId=1050

Please help me how can I fix it, Thanks everyone.

**Comment by mtxr** [comment]
This is more like a https://github.com/cdr/code-server issue than the extension itself.

We don't use port 8080 for nothing, so it shouldnt be breaking.

I don't really understand how code-server works, so I can't help much, also I've in a hurry to deliver v0.22, would you mind opening this issue in their project?

They might have a solution quickly for you.

Thanks!

**Comment by ggongaware** [comment]
I attempted the same thing, and found a work around - On the code-server server, make sure nodejs is installed in the path, then enable in the user settings.json:
``` json
{ "sqltools.useNodeRuntime": true }
```

I can now run queries and see results in the code-server browser :-)
