### ISSUE TITLE
Unable to connect to Cassandra after enabling user defined function.

### ISSUE THREAD

**Issue by Raiyol** [mtxr/vscode-sqltools#495]
**Describe the bug**
Before enabling user defined function, I could connect to cassandra just fine and execute my queries. But after enabling it and creating some aggregate function then restarting vscode, I can't connect to cassandra with SQLTools anymore.
I can still connect to cassandra just fine using cqlsh on cmd.

SQLTools errors : 
```
-Error opening connection obj.argument_types.join is not a function
-Error while preparing columns completions for connection CassandraProjet obj.argument_types.join is not a function
```

Cassandra : 
`WARN  [Native-Transport-Requests-3] 2020-02-03 22:36:06,360 SelectStatement.java:533 - Aggregation query used without partition key (ks: system_schema, tbl: columns)`

**To Reproduce**
1. In apache cassandra folder, go to 'conf' and edit "cassandra.yaml".
2. In the yaml file, set `enable_user_defined_functions: true`
3. Start cassandra on cmd.
4. Create a cassandra connection on SQLTools in vscode.
5. Create a new file and in it create a user defined function.
My code : 
```
CREATE OR REPLACE FUNCTION avgState ( state tuple<int,bigint>, val int )
CALLED ON NULL INPUT RETURNS tuple<int,bigint> LANGUAGE java
AS 'if (val !=null) { state.setInt(0, state.getInt(0)+1);
state.setLong(1, state.getLong(1)+val.intValue()); }
return state;';

CREATE OR REPLACE FUNCTION avgFinal ( state tuple<int,bigint> )
CALLED ON NULL INPUT RETURNS double LANGUAGE java
AS 'double r = 0;
if (state.getInt(0) == 0) return null;
r = state.getLong(1);
r/= state.getInt(0);
return Double.valueOf(r);';

CREATE AGGREGATE IF NOT EXISTS average ( int )
SFUNC avgState STYPE tuple<int,bigint>
FINALFUNC avgFinal INITCOND (0,0);
```
5. Execute the code.
6. Restart vscode and try to connect to cassandra.

**Expected behavior**
A successful connection as usual.

**Desktop (please complete the following information):**
 - SQLTools Version: v0.21.6
 - VSCode Version: v1.41.1
 - Driver Used/Version: [cqlsh 5.0.1 | Cassandra 3.11.3.5117 | CQL spec 3.4.4 | Native protocol v4]
 - OS: Windows

**Additional context**
Followed this to install cassandra : https://www.how2shout.com/how-to/install-apache-cassandra-on-windows-10-8-7-without-datastax.html

**Comment by mtxr** [comment]
@EpicEric can you take a look on this?
