### ISSUE TITLE
Connection refused - SAPHana connection request

### ISSUE THREAD

**Issue by capsamon** [mtxr/vscode-sqltools#496]
**Describe the bug**
I am unable to make a connection to our SAPHana database, since I get a connection refused error.
ERROR: Error:  { Error: Connection failed (RTE:[89006] System call 'connect' failed, rc=111:Connection refused {ipadres:2....} (zeus.hana*******.ondemand.com:2....))
    at /tmp/vscode-unpacked/sqltools-0.21.0.vsix/extension/extension.js:1:22830
    at /tmp/vscode-unpacked/sqltools-0.21.0.vsix/extension/extension.js:1:23237
    at Immediate.messageQueue.size.setImmediate (/tmp/vscode-unpacked/sqltools-0.21.0.vsix/extension/extension.js:1:23781)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
  code: -10709,
  data: { dialect: 'SAPHana', dialectOptions: {} } }

**Expected behavior**
I am expecting to connect to our database.

**Desktop (please complete the following information):**
 - SQLTools Version 0.21.6
 - VSCode Version: 1.37.1
 - Driver Used/Version: SAPHana
 - OS: Windows

**Additional context**
My settings, and at the hanaOptions part I also tried to follow the certificate part, but that did not make it working either

"sqltools.connections": [
        {
            "connectionTimeout": 10,
            "database": "VELD*******",
            "dialect": "SAPHana",
            "name": "Veld*******",
            "password": "*******",
            "port": 2....,
            "server": "zeus.hana.**************.ondemand.com",
            "username": "VELD*******",
            "hanaOptions": {
                "ENCRYPT": true,
                "sslValidateCertificate": false
            }
        }
    ],

**Comment by mtxr** [comment]
@ariel-bentu can you take a look at this?

**Comment by ariel-bentu** [comment]
I have seen this happening if you're not using the latest version of the driver. 
Please verify that you have version 2.4.177.
In Mac, goto ~/.vscode/extensions/mtxr.sqltools-0.21.6/node_modules/@sap/ and delete the hana-client and reinstall via the vscode sqltools.

**Comment by gjsjohnmurray** [comment]
@capsamon did the response from @ariel-bentu help you resolve this issue?
