### ISSUE TITLE
Ability to specify default folder for session files

### ISSUE THREAD

**Issue by Fmstrat** [mtxr/vscode-sqltools#497]
**Is your feature request related to a problem? Please describe.**
When opening a session, the default place SQL session files are stored is at the root of the existing repo. In most cases, saving this file leaves an artifact in the root of the repo that would require a `.gitignore`.

**Describe the solution you'd like**
A setting that stores a folder where session files are opened in by default, that way saving them can be stored separately, or even in their own repo.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by Fmstrat** [comment]
Looks like a settings wrapper here might work: https://github.com/mtxr/vscode-sqltools/blob/2494ff0a95b6a2fef0b0586f001bb5b7c164fa31/packages/plugins/connection-manager/extension.ts#L136

I might be able to do a quick PR.

**Comment by Fmstrat** [comment]
Hrm.. why is the `packages` folder excluded from VSCode? Seems like that's where some of the editing needs to occur.

**Comment by Fmstrat** [comment]
It also looks like the `docs` folder is in the VSCode exclude. Again, not sure why this is the case ;)

**Comment by mtxr** [comment]
@Fmstrat what do you mean?

I see all folders here normally.

I'm closing this issue since you fixed on #498 

Thanks again!

**Comment by pztrn** [comment]
Hey, sorry for necroposting, yet looks like this issue should be re-opened as it is not working properly. Or should I create separate one?

My usecase: store session files within `.vscode` folder (so they'll be `.gitignore`'d automagically). I cannot make it work, tried to specify:

* `${workspaceFolder}/.vscode` - trying to create `$\{workspaceFolder\}/.vscode` and fails to save session file.
* `.vscode` - trying to create `/.vscode` and fails to save session file.

**Comment by gjsjohnmurray** [comment]
@pztrn please open a new issue to request that the `${workspaceFolder}` variable gets supported in the `sqltools.sessionFilesFolder` setting.

**Comment by pztrn** [comment]
Thanks, filed #1010
