### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by SalomaoCruz** [mtxr/vscode-sqltools#499]
- Issue Type: `Performance`
- Extension Name: `sqltools`
- Extension Version: `0.21.6`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.41.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\salomao\mtxr.sqltools-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by mtxr** [comment]
Closed on branch `lazy-tree` with a bunch of commits
