### ISSUE TITLE
How to run SQL query?

### ISSUE THREAD

**Issue by PixelT** [mtxr/vscode-sqltools#50]
How I can run SQL query in VScode?

**Comment by PixelT** [comment]
OK, I must select whole query first and add as bookmark... so to do not waste this topis, I would like to add suggestion to add possibility to run SQL query directly from input field, something like:
`SQLTools: Run query` or sth similar

**Comment by mtxr** [comment]
Sure, it's a simple feature. It'll be release in the next release, ok?

**Comment by BlackLight** [comment]
Not sure if I'm missing something obvious, but I really can't find the "Run Query" menu entry anywhere. Right clicking either on the query itself, on the database or any of its tables doesn't show any entry (that's the case for basically any other db editor out there). How am I supposed to run a query without adding each single one as a bookmark?

**Comment by mtxr** [comment]
Hi @BlackLight , you can select a query and use this option from the command palette:
![image](https://user-images.githubusercontent.com/707561/61194631-1e4bc500-a699-11e9-8b18-d58f1c6a8b28.png)

Anyway I like the idea of adding it to the context menu, I'll do this tonight and release it ASAP.

Thanks for the feedback

**Comment by tonilxm** [comment]
@mtxr : when to release context menu feature?

**Comment by mtxr** [comment]
Doing it right now.

**Comment by dudb** [comment]
ctrl + e, ctrl + e

**Comment by informatik01** [comment]
## How to quickly run an arbitrary SQL query in Visual Studio Code
1. Open a new editor tab and write your SQL expression there OR open an existing SQL file.
2. 👉 **Select** the desired SQL query (yes, this is important to select the whole SQL query you want to execute).
3. Do one of the following:
    ▶︎ click the "Run on active connection" link on top of the opened editor tab<sup>1</sup> (kudos to @gjsjohnmurray for this hint)
    ![Preview 2024-08-04 00 16 42](https://github.com/user-attachments/assets/772bf77a-2ab8-4435-8a6d-3fcbd0801eed)

    ▶︎ right-click on the editor and select "Run Selected Query"
    ![image](https://github.com/user-attachments/assets/ce2d2bb4-ae3f-43c7-a96e-61b31d5c00c9)

    ▶︎ use the dedicated _keyboard shortcut_ (the letter `E` of course can be lowercase):
       - macOS: <kbd>⌘E</kbd> <kbd>⌘E</kbd>
       - Windows and Linux: <kbd>Ctrl</kbd>+<kbd>E</kbd>, <kbd>Ctrl</kbd>+<kbd>E</kbd>

---
<sup>1</sup> In order to see the "Run on active connection" link, make sure that the ["Language mode"](https://code.visualstudio.com/docs/languages/overview#_change-the-language-for-the-selected-file) for the opened file is "SQL".   
By default if the selected _language mode_ (in the bottom right of the VS Code) is set for some other SQL dialect (e.g. "MySQL SQL"), then these custom links provided by the **SQLTools** extension will not be shown.

**Comment by gjsjohnmurray** [comment]
Alternatively, click the "Run on active connection" link (aka Codelens) just above the query.

**Comment by informatik01** [comment]
> Alternatively, click the "Run on active connection" link (aka Codelens) just above the query.

Thank you for the hint, I have updated my post.

**Comment by neongreen** [comment]
My customization:

```json
  {
    "key": "cmd+enter",
    "command": "sqltools.executeCurrentQuery",
    "when": "editorTextFocus && sqltools.file.connectionAttached"
  }
```

This way I can get ⌘Enter for SQLTools without clashes.

**Comment by mayur-cli** [comment]
> My customization:
> 
> ```json
>   {
>     "key": "cmd+enter",
>     "command": "sqltools.executeCurrentQuery",
>     "when": "editorTextFocus && sqltools.file.connectionAttached"
>   }
> ```
> 
> This way I can get ⌘Enter for SQLTools without clashes.

did you modify keybindings.json? I tried this but it's not working in windows
[
  {
    "key": "ctrl+alt+enter",
    "command": "sqltools.executeCurrentQuery",
    "when": "editorTextFocus && sqltools.file.connectionAttached"
  }
]

**Comment by om762** [comment]
You can add the following in your **JSON keybindings**:

```json
{
  "key": "ctrl+enter",
  "command": "sqltools.executeCurrentQuery",
  "when": "editorFocus && editorLangId == sql && sqltoolsViewConnectionExplorer.active"
}
````

After that, just use:

**Ctrl + Enter**

That's all from my side. Welcome! 🚀
