### ISSUE TITLE
Unable to connec to DB

### ISSUE THREAD

**Issue by mloss2423** [mtxr/vscode-sqltools#500]
I have been trying to connect to my DB but everytime i try to i get this message.

ailed to install dependencies for DB2: Request DependencyInstaller/install failed with message: npm Not found. You need to install npm first to install dependencies. Install it and restart before continue.

**Comment by mtxr** [comment]
you need to install NodeJS to get dependencies working.

https://nodejs.org/en/

Install it and you will get it working again.
