### ISSUE TITLE
Assignment operator spacing error bug

### ISSUE THREAD

**Issue by vas1468** [mtxr/vscode-sqltools#506]
**Describe the bug**
Sqltools formatter is not respecting the assignment operator and is adding a space.

**To Reproduce**
1. Create an sql file.
2.  Add `SET @counter := 100;`
3. Format sql file
4. After formatting the file: `SET
  @counter : = 100;`

5. Sql Tools Formatter is adding a space on the assignment operator.
6. Syntax error returned: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ': = 100'

**Expected behavior**
Is expected to keep the operator without adding space like other operators.

**Desktop (please complete the following information):**
 - SQLTools Version: v0.21.6
 - VSCode Version: 1.14.1
 - OS: Windows

**Where is the bug possibly**

[https://github.com/mtxr/vscode-sqltools/blob/master/packages/formatter/src/core/Tokenizer.ts](https://github.com/mtxr/vscode-sqltools/blob/master/packages/formatter/src/core/Tokenizer.ts)

Line 40: `this.OPERATOR_REGEX = /^(!=|<>|==|<=|>=|!<|!>|\|\||::|->>|->|~~\*|~~|!~~\*|!~~|~\*|!~\*|!~|.)/;`

The above regex does not include the assignment operator: `:=`

**Comment by mtxr** [comment]
Duplicate and fixed by #552.
