### ISSUE TITLE
SAP HANA Generating wrong SELECT statement

### ISSUE THREAD

**Issue by jnsjunior** [mtxr/vscode-sqltools#510]
**Describe the bug**
Extension is generating wrong SELECT statement

**To Reproduce**
1. Connect to SAP HANA Database
2. Select a table that contains "::"
3. Right click and select "Show Table Records"

**Expected behavior**
I expected to see the table contents, but it is showing an error (sql syntax error: incorrect syntax near "::model": line 1 col 45 (at pos 45)).
I think the table name on SELECT statement must be created using double quotes.

**Screenshots**
![image](https://user-images.githubusercontent.com/8070232/74749293-b2da5f00-5248-11ea-90a8-eb5c2ea2d74a.png)

**Desktop (please complete the following information):**
 - SQLTools Version 0.21.6
 - VSCode Version: 1.41.1
 - Driver Used/Version: @sap/hana-client@2.4.182
 - OS: Linux

**Additional context**

**Comment by gjsjohnmurray** [comment]
If the problem still occurs please report it to the driver extension authors.
