### ISSUE TITLE
vscode Extension Read me does not list DB2

### ISSUE THREAD

**Issue by ahmednrana** [mtxr/vscode-sqltools#520]
**DB2 is missing from list of supported drivers in vscode extension**

**To Reproduce**
1. Go to 'https://marketplace.visualstudio.com/items?itemName=mtxr.sqltools'
2. In list of supported drivers Db2 is missing

**Expected behavior**
DB2 should be listed as it is listed in repo readme. I believe the documentation should be updated.

**Comment by mtxr** [comment]
Hi @ahmednrana. I'll close this issue. The integration now will be done via extension api integration, so no names will appear in the names soon.

But thanks for the heads up!
