### ISSUE TITLE
VSCode reload required while updating a DB password

### ISSUE THREAD

**Issue by dnlw07** [mtxr/vscode-sqltools#523]
**Describe the bug**
When I add a new DB Oracle connection in settings.json with wrong password I am not able to connectio to DB (what is ofc correct behavior ;) ).
However when I put correct password to the connection in settings.json (ex. remove extra space from end of the password) and try to type again I still won't be able to connect.
I need to restart VSCode to be able connect with updated password.
It seems that after correcting password SQLTools somehow still try to connect using old password. That why VSCode reload is required. 
I had that issue multiple times while creating new connection by directly updating local settings.json with connection strings.

**Comment by mtxr** [comment]
Not supported within this repository anymore.
