### ISSUE TITLE
Return SQL error details in VSCode Output tab

### ISSUE THREAD

**Issue by dnlw07** [mtxr/vscode-sqltools#524]
**Is your feature request related to a problem? Please describe.**
I believe it would be more productive if in Output tab would be inserted log with following informations: 
- SQL error message
- number of returned records
- commit rollback status
- dbms output
- etc.

![screenshot 211](https://user-images.githubusercontent.com/23562689/76977645-dec72e00-6935-11ea-8d1b-ef2e225042b1.jpg)

**Comment by mtxr** [comment]
The branch lazy tree has implemented something similar. See:

![image](https://user-images.githubusercontent.com/707561/81780829-8c396680-94cd-11ea-8e24-25ce07e763ea.png)

Closing.
