### ISSUE TITLE
Cannot commit DML scripts (DELETE, INSERT, UPDATE)

### ISSUE THREAD

**Issue by dnlw07** [mtxr/vscode-sqltools#525]
**Describe the bug**
When I execute Insert or Delete command then the change is not applied in Oracle DB.
After script execution I use COMMIT to finish transaction. 

No errors are returned during script insert, delete, and commit execution.

**Comment by ramonilho** [comment]
I'm also having this problem. When I execute an update/insert/delete query like:
```
update db.sample_table
        set client_name = 'Example' 
        where id = '1';
```
It run with success with the message: 1 rows were affected, but the change it's not represented on table. So I run **COMMIT** in a separated query, and the message is: 
```
No Data
```
And the table is still with the previous value.
If I run something like:
```
update db.sample_table
        set client_name = 'Example' 
        where id = '1';
commit;
```
I get the following message:
**ORA-00933: SQL command not properly ended**

**Comment by mtxr** [comment]
Not supported within this repository anymore.
