### ISSUE TITLE
Allow Generate Insert query with hotkey

### ISSUE THREAD

**Issue by dnlw07** [mtxr/vscode-sqltools#526]
**Is your feature request related to a problem? Please describe.**
1. Current implementation of Generate Insert Query return insert snippet with columns sorted in alphabetical order. Please add an option or change functionality to sort it by row_id.

2. Furthermore only one way to run that function is to manually click on '+' sign in connection tab (what is a bit inconvenient).
When I assign shortcut to the Generate Insert Query function: **Cannot read property 'name' of undefined**

![screenshot 213](https://user-images.githubusercontent.com/23562689/76979466-42525b00-6938-11ea-8f9f-40d8f850b586.jpg)

**Comment by mtxr** [comment]
@dnlw07 :
> Current implementation of Generate Insert Query return insert snippet with columns sorted in alphabetical order. Please add an option or change functionality to sort it by row_id.

This is fixed on V0.22 or newer.

> Furthermore only one way to run that function is to manually click on '+' sign in connection tab (what is a bit inconvenient).
When I assign a shortcut to the Generate Insert Query function: Cannot read property 'name' of undefined
This is a feature request, we don't have it working for hotkeys yet, just from the explorer.

I'm going to rename it to match the feature request, ok?

**Comment by dnlw07** [comment]
Sure!

**Comment by gjsjohnmurray** [comment]
That commands needs to be run from a table node in the connection tree so it knows which table you want an insert statement for, and also to get the column names from that tree.
