### ISSUE TITLE
Some of the reserved words are not converted to upper case after format

### ISSUE THREAD

**Issue by vinclei** [mtxr/vscode-sqltools#533]
**Describe the bug**
Some of the reserved words are not converted to upper case after format, e.g. case, is, null, end, as... 

**To Reproduce**
1. Added the format config in settings.json 
```
"sqltools.format": {
        "indentSize": 4, // changes indentation size when formatting queries
        "reservedWordCase": "upper" // allowed null 'upper' | 'lower'
      }
```
2. format below query
```
select case
        when external_sub_ref_id is null then 'a'
        else 'b'
    end as ref_1,
    case
        when subscription_ref_id is null then 'c'
        else 'd'
    end as ref_2,
    count(1) c
from table1
group by
    1,
    2;
```
3. result like below, some of the reserved words not converted to upper case
```
SELECT
    case
        WHEN external_sub_ref_id is null then 'a'
        ELSE 'b'
    end as ref_1,
    case
        WHEN subscription_ref_id is null then 'c'
        ELSE 'd'
    end as ref_2,
    count(1) c
FROM table1
GROUP BY
    1,
    2;
```
4. See these reserved words are listed here - https://github.com/mtxr/sqltools-formatter/blob/master/src/languages/StandardSqlFormatter.ts#L83

**Expected behavior**
All reserved words could be upper after format

**Screenshots**
See above #2, #3

**Desktop (please complete the following information):**
 - SQLTools Version [0.21.6]
 - VSCode Version: [1.43.2]
 - Driver Used/Version: []
 - OS: [Windows]

**Additional context**

**Comment by cnpryer** [comment]
I believe `object_id`, `count`, `sum` are some examples of reserved words that I'm still seeing unaffected on my end.


> Name: SQL Server (mssql)
Id: ms-mssql.mssql
Description: Develop Microsoft SQL Server, Azure SQL Database and SQL Data Warehouse everywhere
Version: 1.10.1
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-mssql.mssql
+Windows
+VSCode 1.55.2

I'll create another issue if I can do more testing. Currently looking for any existing issues on another formatting problem I'm having that I'd like to submit. (`SELECT` in `UNION` statements indents on every save)

Configuration:
```json
"mssql.format.datatypeCasing": "uppercase",
"mssql.format.keywordCasing": "uppercase",
"mssql.intelliSense.lowerCaseSuggestions": false,
"mssql.format.alignColumnDefinitionsInColumns": true,
"mssql.format.placeSelectStatementReferencesOnNewLine": true,
```

**Comment by indeed-a-genius** [comment]
`sum` is still not converted
I see it's not on the reserved words list in /packages/formatter/src/languages/StandardSqlFormatter.ts

**Comment by gjsjohnmurray** [comment]
@indeed-a-genius for better visibility please open a new issue for this.
