### ISSUE TITLE
Execute "selectConnection" Command From Another Extension

### ISSUE THREAD

**Issue by TomHermanSAP** [mtxr/vscode-sqltools#537]
**Describe the bug**  
Execute "SQLTools.selectConnection" from another extension and connect to a db, without user input.  
From the extension I develop, I want to create a new SQLTools connection and connect to it.  
**I manage to add the connection successfully to the settings.json file:**  
![Connection Created Successfully](https://user-images.githubusercontent.com/54273024/78996976-662b4a00-7b4e-11ea-8af1-88fd14a442c7.png)

I tried to connect to the .db file using the following code:
```
const selectConnection = await vscode.commands.executeCommand("SQLTools.selectConnection", "bookshop");
console.log(selectConnection);
```

Following the code at:  
https://github.com/mtxr/vscode-sqltools/blob/master/packages/plugins/dependency-manager/extension.ts#L55

Yet "nothing happens" (at least from what I understand).  
In case I don't provide a connection name, the options are presented:
```
const selectConnection = await vscode.commands.executeCommand("SQLTools.selectConnection");
console.log(selectConnection);
```
![selectConnection menu](https://user-images.githubusercontent.com/54273024/78997119-a25eaa80-7b4e-11ea-8c01-da2c239e34c0.png)

  
**I don't want the user to choose by themselves the connection, I want to automate this process.**
**Is this the correct way to connect to a connection from another extension? Is it even possible?**  
  
Thank you!

**To Reproduce**  
1. Add and configure a .db file and make sure you could connect to it.
2. git clone https://github.com/microsoft/vscode-extension-samples.git
3. Open using vscode the folder `vscode-extension-samples/helloworld-sample`
4. npm install
5. Add the following code to the extension.ts file:
![To Reproduce Add Code](https://user-images.githubusercontent.com/54273024/78996614-a0e0b280-7b4d-11ea-9c51-5aca1b7e19da.png)

6. run the "Run Extension" launch configuration
7. Execute the command `Hello World`

**Expected behavior**  
The connection is connected after executing the commnad:
```
const selectConnection = await vscode.commands.executeCommand("SQLTools.selectConnection", "bookshop");
```

Meaning the connection is connected and looks like:
![Connection Connected](https://user-images.githubusercontent.com/54273024/78997823-0170ef00-7b50-11ea-9d52-8a859a736095.png)

**Screenshots**  
Added throughout.

**Desktop:**  
 - SQLTools Version 0.21.6
 - VSCode Version: 1.44.0
 - Driver Used/Version: SQLite.
 - OS: Windows, Theia

**Comment by mtxr** [comment]
Hey Tom, I think we can do it another way. I could export some internal functions as an extension API like I'm doing now for the drivers. So you would be able to do this integration you are looking for without using execute commands and possible with auto-completion. See here on current SQLite driver implementation: https://github.com/mtxr/vscode-sqltools/blob/master/packages/driver.sqlite/src/extension.ts#L17

You would even have auto completions. If you want to try it as is now, there are some stuff exported already, like usage of language client for example. With language client you could request to run queries, connect and disconnect if you want
