### ISSUE TITLE
MySQL remote database connection fails with incorrect IP address

### ISSUE THREAD

**Issue by Kevinoh47** [mtxr/vscode-sqltools#541]
**Describe the bug**
I am trying to connect to remote mySQL database server, using a connection that works using MySQLWorkbench. I put in the remote server host, the port, name the connection, put in the default database, my user name and password. When I click the TEST CONNECTION button, I get this error: 

ER_ACCESS_DENIED_ERROR: Access denied for user 'kevinoh'@'10.104.21.11' (using password: YES)

I notice that the IP is not the correct IP. It is not the IP of the remote db server on my network, and indeed I can't ping this IP. Is this some sort of default IP, and the real server is not being pinged successfully?

**To Reproduce**
1. Go to Connection Assistant
2. Click on MySql driver.
3. Add Connection Name, Connection Method (Server and Port), Server Host (remote database server), Port (default 3306), Username, Password.
4. Click TEST CONNECTION.
5. See error showing incorrect IP.

**Expected behavior**
I expect a standard database connection to be opened. Note again that a similar connection setup with the same data works as expected for MySQL Workbench.

**Screenshots**

**Desktop (please complete the following information):**
 - SQLTools Version  0.21.7
 - VSCode Version:  1.44.2
 - Driver Used/Version: MySQL
 - OS: Mac OSX Mojave 10.14.6

**Additional context**
I restarted VS Code after installing the SQLTools extension. For the server host, I tried using both the DNS and the IP of the server. In both cases I got the same error message as noted above.

**Comment by Kevinoh47** [comment]
Solved. found incorrect syntax.

**Comment by PierreOlivierBrillant** [comment]
I've got the same problem with MariaDB. Could you please explain what your synthax error was?

**Comment by christien-kelly** [comment]
@Kevinoh47 can you elaborate on the above I'm having the same issue.
