### ISSUE TITLE
The row height of query result  is too large if there is a jsonb field

### ISSUE THREAD

**Issue by lcgong** [mtxr/vscode-sqltools#543]
**Describe the bug**
The row height of query result  is too large if there is a jsonb field.

**To Reproduce**
```sql
SELECT 123 AS sn, jsonb_build_object('a', 1) AS attrs
```

**Expected behavior**
The height of row is clipped, less than the height of 3 lines. When mouse is hover on it, a window is popped up to show a full content. 

**Screenshots**
![Screenshot from 2020-04-19 16-51-50](https://user-images.githubusercontent.com/127480/79683664-1fc8a000-825e-11ea-96c2-7bd112680553.png)

**Desktop (please complete the following information):**
 - SQLTools Version v0.21.7
 - VSCode Version: 1.44
 - Driver Used/Version: PostgreSQL 12
 - OS: Linux

**Comment by danhalson** [comment]
Can confirm this, it makes it awkward browsing records.

![Screenshot 2020-05-05 at 16 36 20](https://user-images.githubusercontent.com/2422897/81085045-94523e80-8eee-11ea-8eed-c573f49815a6.png)

Thanks.

**Comment by mtxr** [comment]
Fixed on v0.22 or newer.
