### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by deepur126** [mtxr/vscode-sqltools#544]
- Issue Type: `Performance`
- Extension Name: `sqltools`
- Extension Version: `0.21.7`
- OS Version: `Windows_NT x64 10.0.19041`
- VSCode version: `1.44.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\deepa\mtxr.sqltools-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by mtxr** [comment]
merge into #117
