### ISSUE TITLE
auto format on save corrupts cassandra select timeuuid

### ISSUE THREAD

**Issue by xgdgsc** [mtxr/vscode-sqltools#545]
**Describe the bug**
auto format on save corrupts cassandra select timeuuid
 

**To Reproduce**
1. Go to cassandra Session.sql
2.  input code that contain timeuuid column
```
SELECT
  *
FROM alphastore.alphaValueT0
where
  exprid = 08eb9be4-77d2-11ea-a88d-28672d5f4dc4
  and symbol = 'sh600008';
```
3. press save fle

**Expected behavior**
the code should be formated without error.

**Screenshots**
 It formats to this, corrupts the exprid column, making it not executable
```
SELECT
  *
FROM alphastore.alphaValueT0
where
  exprid = 08eb9be4 - 77d2 - 11ea - a88d - 28672d5f4dc4
  and symbol = 'sh600008';
```

**Desktop (please complete the following information):**
 - SQLTools Version 0.21.7
 - VSCode Version: 1.44.2
 
 - OS: Windows connecting to linux remote

**Comment by mtxr** [comment]
@EpicEric can you take a look?

**Comment by EpicEric** [comment]
It is as the issue describes. In CQL, `uuid`s are expressed without quotes, and they shouldn't be broken into multiple identifiers by the formatter. It should be changed to consider the following regex as a value when used in a CQL-connection file.

```regex
\b[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}\b
```

I haven't touched the syntax/formatting part of this extension, so I don't know where to start.

**Comment by xgdgsc** [comment]
Thanks! Hope it will be released soon.
