### ISSUE TITLE
Bookmarks Documentation

### ISSUE THREAD

**Issue by davidmwhynot** [mtxr/vscode-sqltools#546]
I just installed this extension, and was trying to figure out how to add bookmarks, but there is no documentation on how to add new bookmarks.

I would be open to writing the documentation, but I need to know how to do it first!

**Comment by HalfBottleOfMind** [comment]
Hi. Found answer here #50.

**Comment by mtxr** [comment]
Done. https://vscode-sqltools.mteixeira.dev/features/bookmarks
