### ISSUE TITLE
Cannot connect AWS Redshift

### ISSUE THREAD

**Issue by Jiang-Li** [mtxr/vscode-sqltools#547]
**Describe the bug**
On the same machine, I can connect the Redshift using PyCharm, but VS Code gave the following error:
`Error opening connection no pg_hba.conf entry for host "::ffff:10.10.1.125", user "jiangli", database "root", SSL off
`

**Desktop (please complete the following information):**
 - SQLTools Version [0.21.7]
 - VSCode Version: [1.43.2]
 - Driver Used/Version: [AWS Redshift]
 - OS: [Mac 10.15.4]

**Comment by mtxr** [comment]
Please, take a look here: https://vscode-sqltools.mteixeira.dev/driver/postgresql#11-specific-options

And also the driver docs: 
https://node-postgres.com/features/ssl

this is a know issue. You might need to setup the connection with the correct SSL options for you.

try to use `pgOptions: { ssl: true }` at first. Usually this fixes for most of users.
