### ISSUE TITLE
Trying to connect to Cassandra get error "Cannot read property 'results' of undefined"

### ISSUE THREAD

**Issue by stasberkov** [mtxr/vscode-sqltools#548]
**Describe the bug**
Trying to connect to Cassandra get error "Cannot read property 'results' of undefined"

"Error while preparing columns completions for connection cas06 Cannot read property 'results' of undefined"

**To Reproduce**
Just try to connect

**Screenshots**
![image](https://user-images.githubusercontent.com/4071534/80366887-1ca36480-889b-11ea-8aee-fd36a6612989.png)

**Desktop (please complete the following information):**
 - SQLTools Version: 0.21.7
 - VSCode Version: 1.44.2
 - Driver Used/Version: Cassandra
 - OS: Windows 10

**Comment by stasberkov** [comment]
@EpicEric please help

**Comment by EpicEric** [comment]
Which version of Cassandra are you using?

**Comment by stasberkov** [comment]
2.2.14

**Comment by stasberkov** [comment]
2.2.14

**Comment by EpicEric** [comment]
I can reproduced this error in Cassandra v2.2.14. It seems that Cassandra had a different way to store keyspace/table/column data [prior to DataStax Enterprise v5](https://stackoverflow.com/a/38698339/8210631) (equivalent to [versions of Cassandra prior to 3.0](https://docs.datastax.com/en/landing_page/doc/landing_page/compatibility.html#DSEEndofServiceLife(EOSL)compatibility)). Hence, the current queries error out for older versions of Cassandra.

This would require using different queries (from the first link) depending on the system version, and whether the database is Cassandra or another CQL-like database (i.e. Scylla).

I can work on a fix as soon as I have some free time.

**Comment by EpicEric** [comment]
@stasberkov Sorry for taking so long to get back to you. I've opened PR #576, which should fix this.

**Comment by stasberkov** [comment]
@EpicEric thank you so much!
