### ISSUE TITLE
.tt files being reformatted by this plugin

### ISSUE THREAD

**Issue by purge** [mtxr/vscode-sqltools#55]
### Issue Type

* [X] Bugfix/Errors

### Prerequisites (For bugfixes)

* [X] Are you running the latest version?
* [ ] Did you check the logs?
* [ ] Did you check the Setup?

### Description

I haven't dug into why yet but an update to this extension has started reformatting all my .tt files. I disected my plugins and this alone being enabled caused the reformatting.

### Steps to Reproduce (For bugfixes)

Save a file with .tt extension, it gets reformatted onto one line

### Versions

- *Version*: v0.11.3
- *OS*: OSX
- *SGDB*: PostgresSQL

**Comment by mtxr** [comment]
Yeah, it's a bug.

You can fast fix it till the next release by setting the configuration of completionLanguages to 
```json
"sqltools.completionLanguages": [
    "sql"
  ],
```
