### ISSUE TITLE
sqltools continues retrying connecting cassandra db that is down

### ISSUE THREAD

**Issue by xgdgsc** [mtxr/vscode-sqltools#550]
**Describe the bug**
Currently every time I switch window focus to vscode with the `cassandra Session.sql` open. It tries to reconect the cluster although the cluster is down. Is there a way to disable this retry? I just want to edit the file now.

**To Reproduce**
1. Have a down cluster
2. open the session file for cassandra cluster
3. switch windows back and forth
4. It try reconnecting everytime.

**Expected behavior**
A way to disable reconnection temporary. Or auto stop retrying after 10 failed attempts.

**Screenshots**
![image](https://user-images.githubusercontent.com/1189869/80684905-fb3fb400-8af8-11ea-9e5b-fd360c8f574a.png)

**Desktop (please complete the following information):**
 - SQLTools Version 0.21.7
 - VSCode Version: 1.44.2
 - Driver Used/Version: cassandra
 - OS: windows desktop connecting to a remote linux with vscode remote (When the cluster is up the connection is fine)

**Comment by mtxr** [comment]
Is it set to autoconnect?

**Comment by mtxr** [comment]
Not supported within this repository anymore.
