### ISSUE TITLE
How to run multiple queries at once?

### ISSUE THREAD

**Issue by Artur-nav** [mtxr/vscode-sqltools#551]
Hello,

sample queries for Oracle database:
select 1 from dual;
select 'A' from dual;
select sysdate from dual;

After selecting all 3 queries and using Ctrl-E or context menu "Run selected query" it returns:
QUERY
select 1 from dual;
select 'A' from dual;
select sysdate from dual;
MESSAGES
ORA-00933: SQL command not properly ended

So it treats three queries as one. How to "tell" sqltools there are multiple queries?

**Comment by mtxr** [comment]
duplicate of #350
