### ISSUE TITLE
Add-Driver fails to run

### ISSUE THREAD

**Issue by BNMeier** [mtxr/vscode-sqltools#557]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2420%20Funded-%2300A156.svg" />](https://issuehunt.io/r/mtxr/vscode-sqltools/issues/557)

**Describe the bug**
I am trying to run Add-Driver and getting an error. Based on the error and my limited knowledge of exactly what the add-driver.js is doing, it looks like a recent commit, removed the docs/src/components/checkLocation.ts file which seems to be causing the failure due to a diff conflict.

**To Reproduce**
Clone the repo
run: yarn
run: yarn run add-driver

**Expected behavior**
New driver created and ready to be implemented

**Screenshots**
![2020-05-12_17-14-33](https://user-images.githubusercontent.com/64930870/81757598-3a182700-9474-11ea-925e-b9efdc7c416f.jpg)

**Desktop (please complete the following information):**
 - SQLTools Version: Newest
 - VSCode Version: 1.44.2
 - Driver Used/Version: NA
 - OS: Windows 10

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $20.00)

- $20.00 have been anonymously funded.
### Submitted pull Requests
- [#585 Driver generator](https://issuehunt.io/r/mtxr/vscode-sqltools/pull/585)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/mtxr/vscode-sqltools/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by BrettMoan** [comment]
I'm also getting this error. though i didn't realize i didn't know if i needed to be in vscode terminal for not.

for completeness, i'm adding the contents of a what i see from just a powershell terminal when running the `yarn` and `yarn run add-driver` commands:
most importantly. its the same critical error `error: docs/src/components/checkLocation.ts: No such file or directory`

(in addition to various warnings i assume are do to not following instructions of running inside vscode terminal, my bad)

```
PS C:\projects> git clone https://github.com/mtxr/vscode-sqltools.git
Cloning into 'vscode-sqltools'...
remote: Enumerating objects: 217, done.
remote: Counting objects: 100% (217/217), done.
remote: Compressing objects: 100% (153/153), done.
remote: Total 13318 (delta 91), reused 129 (delta 58), pack-reused 13101
Receiving objects: 100% (13318/13318), 8.24 MiB | 4.44 MiB/s, done.
Resolving deltas: 100% (8833/8833), done.
PS C:\projects> cd .\vscode-sqltools\
PS C:\projects\vscode-sqltools> yarn
yarn install v1.22.0
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.9: The platform "win32" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
warning @sqltools/extension@0.21.7: The engine "vscode" appears to be invalid.
warning vscode-languageclient@5.2.1: The engine "vscode" appears to be invalid.
[3/4] Linking dependencies...
warning " > @sqltools/types@0.0.1" has unmet peer dependency "vscode-languageclient@*".
warning " > @sqltools/types@0.0.1" has unmet peer dependency "vscode-languageserver-protocol@*".
warning " > @sqltools/types@0.0.1" has unmet peer dependency "vscode-languageserver@*".
warning "workspace-aggregator-a881051f-6555-499f-a7e9-2850fc17a715 > @sqltools/extension > @babel/cli@7.7.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-a881051f-6555-499f-a7e9-2850fc17a715 > @sqltools/extension > babel-loader@8.0.6" has unmet peer dependency "@babel/core@^7.0.0".
warning "workspace-aggregator-a881051f-6555-499f-a7e9-2850fc17a715 > @sqltools/ui > @devexpress/dx-react-grid@2.2.1" has unmet peer dependency "@devexpress/dx-core@2.2.1".
warning "workspace-aggregator-a881051f-6555-499f-a7e9-2850fc17a715 > @sqltools/ui > @devexpress/dx-react-grid-material-ui@2.2.1" has unmet peer dependency "@devexpress/dx-grid-core@2.2.1".
warning "workspace-aggregator-a881051f-6555-499f-a7e9-2850fc17a715 > @sqltools/ui > @devexpress/dx-react-grid > @devexpress/dx-grid-core@2.2.1" has unmet peer dependency "@devexpress/dx-core@2.2.1".
[4/4] Building fresh packages...
warning Your current version of Yarn is out of date. The latest version is "1.22.4", while you're on "1.22.0".
$ yarn workspace @sqltools/formatter install
yarn workspace v1.22.0
yarn install v1.22.0
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.74s.
Done in 1.21s.
Done in 85.21s.
PS C:\projects\vscode-sqltools> yarn run add-driver --name "jdbc"
yarn run v1.22.0
$ node ./tools/add-driver.js --name jdbc
error: docs/src/components/checkLocation.ts: No such file or directory

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
PS C:\projects\vscode-sqltools>
```

**Comment by BNMeier** [comment]
Can someone please provide the steps to manually add a driver if the Add-Driver code isn't going to be fixed any time soon?

**Comment by mtxr** [comment]
@BNMeier @juanmonsa @alucard17 I need to merge some change on master before fix this. I got some progress during the weekend of the release of next version, so we are close to the big release of v0.22 and that will change the way we handle drivers, so tomorrow possibly we will have more updates on the way we add drivers

**Comment by mtxr** [comment]
Hey @BNMeier I've just replied you here: 

https://github.com/mtxr/vscode-sqltools/issues/466

**Comment by BNMeier** [comment]
Thanks for the reply @mtxr. I spun up a new driver and the recent changes seem to work. I am a little lost in how the plugins now work as it's a different paradigm from the last implementation. Is the idea to clone the SQLTools repo and then run the "yo sqltools-driver" or can you just run the "yo sqltools-driver" by itself and some how it references the SQLTools extension? I am looking to start the work on the Snowflake driver. Thanks for the info in advance!
