### ISSUE TITLE
Windows has sqltools.log_level, unix has sqltools.logLevel ?

### ISSUE THREAD

**Issue by awagner-mainz** [mtxr/vscode-sqltools#56]
### Issue Type

* [X] Question

### Prerequisites (For bugfixes)

Windows: VSCode 1.17.2, SQLTools v0.7.4
Linux: VSCode 1.19.2, SQLTools v0.11.3

I can not update either of the SQLTools extensions in VSCode.

### Description

Opening the settings,
I get a Warning about the Loglevel setting:
```
file: 'file:///c%3A/Users/wagner/AppData/Roaming/Code/User/settings.json'
severity: 'Warnung'
message: 'Unknown configuration setting'
at: '37,5'
source: ''

```
In windows, suggestions for sqltools.log* contain only "logging", but I get no warning for "log_level". But I do get a warning for "logLevel". In Linux, suggestions contain "logging" and "logLevel", and I get no warning for "logLevel", but get one for "log_level"...

I would prefer both settings to be called identically (and to have a corresponding suggestion in windows).
Maybe it is only a matter of getting a newer version of the extension installed in windows, tho. Then this is a request to put the new version into the extension "store". Or how would I go about updating it manually?

Thanks and cheers,

Andreas

**Comment by mtxr** [comment]
It doesn't seem to be a bug.

The settings are described here https://github.com/mtxr/vscode-sqltools#migrating-from-v00-to-v01-or-newer. We had some changes lately.

But for the updating issue, I didn't understand exactly what happened. I guess you can just uninstall and install it again to solve it, would you mind to try?

**Comment by awagner-mainz** [comment]
Thanks for looking after it - and I apologize for not having noticed the settings migration documentation. Makes sense now.
... although, coming to think of it, the documentation says the changes have happened between from v0.**0***.* to v0.1*.*, whereas I am currently stuck between 0.7.4 (windows) and 0.11.3 (linux), so theoretically both version are newer than 0.1?

What does not work is getting 0.1* installed in windows. I have uninstalled the extension, restarted, installed it again, restarted again, and there is v0.7.4 again! (When I open the extensions manager, and go to the sqltools page there, it reports about the new settings ("logLevel") in the "Beiträge" ("Contributions?") register, but says 0.7.4 in the output and reports the warning in the problems window. Maybe for the "Beiträge" register it pulls the current documentation from github or something and not from the currently installed version?)

FWIW, I am referring to version numbers according to the "Output" window, "SQLTools Logs" dropdown, where entries like this one appear:
```
[2018-01-16T11:26:38.][v0.7.4] INFO: Telemetry disabled!
[2018-01-16T11:26:38.][v0.7.4] INFO: Telemetry UUID: 
```

**Comment by awagner-mainz** [comment]
Hi - I've gotten a new computer in the office on wednesday, and with a new install of VSCode (for windows), and reinstall of sqltools (via Settings Sync extension), I automatically got an updated sqltools v0.11.4.

So, for me, everything is fine now it seems. Thank you for your support, and for the effort that goes into sqltools.
