### ISSUE TITLE
Error selecting connection password authentication failed for user 

### ISSUE THREAD

**Issue by aimanhafeez04** [mtxr/vscode-sqltools#560]
**Describe the bug**
want to connect the new database but couldn't able to do that

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem
![db error5](https://user-images.githubusercontent.com/31538556/81511241-932d7100-9335-11ea-9a8f-a42934b3a240.PNG)
.

**Desktop (please complete the following information):**
 
 - VSCode Version: [1.4.0]
 - Driver Used/Version: [ PostgreSQL 12]
 - OS: [ Windows]

**Additional context**

**Comment by mtxr** [comment]
@aimanhafeez04 can you provide more information?

How did you create the connection? Do you use SSL? PGPASS file?
Anything you can give me will help

**Comment by aimanhafeez04** [comment]
I had created from  the vs code extension 
![database aiman](https://user-images.githubusercontent.com/31538556/81557106-0fad6780-93a9-11ea-98d5-12b53418a22d.PNG) 
and when I try to connect this pop up comes all around. 
![error pops up](https://user-images.githubusercontent.com/31538556/81557173-29e74580-93a9-11ea-9b07-9d4565131c91.PNG)

**Comment by aimanhafeez04** [comment]
my database is created successfully in Pg Admin 
![pg admin database](https://user-images.githubusercontent.com/31538556/81558628-9fecac00-93ab-11ea-98a9-fef4c4523a6d.PNG)
it is compulsory to connect from the vs code as well?

**Comment by mtxr** [comment]
Can you try the latest version of the extension (v0.22)? This message error is from PostgreSQL, so somehow the password wasn't being passed to the connection request. Please re-open if you still have problems with this.
