### ISSUE TITLE
hanaOptions not suggested in JSON settings

### ISSUE THREAD

**Issue by alumni** [mtxr/vscode-sqltools#561]
**Describe the bug**
When adding a new connection with `"dialect": "SAPHana"`, additional options can be specified using the `hanaOptions` attribute: 

```
            "hanaOptions": {
                "encrypt": true,
            }
```
However, `hanaOptions` is not suggested by vscode.

**Expected behavior**
The `hanaOptions` property should be suggested, with the following options:
https://help.sap.com/viewer/0eec0d68141541d1b07893a39944924e/2.0.03/en-US/4fe9978ebac44f35b9369ef5a4a26f4c.html

**Comment by mtxr** [comment]
That's normal, we don't have all the driver options there. But don't worry, that will be fixed on new driver releases now since that will be maintained by the community and as different extensions, so this issue is invalid now
