### ISSUE TITLE
Can't connect to remote Oracle server: ORA-24408: could not generate unique server group name

### ISSUE THREAD

**Issue by u84six** [mtxr/vscode-sqltools#562]
**Describe the bug**
After following the Oracle client installation for macOS here: [https://www.oracle.com/database/technologies/instant-client/macos-intel-x86-downloads.html](url)
followed steps to Install 12.1 client, I'm getting the error "Error opening connection ORA-24408: could not generate unique server group name". This does seem like it's specific to Oracle client for macOS, but all the Google hits point to the issue being a local host problem. But I'm trying to connect to remote Oracle database, not one running on my local machine, so the fix doesn't make sense.

**To Reproduce**
1. On macOS, go to the link (I posted above) and download/install macOS client 12.1 x64 (follow instructions)
2. Enabled "node native"
3. In vscode, go to SQLTools New Connection, select Oracle and enter connection information (I verified this all works in other tools, for example dBeaver).
4. Click Connect and see error: "ORA-24408: could not generate unique server group name"

**Expected behavior**
I should be able to connect to the remote server (works in dBeaver)

**Desktop (please complete the following information):**
 - SQLTools Version 0.21.7
 - VSCode Version: 1.45.0
 - Driver Used/Version: Oracle CE
 - OS: macOS

**Comment by mtxr** [comment]
Not supported within this repository anymore.
