### ISSUE TITLE
Cannot connect to Oracledb

### ISSUE THREAD

**Issue by Talib07** [mtxr/vscode-sqltools#563]
**Describe the bug**
Connection of OracleDb fails with error message : "Failed to install dependencies for undefined: Request DependencyInstaller/install failed with message:Nothing to install for undefined.Request is invalid"

**To Reproduce**
1. Go to 'Activity bar and click on SQL tools extension icon'
2. Click on 'Add new connection'
3. Enter all the details of the connection settings
4. Click on "TEST CONNECTION"

**Expected behavior**
Should get connected to the database on clicking "TEST CONNECTION"

**Screenshots**
![errorSS](https://user-images.githubusercontent.com/43445227/81676460-7d22cc00-946d-11ea-8ce6-9ec274e0aa84.jpg)

**Desktop (please complete the following information):**
 - SQLTools Version : 0.21.7
 - VSCode Version: 1.45.0
 - Driver Used/Version: Oracle 
 - OS: Windows_NT x64 10.0.18362
 - Node.js: 12.8.1
 - V8: 7.8.279.23-electron.0

**Additional context**

**Comment by isaacwhittaker** [comment]
I also have the same error while attempting to set up a new oracledb connection.

Windows 10, Node version 12.16.3, VSCode version 1.45.0, SQLTools version 0.21.7.

Here are the outputs from my logs **SQLTools**:

```
DEBUG: Settings updated!
INFO: Executing SQLTools.getConnectionStatus
INFO: Executing SQLTools.openAddConnectionScreen
INFO: Executing SQLTools.testConnection
INFO: Executing SQLTools.showOutputChannel

```

and **SQLTools Language Server**:

```
===============================
SQLTools Server started!
Using node runtime?: true
ExecPath: C:\Program Files\nodejs\node.exe
===============================

Request connection/GetConnectionsRequest received
Request connection/GetConnectionPasswordRequest received
Request connection/TestConnectionRequest received
Request DependencyInstaller/install received
Dependency manage settings:
{
  "packageManager": "npm",
  "installArgs": [
    "install"
  ],
  "runScriptArgs": [
    "run"
  ],
  "autoAccept": false
}
Nothing to install for undefined. Request is invalid.
```

**Comment by mtxr** [comment]
Not supported within this repository anymore.
