### ISSUE TITLE
PostgresSQL - column with same name gets overridden by last column's queried value

### ISSUE THREAD

**Issue by ksdaftari** [mtxr/vscode-sqltools#569]
**Describe the bug**
as was using driver = postgresql, when doing table join and querying with columns from both tables that happen to have same name would have those same named columns be same data (previous columns being overriden to last column queried with same name's data)

**To Reproduce**
```sql
select  country.name,
        tableA.code,
        tableA.name,
        tableB.name
from data.tableA
join data.tableB
on tableB_id= tableB.id 
```

would have both "name" columns with data from tableB, similarly if 

```sql 
select  country.name,
        tableA.code,
        tableA.name,
        tableB.name,
        tableA.name
from data.tableA
join data.tableB
on tableB_id= tableB.id 
```

would all "name" columns with data from tableA

**Desktop (please complete the following information):**
 - SQLTools Version 0.21.7
 - Driver Used/Version:  PostgreSQL 9
 - OS: Windows

**Comment by mtxr** [comment]
This was fixed on new versions. Closing
