### ISSUE TITLE
Connecting with Oracle Connection String

### ISSUE THREAD

**Issue by WaylonWalker** [mtxr/vscode-sqltools#574]
**Describe the bug**
I am trying to connect to an oracle database, and unable to do so.  I have installed the node package `oracledb` and have had success connecting using the connection string method, but when I try with SQLtools I get an error `Error opening connection ORA-24415: Missing or null username.`

**To Reproduce**
1. control-shift-p
2. Go to 'SQLTools Management: Add new connection'
3. Click on 'OracleDB (Node Native)'
4. insert connection name
5. switch connection method to `connection string`
6. paste in constr
   * I tried pasting the constr object straight in
   * I tried with and without each of user and password fields
   * I tried changing user to username
   * I tried just the connectString field by itself wrapped in quotes and not

 **working script**

Running this in node works.

``` javascript
const oracledb = require('oracledb');


const constr = {
    user: "<my-user>",
    password: "<my-password>",
    connectString: "<my-connect-string>"
}
async function run() {
    const connection = await oracledb.getConnection(constr)

    const result = await connection.execute(`select * from <my-table>`)

    console.log(result.rows)

}
run()
```
**Expected behavior**
I would expect the connection string passed into `oracledb.getConnection` to work in sqltools

**Screenshots**

![image](https://user-images.githubusercontent.com/22648375/82684475-4476b580-9c18-11ea-9ef0-09c7939d37a2.png)

**Desktop (please complete the following information):**
 - SQLTools Version v0.21.7
 - VSCode Version: v1.45.1
 - Driver Used/Version: OracleDB (Node Native)
 - OS: Windows (wsl)

**Comment by WaylonWalker** [comment]
I was able to resolve this issue by opening my .vscode settings, add the `username` manually, removed `server` and `port`. And got a successful connection.

Username should be added to the UI, and server/port should be removed in connectionstring mode.

**Comment by mtxr** [comment]
Not supported within this repository anymore.
