### ISSUE TITLE
Connections & others lost in Activity bar

### ISSUE THREAD

**Issue by gioridu** [mtxr/vscode-sqltools#575]
All the SQLTOOL options in the Activity bar are not showing 

This just stops work this week. Not sure if is due to an update from your side or from Visual Studio 
I tried to use a previous version for SQLTool but the issue persists. 
Only when I use the "Connect" button on the Status Bar shows the connections list in the popup in the middle of the screen.
But I'm unable to explore the database and the tables.

Expected behavior
Show the Connections and the tables.  

Screenshots
![Annotation 2020-05-22 191430](https://user-images.githubusercontent.com/10067007/82717425-9859bc80-9c61-11ea-8847-5c77e8a397ba.png)

Desktop:
 - SQLTools Version v0.21.7
 - VSCode Version: 1.46.0-insider
 - Driver Used/Version: PostgreSQL
 - OS: Windows,

**Comment by mtxr** [comment]
this is fixed on branch `lazy-tree`. Although, for now v0.21.x Supports only VSCode 1.45 or older. v0.22 and newer will have this issue fixed

**Comment by mantcz** [comment]
I am afraid this is happening to me too. Few days ago it was still there though, so something recent. 

Desktop:

SQLTools Version v0.23.0
VSCode Version: Version: 1.60.2
Version: 1.60.2
Commit: 7f6ab5485bbc008386c4386d08766667e155244e
Date: 2021-09-22T11:59:27.195Z
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0

Driver Used/Version: PostgreSQL
OS: MacOS BigSur

**Comment by mantcz** [comment]
Interesting, it looks like `sqltools` ended up inside `Run and debug` section.

<img width="529" alt="Screenshot 2021-10-01 at 23 37 33" src="https://user-images.githubusercontent.com/43110249/135693242-2d7b01c1-700c-4be9-8b75-4a278405c21a.png">
