### ISSUE TITLE
Can't connect to Postgresql with the option sqltools.useNodeRuntime enabled

### ISSUE THREAD

**Issue by DarkPerl** [mtxr/vscode-sqltools#584]
I can not establish a connection with the option enabled:
"sqltools.useNodeRuntime" : true
Hangs on the connection stage
With the option disabled, everything works well 
"sqltools.useNodeRuntime" : false

 - SQLTools v0.21.8
 - VSCode v1.45.1
- Node.js v12.8.1
 - PostgreSQL v12.3
 - OS: Windows_NT x64 10

**Comment by mtxr** [comment]
Can you provide some logs?

**Comment by DarkPerl** [comment]
> Can you provide some logs?

Yes I can.
Which ones are needed?
Where to see them?

**Comment by DarkPerl** [comment]
['ext:lc:info'] LanguageClient ready
['ext:main:info'] EXECUTING => sqltools.getConnections
['ext:main:info'] EXECUTING => sqltools.selectConnection
['ext:main:info'] EXECUTING => sqltools.getConnections
['ext:main:info'] EXECUTING => sqltools.getConnections
['ext:main:info'] EXECUTING => sqltools.refreshTree
['ext:main:info'] EXECUTING => sqltools.getConnections
['ext:main:info'] EXECUTING => sqltools.getChildrenForTreeItem

Endless cycle

**Comment by DarkPerl** [comment]
"SQLTools" Language Server
--------------------------------
['ls:info'] "SQLTools" Server started!
===============================
Using node runtime?: true
ExecPath: C:\nodejs\node.exe
===============================
['ls:ls-context:register-driver'] Driver mssql registered!
['ls:ls-context:register-driver'] Driver mysql registered!
['ls:ls-context:register-driver'] Driver mariadb registered!
['ls:ls-context:register-driver'] Driver postgresql registered!
['ls:ls-context:register-driver'] Driver aws redshift registered!
['ls:ls-context:register-driver'] Driver sqlite registered!
['ls:cache:query-results:info'] DELETE keys starting with [postgresql_connection|PostgreSQL|localhost|postgresql_test_db]...
['ls:cache:query-results:info'] DELETE keys starting with [postgresql_connection|PostgreSQL|localhost|postgresql_test_db] completed!
['ls:cache:manager:info'] DELETE keys starting with [postgresql_connection|PostgreSQL|localhost|postgresql_test_db]...
['ls:cache:manager:info'] DELETE keys starting with [postgresql_connection|PostgreSQL|localhost|postgresql_test_db] completed!

**Comment by DarkPerl** [comment]
![screenshot_pgconnection](https://user-images.githubusercontent.com/61414535/83323344-d446e000-a266-11ea-9917-22c7078569e3.jpg)

**Comment by mtxr** [comment]
can you try again latest version?

**Comment by pojntfx** [comment]
I can confirm this with on a fresh macOS & VSCode installation.

**Comment by mtxr** [comment]
If you all are using v0.21.x you should see 2 outputpanels, SQLTools and SQLTools language server.
If you are using v0.22.x all logs are in the same panel, named SQLTools. Can you guys provide more info about the versions you are using? and if it is v0.21, please share the logs of the language server, but I recommend upgrading as soon as possible

**Comment by Soren-Knudsen** [comment]
SQLTools - 0.22.6
SQLTools PostgreSQL/Redshift Driver - 0.0.4

```
['ext:error-handler'] Error opening connection Request connection/ConnectRequest failed unexpectedly without providing any details.
['ext:error-handler:verbose'] ResponseError: Request connection/ConnectRequest failed unexpectedly without providing any details.
    at /Users/sk/.vscode/extensions/mtxr.sqltools-0.22.6/extension.js:16:111705
    at /Users/sk/.vscode/extensions/mtxr.sqltools-0.22.6/extension.js:16:112112
    at Immediate.<anonymous> (/Users/sk/.vscode/extensions/mtxr.sqltools-0.22.6/extension.js:16:112654)
    at processImmediate (internal/timers.js:439:21)
    at process.topLevelDomainCallback (domain.js:131:23) {
  code: -32603,
  data: undefined
}
['ext:main:info'] EXECUTING => sqltools.selectConnection
['ext:main:info'] EXECUTING => sqltools.getConnections
['ext:main:info'] EXECUTING => sqltools.getConnections
['ext:main:info'] EXECUTING => sqltools.getConnections
['ext:main:info'] EXECUTING => sqltools.getConnections
['ext:main:info'] EXECUTING => sqltools.getConnections
['ext:main:info'] EXECUTING => sqltools.getConnections
['ext:main:info'] EXECUTING => sqltools.getConnections
['ext:main:info'] EXECUTING => sqltools.showOutputChannel
```

**Comment by JunkMyFunk** [comment]
I'm having the same issue trying to connect to Redshift. All working fine before latest update, now it just hangs on connecting. 

MacOS 10.14.6
SQLTools - 0.22.6
SQLTools PostgreSQL/Redshift Driver - 0.0.4

I have tried to disable `useNodeRuntime` but it doesn't seem to have any effect. 

```
['ls:info'] SQLTools Server started!
===============================
Using node runtime?: true
ExecPath: /usr/local/Cellar/node/14.3.0/bin/node
===============================
['ext:lc:info'] LanguageClient ready
namespaces set to  *,-babel*,-*:debug,-*:*:debug,-*:*:*:debug,-*:*:*:*:debug,-*:*:*:*:*:debug
['ls:info'] request to register plugin: "/Users/si/.vscode/extensions/mtxr.sqltools-driver-pg-0.0.4/out/ls/plugin.js"
['ls:ls-context:register-driver'] Driver postgresql registered!
['ls:ls-context:register-driver'] Driver aws redshift registered!
['ext:main:info'] EXECUTING => sqltools.getConnections
['ext:main:info'] EXECUTING => sqltools.selectConnection
['ext:main:info'] EXECUTING => sqltools.getConnections
['ext:main:info'] EXECUTING => sqltools.getConnections
['ls:cache:query-results:info'] DELETE keys starting with [SS Analytics Redshift|AWS Redshift|xxx|transactional]...
['ls:cache:query-results:info'] DELETE keys starting with [SS Analytics Redshift|AWS Redshift|xxx|transactional] completed!
['ls:cache:manager:info'] DELETE keys starting with [SS Analytics Redshift|AWS Redshift|xxx|transactional]...
['ls:cache:manager:info'] DELETE keys starting with [SS Analytics Redshift|AWS Redshift|xxx|transactional] completed!
['ext:main:info'] EXECUTING => sqltools.selectConnection
['ext:main:info'] EXECUTING => sqltools.getConnections
['ext:main:info'] EXECUTING => sqltools.getConnections
['ext:main:info'] EXECUTING => sqltools.getConnections
['ext:main:info'] EXECUTING => sqltools.getConnections
['ext:main:info'] EXECUTING => sqltools.getConnections
['ext:main:info'] EXECUTING => sqltools.getConnections
['ext:main:info'] EXECUTING => sqltools.getChildrenForTreeItem
```

**Comment by Dzejkop** [comment]
I'm also getting this bug

Ubuntu 18.04.4 LTS
VSCode 1.46.0-insider
SQLTools 0.22.6
SQLTools PostgreSQL/Redshift Driver 0.0.4

When trying to connect:
```
['ext:main:info'] EXECUTING => sqltools.selectConnection
['ext:main:info'] EXECUTING => sqltools.getConnections
['ext:main:info'] EXECUTING => sqltools.getConnections
['ls:cache:query-results:info'] DELETE keys starting with [Mercures Root|PostgreSQL|localhost|mercures]...
['ls:cache:query-results:info'] DELETE keys starting with [Mercures Root|PostgreSQL|localhost|mercures] completed!
['ls:cache:manager:info'] DELETE keys starting with [Mercures Root|PostgreSQL|localhost|mercures]...
['ls:cache:manager:info'] DELETE keys starting with [Mercures Root|PostgreSQL|localhost|mercures] completed!
```

When testing connection
```
['ext:main:info'] EXECUTING => sqltools.testConnection
```

Setting `"sqltools.useNodeRuntime"` to `false` seems to have fixed the issue but I'm getting, this notification when I'm connecting to the db

![image](https://user-images.githubusercontent.com/5088647/84023856-25528480-a989-11ea-9828-410f8c1b3869.png)
