### ISSUE TITLE
New driver integration - Adapt existing drivers

### ISSUE THREAD

**Issue by mtxr** [mtxr/vscode-sqltools#586]
Hi @EpicEric, @snyang, @mickeypearce, @ariel-bentu.

Folks, I need your help. I've changed the way we integrate drivers so we can grow without having all drivers bundled with the core extension.

I'm taking advantage of VSCode export extension api feature to allow us to create extensions that can integrate with SQLTools. Now you should be able to publish the drivers by yourselves for example.

That said, can you re-create the drivers and publish extensions for those drivers?

I've updated the docs with some information about it, but the code has some comments as well, also we have for drivers as examples.

Docs: https://vscode-sqltools.mteixeira.dev/contributing/support-new-drivers
SQLite: https://github.com/mtxr/vscode-sqltools/tree/master/packages/driver.sqlite
MSSQL: https://github.com/mtxr/vscode-sqltools/tree/master/packages/driver.mssql
PostgreSQL: https://github.com/mtxr/vscode-sqltools/tree/master/packages/driver.pg
MySQL: https://github.com/mtxr/vscode-sqltools/tree/master/packages/driver.mysql

The main idea behind this new release was to have a lazy-tree implementation and some enhancements to completions. Still in the very beginning, but now we should be able to move faster with the features and the integrations.

Feedbacks are welcome.

Let me know if you guys can do those changes

**Comment by ariel-bentu** [comment]
Hi Metheus,
I started porting the code of SAP HANA. The main time consuming task would
be to get the legal aspects to publish to vscode marketplace. meanwhile I
started the port.
I noticed that the generated project does not compile unless I add 4
dev-dependencies:
npm install @types/node --save-dev
npm install @types/jest --save-dev
npm install @types/react-native --save-dev
npm install vscode-languageclient --save-dev

Now that it compiles, it outputs to .../out/src/ls the extension.js and you
look for it in out/extension.js -> any idea what to change to make it load?
Also, At this point the old way still works? so how do I test the new way
while the old way for SAP HANA is still in?
Thanks,
Ariel

**Comment by mtxr** [comment]
@ariel-bentu can you re-do the process? I've fixed that already, you should be good to good now with [generator-sqltools-driver@v0.1.2](https://www.npmjs.com/package/generator-sqltools-driver)

But answering your question, this line is the one that fixed the output issue: https://github.com/mtxr/vscode-sqltools/commit/1410daed8b3619d02ec3b88f9d606f59941fc9d8#diff-79ecd107e18e7dcff3185949efe506b3R5

If I use import, typescript will consider the src folder as a part of the output filename.

Thank you for the effort to port!

**Comment by stasberkov** [comment]
@EpicEric you did really outstanding job adding support of cassandra 2.x to 0.21 version, please release new driver integration for sqltools 0.22.

**Comment by EpicEric** [comment]
Adapting driver integration seemed non-trivial, and I don't have enough time to work on this at the moment. Any help would be extremely appreciated.

For now I've been using a previous version of SQLTools.

**Comment by mickeypearce** [comment]
I am also busy at the moment but I will dig into ASAP...

**Comment by snyang** [comment]
I will get around to dig into.

**Comment by xgdgsc** [comment]
@EpicEric I saw your working repo on cassandra. How far is it from release?

**Comment by EpicEric** [comment]
@xgdgsc I still don't have enough time to work on it. I can't give any estimates at this point.

**Comment by cfont** [comment]
Is the lack of an Oracle Driver simply just needing a developer to have time to work on it or is it more of a legal/license issue?

**Comment by ElCondor1969** [comment]
Any updates or roadmap for Oracle Driver porting on last version?
Thanks.

**Comment by mtxr** [comment]
@cfont we need a dev. @mickeypearce has been busy, do you want to try?

**Comment by mtxr** [comment]
I'm closing this issue since a couple of months passed. In case anyone need an specific driver, feel free to open a issue targeting just the driver needed.

**Comment by gjsjohnmurray** [comment]
Information about a community-contributed driver for Oracle is now in the table at https://vscode-sqltools.mteixeira.dev/en/drivers/
