### ISSUE TITLE
Correct query throws an error in SQLTools

### ISSUE THREAD

**Issue by dnlw07** [mtxr/vscode-sqltools#587]
**Describe the bug**
Wile trying to execute a query at Oracle DB an error occurs.
The query below is working perfectly fine while executed in SQL Developer.
However the query executed in SQLTools throws the error. I have noticed that the custom `ORDER BY` clause cause the issue.
If query ends with custom order `CASE` statement then then the error occurs.
However if `CASE` statement is first in `ORDER BY` clause then the error does not appear.

Query:
```sql
WITH HCPERM AS (
select '1' AS COST_CENTER_CODE, 'HCPERM' AS SKF_NAME from dual
)

, EHPERM AS (
select '2' AS COST_CENTER_CODE, 'EHPERM' AS SKF_NAME from dual
)

SELECT COST_CENTER_CODE, SKF_NAME FROM (
	SELECT * FROM HCPERM UNION ALL
	SELECT * FROM EHPERM
)
-- ORDER BY CASE SKF_NAME WHEN 'HCPERM' THEN 1 WHEN 'EHPERM' THEN 2 WHEN 'HCTEMP' THEN 3 WHEN 'EHTEMP' THEN 4 WHEN 'HCCONT' THEN 5 ELSE 6 END, COST_CENTER_CODE -- working fine
ORDER BY COST_CENTER_CODE, CASE SKF_NAME WHEN 'HCPERM' THEN 1 WHEN 'EHPERM' THEN 2 WHEN 'HCTEMP' THEN 3 WHEN 'EHTEMP' THEN 4 WHEN 'HCCONT' THEN 5 ELSE 6 END; -- cause an error: ORA-00933: SQL command not properly ended
```

Error: 
`ORA-00933: SQL command not properly ended`

**To Reproduce**
Execute query using SQLTools

**Desktop (please complete the following information):**
 - SQLTools Version v0.21
 - VSCode Version: 1.41
 - Driver Used/Version: Oracle CE
 - OS: Windows

**Additional context**

**Comment by mtxr** [comment]
@mickeypearce any ideas on this?

**Comment by mickeypearce** [comment]
Did you tried removing ";" at the end?

**Comment by dnlw07** [comment]
when I remove ";" the query executes fine.
however its a workaround not to solution.

**Comment by mtxr** [comment]
Not supported within this repository anymore.
