### ISSUE TITLE
Result pane disappears after applying regex filter and resizing a column

### ISSUE THREAD

**Issue by dnlw07** [mtxr/vscode-sqltools#588]
**Describe the bug**
Result pane disappears after applying regex filter and resizing a column

**To Reproduce**
1. Execute a query
2. Switch filter to Regex
3. Apply any regex pattern as a filter
4. Resize column

**Screenshots**
Change filter type to regex:
![screenshot 344](https://user-images.githubusercontent.com/23562689/83248333-35a67a80-a1a5-11ea-84d9-7f09ce9a9eeb.jpg)

Apply a regex pattern:
![screenshot 347](https://user-images.githubusercontent.com/23562689/83248463-625a9200-a1a5-11ea-81da-18037dd93560.jpg)

Try to resize the column:
![screenshot 345](https://user-images.githubusercontent.com/23562689/83248615-9fbf1f80-a1a5-11ea-9c1d-9e8cac99b314.jpg)

Result:
![screenshot 346](https://user-images.githubusercontent.com/23562689/83248343-38a16b00-a1a5-11ea-93e4-e1eb2d63c6be.jpg)

**Desktop (please complete the following information):**
 - SQLTools Version 0.21
 - VSCode Version: 1.41
 - Driver Used/Version: Oracle CE
 - OS: Windows

**Comment by mtxr** [comment]
I see, totally reproducible. I found I bug in the lib I'm using, @devex/data-grid, I'll try to upgrade to check if it's fixed already otherwise I need to try something else.
