### ISSUE TITLE
How do I use IAM with Redshift?

### ISSUE THREAD

**Issue by triatomo** [mtxr/vscode-sqltools#589]
I have problems connecting to Redshift using IAM authentication through the plugin. In SQLTools documentation the URI can be inserted in Connection String as shown in the picture. I also tried using different varieties of string, e.g. without "jdbc:".

<img width="470" alt="Screenshot 2020-05-29 at 12 08 34" src="https://user-images.githubusercontent.com/47907076/83248747-d5fc9f00-a1a5-11ea-896f-b59a911850e5.png">

This is what I was trying to follow https://docs.aws.amazon.com/redshift/latest/mgmt/generating-iam-credentials-configure-jdbc-odbc.html

Could you help me out?

**Comment by mtxr** [comment]
We still do not suppport jdbc connection strings. Just `postgres://`. You need to convert this to username and password based connection. There are some discussion about this on the node driver version we use: https://github.com/brianc/node-postgres/issues/1843 but the connection is possible.
