### ISSUE TITLE
Unable to connect with "Drivers XXXX is not installed"

### ISSUE THREAD

**Issue by ctrlShiftBryan** [mtxr/vscode-sqltools#590]
**Describe the bug**
When I upgrade from 0.21.9 to  0.22.2 
```
['ext:error-handler'] Error opening connection Driver PostgreSQL is not installed
['ext:error-handler:verbose'] [ResponseError: Driver PostgreSQL is not installed
	at /Users/barendt/.vscode/extensions/mtxr.sqltools-0.22.2/extension.js:16:111673
	at /Users/barendt/.vscode/extensions/mtxr.sqltools-0.22.2/extension.js:16:112080
	at Immediate.<anonymous> (/Users/barendt/.vscode/extensions/mtxr.sqltools-0.22.2/extension.js:16:112622)
	at processImmediate (internal/timers.js:439:21)
	at process.topLevelDomainCallback (domain.js:131:23)] {
  code: -1,
  data: { driver: 'PostgreSQL', driverOptions: {} }
}
```
I cannot connect to any postgres databases. 

```
['ext:error-handler'] Error opening connection Driver MySQL is not installed
['ext:error-handler:verbose'] [ResponseError: Driver MySQL is not installed
	at /Users/barendt/.vscode/extensions/mtxr.sqltools-0.22.2/extension.js:16:111673
	at /Users/barendt/.vscode/extensions/mtxr.sqltools-0.22.2/extension.js:16:112080
	at Immediate.<anonymous> (/Users/barendt/.vscode/extensions/mtxr.sqltools-0.22.2/extension.js:16:112622)
	at processImmediate (internal/timers.js:439:21)
	at process.topLevelDomainCallback (domain.js:131:23)] {
  code: -1,
  data: { driver: 'MySQL', driverOptions: {} }
}
```

I also get the same error conencting to MySQL. Downgrading to 0.21.9 fixes the issue.

**To Reproduce**
Simply upgrade and try to connect to any database.

**Expected behavior**
It should allow me to connect to databases.

**Screenshots**

**Desktop (please complete the following information):**
 - SQLTools Version 0.22.2 
 - VSCode Version: 1.45.1
 - Driver Used/Version: PostgreSQL 9 & MySQL 6
 - OS: mac

**Comment by mtxr** [comment]
I'll work to make this message better, but you can use v0.22 and install the driver needed to use it from here: https://marketplace.visualstudio.com/search?term=tag%3Asqltools-driver&target=VSCode&category=All categories&sortBy=Relevance

**Comment by ctrlShiftBryan** [comment]
Thank you

**Comment by stasberkov** [comment]
@mtxr your link allows downloading the following drivers:
![image](https://user-images.githubusercontent.com/4071534/83494441-5a616180-a4c7-11ea-889e-77dbf3f3869c.png)
What about community drivers, e.g. Cassandra driver?

**Comment by jonyhayama** [comment]
Hi I'm having the exact same issue, but installing the drivers didn't solve it...
for some reason, the extension can't find them..

![image](https://user-images.githubusercontent.com/6155323/83509202-7520df80-a4a1-11ea-8f00-502786bfb228.png)

- SQLTools v0.22.3
- SQLTools PostgreSQL/Redshift Driver v0.0.2
- VSCode v1.45.1
- OS: Windows + Ubuntu 20.04 (WSL2)

I rolled back to v0.22.2 and got the same messages as @ctrlShiftBrian. I rolled back another time to v0.21.9 and it fixed the issue...

**Comment by beantowel** [comment]
I found v0.21.9 was the last version not popping this error. And i found some time i can execute the query directly in the *Session.sql file since there are those buttons, but in v0.21.9 i only got the button Detach file from *db.
<img width="334" alt="屏幕快照 2020-06-02 下午6 35 35" src="https://user-images.githubusercontent.com/21239094/83510645-ee4f1f80-a4ff-11ea-8e13-fbde7a4b5fc8.png">

**Comment by elibal** [comment]
Hi I'm having the exact same issue, but installing the drivers didn't solve it...

- SQLTools v0.22.3

- SQLTools PostgreSQL/Redshift Driver v0.0.2

- VSCode v1.45.1

- OS: Windows 10

**Comment by ginkgomzd** [comment]
The problem is resolved for me by rolling-back the driver extension.
I only have this problem on sqltools-driver-mysql 0.0.2

**Comment by mtxr** [comment]
> @mtxr your link allows downloading the following drivers:
> ![image](https://user-images.githubusercontent.com/4071534/83494441-5a616180-a4c7-11ea-889e-77dbf3f3869c.png)
> What about community drivers, e.g. Cassandra driver?

@stasberkov they will be releasing this driver soon. Still work in progress. If you need those drivers while they are working on that, you need to roll back to v0.21.x.

You can follow up the integration here: #586

**Comment by r21meghashyam** [comment]
![image](https://user-images.githubusercontent.com/16733388/84039732-5057cb00-a9bf-11ea-9a61-f3c874665716.png)
Need support for OrableDB

**Comment by Zimtir** [comment]
Need support for Cassandra

**Comment by ramonilho** [comment]
Why is this issue closed? It should be reopened.

**Comment by DarkPerl** [comment]
Driver OracleDB is not installed. :-(
What to do ?
