### ISSUE TITLE
Cannot edit connection - Error running command sqltools.openEditConnectionScreen

### ISSUE THREAD

**Issue by guneyozsan** [mtxr/vscode-sqltools#591]
**Describe the bug**
After upgrading to 0.22.2 `right click connection/edit connection` gives the following error:

`Error running command sqltools.openEditConnectionScreen: Cannot read property '_lower' of undefined. This is likely caused by the extension that contributes sqltools.openEditConnectionScreen.`

**To Reproduce**
- Create a connection
- Upgrade
- Right click an existing connection and click edit
- The error appears

**Expected behavior**
Edit connection dialog should appear.

**Desktop (please complete the following information):**
 - SQLTools Version v0.22.2
 - VSCode Version: 1.45.1
 - Driver Used/Version: MariaDB
 - OS: Windows 10

**Additional context**
May be related with https://github.com/mtxr/vscode-sqltools/issues/590

**Comment by guneyozsan** [comment]
It is fixed after installing **SQLTools MySQL/MariaDB**. So probably a similar error message context issue similar to #590.

**Comment by mtxr** [comment]
@guneyozsan yeah, we had this bug

**Comment by mtxr** [comment]
FIxed on recent releases.
