### ISSUE TITLE
sql queries in .sql files get some strange blue hightlight...

### ISSUE THREAD

**Issue by klukiyan** [mtxr/vscode-sqltools#592]
**Describe the bug**
When clicking anywhere in *.sql files, the query gets some strange blue hightlight behind it. 

**To Reproduce**
1. Open any `*.sql` file and click anywhere. (not select, simply put cursor), query gets highlighted with some blue background as on screenshot.
**Expected behavior**
I expect not to see this highlight.

**Screenshots**
![image](https://user-images.githubusercontent.com/27725051/83332733-12f78d00-a29d-11ea-8b6f-cd13f310b7a0.png)

**Desktop (please complete the following information):**
 - SQLTools Version 0.22.2
 - VSCode Version: 1.45.1
 - Driver Used/Version: MySQL, MS SQL
 - OS: Widnows 

**Additional context**
Maybe I accidentally clicked some shortcut that enabled this strange behaviour. Or it came with update. Please help me to get rid of it.

**Comment by sempasha** [comment]
This appears since version 0.22.0. [Installing](https://code.visualstudio.com/updates/v1_30#_install-previous-versions) 0.21.9 makes sql files syntax highlight looks like before.

**Comment by mtxr** [comment]
That was intentional, it highlights the current query under cursor so you can you `Run current query` command with visible feedback of what query extension will execute. But some users didn't like it at all, so I've added a setting to enable/disable that behavior called `sqltools.highlightQuery` so you should be able to remove that if you want now. Starting on v0.22.4

**Comment by adamrybak** [comment]
Thank you for the option, made seeing queries very difficult.

**Comment by mtxr** [comment]
if you want, you can use this VSCode option to set the colors and still use that:
```json
"workbench.colorCustomizations": {
    ...
    "sqltools.currentQueryBg": "#ff0000",
    "sqltools.currentQueryOutline": "#ff0000"
    ...
},
```

**Comment by klukiyan** [comment]
> That was intentional, it highlights the current query under cursor so you can you `Run current query` command with visible feedback of what query extension will execute. But some users didn't like it at all, so I've added a setting to enable/disable that behavior called `sqltools.highlightQuery` so you should be able to remove that if you want now. Starting on v0.22.4

@mtxr 
I did as you suggested and the highlight nicely disappeared. But now there is appearing this clickable helper on the top `Run on active Connection | Select block`
How can I disable them too?

**Comment by StefanBrand** [comment]
Is it possible to turn background colour off, while keeping outline colour? E.g. setting `"sqltools.currentQueryBg": false` does not work.

**Comment by kc-salazar** [comment]
This is closed so I assume the devs consider it a feature rather than an issue. Why is this a default? It is disruptive, not a value-add. Shading all the SQL, making it appear to be actively selected, is nonsensical.

**Comment by gjsjohnmurray** [comment]
@kc-bonilla I guess it is intended to be useful when your document contains multiple statements separated by semicolons.

As detailed above, if you don't want it please change your `sqltools.highlightQuery` setting. Changing the default value of a setting is potentially disruptive for a lot of people.

**Comment by gjsjohnmurray** [comment]
> I did as you suggested and the highlight nicely disappeared. But now there is appearing this clickable helper on the top `Run on active Connection | Select block`
> How can I disable them too?

@klukiyan these are instances of a feature VS Code calls code lenses. If you want to prevent them from appearing in files for which the language has been set to `sql`, edit the `sqltools.codelensLanguages` setting and remove the `sql` entry from its array.

**Update**: after changing this setting, run the `Developer: Reload Window` command to refresh the appearance of open documents.

**Comment by klukiyan** [comment]
@gjsjohnmurray . this thread is dead since long time ago.
I abandoned this extension because after some research I discovered that it's the "guilty" extension that freezes the sql user snippets.
Without it they pop-up immediately, with this extension enabled it thinks for 1-3 seconds even on a very powerful PC.
I couldn't find a solution to it, so I switched to using another extension.

**Comment by gjsjohnmurray** [comment]
@klukiyan thanks for the update.

**Comment by kc-salazar** [comment]
> @kc-bonilla I guess it is intended to be useful when your document contains multiple statements separated by semicolons.
> 
> 
> 
> As detailed above, if you don't want it please change your `sqltools.highlightQuery` setting. Changing the default value of a setting is potentially disruptive for a lot of people.

@gjsjohnmurray doubtful. A default formatting that's nearly indiscernible from text selection? And not just the line or the block, but the entire file. It's not a default in the other 200+ common extensions affecting the editor, which tells me people don't want it.

**Comment by gjsjohnmurray** [comment]
@kc-bonilla I don't understand what you mean by "the entire file". Here's what I get when I click on the word CREATE on line 8:

![image](https://user-images.githubusercontent.com/6726799/184306687-39f6ade0-84e0-4812-b5a3-813c800ec2d1.png)

**Comment by alan-hma** [comment]
![image](https://user-images.githubusercontent.com/97567852/185187555-b1b6a96e-d470-42e2-bd88-e7616cbcc464.png)

When I double-click to select some text, it changes to:

![image](https://user-images.githubusercontent.com/97567852/185191076-b958d8ad-1139-4a1f-97d0-133958671faf.png)


I am uncertain why any user would want their code to constantly look (incorrectly) like selected text as a default.

SSMS does not do this.
Sublime does not do this.
VS2019/2022 does not do this.

Additionally, the proposed fix will break if the user decides to change themes, since you have to hard code the background colors into your settings.

**Comment by gjsjohnmurray** [comment]
@alan-hma did you try the suggestion about turning  the feature off?

![image](https://user-images.githubusercontent.com/6726799/185192405-4ad23caf-409f-4701-a75b-39dab2903f55.png)

I think your code is getting so much highlighted because you don't have semicolons at the end of your statements.

**Comment by alan-hma** [comment]
Sorry @gjsjohnmurray, had to move on and uninstalled the extension.

I'm dealing with a lot of legacy code support, so minimal changes are the goal on my end.

**Comment by adjenks** [comment]
This "feature" was very upsetting.
