### ISSUE TITLE
Column data types in MySQL database are no longer shown

### ISSUE THREAD

**Issue by pspanoudakis** [mtxr/vscode-sqltools#595]
The Data Type of each column is no longer shown after the recent update. Also, after executing a query, all column data types in the result are shown as "abc". Reinstalling the extension and the MySQL driver did not work.

![bug](https://user-images.githubusercontent.com/52857036/83360307-f33d9300-a388-11ea-879c-38624798b9af.png)

![bug3](https://user-images.githubusercontent.com/52857036/83360364-6fd07180-a389-11ea-967f-9303b79f4ea9.PNG)

 - SQLTools Version: 0.22.2
 - VSCode Version: 1.45.1
 - Driver Used: SQLTools MySQL/MariaDB 0.0.1
 - OS: Windows 10

**Comment by mtxr** [comment]
Fixed on recent releases. SQLTools v0.22.4 and MySQL extension v0.0.4

**Comment by Tobeyforce** [comment]
Having the same issue on postgres, no datatype is shown in the result table (on the left panel it does show them though).
![image](https://github.com/mtxr/vscode-sqltools/assets/49819839/d3cebced-e5f8-44da-983b-35c377cc4722)

SQLtools 0.28 & postgresq/cochroach driver v0.5.1

Version: 1.84.0 (user setup)
Commit: d037ac076cee195194f93ce6fe2bdfe2969cc82d
Date: 2023-11-01T11:29:04.398Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621
