### ISSUE TITLE
Option to change character number to line number in error messages

### ISSUE THREAD

**Issue by willcray** [mtxr/vscode-sqltools#598]
I recently received the error message "syntax error at or near "AS" at character 1685.

I'm using VSCode, so I don't know where character 1685 is. It's effectively meaningless to me. I would love to have the line number, rather than the character number in the error message.

Let me know your thoughts, or if you see a way I can change something to be able to identify where my errors exist.

Thanks!

**Comment by mtxr** [comment]
HI @willcray ,

Unfortunately, I won't be doing this. This is a standard for PG clients and it was previously added to match the part of the existing behavior of pgsql.

If you want, you can know the char position using this extension https://marketplace.visualstudio.com/items?itemName=kyrcha.character-position.

Thanks
