### ISSUE TITLE
Cannot find type definition file after generating new driver... 

### ISSUE THREAD

**Issue by BNMeier** [mtxr/vscode-sqltools#599]
**Describe the bug**
I am getting multiple errors after trying to debug a newly generated driver using the driver generator. The errors occur in most TypeScript files. An example is in: node_modules\@sqltools\base-driver\dist\lib\require.d.ts

The errors are:
Cannot find type definition file for 'node'.
Cannot find type definition file for 'jest'.
Cannot find type definition file for 'react-native'.

**To Reproduce**
1. Run: npm install -g yo
2. run: npm install -g generator-sqltools-driver
3. Fill-in information the generator asks for like name
4. Run debugger

**Expected behavior**
No errors and debugging to begin

**Screenshots**
![2020-06-01_13-10-38](https://user-images.githubusercontent.com/64930870/83450010-5a029100-a409-11ea-8423-a436204aa35d.jpg)

**Desktop (please complete the following information):**
 - SQLTools Version 0.22.2
 - VSCode Version: 1.45.1
 - Driver Used/Version: New Driver
 - OS: Windows 10

**Comment by mtxr** [comment]
@BNMeier it's fixed. I've just released new packages. Please let me know how it goes.
