### ISSUE TITLE
Server Requires Encryption error

### ISSUE THREAD

**Issue by WilGatlin** [mtxr/vscode-sqltools#60]
> This is a guideline to help us to understand SQLTools Issues. 
> 
> You don't need to stick to this, but please try to guide us to reproduce the errors or understand your feature requests.

### Issue Type

* [ ] Feature Request
* [x ] Bugfix/Errors
* [ ] Questions
* [ ] Other

### Prerequisites (For bugfixes)

* [x ] Are you running the latest version?
* [x ] Did you check the logs?
* [x ] Did you check the Setup?

### Description

[Description of the bug or feature]

Followed through with the setup procedure and experimented with different types of set ups, always terminating in this error: "Error Selecting connection" and "Server Requires encryption, set 'encrypt' to true." 

Of course, added encrypt option and set to true with no success. 

### Steps to Reproduce (For bugfixes)

1. [First Step]
Follow Connection Setup for MSSQL
2. [Second Step]
Connect to DB (ask for password or dont)
3. [Third Step]
Encryption Error

**Expected behavior:** [What you expected to happen]

Should be able to connect at this point and fill out side bar. 

**Actual behavior:** [What actually happened]

Server does show its connected on bottom status bar but log errors show it is not and side bar is not filled out. 

### Versions

- *Version*: v0.11.4
- *OS*:  macOS Sierra
- *SGDB*: MSSQL

You can get this information from executing `SQLTools: Version` from VSCode `Quick Open`.

**Comment by mtxr** [comment]
Fixed. Will be release soon!
