### ISSUE TITLE
Driver not found but installed

### ISSUE THREAD

**Issue by PapsOu** [mtxr/vscode-sqltools#600]
**Describe the bug**
On a mysql connection, I have installed the mysql driver from the vscode marketplace, but, after a reboot, the driver is not recognized.

**To Reproduce**
1 - Install the driver with the new way
2 - Reboot your computer
3 - Try connect to existing mysql connection
4 - The popup message `Driver MySQL is not installed.` is shown

**Expected behavior**
The driver should be recognized even after a reboot

**Screenshots**
![image](https://user-images.githubusercontent.com/5792207/83524629-29435a00-a4e4-11ea-85b3-6a6603b96081.png)
![image](https://user-images.githubusercontent.com/5792207/83524694-3eb88400-a4e4-11ea-9f29-e8061e474c1b.png)

**Desktop:**
```
Version : 1.45.1
Commit : 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date : 2020-05-14T08:27:22.494Z
Electron : 7.2.4
Chrome : 78.0.3904.130
Node.js : 12.8.1
V8 : 7.8.279.23-electron.0
OS : Linux x64 5.6.14-300.fc32.x86_64
```

**Comment by antherkiv** [comment]
I have exact the same issue 
![image](https://user-images.githubusercontent.com/11079619/83528366-a2c05580-a4ae-11ea-8599-c0a0ad712f54.png)

Ubuntu 18.04 (updated)

**Comment by Fmstrat** [comment]
Same thing, v0.22.3 introduces this with postgres even with the driver installed.

**Comment by Fmstrat** [comment]
For Postgres, I had to roll back both the SQLTools extension and the postgres driver to the version from 4 days ago.

**Comment by DarkPerl** [comment]
The exact same problem.
The driver does not work.
MySQL, Postgresql, Oracle, SQLite.
He does not see them.
---------
SQLTools 0.22.3
---------
Version: 1.45.1 (user setup)
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08: 27: 35.169Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by timsolov** [comment]
Same problem: SQLTools v0.22.3, MysqlDriver 0.0.2

Also MysqlDriver v0.0.1 staill working fine.

**Comment by n0vice** [comment]
Same problem: PostgreSQL/Redshift Driver 0.0.2
SQLTools 0.22.3
Ubuntu 20.04 LTS (tried with vscode installed from both snapcraft and MS store)

**Comment by bSolt** [comment]
@Fmstrat How do I roll back the postgres driver version exactly?

**Comment by bSolt** [comment]
Also Same Problem: 
- SQLTools v0.22.3
- PostgreSQL/Redshift Driver 0.0.2

``` 
    Virtualization: vmware
  Operating System: CentOS Linux 7 (Core)
       CPE OS Name: cpe:/o:centos:centos:7
            Kernel: Linux 3.10.0-957.21.3.el7.x86_64
      Architecture: x86-64
```

**Comment by ihenry** [comment]
> @Fmstrat How do I roll back the postgres driver version exactly?

I had to role back the SQLTools extension 0.21.7 works for me.  You can right click on the extension and find the older versions there.

**Comment by samthesuperhero** [comment]
> > @Fmstrat How do I roll back the postgres driver version exactly?
> 
> I had to role back the SQLTools extension 0.21.7 works for me. You can right click on the extension and find the older versions there.

Yes, this works!

**Comment by PapsOu** [comment]
It seem to work now, Thanks @mtxr !
