### ISSUE TITLE
needToInstallDependencies is missing

### ISSUE THREAD

**Issue by BNMeier** [mtxr/vscode-sqltools#601]
**Describe the bug**
Since the release last night for the other issue I reported in the new driver there seems to be another bug that popped up. In the driver.ts file there is a line for installing dependencies (this.needToInstallDependencies && await this.needToInstallDependencies();) This now throws an error when compiling a brand new driver. because it no longer exists. It looks to me like it used to exist in the base-driver.

**To Reproduce**
1. Compile a fresh driver

**Expected behavior**
Dependencies to be installed installed

**Screenshots**
![2020-06-02_7-54-35](https://user-images.githubusercontent.com/64930870/83535099-76a0d680-a4a6-11ea-8d57-fb14fbb3c0fd.jpg)

**Desktop (please complete the following information):**
 - SQLTools Version 0.22.3
 - VSCode Version: 1.45.1
 - Driver Used/Version: New Driver
 - OS: Windows 10

**Additional context**

**Comment by mtxr** [comment]
You can just remove this line. I've moved this checking to the upper level to make it simpler.

See: https://github.com/mtxr/vscode-sqltools/blob/master/packages/language-server/connection.ts#L34
