### ISSUE TITLE
pwa-extensionHost is not supported

### ISSUE THREAD

**Issue by BNMeier** [mtxr/vscode-sqltools#602]
**Describe the bug**
After creating a fresh driver and running the debugger a Visual Studio Code error is thrown:
"Configured debug type 'pwa-extensionHost' is not supported.

**To Reproduce**
1. Create new driver
2. Run debug

**Expected behavior**
Debugging starts

**Screenshots**
![2020-06-02_8-14-26](https://user-images.githubusercontent.com/64930870/83537214-1bbcae80-a4a9-11ea-97f4-9619312f6385.jpg)

**Desktop (please complete the following information):**
 - SQLTools Version 0.22.3
 - VSCode Version: 1.45.1
 - Driver Used/Version: New Driver
 - OS: Windows 10

**Comment by mtxr** [comment]
I'll update the launch.json. pwa-extensionHost is an option for an preview version of the node debugger extension. You can use extensionHost only instead.

**Comment by qbtf** [comment]
The documentation still references this deprecated value: https://code.visualstudio.com/api/extension-guides/web-extensions#test-your-web-extension

> Use the pwa-extensionhost launch configuration provided by the New Web Extension generator: [...]
