### ISSUE TITLE
Postgres JSON operators not supported when formatting

### ISSUE THREAD

**Issue by andy-g** [mtxr/vscode-sqltools#605]
**Describe the bug**
Certain special Postgres JSON operators (such as `@>`) aren't handled by the sqltools formatter and cause the query to become invalid, for example:
```sql
SELECT json_col
FROM (
        SELECT '[{"a":"foo"},{"b":"bar"},{"c":"baz"}]' :: jsonb json_col
    ) AS tbl
WHERE json_col @> '[{"c":"baz"}]';
```

is transformed to the below when formatted (space added between `@` & `>`):
```sql
SELECT json_col
FROM (
        SELECT '[{"a":"foo"},{"b":"bar"},{"c":"baz"}]' :: jsonb json_col
    ) AS tbl
WHERE json_col @ > '[{"c":"baz"}]';
```

**To Reproduce**
1. Open a new sql file and paste the following query:  
    ```sql
    SELECT json_col
    FROM (
            SELECT '[{"a":"foo"},{"b":"bar"},{"c":"baz"}]' :: jsonb json_col
        ) AS tbl
    WHERE json_col @> '[{"c":"baz"}]';
    ```
2. Format the document (or simply save if format on save is configured)
3. Attempting to execute the query will now result in an error:
`operator does not exist: jsonb @`

**Expected behavior**
The document should be formatted as usual but any special JSON operators (https://www.postgresql.org/docs/current/functions-json.html) should remain valid, and not be split with a space.

**Desktop:**
 - SQLTools Version: **0.22.4**
 - VSCode Version: **1.45.1**
 - Driver Used/Version: **SQLTools PostgreSQL/Redshift Driver / 0.0.4**
 - OS: **Mac**

**Comment by andy-g** [comment]
That was incredibly fast, thanks so much @mtxr 🙇‍♂️

**Comment by mtxr** [comment]
I'll release this later today, ok?

**Comment by andy-g** [comment]
Absolutely, I was never expecting you to get to this so quickly. Thanks so much, and thanks for a super valuable extension 👍 .
