### ISSUE TITLE
How to connect to LocalDB (Sql Server)?

### ISSUE THREAD

**Issue by gpuma** [mtxr/vscode-sqltools#61]
> This is a guideline to help us to understand SQLTools Issues. 
> 
> You don't need to stick to this, but please try to guide us to reproduce the errors or understand your feature requests.

### Issue Type

* [ ] Feature Request
* [ ] Bugfix/Errors
* [x] Questions
* [ ] Other

### Prerequisites (For bugfixes)

* [x] Are you running the latest version?
* [x] Did you check the logs?
* [x] Did you check the Setup?

### Description
`(Running v0.11.4)`

Hello, how can I connect to a LocalDB SQL server instance? Using the following config gives me a connection error:

```
"sqltools.connections": [
        {
            "name": "MSSQL",
            "server": "127.0.0.1",
            "dialect": "MSSQL",
            "port": 1433,
            "database": "EFGetStarted.AspNetCore.NewDb",
            "username": "sa",
            "askForPassword": false,
            "password": null,
            "connectionTimeout": 30
        }
    ]
```
This database was created using Entity Framework Core, so, AFAIK there's no password or username, at least explicitly. The following connection string works for me if I want to connect using Visual Studio 2017 data tools:

`Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=C:\User\Gus\EFGetStarted.AspNetCore.NewDb.mdf;Integrated Security=True;Connect Timeout=30`

And this is the actual connection string used by EF Core: `@"Server=(localdb)\mssqllocaldb;Database=EFGetStarted.AspNetCore.NewDb;Trusted_Connection=True;ConnectRetryCount=0";`

Thank you for your time.

**Comment by art-ist** [comment]
Looks like you are using tedious to connect to MS SQL? If my impression is correct, you'l have two problems:
- tedious doesen't seem to support Integrated Security (=Trusted_Connection) thus only Sql Logins would work. [see issue 306](https://github.com/tediousjs/tedious/issues/306)
- tedious doesen't seem to support named pipes. [see issue 348](https://github.com/tediousjs/tedious/issues/348)
