### ISSUE TITLE
Postgres connection password prompt should be optional

### ISSUE THREAD

**Issue by ThiefMaster** [mtxr/vscode-sqltools#613]
**Describe the bug**
I'm using a UNIX socket connection to connect to postgres, using peer auth. But when adding the connection I'm still required to enter a password (or tick "ask for password" and then get prompted for one when going to the next step).

**To Reproduce**
Try adding a postgres database connection that does not require a password and don't enter one.

**Expected behavior**
No password prompt, and the password field being optional.

**Desktop (please complete the following information):**
 - SQLTools Version: 0.22.6
 - VSCode Version: 1.46.0-insiders
 - Driver Used/Version: Postgres
 - OS: Windows desktop, Linux remote via SSH

**Comment by mtxr** [comment]
did you try to set `askForPassword` to false and delete prop password? or leave it empty?

**Comment by mtxr** [comment]
Close in favor of #621.
