### ISSUE TITLE
'Driver OracleDB is not installed' since version v22.0 and higher

### ISSUE THREAD

**Issue by dnlw07** [mtxr/vscode-sqltools#617]
**Describe the bug**
After updating SQLTools to v22 I cannot connect to Oracle DB. When I downgrade version to v21.9 then I can normally connect to Oracle DB.

**log taken from Output pane**
['ext:error-handler'] Auto connect failed Driver OracleDB is not installed
['ext:error-handler:verbose'] 'Driver OracleDB is not installed'
['ext:main:info'] EXECUTING => sqltools.showOutputChannel

**To Reproduce**
1. Update extension from v21.9 to v22.*
2. Try to connect to Oracle DB

**Desktop (please complete the following information):**
 - SQLTools Version v0.22.7
 - VSCode Version: 1.45.1
 - Driver Used/Version: Oracle CE
 - OS: Windows

**Comment by mtxr** [comment]
Tracked in #586
