### ISSUE TITLE
Support for JSON-Fields

### ISSUE THREAD

**Issue by SirTori** [mtxr/vscode-sqltools#62]
### Issue Type

* [x] Feature Request
* [ ] Bugfix/Errors
* [ ] Questions
* [ ] Other

### Description

As of version 9.4 (I think) postgresql supports the JSON-Type.
Currently if I query a row with this type the output only displays ```[object Object]```.

Since showing the whole JSON within a table gets unreadable very fast, I suggest the JSON content should at least be available through copy&paste (just like one can copy longer texts from the output even though it's truncated). Also showing a truncated version of the content (just like long texts) could be beneficial.

**Comment by mtxr** [comment]
Fixed. WIll be release soon.
