### ISSUE TITLE
Password via Wizard should be made optional

### ISSUE THREAD

**Issue by brandinarsenault** [mtxr/vscode-sqltools#621]
**Is your feature request related to a problem? Please describe.**
As mentioned in #613 #396 and #150 - passwords via Wizard are still required. Some connections, in particular to localhost, don't require a password, and the "Ask for password" input cannot be empty.

**Describe the solution you'd like**
Remove the requirement to enter a password on the Wizard

**Describe alternatives you've considered**
Creating the connection manually, or entering a dummy password and removing it in the settings after

**Additional context**
In particular, I noticed this with MySQL/MariaDB.

**Comment by mtxr** [comment]
Done already on MSSQL Driver. I'll extend this to other drivers as well
