### ISSUE TITLE
Intellisense code completion not working

### ISSUE THREAD

**Issue by leecolarelli** [mtxr/vscode-sqltools#622]
**Describe the bug**
Sorry if I am incorrect, but should intellisense provide code completion with a connected database? I am trying to get MySQL/MariaDB code completion in php files but cannot.

**To Reproduce**
I have both SQLTools and the MySQL/MariaDB drivers installed.
I have added php to the completionlanguages section in settings (as well as trying codelens and formatting sections).
I have the database i want to use added and connected to.
In a php file I am writing sql but there is no code completion.

**Expected behavior**
I was hoping for code completion for table names, field names etc from the connected database.

**Desktop (please complete the following information):**
 - SQLTools Version 0.22.7
 - VSCode Version: 1.45.1
 - Driver Used/Version: MySQL/MariaDB
 - OS: Windows 10 latest version

**Comment by mtxr** [comment]
There are some changes we need to do now to get that working properly.

MS developed a feature called `embedded languages` for the language servers and I need to adapt that to get it working. So far only SQL files should be getting completions correctly. A new MySQL driver version will be released today fixing some issues.

**Comment by leecolarelli** [comment]
Ok thank you for clarifying! And all the efforts on the plugin!
