### ISSUE TITLE
Postgres: Run query results in blank window

### ISSUE THREAD

**Issue by Fmstrat** [mtxr/vscode-sqltools#624]
**Describe the bug**
When running queries the new tab pops up, however the "loading" spinner never shows and the window remains blank. Postgres shows no signs that the query ran.

Sometimes running the query again 2 or 3 times brings things back. But most of the time VSCode must be restarted.

**To Reproduce**
1. Connect to a postgres DB
2. Type a SELECT query and run it
3. Sometimes the tab is blank

**Expected behavior**
The query to run.

**Screenshots**
![blank](https://user-images.githubusercontent.com/971474/85234532-f18d4b00-b3db-11ea-8443-74340269f92c.png)

**Desktop (please complete the following information):**
 - SQLTools Version [e.g. v0.17.x] v0.22.8
 - VSCode Version: [e.g 1.x.y] 1.46.1
 - Driver Used/Version: [e.g PostgreSQL 9, Oracle CE, SQLite, MySQL 6, Redshift..] Postgres 11.3
 - OS: [e.g. Windows, Linux, Mac] Linux

**Comment by mtxr** [comment]
Do you see any errors on the SQLTools output channel? Also, you can try to check the errors running the command `Developer: Open webview developer tools`. It's built-in on VSCode

**Comment by Fmstrat** [comment]
I did not, but i will try the webview the next time it occurs. I have noticed since reporting that if I wait for say, 15s, then run the query again, it works. So a pattern like this occurs:
- Run query, blank tab opens
- Wait 1s
- Run query, another blank tab opens
- Wait 1s
- Do that over and get a bunch of blank tabs
- Wait 15s
- Run query, results appear

**Comment by Fmstrat** [comment]
From the webview console:
```
Failed to load resource: net::ERR_UNKNOWN_URL_SCHEME
theme.css:1 Failed to load resource: net::ERR_UNKNOWN_URL_SCHEME
vendor.js:1 Failed to load resource: net::ERR_UNKNOWN_URL_SCHEME
commons.js:1 Failed to load resource: net::ERR_UNKNOWN_URL_SCHEME
Results.js:1 Failed to load resource: net::ERR_UNKNOWN_URL_SCHEME
```
This happened by:
- Connect to DB1
- Run query
- Connect to DB2 without disconnecting from DB1
- Run query
- Go back to DB1
- Run query (error)

It does not always happen that way, though, in fact, after restarting VSCode it happened again right away on my first query to DB1.

**Comment by mtxr** [comment]
Apparently we don't need `.with({ scheme: 'vscode-resource' })` anymore.
I see some vscode issues https://github.com/microsoft/vscode/issues/98231 https://github.com/microsoft/vscode/issues/100918 as well also that is not part of the docs anymore https://code.visualstudio.com/api/extension-guides/webview

I will do this later tonight, doesn't seem to be a big change

**Comment by Fmstrat** [comment]
@mtxr Hey! Is this assigned to a version that's live yet? I'm still seeing this issue in 0.22.11.
