### ISSUE TITLE
Long queries with no data responses cause flashing "no data"

### ISSUE THREAD

**Issue by Fmstrat** [mtxr/vscode-sqltools#626]
**Describe the bug**
When running a long query (multiple screens long) where no data is returned, "No data" flashes on the screen repeatedly, as if a scroll bar is going back and forth.

I believe this may be because the title of a tab in VSCode can now be set to default to the first line of copy, and queries get placed in the tab title when the tab opens. For instance, if using a connection titled `my-connection` and running `SELECT NOW();`, the title of the tab would be:
```
my-connection: SELECT NOW();
```
Now picture if `SELECT NOW()` was very, very long.

**To Reproduce**
1. Open a postgres connection (may happen in other drivers)
2. Run a very long query
3. Watch the flash

**Expected behavior**
The title of the tab should be truncated to the first *n* characters of the query.

**Desktop (please complete the following information):**
 - SQLTools Version [e.g. v0.17.x] v0.22.8
 - VSCode Version: [e.g 1.x.y] 1.46.1
 - Driver Used/Version: [e.g PostgreSQL 9, Oracle CE, SQLite, MySQL 6, Redshift..] Postgres 11.3
 - OS: [e.g. Windows, Linux, Mac] Linux

**Comment by mtxr** [comment]
Can you confirm that? v0.22.8 was the one where the "No data" text was removed. So you should not see it at all in this version.
The issue you mentioned lasted till v0.22.7, after that, the message changed to "Query returned 0 rows".

**Comment by Fmstrat** [comment]
I will check on that. I had batched a few errors I was seeing and it's possible the extension updated since seeing them. If that's the case, sorry about that.
