### ISSUE TITLE
Create new driver

### ISSUE THREAD

**Issue by daimor** [mtxr/vscode-sqltools#627]
**Describe the bug**
Just generated new driver with `yo sqltools-driver`
No changes made in the code, run from scratch in debugging mode will cause an error 
```
Error loading plugin InterSystems IRIS Driver Plugin Request ls/RegisterPlugin failed with message: __non_webpack_require__ is not defined
```

**Desktop (please complete the following information):**
 - SQLTools Version 0.22.8
 - VSCode Version:  1.47.0-insider
 - OS: Mac

**Comment by mtxr** [comment]
Can you update the generator to v0.1.3? It was realeased this morning addressing exactly this issue
