### ISSUE TITLE
Some request make result page infinite loading

### ISSUE THREAD

**Issue by MGMehdi** [mtxr/vscode-sqltools#631]
**Describe the bug**
All in the title

**To Reproduce**
- Drop a database or create a new one
- Delete row

**Expected behavior**
A result or something

**Screenshots**
![image](https://user-images.githubusercontent.com/48625769/85563748-f5181080-b62d-11ea-9152-f6f118e7859a.png)

**Desktop (please complete the following information):**
 - Driver Used/Version: mySQL
 - OS: Windows with database in Ubuntu WSL

**Comment by mtxr** [comment]
Are you using VSCode insiders?

**Comment by johndevedu** [comment]
I can confirm. Not Insiders Edition.

 - SQLTools Version: v0.22.9
 - VSCode Version: 1.46.1
 - Driver Used/Version: MySQL v0.0.6
 - OS: Mac OSX

Going to try and debug your extension for the first time @mtxr! If you have any direction for a first time contributor (which module to look at), I'm all ears.

**Comment by mtxr** [comment]
Thanks @johndevedu. You can take a look on the results window to see what's going on using the command `Developer: Open webview develper tools` and also trying on `SQLTools: Show output channel logs`.

Anything you can get from there might help!

**Comment by johndevedu** [comment]
@mtxr nothing to report from the devtools

From the channel logs:
['ext:main:info'] EXECUTING => sqltools.getConnections
['ext:main:info'] EXECUTING => sqltools.getConnections
['ext:main:info'] EXECUTING => sqltools.executeCurrentQuery <=========== SELECT statement shows result table OK
['ext:main:info'] EXECUTING => sqltools.getConnections
['ext:main:info'] EXECUTING => sqltools.getConnections
['ext:main:info'] EXECUTING => sqltools.executeCurrentQuery <=========== UPDATE/DELETE shows spinner
['ext:main:info'] EXECUTING => sqltools.getConnections
['ext:main:info'] EXECUTING => sqltools.getConnections

**Comment by mtxr** [comment]
I could just reproduce it locally. There's a uncaught promise somewhere in the driver.
I expect this fix to be released today/tomorrow

**Comment by johndevedu** [comment]
Seems like you don't need this at this point, but here is the output from devtools when running the extension through Development Host (previously it was from the live production extension version).

![image](https://user-images.githubusercontent.com/5439943/85658756-899f6480-b668-11ea-8b2a-f1f1069de727.png)

**Comment by johndevedu** [comment]
@mtxr as a learning experience (both general extension development and your extension in particular), I wanted to debug this issue. I was able to fire up Launch SQLTools and Attach LS, but breakpoints are not hitting. Is it possible to hit breakpoints running this launch config? 

Basically, I want to place a breakpoint in places like `language-server/connection.ts/query` or` plugins/connection-manager/ext_executeQuery`

Any guidance will be appreciated.

**Comment by MGMehdi** [comment]
@mtxr I'm sorry I didn't answer sooner, I had my final exams and I didn't think about it anymore.
