### ISSUE TITLE
Connection Assistant stuck at Step 1 (Select ur DB driver)

### ISSUE THREAD

**Issue by spareidsubbu** [mtxr/vscode-sqltools#636]
Hi,
I am new to VSCode and trying to set up a connection to Oracle DB and the connection assistant is stuck at Step 1: Select Your Database Driver. I have waited for more than 10 mins but no driver was shown.

The assistant is failing to locate any of the drivers (however few drivers can be searched in vscode market place). I am not sure if we can download driver for oracle as well from market place (if yes, pls let me know how... I couldn't find it in documentation)

Attaching the behaviour for reference.

Thanks
![Peek 2020-06-27 01-00](https://user-images.githubusercontent.com/61294660/85909664-dfb00b80-b812-11ea-9447-e65290218ff3.gif)

**Comment by mtxr** [comment]
Oracle Driver sitll under development. If you want to use it right now, you need to install v0.21.X.

The screen stays in the loading state till we find a driver installed and loaded.
