### ISSUE TITLE
Can not find npm

### ISSUE THREAD

**Issue by louis-bec** [mtxr/vscode-sqltools#638]
I'm using nvm as node version manager. SQLTools does not find npm:

```['ext:error-handler'] Failed to install dependencies for SQLite: Request DependencyInstaller/install failed with message: npm Not found. You need to install npm first to install dependencies. Install it and restart before continue.```

**To Reproduce**
- Add an SQLite connection in vscode
- Try to connect to db
- Message popup at the bottom right of the vscode  `You need to install "sqlite3@4.2.0" to connect to development.`
- Click install button
- An error occurs, see error message above in SQLTools console 

**Expected behavior**
It should use the npm installed by nvm, npm should be found or I can specify the npm/node path in setting.json file.

When I open the vscode, a info will popup at the bottom right `Node runtime not found. Using default as a fallback.` Where does the SQLTools find my node? 

node & npm works fine in terminal.
```
$ which node
{my_home}/.nvm/versions/node/v10.21.0/bin/node
$ which npm
{my_home}/.nvm/versions/node/v10.21.0/bin/npm
```

**Desktop (please complete the following information):**
 - SQLTools Version [v0.22.10]
 - VSCode Version: [1.46.1]
 - OS: [Mac]
 - Driver: 
   - [x] SQLite

**Comment by mtxr** [comment]
You can set the package manager path as seen here: https://vscode-sqltools.mteixeira.dev/settings/dependency-manager#packageManager

We try as much as possible to get it from PATH, but sometimes it is not possible so the fallback is available.

If you want to contribute and help to make it better, any suggestions or PRs are welcome

**Comment by louis-bec** [comment]
Thanks @mtxr, it's now working well on my dev env.

 I'm not sure but it could be a problem of nvm, you can't find a constant path for current in using node/npm. I'm also using rbenv to manage ruby versions, it has a shims folder.

Anyway, thanks for the help!

**Comment by fappelman** [comment]
I had the same problem and fixing the path didn't do the job for me. I got it working (on the Mac) using the following steps. If you are not on a Mac it may still be the right steps, you just have to figure out the paths yourself.

First step is to go to the directory where `vscode-sqltools` stores its dependencies:

```bash
cd
cd 'Library/Application Support/vscode-sqltools'
```
Next make certain that the dependency is in the file `package.json`. My file looks like this:

```json
{
  "dependencies": {
    "sqlite3": "^4.2.0"
  }
}
```

If that is the case (you may have more dependencies, just make certain that the `sqlite` dependency is present) take the following steps:

```sh
rm package-lock.json
rm -rf node_modules
npm i
```
You should be all set now.

Note that I first tried it without removing `package-lock.json`. That showed the underlying problem. I got an error from a tool called `gyp`. This is the most informative line:

```log
gyp: Undefined variable module_name in binding.gyp while trying to load binding.gyp
```

So by removing `package-lock.json` and fully rebuilding`node_modules` I fixed the problem.
