### ISSUE TITLE
Allow to remove connections from explorer

### ISSUE THREAD

**Issue by mtxr** [mtxr/vscode-sqltools#64]
### Issue Type

* [x] Feature Request
* [ ] Bugfix/Errors
* [ ] Questions
* [ ] Other

### Description

I would like to change/update/add connections from Setup Connection screen.

**Comment by aszenz** [comment]
Is there no way to edit/delete a connection right now? If so then then the edit/delete buttons could be added to the sql connection sidebar next to each connection.

**Comment by bfranklyn** [comment]
Where are the connections stored right now? I noticed that even when I uninstall the extension and then reinstall it the previous incorrect connections are still there. Are they stored in a file somewhere in the file system?

**Comment by mtxr** [comment]
It's not released yet.

Next week you will be able to remove it using the right click menu over a connection
Matheus Teixeira

**Comment by mtxr** [comment]
Here is how it will work for it's first version: 
![image](https://user-images.githubusercontent.com/707561/53702437-aebdf300-3de5-11e9-8bb2-9a20d546e209.png)

**Comment by bfranklyn** [comment]
Awesome! 👍
