### ISSUE TITLE
Test Connection indicates connection wouldn't work, but it does

### ISSUE THREAD

**Issue by Dzejkop** [mtxr/vscode-sqltools#640]
After a recent update I cannot connect to a local instance of Postgres DB.

When testing connection I get `The server does not support SSL connections` right above the `Save Connection` button

**Comment by Dzejkop** [comment]
Actually I was wrong, I can connect to the database just fine, it's just that the `Test Connection` indicates I wouldn't be able to

**Comment by paytonrules** [comment]
I am seeing the same problem - but in fact fail to connect. I get nothing but The server does not support SSL connections. Can I set - somewhere - the connection to be non-ssl for this connection?

**Comment by n5ken** [comment]
Same here, just get this error connecting my dev db.

**Comment by Dzejkop** [comment]
Yeah, I'm able to connect using my old connection config. But anything new I create fails.

**Comment by trafium** [comment]
> Yeah, I'm able to connect using my old connection config. But anything new I create fails.
My experience is exactly the same.

**Comment by n5ken** [comment]
Hey guys, here is a workaround for this issue, click "Open settings" at the right bottom corner in SQLTools Settings page, edit the config directly to set:
```
...
"pgOptions": {
    "ssl": false
},
...
```

Reconnect and you will do the trick.

**Comment by Chenwenfeng87** [comment]
Below steps are work for me
1. Open Settings at the right bottom corner in SQLTools Setting to edit setting.json directly by adding 
"pgOptions": {
    "ssl": false
},
2. Open file C:\Users\xxxxxxx\.vscode\extensions\mtxr.sqltools-driver-pg-0.1.0\connection.schema.json, remove "ssl" group under "pgOptions"

Create a new connection and try to connect
