### ISSUE TITLE
Regression: Empty "SQLTools Results" tab after executing query (SQLite)

### ISSUE THREAD

**Issue by tylerbrockett** [mtxr/vscode-sqltools#643]
**Describe the bug**
When I run a query, the results do not show in the "SQLTools Results" tab that comes up. It is a blank screen.

Downgrading to SQLTools 0.22.9 and restarting vscode (window reload doesn't work) fixes the issue.

**To Reproduce**
1. Execute any query

**Expected behavior**
Results to show in the opened tab

**Screenshots**
![image](https://user-images.githubusercontent.com/6251230/86504447-48e0d300-bd6d-11ea-83c6-5df693cf7061.png)

**Desktop (please complete the following information):**
 - SQLTools Version v0.22.10
 - VSCode Version: 1.47.0-insider (user setup)  2020-07-03T10:27:06.804Z
 - OS: Windows 10 20.04
 - Driver: SQLite
 - Database version: SQLite 3.31.1

**Comment by gegutierrezneri** [comment]
I also see this issue with the Postgres Driver

**Comment by mtxr** [comment]
Dup #639
