### ISSUE TITLE
STOP adding debug env

### ISSUE THREAD

**Issue by dreamerblue** [mtxr/vscode-sqltools#644]
**Describe the bug**

Please DO NOT add debug env so that the vscode remote server will be effected by this.

And user's dev progress will output so many useless logs.

For example, when I installed SQLTools in remote server, and start a Node.js debug progress via `npm run dev`, the terminal outputs so many installed dependencies debug logs which are unexpected and noisy.

**To Reproduce**
1. Install `Remote - SSH` ext and open a remote project
1. Open a new terminal window after SQLTools activated
1. Output the process.env.DEBUG in Node.js or run `echo $DEBUG`
1. It outputs `*,-*:debug,-*:*:debug,-*:*:*:debug,-*:*:*:*:debug,-*:*:*:*:*:debug` or `*,-babel*,-*:debug,-*:*:debug,-*:*:*:debug,-*:*:*:*:debug,-*:*:*:*:*:debug`

**Expected behavior**
No debug env added.

**Screenshots**
![screenshot-vscode-remote-debug-env](https://user-images.githubusercontent.com/19774268/83374449-400f8100-a3fe-11ea-8b1c-df100bd0dfb6.png)

**Desktop (please complete the following information):**
 - SQLTools Version 0.22.10
 - VSCode Version: 1.46.1
 - OS: macOS 10.15.5 (local) and Ubuntu 18.04 (remote)
 - Driver: 
   - [ ] PostgreSQL/Redshift
   - [x] MySQL/MariaDB
   - [ ] MSSQL/Azure
   - [ ] SQLite
   - [ ] Other? Which...
 - Database version: [e.g. MySQL v5.6, PostgreSQL vX...]

**Additional context**
Related issue: https://github.com/microsoft/vscode-remote-release/issues/3091

**Comment by mtxr** [comment]
I'll replace `debug` lib by another one. This is not something done intentionally but when I call debug.enable it's setting the env variable..
