### ISSUE TITLE
Adding new connection error

### ISSUE THREAD

**Issue by LuisMnrqz** [mtxr/vscode-sqltools#646]
When I try to add a new connection to try to connect to to my XAMPP, after clicking new connection the new tab appears blank.

**Comment by shaunie2fly** [comment]
I get the same issue.

**Comment by afliw** [comment]
Same here. Can't create new connections after extensions installation.

OS: Windows 10 V2004 (OS Build 19041.329)

**Comment by mtxr** [comment]
Fixed on v0.22.11.
