### ISSUE TITLE
Not able to connect

### ISSUE THREAD

**Issue by Jeordie** [mtxr/vscode-sqltools#65]
> This is a guideline to help us to understand SQLTools Issues. 
> 
> You don't need to stick to this, but please try to guide us to reproduce the errors or understand your feature requests.

### Issue Type

* [ ] Feature Request
* [ ] Bugfix/Errors
* [x] Questions
* [ ] Other

### Prerequisites (For bugfixes)

* [x] Are you running the latest version?
* [x] Did you check the logs?
* [x] Did you check the Setup?

### Description

I'm not able to connect to an MSSQL database. I think the problem is that I have to use a domainname before my username. These are the settings I'm using right now

`"sqltools.connections": [
        {
            "name": "Test2",
            "server": "svr-t-evasql01.otapp.local",
            "dialect": "MSSQL",
            "port": 1433,
            "database": "<dbname>",
            "username": "<domain>\<username>",
            "askForPassword": false,
            "password": null,
            "connectionTimeout": 60
        }
    ]`

I'm getting the following error in the log:
[2018-02-20T08:01:19.][v0.11.4] {"code":"ELOGIN","originalError":{"message":"Login failed for user '<domain>\<username>'.","code":"ELOGIN"},"name":"ConnectionError"}
[2018-02-20T08:01:19.][v0.11.4] ERROR: Error while preparing columns completions
[2018-02-20T08:01:19.][v0.11.4] {"code":"ELOGIN","originalError":{"message":"Login failed for user '<domain>\<username>'.","code":"ELOGIN"},"name":"ConnectionError"}

I'm also using the mssql extension with the following connection settings:

` "mssql.connections": [
        {
            "server": "svr-t-evasql01.otapp.local",
            "database": "<dbname>",
            "authenticationType": "Integrated",
            "profileName": "Test1",
            "password": ""
        }`

**Comment by mtxr** [comment]
Will be fixed together with #60 

MSSQL has some particularities that SQLTools is not handling in this current version.

Thank you for reporting
