### ISSUE TITLE
Unable to establish new connection

### ISSUE THREAD

**Issue by Jesse3692** [mtxr/vscode-sqltools#650]
**Describe the bug**
When I click `Add new connection` to add a new database connection, I get a blank page and do nothing. There have been many attempts to reinstall plugins and vscode, but nothing has worked.

**To Reproduce**

**Expected behavior**
Ability to open a set of pages and add new database connections

**Screenshots**
![image](https://user-images.githubusercontent.com/24291671/87249338-1f245c00-c491-11ea-9279-56e0361c2c72.png)
![image](https://user-images.githubusercontent.com/24291671/87250094-70364f00-c495-11ea-83ac-7b04da38da9c.png)

**Desktop (please complete the following information):**
VScode Version: 1.47.0 (user setup)
Commit: d5e9aa0227e057a60c82568bf31c04730dc15dcd
Date: 2020-07-09T08:02:06.629Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041
 - Driver: 
   - [ ] PostgreSQL/Redshift
   - [ √] MySQL/MariaDB
   - [ ] MSSQL/Azure
   - [ ] SQLite
   - [ ] Other? Which...
 - Database version: [MySQL v5.6]

**Additional context**

**Comment by raoziqiang** [comment]
Me too，I tried and it doesn't work, I get prompted with an empty window and that's it.

**Comment by raoziqiang** [comment]
![捕获](https://user-images.githubusercontent.com/37203457/87671750-703f9300-c7a4-11ea-8fab-f71893c89da2.PNG)

**Comment by Jesse3692** [comment]
> Me too，I tried and it doesn't work, I get prompted with an empty window and that's it.

Try The old version 0.22.9

**Comment by raoziqiang** [comment]
Is it a sqltools of plugin?

**Comment by Jesse3692** [comment]
Bingo！！
![image](https://user-images.githubusercontent.com/24291671/87877946-d1b96900-ca13-11ea-8019-c8d8a61f85b3.png)

**Comment by mtxr** [comment]
Dup #639

**Comment by mtxr** [comment]
Fixed on v0.22.11.
