### ISSUE TITLE
Certificate has expired

### ISSUE THREAD

**Issue by mosesontheweb** [mtxr/vscode-sqltools#654]
**Describe the bug**
I installed SQL Tools for testing it against some databases I usually manage with DBeaver. Every requirement is installed, but the connection to ElephantSQL fails with the message "certificate has expired", regardless which action I try - test connection, show tables, etc. For some reason the connection seems to be established, but I can't do a thing with it. I tried the same credentials with DBeaver, works like a charme.

I cannot determine, if this depends on the PostgreSQL driver implemention or a problem in error handling.

Error message when creating a connection:
`Error opening connection Request connection/ConnectRequest failed unexpectedly without providing any details.`

Here's some output in VSCode:
```
['ext:error-handler'] Error opening connection Request connection/ConnectRequest failed unexpectedly without providing any details.
['ext:error-handler:verbose'] [ResponseError: Request connection/ConnectRequest failed unexpectedly without providing any details.
	at /Users/thomas/.vscode/extensions/mtxr.sqltools-0.22.10/extension.js:16:111706
	at /Users/thomas/.vscode/extensions/mtxr.sqltools-0.22.10/extension.js:16:112113
	at Immediate.<anonymous> (/Users/thomas/.vscode/extensions/mtxr.sqltools-0.22.10/extension.js:16:112655)
	at processImmediate (internal/timers.js:439:21)
	at process.topLevelDomainCallback (domain.js:131:23)] {
  code: -32603,
  data: undefined
}
```

**To Reproduce**

**Expected behavior**
Well, a working connection :)

**Screenshots**
Sorry, nope

**Desktop (please complete the following information):**
 - SQLTools Version 0.22.10
 - VSCode Version: 1.47.1
 - OS: MacOS 10.14.6
 - Driver: 
   - [x] PostgreSQL/Redshift
   - [ ] MySQL/MariaDB
   - [ ] MSSQL/Azure
   - [ ] SQLite
   - [ ] Other? Which...
 - Database version: PostgreSQL 11.5

**Additional context**
Sorry, nothing to add here.

**Comment by mtxr** [comment]
Fixed on v0.22.11.
