### ISSUE TITLE
"SQLTools Settings" tab is blank

### ISSUE THREAD

**Issue by CrSjimo** [mtxr/vscode-sqltools#664]
**Describe the bug**
"SQLTools Settings" tab is blank

**To Reproduce**
1. Use the command "SQLTools Management: Add New Connection"
2. An "SQLTools Settings" tab opens, but it is blank. (No matter how long I wait and how many times I restart VSCode)

**Expected behavior**
There should be some settings in the "SQLTools Settings" tab.

**Screenshots**
![U461ns.png](https://s1.ax1x.com/2020/07/20/U461ns.png)

**Desktop (please complete the following information):**
 - SQLTools Version 0.22.10
 - VSCode Version: 1.47.2
 - OS: windows 10
 - Driver: 
   - [ ] PostgreSQL/Redshift
   - [ ] MySQL/MariaDB
   - [ ] MSSQL/Azure
   - [*] SQLite
   - [ ] Other? Which...
 - Database version: [e.g. MySQL v5.6, PostgreSQL vX...]

**Additional context**

**Comment by ahgoodman** [comment]
Having same issue, with all the same versions listed above

**Comment by bRaInT00T** [comment]
Same here

**Comment by mpchean** [comment]
Also having same issue.

**Comment by mtxr** [comment]
Fixed on v0.22.11.
