### ISSUE TITLE
Connected database not showing

### ISSUE THREAD

**Issue by gottogethelp** [mtxr/vscode-sqltools#668]
Describe the bug:

Connected database not showing

Click ```Add new connection```
Click ```MySQL```
Click ```TEST CONNECTION``` - says ```Successfully connected```
Click ```SAVE CONNECTION``` - says:
```
capra was added to your settings!
Review JSON Syntax
{
  "database": "belgarath",
  "driver": "MySQL",
  "mysqlOptions": {
    "authProtocol": "default"
  },
  "name": "capra",
  "password": "root",
  "port": 3306,
  "previewLimit": 50,
  "server": "localhost",
  "username": "root"
}
```
Click ```CONNECT NOW``` - displays a new tab:

![image](https://user-images.githubusercontent.com/62015141/88458024-3a2c9e00-ce8b-11ea-995e-58a9e3ace719.png)

Expected behaviour:
Should see my connection in ```CONNECTIONS``` but it's not there:

![image](https://user-images.githubusercontent.com/62015141/88458062-84158400-ce8b-11ea-9475-4021d7bc5fe4.png)

Hitting refresh gets me:

![image](https://user-images.githubusercontent.com/62015141/88451062-29ad0100-ce54-11ea-8f58-fcbf93e39c76.png)

in the bottom right hand corner.

Desktop (please complete the following information):

SQLTools Version 0.22.11
VSCode Version: 1.47.2
OS: [e.g. Windows, Linux, Mac]
Driver: MySQL

Database version: 8.0

Additional context Add any other context about the problem here.

I had successfully installed the SQLTools and SQLTools MySQL/MariaDB extensions and they were working fine. However, I had some issues elsewhere so I'd temporarily uninstalled them whilst trying to bug fix.

I've now added them back and reconnected my MySQL database - everything in the connection process, including testing the connection, looked fine. However, it says ```No connections found```. I've tried a few times with different databases and always the same result - connection process looks fine but no end result.

Weirdly, whenever I click on the refresh button icon then a message pops up in the bottom right of the screen to say ```Element with id capra|MySQL|localhost|belgarath is already registered```. It always says this and never refers to any other database. This is the first database I tried to connect to originally. It also appeared when on the very first reinstall so somewhere it had remembered those settings.

**Comment by mtxr** [comment]
which VSCode version are you using? is it a remote development setup? are you connecting to docker database?

Can you provide more info? If possible, follow the template here: https://github.com/mtxr/vscode-sqltools/blob/master/.github/ISSUE_TEMPLATE/bug_report.md so I can try to reproduce it here.

**Comment by gottogethelp** [comment]
Hi. Updated comment

**Comment by eezotope** [comment]
Encountered the exact same behavior.

SQLTools Version 0.23.0
VSCode Version: 1.48.2
OS: Ubuntu 18.04
Driver: MSSQL

I have previously created a similar db connection and deleted SQLTools, after the new installation I'm getting this error too.

**Comment by savvo** [comment]
I've just run across the same. It seems "Add new connection" doesn't check for duplicate entries, allowing e.g.

```
    "sqltools.connections": [
        {
            "mysqlOptions": {
                "authProtocol": "default"
            },
            "previewLimit": 50,
            "server": "localhost",
            "port": 3306,
            "askForPassword": true,
            "driver": "MySQL",
            "name": "heretic",
            "database": "default",
            "username": "root"
        },
        {
            "mysqlOptions": {
                "authProtocol": "default"
            },
            "previewLimit": 50,
            "server": "localhost",
            "port": 3306,
            "askForPassword": true,
            "driver": "MySQL",
            "name": "heretic",
            "database": "default",
            "username": "root"
        }
    ]
```

and resulting in:

```
Element with id heretic|MySQL|localhost|default is already registered
```
Worked around it by editing settings.json

**Comment by TomPohys** [comment]
I was able to delete duplicated connection by Command Palette (`Ctrl + Shift + P`) -> `SQLTools Management: Delete connection`. Then the rest of the connection shows up

**Comment by gjsjohnmurray** [comment]
Starting with today's 0.27.1 release it should no longer be possible to define connections with duplicate IDs using the UI.
