### ISSUE TITLE
requiring self-signed cert when rejectCert is set to false

### ISSUE THREAD

**Issue by clarkngo** [mtxr/vscode-sqltools#675]
**Describe the bug**
In local development, Connecting VSCode to PostgreSQL for the first time does not populate the driver settings for self-signed cert. This cause the default of rejectCert set to false not working. 

Workaround: After tick requestCert and save connection, then un-tick requestCert and save connection before testing the connection.

Here the user creates his connection profile:
![image](https://user-images.githubusercontent.com/30854108/89114330-083dad80-d430-11ea-869c-2faa70347610.png)

Result of JSON
![image](https://user-images.githubusercontent.com/30854108/89114456-6b7c0f80-d431-11ea-9897-3c1cb6ad6b57.png)

After tick requestCert and save connection, then un-tick requestCert and save connection before testing the connection.

![image](https://user-images.githubusercontent.com/30854108/89114366-6cf90800-d430-11ea-8387-b7ea8d539589.png)

![image](https://user-images.githubusercontent.com/30854108/89114337-17bcf680-d430-11ea-97b7-15bd8d73ab34.png)

**To Reproduce**
1. Creating a connection through Connection Assistant of SQLTools Settings (PostgreSQL)
2. Without adding any options, click Test Connections

**Expected behavior**

**Desktop (please complete the following information):**
 - SQLTools Version: 0.22.11
 - VSCode Version: 1.47.3
 - OS: Ubuntu 18.10.1
 - Driver: 
   - PostgreSQL 

 - Database version: 10.9

**Comment by pbower** [comment]
This is still an issue in the current version.
