### ISSUE TITLE
Strings are displayed as hex values

### ISSUE THREAD

**Issue by hdd1013** [mtxr/vscode-sqltools#678]
**Describe the bug**
Query result displays hex values instead of the correct strings.

**To Reproduce**
1. Run SQL query

**Expected behavior**
Query result displays the string values correctly

**Screenshots**
![89259510-6d2e1900-d665-11ea-8b8a-975bd6c7d3191](https://user-images.githubusercontent.com/7456108/89260038-723f9800-d666-11ea-8acf-b2ca0ffcdfba.jpg)

![Annotation 2020-08-04 152024](https://user-images.githubusercontent.com/7456108/89259898-37d5fb00-d666-11ea-8df2-31de599d2ba8.jpg)

**Desktop (please complete the following information):**
 - SQLTools Version: 0.22.11
 - VSCode Version: 1.47.3
 - OS: Windows 10 2004
 - Driver: 
   - [x] MySQL/MariaDB
 - Database version: See screenshot

**Additional context**

**Comment by mtxr** [comment]
which extension driver version are you using?

**Comment by hdd1013** [comment]
> 
> 
> which extension driver version are you using?

It's v0.1.1

**Comment by mtxr** [comment]
@hdd1013 I believe this is fixed already. Can you confirm on latest version?

Can't reproduce it anymore
