### ISSUE TITLE
Trying to expand my database to see schema and tables fails with Expected value of type 'boolean' but 'db.datallowconn' is of type 'char' and no implicit conversion is available

### ISSUE THREAD

**Issue by els-pnw** [mtxr/vscode-sqltools#679]
**Describe the bug**

Set up postgresql database and receive successful connection. 
Try to expand the database from the explorer panel to see schema and tables
Receive error:
```
Request connection/GetChildrenForTreeItemRequest failed with message: TEIID30082 Expected value of type 'boolean' but 'db.datallowconn' is of type 'char' and no implicit conversion is available.
```
It does appear that my queries work nonetheless; however, it would be helpful if I were able to expand the database in explorer so that I can see the schema and tables I work with.
**Desktop (please complete the following information):**
 - SQLTools Version v0.1.0
 - VSCode Version: 
Version: 1.47.3
Commit: 91899dcef7b8110878ea59626991a18c8a6a1b3e
Date: 2020-07-23T13:08:29.692Z (2 wks ago)
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.6.0
 - Driver: 
   - [x] PostgreSQL/Redshift
   - [ ] MySQL/MariaDB
   - [ ] MSSQL/Azure
   - [ ] SQLite
   - [ ] Other? Which...
 - Database version: [e.g. MySQL v5.6, PostgreSQL vX...]

**Additional context**

**Comment by gjsjohnmurray** [comment]
Does the problem still occur with the current release?
