### ISSUE TITLE
:bug: Split space formatter creates invalid syntax for Postgres escaped string literals `E'This is a comment'` erroneously corrects to `E 'This is a comment'`` which is no longer parseable

### ISSUE THREAD

**Issue by slimlime** [mtxr/vscode-sqltools#680]
**Describe the bug**
Formatter creates invalid syntax for Postgres escaped string literals `E'This is a comment'` erroneously corrects to `E 'This is a comment'`` which is invalid syntax; no longer parseable. Results in error when attempting to run the formatted .sql.

I didn't see a workaround or setting for this postgres-specific syntax. Currently using bulk replace-all on sql files after linting. `E '` -> `E'` may not be reliable.

**To Reproduce**
As above, type an escaped string literal `E'somestring'` and run the formatter to see it become invalid postgres syntax `E 'someinvalidstring'`

**Expected behavior**
Escaped string literals in postgres syntax should not be split with a whitespace
`E'this is a valid escaped string literal'`

**not:** `E 'this is an invalid escaped string literal'`

**Screenshots**

**Desktop (please complete the following information):**
 - SQLTools Version [v0.22.11]
   - Also on previous versions this past year I had been working around until googling the repo to submit an issue. This may have been missed or I am missing a postgres-specific option flag somewhere?

 - VSCode Version: [1.47.3]
 - OS: [Windows, Linux] . Likely Mac as well
 - Driver: 
   - [x] PostgreSQL/Redshift
   - [ ] MySQL/MariaDB
   - [ ] MSSQL/Azure
   - [ ] SQLite
   - [ ] Other? Which...
 - Database version: [e.g. MySQL v5.6, PostgreSQL vX...]
 - Postgres 12.x (not sure if relevant)

**Additional context**

**Comment by kantum** [comment]
Any new on this?

**Comment by sivaramasubramanian** [comment]
I have created PR #935 to fix this issue.
@mtxr Please review and merge it.
