### ISSUE TITLE
Add the extension to open-vsx.org 

### ISSUE THREAD

**Issue by bruno-robert** [mtxr/vscode-sqltools#697]
**Is your feature request related to a problem? Please describe.**
Currently, you can only access this extension directly from the [Microsoft marketplace](https://marketplace.visualstudio.com/vscode). Thus when using code without visual studio, you cannot conveniently add this extension (legally). This happens when using [vsCodium](https://vscodium.com/) for example.

**Describe the solution you'd like**
Please add this extension to [open-vsx.org](https://open-vsx.org/).
Here is [a guide](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions) to publishing on [open-vsx.org](https://open-vsx.org/).

**Describe alternatives you've considered**
- It is possible to install via the Microsoft marketplace ([but it's not clear whether this is legal](https://github.com/microsoft/vscode/issues/31168)). 
- You can install directly via .vsix files (but it's not very convenient 😢 )

**Additional context**
[Here](https://www.gitpod.io/blog/open-vsx/) is a more detailed explanation as to why open-vsx.org was created.

Thank you to all contributors for the hard work put into this project! Truly 😄 
Also please let me know if I am wrong and this extension is already published to an open marketplace.

**Comment by glamax13** [comment]
I love your extension and it is the only thing that annoy me as i am transitioning to VSCodium. 

I am not blaming you on the contrary. I find it that useful that at this time i manually download the extension and the driver in the VSIX format to install it in VSCodium.
But i don't get the update so i would be really gratefull if you could add it to open-vsx marketplace :smile:

**Comment by bjornhansen** [comment]
+1 for Gitpod users as well.

**Comment by bjornhansen** [comment]
I have added v0.22.11 of this extension to [OpenVSX](https://open-vsx.org/) under the `mtxr` namespace. [See it here.](https://open-vsx.org/extension/mtxr/sqltools)

This namespace is currently public and I suggest @mtxr:
1. Claim it so nobody meddles with it.
2. Update the readme to not include the title SVG, which OpenVSX doesn't like. Turn it into a PNG?
3. Update any github deployment actions/pipelines to [publish](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions) to OpenVSX on each release.
    - I may be able to dig into this and submit a pull request, though it will involve a new environment variable. Is that of interest?

**Comment by mtxr** [comment]
Will do! thanks guys

**Comment by mtxr** [comment]
just published the latest versions available on vscode marketplace. new releases will be published as well.

closing

**Comment by alexandruchircu** [comment]
Hi, using a code-server instance (https://github.com/coder/code-server), the main extension is found in open-vsx's marketplace, but no drivers are available to download (@tag:sqltools-driver returns nothing).
