### ISSUE TITLE
AWS MariaDB...

### ISSUE THREAD

**Issue by stedesDev** [mtxr/vscode-sqltools#704]
**Describe the bug**
Hi, how is life

Here is my paramters for the connection

`{
    "sqltools.connections": [
        {
            "mysqlOptions": {
                "authProtocol": "default"
            },
            "previewLimit": 50,
            "server": "mariadb.blablablabla.us-east-1.rds.amazonaws.com",
            "port": 3306,
            "driver": "MariaDB",
            "name": "TestMariaDb",
            "database": "crm",
            "username": "blablablabla",
            "password": "blablablabla"
        }
    ]
}
`

Can connect to the DB...
When I want to expend the tree for tables and... II have this error

Request connection/GetChildrenForTreeItemRequest failed with message: getaddrinfo ENOTFOUND mariadb.blablablabla.us-east-1.rds.amazonaws.com

Here the log entry

[1601042629774] INFO  (ext): EXECUTING COMMAND => sqltools.getChildrenForTreeItem
[1601042629775] INFO  (ls): REQUEST RECEIVED => connection/GetChildrenForTreeItemRequest

**Desktop (please complete the following information):**
 - SQLTools Version: v0.23.0
 - VSCode Version: 1.49.2
 - OS: Ubuntu
 - Driver: MySQL/MariaDB  
 - Database version: MariaDB 10.4.8

**Additional context**
The DB is host on AWS RDS MariaDB  free tier

Best regards,
Steph

**Comment by ch33orange** [comment]
me tooooooooo~  We need help!!!

**Comment by gjsjohnmurray** [comment]
<strike>Please try using the dedicated Redshift driver from https://marketplace.visualstudio.com/items?itemName=kj.sqltools-driver-redshift and report back here. </strike>

Ignore that. You are asking about MariaDB whereas Redshift is based on PostgreSQL.

**Comment by gjsjohnmurray** [comment]
Please update to latest VS Code and extensions, then re-test. If you still have these problems, open a new issue.
