### ISSUE TITLE
New Oracle Driver for v0.22 or newer

### ISSUE THREAD

**Issue by phudson** [mtxr/vscode-sqltools#705]
**Is your feature request related to a problem? Please describe.**
I'm making good use of this extension. Unfortunately, most of my work is with Oracle which is only supported in older versions

**Describe the solution you'd like**
A supported Oracle driver that works with the latest version of sqltools

**Describe alternatives you've considered**
I'm using the older version but am suffering feature-envy :)

**Additional context**

**Comment by mtxr** [comment]
@mickeypearce long time we don't talk about this, but would you be willing to work on that?

**Comment by mtxr** [comment]
@phudson personally I don't have time to start supporting another driver by myself. I've just started a new job, my kid is growing, so I'm spending more time with him. I'll be mostly supporting the drivers I've been supporting already.

I hope the community can develop new drivers and keep it going, I can provide guidance and so insights, but to code won't be possible

**Comment by mtxr** [comment]
Closing. Already tracking on #586
