### ISSUE TITLE
Add export to clipboard

### ISSUE THREAD

**Issue by sebastienroul** [mtxr/vscode-sqltools#712]
Export in CSV is great but direct export to clipboard could be super

When clicking on export, a new entry chould be 'Clipboard', and when selected, the results are in clipboard.
The important thing is to export as CSV, but with "tab" (\t) delimiter [https://csv.js.org/stringify/options/delimiter/] and quoted_string [https://csv.js.org/stringify/options/quoted_string/] - It's really easier to paste it into spreadsheet

Thanks a lot

**Comment by lex3001** [comment]
+1 for this feature ... and the ability to export with or without Headers would be helpful too.
Being to able to export to the clipboard and then paste into Excel or Google Sheets would be fantastic.

**Comment by gjsjohnmurray** [comment]
PR merged. Feature will be in next release.
