### ISSUE TITLE
Snowflake Driver Support

### ISSUE THREAD

**Issue by ParzivalWins** [mtxr/vscode-sqltools#713]
With the explosion of Snowflake as a data warehouse/lake platform, it would be great to have driver support for it inside of SQLTools. Thank you.

**Comment by koszti** [comment]
I have started working on it and I’d like to send a PR soon. Please let me know if anyone else working on it to avoid double effort.

**Comment by koszti** [comment]
The first version of the snowflake driver documented in https://github.com/mtxr/vscode-sqltools/pull/726 and it's now installable directly from the vscode extension menu.

Github source code: https://github.com/koszti/sqltools-snowflake-driver.
VS Marketplace: https://marketplace.visualstudio.com/items?itemName=koszti.snowflake-driver-for-sqltools

### What's implemented:

* Connection form, running SQL commands, schemas/table/view objects tree

### What's not implemented:

* **`externalbrowser` authenticator for SSO**: the [snowflake nodejs connector](https://github.com/snowflakedb/snowflake-connector-nodejs) doesn't implemnt the SSO authentication
* **Intellisense auto completion**: Fast code completion has to use the [SHOW objects](https://docs.snowflake.com/en/sql-reference/sql/show-objects.html) commands to get search matches, that requires to run multiple sql queries for each search. SQLTools not supporting it at the moment.

**Comment by siddharthlal25** [comment]
Any updates on the authenticator for SSO?

**Comment by gjsjohnmurray** [comment]
Closing because standalone driver extension exists.
