### ISSUE TITLE
Tab's name after running query

### ISSUE THREAD

**Issue by miiguelkf** [mtxr/vscode-sqltools#716]
**Describe the bug**
After running a query, and creating a tab for its result, the tab's name is getting huge. As I could see it is named as the query code. So, bigger queries are resulting in bigger names.

**To Reproduce**
1. Just run any query
2. See the tabs name

**Expected behavior**
Tab name should be something cleaner. Maybe "Result" or anything like that I guess would work better.
Or limit the number of char

**Screenshots**
![image](https://user-images.githubusercontent.com/61953892/96750850-d5f27b00-13a2-11eb-8e0c-b1bacd885bc5.png)

**Desktop (please complete the following information):**
 - SQLTools Version [e.g. v0.23.0]
 - VSCode Version: [e.g 1.50.1]
 - OS: [Windows]
 - Driver: 
   - [x] PostgreSQL/Redshift

**Comment by Odwerneh** [comment]
+1

I work on queries having >400 lines and I really cannot orient myself among the different result set tabs.

Resul#1 - Result#n would be perfectly fine. Nice to have would be to add possibility to rename the tab or take just 1st line of query where I cann add some coment that would be displayed as a header.

**Comment by mtxr** [comment]
Fixed by #774. Pending release
