### ISSUE TITLE
Ctrl+e conflicts with vscode "Go to File"

### ISSUE THREAD

**Issue by archongum** [mtxr/vscode-sqltools#718]
Ctrl+e conflicts with vscode "Go to File" and I don't wanna change it. Is there a way to set Ctrl+E to other shortcut instead?

**Comment by mtxr** [comment]
You can always change It in your editor to anything else. This shortcut is there since the beginning, I don't think worth changing now. So since vscode has a way to do that individually, I'll close this issue for now

**Comment by SethFalco** [comment]
While I see where you're coming from, I do think it offers a bad user-experience to override default shortcuts in Visual Studio Code with no warning.

I think it makes sense to either:
1. Change the shortcut.
2. At least use an info message or prompt to ask the user on initial usage if they'd like their shortcuts overridden.

Or at least, anything but doing it silently where the user has to figure out why `CTRL` + `E` isn't doing what it's expected to, especially given it's such a frequently used shortcut. ^-^'
