### ISSUE TITLE
Show syntax error in Problems instead of SQL Console: Messages

### ISSUE THREAD

**Issue by ZZYSonny** [mtxr/vscode-sqltools#719]
**Is your feature request related to a problem? Please describe.**
When I type in a wrong query, I can only see where I am wrong after I open a third window. Also the syntax error is not informative.
![image](https://user-images.githubusercontent.com/28442838/97098375-2b869a80-16b7-11eb-9a6e-bafda575dedd.png)

**Describe the solution you'd like**
Syntax error in SQL files should appear in Problems. Also, in the case of syntax error, Problems window should be automatically shown instead of the result page with "Query with errors"

**Describe alternatives you've considered**
not yet.

**Additional context**
Also I think it will be helpful to add realtime syntax checking to sql files.

**Comment by gjsjohnmurray** [comment]
In the current version (0.24.0) the error message also shows in the Results tab immediately below the red X icon.

Closing this issue.
