### ISSUE TITLE
No pg_hba.conf for host

### ISSUE THREAD

**Issue by brbarkley** [mtxr/vscode-sqltools#72]
### Issue Type

* [ ] Feature Request
* [X] Bugfix/Errors
* [X] Questions
* [ ] Other

### Prerequisites (For bugfixes)

* [X] Are you running the latest version?
* [X] Did you check the logs?
* [X] Did you check the Setup?

### Description

Received error message: "no pg_hba.conf entry for host..." when trying to connect to postgresql database using SQLTools. I can connect on same computer from command line using psql and via python using psycopg2. Do you know what the problem might be?

### Steps to Reproduce (For bugfixes)

1. Entered sqltools.connections settings

![sqltoolsconnections](https://user-images.githubusercontent.com/29204320/37719515-97b2ab52-2cfb-11e8-8be7-af3c3856ee52.PNG)

2. Connect to database and receive message "currently connected"

3. Used SQLToolsConnection: Run Query

**Expected behavior:** [What you expected to happen]
Expected to retrieve data from database

**Actual behavior:** [What actually happened]
Received error message: "no pg_hba.conf entry for host..."

![image](https://user-images.githubusercontent.com/29204320/37719861-6bf82dc4-2cfc-11e8-8a80-496c34787001.png)

### Versions

- *Version*: SQLTools v0.12.1
- *OS*: Windows 10
- *SGDB*: PostgresSQL

You can get this information from executing `SQLTools: Version` from VSCode `Quick Open`.

**Comment by mtxr** [comment]
Have you tried this?

https://dba.stackexchange.com/questions/83984/connect-to-postgresql-server-fatal-no-pg-hba-conf-entry-for-host

Let me know if it works.

**Comment by mtxr** [comment]
Closing. No response.

**Comment by fatangare** [comment]
I am facing same issue while connecting to aws redshift

**Comment by sabahang** [comment]
I understand I need to make a change in `postgresql.conf` but where is this file?

**Comment by holgerzer** [comment]
> @mtxr I understand I need to make a change in `postgresql.conf` but where is this file? my postgres is on a cloud server and everyone else can connect to it. I'm not running it locally nor have access to it's config

I'm facing the same situation. I tried to add the pgOptions to my settings (see #547 ) but can't find the json.

**Comment by Vorobeyko** [comment]
i fixed problem with following step

1. Enabled ssl
2. check requestCert

<img width="669" alt="image" src="https://github.com/mtxr/vscode-sqltools/assets/11293201/2286572b-6f98-41c2-821f-246a5ba94e3f">

**Comment by jqknono** [comment]
To connect  to AWS RDS, I need to set this TWO:

- SSL: Enabled
- rejectUnauthorized: **Check And Uncheck**. This is important, and make a difference.

The `"rejectUnauthorized": false` should fill in the setting explicitly.

```json
{
  "pgOptions": {
    "ssl": {
      "requestCert": true,
      "rejectUnauthorized": false
    }
  },
  "previewLimit": 50,
  "server": "XXX",
  "port": 5432,
  "driver": "PostgreSQL",
  "name": "aws.rds.starter",
  "username": "XXX",
  "database": "XXX"
}
```
