### ISSUE TITLE
Table Designer for create / alter table

### ISSUE THREAD

**Issue by softgandhi** [mtxr/vscode-sqltools#720]
Requesting to add feature create or alter table using GUI designer similar to SQL Server Management Studio

**Describe the solution you'd like**
It would be great if just right click on tables and select "New Table", then we get an editor to create table similar to that of Sql Server Management Studio

**Describe alternatives you've considered**
Alternative solution is to use SQL Server Management Studio, but it's not available on Mac. I have also considered other SQL tools, but could not find any one as a good option.

**Additional context**
Whenever I need to create a new table, I find it comparatively difficult to type create table syntax with typing accuracy. A GUI designer feature for SQL server would be a great solution.

**Comment by adriancuadrado** [comment]
You can use these web apps as a workaround in the meantime:
https://wtools.io/generate-sql-create-table
https://editor.datatables.net/generator/

Or you can google "online database table creator" and choose your favourite option.

**Comment by gjsjohnmurray** [comment]
@softgandhi this is unlikely to happen.

@adriancuadrado thanks for your suggestions.
