### ISSUE TITLE
Publish to OpenVSX

### ISSUE THREAD

**Issue by ItsDrike** [mtxr/vscode-sqltools#721]
Arch Linux (Linux based operating system distribution) has decided to switch the marketplace for extensions from the [MS Visual Studio Marketplace](https://marketplace.visualstudio.com) to [OpenVSX](https://open-vsx.org/) in [this commit](https://git.archlinux.org/svntogit/community.git/commit/trunk?id=b62a02ec645f16528c0269faf12e362a55efda75).

[Here](https://www.gitpod.io/blog/open-vsx/) are some more details about OpenVSX, its goal, and why it was created

For that reason, I can't use your extension anymore, could you publish on OpenVSX too?
(It's typically just a matter of running `npx ovsx publish` you can also check the [full guide for publishing](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions))

**Comment by bjornhansen** [comment]
I'd also love to see this happen! As a Gitpod user, the current SQL toolset is a bit limited.

**Comment by mtxr** [comment]
Dup #697
