### ISSUE TITLE
[Feature Request]Firebird Support

### ISSUE THREAD

**Issue by LiPengfei19820619** [mtxr/vscode-sqltools#73]
### Issue Type

* [* ] Feature Request
* [ ] Bugfix/Errors
* [ ] Questions
* [ ] Other

Would you please support Firebird Database? Thanks.

**Comment by mtxr** [comment]
Hey @LiPengfei19820619, could you please submit a pull request of this feature?

As you are a user that understands the needs for Firebird, you could follow this commit 6cc9774 and use this lib [hgourvest/node-firebird](https://github.com/hgourvest/node-firebird) to accomplish the same result that I've got with Postgres. Is it ok?

As you can see at the commit, it's not difficult, it's almost to define the queries it needs to run.

Thanks!

**Comment by Level0r0s** [comment]
I did the Firebird Interface implementation.

As I have no experience with extensions and do not know how to test.
@mtxr It would be possible to test and upgrade the master.

Tanks

https://github.com/Level0r0s/vscode-sqltools

**Comment by mtxr** [comment]
@LiPengfei19820619 can you test the open PR?

I believe it's already working, I've updated the references to the new code.

Thanks!

**Comment by mtxr** [comment]
Closing. Needs users to test it.

If someone want to move forward with it, here is the PR #123 and the branch with the code is `feature/firebird`.
