### ISSUE TITLE
Correct way to import sqlFormatter from @sqltools/formatter?

### ISSUE THREAD

**Issue by hacker0limbo** [mtxr/vscode-sqltools#733]
**Describe the bug**
I installed [@sqltools/formatter](https://www.npmjs.com/package/@sqltools/formatter) this package and try to use it like this as [README](https://github.com/mtxr/vscode-sqltools/blob/master/packages/formatter/README.md) describes:

```javascript
import sqlFormatter from 'sql-formatter';
```

However i got this error:

```bash
Module not found: Can't resolve 'sql-formatter' in '...'
```

After a while i realize and fix it like this:
```javascript
import sqlFormatter from "@sqltools/formatter";
```

So am i right? or is just because the README for @sqltools/formatter is outdated?

**Comment by mtxr** [comment]
Yeah, it's outdated. Would you like to send a PR?

**Comment by hacker0limbo** [comment]
@mtxr requested PR, see #734
