### ISSUE TITLE
Add localization options for CSV export

### ISSUE THREAD

**Issue by jtommi** [mtxr/vscode-sqltools#739]
As you might know, CSV formatting depend on the localization of your PC.
Here in Belgium a CSV uses semi-colon as field separator and comma as decimal separator.

Since most exports I do will be used by basic Excel users, this is a blocker for me.

So the suggestion is to add settings for CSV field separator and CSV decimal separator.
CSV field separator I'd suggest a choice between comma and semicolon (and maybe tabs while we're add it).
CSV decimal separator, period and comma should be enough.

What do you think?

**Comment by RnoldR** [comment]
Second that! I noticed  something similar for the export to .csv to clipboard (#712) that was granted. Please add it to exporting to file as well. 
That it is possible to export the results at all, however, is extremely appreciated.

**Comment by cornettew** [comment]
This feature would be very useful. Any chance it will be available soon ?

**Comment by gjsjohnmurray** [comment]
> Any chance it will be available soon ?

Probably not unless someone [contributes a PR](https://vscode-sqltools.mteixeira.dev/en/contributing/).
