### ISSUE TITLE
Setting formatLanguages to []. doesn't disable formatting

### ISSUE THREAD

**Issue by jtommi** [mtxr/vscode-sqltools#741]
**Description**
As explained in https://github.com/mtxr/vscode-sqltools/issues/116, setting formatLanguages to [] should disable formatting, but it doesn't

This was also mentioned in July on the issue https://github.com/mtxr/vscode-sqltools/issues/116#issuecomment-658196456

**How to reproduce**
1. Go to VS Code Settings UI
2. Search for sqltools.formatLanguages
3. Remove sql
4. Create a SQL file with weird formatting
5. Trigger formatting (for my case that's saving it because I have "Format on save" enabled

**Expected behavior**

**Desktop (please complete the following information):**
 - SQLTools Version v0.23.0
 - VSCode Version: 1.51.1
 - OS: Windows
 - Driver: 
   - [ ] PostgreSQL/Redshift
   - [x] MySQL/MariaDB
   - [ ] MSSQL/Azure
   - [ ] SQLite
   - [ ] Other? Which...

**Comment by maxx27** [comment]
The same issue with Postgres. Could you please fix it?

**Comment by alex-marty** [comment]
Hello, I have the same issue, I would like to disable formatting of .sql files but this doesn't change the behavior. Can it be fixed?

**Comment by gjsjohnmurray** [comment]
Please make sure you restart VS Code after you set `"sqltools.formatLanguages": [],`
