### ISSUE TITLE
Cannot destructure property 'name' of 'undefined' as it is undefined when calling proc

### ISSUE THREAD

**Issue by mocart2** [mtxr/vscode-sqltools#747]
I try to call stored proccedure(is exists)  by using CALL method:
`CALL myProc();`
end get error in console:
`Cannot destructure property 'name' of 'undefined' as it is undefined `
why? how i can solve it?

 - SQLTools Version v0.23.0
 - VSCode Version: 1.53.0-insider
 - OS: [e.g. Windows, Linux, Mac]
 - Driver: 
   - [x] MySQL/MariaDB
 - Database version: [e.g. MariaDB Ver 15.1 Distrib 10.5.8-MariaDB]

**Comment by ysl2** [comment]
I have the same problem when I select the two line to execute:
![image](https://user-images.githubusercontent.com/39717545/107608448-fc506500-6c76-11eb-91b2-fb825ba8e2d0.png)
However when I select a single line to execute, it performed well.

**Comment by mtxr** [comment]
Dup of #723
