### ISSUE TITLE
publishing sqltools in Open VSX Registry "managed by Eclipse Foundation"

### ISSUE THREAD

**Issue by Hesham937** [mtxr/vscode-sqltools#749]
could you please consider in the future publish you extension in open VFX 

open VFX is an open source alternative to vscode marketplace

open VFX homepage and github page : 

https://open-vsx.org/

https://github.com/eclipse/openvsx

thanks

**Comment by protron** [comment]
This issue seems like a duplicate of #697 

I'm pointing it out in order for people to vote (thumbs up) on that original issue.
That one already has nice description, some thumbs up and some comments.

**Comment by mtxr** [comment]
Duplicate of #697. Closing
