### ISSUE TITLE
Support for schema (full qualified object name)

### ISSUE THREAD

**Issue by art-ist** [mtxr/vscode-sqltools#75]
### Issue Type

* [x] Feature Request
* [x] Bugfix/Errors

### Prerequisites (For bugfixes)

* [x] Are you running the latest version?
* [x] Did you check the logs?
* [x] Did you check the Setup?

### Description

I didn't check with other dialects. But for MS SQL sqltools completely **ignores the Schema** or a database object. Let's say we have a table `Sales.Offers`. sqltools would in all commands just refer to it as `Offers`. So if Sales was not the default schema of the current user you will get the error `Invalid object name 'Offers'`.

### Steps to Reproduce (For bugfixes)

1. Connect
2. Use the command "Show Table Records"

**Expected behavior:** [What you expected to happen]
Results are shown.

**Actual behavior:** [What actually happened]
Error: Invalid object name 'Offers'

**Comment by ttraenkler** [comment]
Same for PostgreSQL

**Comment by mtxr** [comment]
#71 seems to be the same.

I've created a milestone to fix this problem.

**Comment by mtxr** [comment]
Closed in flavor of #71
