### ISSUE TITLE
In column completions, `database` is a typo for `db`

### ISSUE THREAD

**Issue by smaspe** [mtxr/vscode-sqltools#751]
As shown in [node-sql-parser From model](https://github.com/taozhi8833998/node-sql-parser/blob/dd1a4b217a99e0cab42030524c93ab70b210a0cc/types.d.ts#L22), the property containing the database is `db`

Currently, it is referred to as `database`, resulting in `undefined` database in all column completion. See
https://github.com/mtxr/vscode-sqltools/blob/b8938cafa59dd378d22a7ef24ecb710de51b400e/packages/plugins/intellisense/language-server.ts#L143 where t is of type From

**Comment by gjsjohnmurray** [comment]
Code has changed in this area. Do you still experience the problem with the latest version, 0.24.0?
