### ISSUE TITLE
i want to know how to set connection charset

### ISSUE THREAD

**Issue by zhmacn** [mtxr/vscode-sqltools#753]
**Describe the bug**
i connect db server,when server charset is 936(gbk),the return result is show garbled

**Screenshots**
![image](https://user-images.githubusercontent.com/45324426/104309335-f6972080-550c-11eb-87b1-9afc213ebfb7.png)

**Desktop (please complete the following information):**
 - SQLTools Version [0.21.9]
 - VSCode Version: [1.51.1]
 - OS: [Linux-Ubuntu20.04]
 - Driver: 
   - [ ] PostgreSQL/Redshift
   - [ Y] MySQL/MariaDB
   - [ ] MSSQL/Azure
   - [ ] SQLite
   - [ ] Other? Which...
 - Database version: [MySQL v5.6]

**Additional context**
i want to know how to set client charset

**Comment by gjsjohnmurray** [comment]
Does https://github.com/mtxr/vscode-sqltools/issues/925#issuecomment-1201026001 help?
