### ISSUE TITLE
BUG: Any change in settings causes the command plate to come up with “null password (Press 'Enter' to confirm or 'Escape' to cancel)”

### ISSUE THREAD

**Issue by Ahmad-Magdy-Osman** [mtxr/vscode-sqltools#76]
### Issue Type

* [x] Bugfix/Errors

### Prerequisites (For bugfixes)

* [x] Are you running the latest version? Yes

### Description

Every time I change any of the settings in VSCode, the command plate to come up with "null password (Press 'Enter' to confirm or 'Escape' to cancel)". Hitting enter is enough to make things work fine, however, it is still annoying. I am not sure of the reason behind this and was wondering if anybody came across something similar.

### Steps to Reproduce (For bugfixes)

I asked about this on StackOverflow, and a member of the community who faced the same issue tracked it down to this line of code: https://github.com/mtxr/vscode-sqltools/blob/0865cf0/src/sqltools.ts#L419-L424.

His solution was:

> Putting this in my settings.json made the extension stop prompting me:
              "sqltools.autoConnectTo": "blah",
> (The default value is null. Putting a string somehow causes it to generate an error in the console but whatever, it solves the problem.)

[Link to StackOverflow Question](https://stackoverflow.com/questions/49354802/any-change-in-settings-causes-the-command-plate-to-come-up-with-null-password)

**Comment by szhu** [comment]
+1

(I was the one who posted the quoted answer. Thanks @Ahmad-Magdy-Osman for asking it!)

**Comment by AfonsoOliveira** [comment]
+1

**Comment by mtxr** [comment]
Sorry for my late reply guys.

I'll try to fix it till the weekend, okay?


Thanks!
