### ISSUE TITLE
Formatter types path incorrect in latest @sqltools/formatter version

### ISSUE THREAD

**Issue by jasonsack** [mtxr/vscode-sqltools#765]
**Describe the bug**
Typescript does not recognize types for `@sqltools/formatter` in the latest released version `1.2.2` as the types path is incorrect.

The path was fixed in [this commit](https://github.com/mtxr/vscode-sqltools/commit/0be895d3b6f8dd9732901d3378ab13c0969af5a9) on Oct 9 2020 but has not yet been released.

**To Reproduce**
1. import `@sqltools/formatter` `1.2.2`
2. run typescript compiler

**Screenshots**

**Additional context**

**Comment by jasonsack** [comment]
PR for the fix here: https://github.com/mtxr/vscode-sqltools/pull/709

**Comment by mtxr** [comment]
Released already

**Comment by mtxr** [comment]
Duplicate of #733
