### ISSUE TITLE
AWS Redshift Data API support

### ISSUE THREAD

**Issue by f0rk** [mtxr/vscode-sqltools#773]
**Is your feature request related to a problem? Please describe.**
Redshift has a Data API, essentially an HTTP-based API for executing SQL queries.

Here's a description of the functionality: https://aws.amazon.com/blogs/big-data/using-the-amazon-redshift-data-api-to-interact-with-amazon-redshift-clusters/

**Describe the solution you'd like**
Database driver supporting this method of interaction.

**Describe alternatives you've considered**
Considered using the standard Redshift driver and connection, but requires VPN access and so on to the infrastructure.

**Additional context**
I would like to help build (or build entirely) the driver, I am just looking for some pointers to make sure when I go to submit a PR I am not way off base.

Current thinking is to use the existing driver.pg functionality but implement a new driver class that uses the AWS SDK for JS and executes queries/retrieves results that way. Thoughts on the viability of this approach or if I should be thinking about this a different way are welcomed.

Here's the SDK docs: https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/RedshiftData.html

**Comment by gjsjohnmurray** [comment]
I suggest you create and publish a standalone driver extension. Maybe use the source of the embedded driver as a starting point.
