### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by samdruster** [mtxr/vscode-sqltools#779]
- Issue Type: `Bug`
- Extension Name: `sqltools`
- Extension Version: `0.23.0`
- OS Version: `Windows_NT x64 10.0.19042`
- VSCode version: `1.54.3`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by mtxr** [comment]
I'm closing it for now. As is I can't do neither guess anything about this issue. In can you want to reopen, please add more details and feel free to reopen it
