### ISSUE TITLE
Oracle Driver porting or adding

### ISSUE THREAD

**Issue by ElCondor1969** [mtxr/vscode-sqltools#781]
Any updates or roadmap for Oracle Driver porting or adding on last version?
Thanks in advance.

**Comment by mtxr** [comment]
We need a dev for that. The maintainer the oracle driver reported to be busy.
I don't have the knowledge required on Oracle DB to get it ported, so we need someone willing to work on that to have any updates

**Comment by mtxr** [comment]
I'll convert this to a discussion since it won't be worked in this repository, but the discussion still have room to grow here
