### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by samdruster** [mtxr/vscode-sqltools#788]
- Issue Type: `Bug`
- Extension Name: `sqltools`
- Extension Version: `0.23.0`
- OS Version: `Windows_NT x64 10.0.19042`
- VS Code version: `1.55.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by davidshq** [comment]
Looks like there should have been some data associated with the bug that was copied to your clipboard and you need to paste? That info alone doesn't provide enough to troubleshoot the issue.
