### ISSUE TITLE
MS SQL Server query timeout: request failed to complete in 15000ms

### ISSUE THREAD

**Issue by KikeSenpai** [mtxr/vscode-sqltools#794]
More complex queries failed to execute due a timeout limit, it seems there is no way to change this setting.

This is the log, but it doesn't show anything about the timeout
[1618923065059] INFO  (ext): EXECUTING COMMAND => sqltools.getConnections
[1618923065053] INFO  (ls): REQUEST RECEIVED => connection/GetConnectionsRequest
[1618923065055] INFO  (ls): REQUEST RECEIVED => connection/RunCommandRequest
[1618923257583] INFO  (ext): EXECUTING COMMAND => sqltools.showOutputChannel

 - SQLTools Version: 0.23.0
 - VSCode Version: 1.55.2
 - OS: Windows
 - Driver: MSSQL/Azure
 - Database version: SQL Server 2012

**Comment by Sheepyhead** [comment]
Seconded, this needs to be an option somewhere, or if it is, it needs to be more obvious. I've scoured settings and documentation and found nothing

Edit: There is an option actually but it's connection specific so you need to go to edit connection and there it is down by the bottom

Edit2: It seems to not be respected as I get the "Timeout: Request failed to complete in 15000ms" error regardless of what the connectionTimeout value is in the settings

**Comment by KikeSenpai** [comment]
It seems we are not getting support on this issue

**Comment by ferm10n** [comment]
https://github.com/mtxr/vscode-sqltools/blob/ba294769be006e9e605d70ca487e5ce6fb4126c8/docs/src/pages/driver/mssql.mdx#11-specific-options

>You can use any setting defined in See https://github.com/tediousjs/node-mssql/#tedious also extra options defined in Tedious specific options

Looks like there is support for this. This got mine working:
```json5
// .vscode/settings.json
{
  // ...
  "sqltools.connections": [
    {
      "mssqlOptions": {
        "appName": "SQLTools",
        "useUTC": true,
        "encrypt": true,
        "requestTimeout": 0 // 0 to disable
      },
      "previewLimit": 50,
      "port": 1433,
      "driver": "MSSQL",
      // ...omitting creds and stuff
    }
  ]
}
```

**Comment by gjsjohnmurray** [comment]
@ferm10n thanks for providing the information.
