### ISSUE TITLE
SQLTools Ability to Connect to Dev Containers?

### ISSUE THREAD

**Issue by davidshq** [mtxr/vscode-sqltools#795]
I have a Python 3 project I've opened in a dev container (using VSC's Remote-Containers). When I attempt to connect to the SQLite db I have in this container the SQLTools interface only sees the local OS, not the container's OS.

Am I simply misusing the tool or does it not yet support interacting with container db's directly?

**Comment by mathroc** [comment]
Looks like this is the same as https://github.com/mtxr/vscode-sqltools/issues/692

**Comment by gjsjohnmurray** [comment]
Thanks @mathroc. Closing as duplicate.
