### ISSUE TITLE
not able to connect AWS RDS for postregSQL database

### ISSUE THREAD

**Issue by matsujju** [mtxr/vscode-sqltools#799]
**Error on connection testing:**
## Running the contributed command: 'sqltools.testConnection' failed.

**Desktop information:**
 - SQLTools Version [e.g. v0.23]
 - VSCode Version: [latest]
 - OS: [Windows]
 - Driver: 
   - AWS PostgreSQL
 - Database version: [PostgreSQL 12.1]

**Comment by assapir** [comment]
Same in MacOS and PG 11.7 and the driver is `SQLTools PostgreSQL/Redshift Driver`
logs:
```
EXECUTING COMMAND => sqltools.openAddConnectionScreen
[1621509386171] INFO  (ext): getting extension mtxr.sqltools-driver-pg information.
    ns: "ext-util"
[1621509386171] INFO  (ext): loaded extension information mtxr.sqltools-driver-pg for driver PostgreSQL/Redshift.
    ns: "ext-util"
```

**Comment by gjsjohnmurray** [comment]
Are you able to try the community-contributed driver?

https://marketplace.visualstudio.com/items?itemName=kj.sqltools-driver-redshift

**Comment by jqknono** [comment]
To connect  to AWS RDS, I need to set this TWO:

- SSL: Enabled
- rejectUnauthorized: **Check And Uncheck**. This is important, and make a difference.

The `"rejectUnauthorized": false` should fill in the setting explicitly.

```json
{
  "pgOptions": {
    "ssl": {
      "requestCert": true,
      "rejectUnauthorized": false
    }
  },
  "previewLimit": 50,
  "server": "XXX",
  "port": 5432,
  "driver": "PostgreSQL",
  "name": "aws.rds.starter",
  "username": "XXX",
  "database": "XXX"
}
```
