### ISSUE TITLE
Formatting keybindings aren't triggering formatting

### ISSUE THREAD

**Issue by ckingdev** [mtxr/vscode-sqltools#80]
### Issue Type

* [x] Bug
* [ ] Enhancement 
* [ ] Feature Request
* [ ] Question
* [ ] Other

### Prerequisites (For bugfixes)

* [x] Are you running the latest version?
* [x] Did you check the logs?
* [x] Did you check the Setup?

### Description

With the default configuration for VS Code and SQLTools, Linux, following the instructions in the readme for formatting SQL with the keybindings (ctrl+e, ctrl+b) results in attempting to run the query (ctrl + e) or the explorer sidebar has visibility toggled.

Note: using the command palette to select "SQLTools: Format SQL (for any doc)" results in the intended behavior, but the entry in the command palette also shows the incorrect keybindings.

### Steps to Reproduce (For bugfixes)

1. Select a section of a document with SQL code or focus a tab on a document.
2. Press ctrl+e or ctrl+b to beautify code.

**Expected behavior:** SQL code is formatted.

**Actual behavior:**

- Ctrl+e: Extension attempts to run the query, which fails.
- Ctrl+b: Explorer bar's visibility is toggled.

### Versions

- *Version*: v0.12.1
- *OS*: Linux (Debian testing, 64 bit)
- *SGDB*: Postgres

**Comment by mtxr** [comment]
Hi @ckingdev!

You should press all ctr+e, holding ctrl, press b. It's a combination.

The actual behavior is correct with the default keybinding of vscode.

I'm closing the issue, ok?

Just let me know if you need :smile: 

Thank you!
