### ISSUE TITLE
Remove redundant autocomplete suggestions 

### ISSUE THREAD

**Issue by zing-rsa** [mtxr/vscode-sqltools#811]
When you hit space at the end of any line in the SQL file inside VSCode, it presents you with a set of autocomplete suggestions: 
```
#
--
/*
:=
=
```
Does this happen to everyone? I have tried my best to narrow it down, the only time it stops is when I disable SqlTools. 
Is there potentially a way to prevent this from happening in the settings? Thanks

1. Go to end of a line in SQL file
2. Hit space

Expected behavior:
The autocomplete should only suggest things once I have started typing, surely. Otherwise it is just guessing with nothing to base it off. 

Screenshot:
![image](https://user-images.githubusercontent.com/33256042/117822666-0b8e8100-b26d-11eb-92bb-050ed72fcc85.png)

**Desktop (please complete the following information):**
 - SQLTools Version 0.23.0
 - VSCode Version: 1.56.0
 - OS: Windows

**Comment by gjsjohnmurray** [comment]
@zing-rsa can you still reproduce this with the latest versions of VS Code and SQLTools?
