### ISSUE TITLE
Invalid regular expression

### ISSUE THREAD

**Issue by prakashrajPk** [mtxr/vscode-sqltools#821]
return new RegExp("^([\\p{Alphabetic}\\p{Mark}\\p{Decimal_Number}\\p{Connector_Punctuation}\\p{Join_Control}" + specialChars.join('') + "]+)", 'u');
               ^

SyntaxError: Invalid regular expression: /^([\p{Alphabetic}\p{Mark}\p{Decimal_Number}\p{Connector_Punctuation}\p{Join_Control}]+)/: Invalid escape
    at new RegExp (<anonymous>)

**Comment by chaitanya71998** [comment]
@prakashrajPk  did you got solved from this issue?

**Comment by gjsjohnmurray** [comment]
If you are still getting this problem please give detailed reproduction steps.
