### ISSUE TITLE
Table suggestion at max 100 tables

### ISSUE THREAD

**Issue by Maransatto** [mtxr/vscode-sqltools#830]
**Describe the bug**
Some tables tables are not shown on table suggestions.
I realized that it shows me at max 100 tables

Another thing that I realized is that it shows me the suggestion of all the tables on the server, but it would be better to bring only from the active database.

**To Reproduce**
1. Connect to one or more databases having more than 100 tables.

**Expected behavior**
Suggesting all the the tables on my active database

**Screenshots**
![image](https://user-images.githubusercontent.com/17170380/122219531-e7364d80-ce85-11eb-9c92-4a97dec1180d.png)

But as you can see, there's more table
![image](https://user-images.githubusercontent.com/17170380/122219701-13ea6500-ce86-11eb-9f03-26eaa4ea29e8.png)

**Desktop (please complete the following information):**
 - SQLTools Version [v0.23.0]
 - VSCode Version: [1.57.0]
 - OS: [Mac]
 - Driver: 
   - [x] MySQL/MariaDB
 - Database version: mysql:5.6.47

**Comment by Lucs1590** [comment]
+1

**Comment by Lucs1590** [comment]
Up!

**Comment by gjsjohnmurray** [comment]
Do you see more if you set a larger value on `SQLTools.results.limit`? Or maybe on the `previewLimit` property of your connection definition?
