### ISSUE TITLE
Unable to save results as CSV or JSON. EXPORT, Open Results and Save Results all broken.

### ISSUE THREAD

**Issue by pbower** [mtxr/vscode-sqltools#832]
After running a query, 'Save as CSV' or 'Save as JSON' options do not work.

**Steps to reproduce the behavior**:
1. Go to SQLTools and run a query.
2. Click on EXPORT, 'Open Results', or 'Save Results' 
3. For EXPORT, nothing happens and no notification.
4. For Save Results/Open Results, See error

**Expected behavior**:
A saved CSV file or JSON file on hard drive. XLSX would be nice too, but out of scope for a fix.

**Screenshot**:
![Screenshot from 2021-06-22 11-02-14](https://user-images.githubusercontent.com/37089506/122846538-67a6f380-d349-11eb-8f41-4d98f9afc7f6.png)

**Desktop**
 - SQLTools Version 0.23.0
 - VSCode Version: VSCode Version 1.58.0-insider
 - OS: Ubuntu 20.04.2 LTS focal
 - Driver: 
   - PostgreSQL/Redshift

**Additional context**
It has never worked, including on older versions to my knowledge, for the last 6-12 months.

**Comment by laurenh-soa** [comment]
I am having precisely this issue with a different configuration:

- SQLTools v0.23.0
- VSCode v1.58.2 (user setup)
- OS: Windows_NT x64 10.0.18363 (Windows 10 1909)
- Driver: SQLTools Intersystems IRIS v1.1
- Database: Cache for Windows (x86-64) 2018.1.5 (Build 659U)

**Comment by dthompson-maystreet** [comment]
The offending code appears to be here:

https://github.com/mtxr/vscode-sqltools/blob/ba294769be006e9e605d70ca487e5ce6fb4126c8/packages/plugins/connection-manager/language-server.ts#L56

What it looks like to me is that the cache is never set; any successfully executing response should invoke the function defined at https://github.com/mtxr/vscode-sqltools/blob/8ee200af8cd659eb868f2889f0c42dd9c889842a/packages/plugins/connection-manager/cache/handlers.ts#L41, but this doesn't appear to happen with the extensions.

@sdissegna-maystreet, would you please take a quick look at this issue? Thank you.
