### ISSUE TITLE
connections fails / maybe TLS version problem

### ISSUE THREAD

**Issue by cherub-i** [mtxr/vscode-sqltools#835]
**Describe the bug**
Using SQLTool and the MySQL driver, I cannot successfully connect to a specific database:
```
[2021-07-06 13:11:24.017] [exthost] [error] Error: Request connection/GetChildrenForTreeItemRequest failed with message: ER_ACCESS_DENIED_ERROR: Access denied for user '<USER>'@'<IP>' (using password: YES)
	at c:\Users\bbaumeister\.vscode\extensions\mtxr.sqltools-0.23.0\dist\extension.js:16:111820
	at c:\Users\bbaumeister\.vscode\extensions\mtxr.sqltools-0.23.0\dist\extension.js:16:112227
	at Immediate.<anonymous> (c:\Users\bbaumeister\.vscode\extensions\mtxr.sqltools-0.23.0\dist\extension.js:16:112769)
	at processImmediate (internal/timers.js:461:21) sqltools.getChildrenForTreeItem
```

With the exact same connection parametes (server, port, database, user, password) I can connect using the MySQL Workbench client.
I would however very much prefer to use SQLTools as it is so nicely integrated into VSCode.

Colleagues of mine use IntelliJ and the database browser integrated there. 
In order to get that database client to work with this specific database, you have **enable TLSv1.2 for that database** 
 (```enabledTLSProtocols: TLSv1.2, TLSv1.3```).
**Is there any way to do that for SQLTools?**

**To Reproduce**
As I cannot pass on information for this specific database, I am sorry I can offer very little here :-(

**Expected behavior**
I can connect to the database

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - SQLTools Version: 0.23.0 [e.g. v0.17.x]
 - VSCode Version: 1.57.1
 - OS: Win 10
 - Driver: 
   - [ ] PostgreSQL/Redshift
   - [X] MySQL/MariaDB
   - [ ] MSSQL/Azure
   - [ ] SQLite
   - [ ] Other? Which...
 - Database version: [e.g. MySQL v5.6, PostgreSQL vX...]

**Additional context**
See above, part of the description.

**Comment by gjsjohnmurray** [comment]
@cherub-i does the problem also happen after you update to the current release of VS Code and the SQLTools extension and driver?

**Comment by cherub-i** [comment]
Hello @gjsjohnmurray, thank you for coming back on this.
In the meanting, the project to which that database belonged, has migrated to a different infrastructure. 
I am sorry, but therefore I cannot test that change under the same conditions as when I opened the issue.

**Comment by gjsjohnmurray** [comment]
Thanks for letting us know. I'll close the issue.
