### ISSUE TITLE
All connections gone, cannot add new conenction.

### ISSUE THREAD

**Issue by leepatrick-goop** [mtxr/vscode-sqltools#836]
**Describe the bug**

When opening SQLTools today my connections were missing and I am unable to add new connections.

Webview console output:

![4A5F67E2-EBC5-44EB-AADA-B77924CC57AE](https://user-images.githubusercontent.com/36421292/124993684-8cfa5980-dff9-11eb-8c9e-47ed6aeb0c72.png)

**To Reproduce**
1. Go to 'Add new connection'
2. Fill out connection details (using MySQL/PostgreSQL here)
3. Click 'Test Connection' (works)
4. Click on 'Save Connection' (doesn't work error is `Running the contributed command: 'sqltools.addConnection' failed.`)

**Expected behavior**
expect to see existing connections and be able to add new.

**Desktop (please complete the following information):**
 - SQLTools Version [v0.23.0]
 - VSCode Version: [1.58.0]
 - OS: [Mac]
 - Driver: 
   - [X] PostgreSQL/Redshift
   - [X] MySQL/MariaDB
   - [ ] MSSQL/Azure
   - [ ] SQLite
   - [ ] Other? Which...

**Comment by gjsjohnmurray** [comment]
Please check that your `settings.json` file contains valid JSON.

**Comment by gjsjohnmurray** [comment]
@leepatrick-goop if you post more information we can reopen this.
