### ISSUE TITLE
Add "drop table" option

### ISSUE THREAD

**Issue by adriancuadrado** [mtxr/vscode-sqltools#837]
**Is your feature request related to a problem? Please describe.**
I cannot drop a table directly from the UI. I cannot create a table either, but that feature is already requested in this issue: https://github.com/mtxr/vscode-sqltools/issues/720

**Describe the solution you'd like**
It would be nice to have an option in the context menu that opens when I right-click a table to drop the table.

**Comment by gjsjohnmurray** [comment]
Please write a DROP TABLE statement and execute it.

**Comment by adriancuadrado** [comment]
@gjsjohnmurray The whole point of this feature request is to drop a table more easily without wasting time manually writting a DROP TABLE statement. Duh.

**Comment by gjsjohnmurray** [comment]
@adriancuadrado how much time do you estimate such a button would save you per year, say?

**Comment by adriancuadrado** [comment]
@gjsjohnmurray It's just a feature request, for fuck sake. Don't implement it if you don't want to. Who the fuck am I to tell you what to do with your project? I just wanted to suggest an idea I thought was worth implementing, but whether you think it's actually worth whichever time and effort it takes to implement it is up to you. Just close this issue if you don't feel like implementing it. Or keep it open and wait for someone else to create a pull request for you, whatever.

**Comment by lsarrazi** [comment]
@adriancuadrado Im sure @gjsjohnmurray is the type of guy to put every files he has flat on the desktop instead of sorting into folders
Because hey, how much time would it save him per year lmfao ?
