### ISSUE TITLE
Do not open an sql editor each time you connect

### ISSUE THREAD

**Issue by adriancuadrado** [mtxr/vscode-sqltools#839]
**Describe the bug**
When I connect to the database, an sql editor opens and is annoying because I have to close it every time and because I also have to tell the popup that asks me "Do you want to save changes you made to xxx?" that I don't want to save the changes because I didn't do any changes at all.

**To Reproduce**
1. Go to connections
2. disconnect and connect again to the connection

**Expected behavior**
The sql editor shouldn't open every time. It's annoying.

**Desktop (please complete the following information):**
 - SQLTools Version v0.23.0
 - VSCode Version: 1.58.0
 - OS: Windows (with WSL)
 - Driver: 
   - [ ] PostgreSQL/Redshift
   - [ ] MySQL/MariaDB
   - [ ] MSSQL/Azure
   - [x] SQLite
   - [ ] Other? Which...

**Comment by SiJiL82** [comment]
There's an option in the extension settings to disable this:
![image](https://user-images.githubusercontent.com/65114782/144266335-a409b59e-90a4-479d-bd53-8845c71536f3.png)

**Comment by gjsjohnmurray** [comment]
@SiJiL82 thanks for answering this issue.
