### ISSUE TITLE
Running the contributed command: 'sqltools.saveResults' failed.

### ISSUE THREAD

**Issue by ismusidhu** [mtxr/vscode-sqltools#848]
Sometimes I get this error when I try to save results in CSV/JSON file. Once I get this error, I'm not able to save it even after repeated attempts.

MacOS Catalina 10.15.4 (19E287)

VSCode details->
Version: 1.59.0
Commit: 379476f0e13988d90fab105c5c19e7abc8b1dea8
Date: 2021-08-04T23:14:40.191Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Darwin x64 19.4.0

**Comment by gjsjohnmurray** [comment]
Can you provide steps that reproduce the issue?
