### ISSUE TITLE
command 'mssql.runQuery' not found

### ISSUE THREAD

**Issue by onrgumus** [mtxr/vscode-sqltools#854]
Hey All, I have seen command 'mssql.runQuery' not found into the vcscode all the time. I have tryied many time. Please help me !!

**Comment by gjsjohnmurray** [comment]
Can you provide details of how to reproduce the issue?

**Comment by gjsjohnmurray** [comment]
No response from OP.

**Comment by LiaoZhengxin** [comment]
I have the same question,help me

**Comment by onrgumus** [comment]
Hi,Do you need still support?Sent from my iPhoneOn 18 Jun 2023, at 11:36, LiaoZhengxin ***@***.***> wrote:﻿
I have the same question,help me
