### ISSUE TITLE
Connect to database over SSH

### ISSUE THREAD

**Issue by Actticus** [mtxr/vscode-sqltools#855]
For additional security, our team has closed access to the database directly, so a solution is needed to access the database over SSH, for example, as in TablePlus

**Comment by evanwills** [comment]
I would also find this very useful.

On top of the normal DB connections settings it would need
* Host/IP
* (possibly) Port
* Username, 
* Password, 
* SSH key (or the option to use .ssh/config)

**Comment by slankka** [comment]
Same for our company, we use SSH tunnel to access databases for development. And we're not allowed to access Linux server via password, we perfer SSH public keys.

**Comment by ivorynoise** [comment]
+1

**Comment by cameronmitchellapps** [comment]
+1 agreed this would be incredibly helpful feature for development in company environments

**Comment by gjsjohnmurray** [comment]
See also #395

**Comment by gjsjohnmurray** [comment]
See also #692 which suggests using VS Code's ability to work on a remote server over SSH.

**Comment by cameronmitchellapps** [comment]
Thanks @gjsjohnmurray - should we close this and track any updates/progress on #395 (and #692)?

**Comment by mtxr** [comment]
That makes sense.

Let's close it to track it on the previous that were reported.

Thanks @cameronmitchellapps
