### ISSUE TITLE
Query columns with special characters not working

### ISSUE THREAD

**Issue by qaisershehzad** [mtxr/vscode-sqltools#856]
Query columns with special characters not working.. 

I have a below query and is valid query with column names with some special characters like #, $ etc 
```
Select a#
 from b
```
Now when I format this query it get white space between special character and name. e.g 
`Select a #
 from b`
 which makes it invalid query. As column name is `a#`
 
is there a way we can allow special characters in query or format ignore while formatting so query remains valid.

**Comment by gjsjohnmurray** [comment]
Try enclosing column name in doublequotes (tested with PG):
```sql
CREATE TEMP TABLE DEBUG ("WEIRD#" VARCHAR(32));
INSERT INTO DEBUG ("WEIRD#")
VALUES ('APPLE'),
    ('PEACH');
SELECT *
FROM DEBUG;
```
