### ISSUE TITLE
Test Connection Success with wrong credentials

### ISSUE THREAD

**Issue by ubermanl** [mtxr/vscode-sqltools#860]
**Describe the bug**
When a new connection is to be added, "Test Connection" shows success with no data.

**To Reproduce**
1. Go to Connections
2. Click on Add New Connection
3. Scroll down to Test Connection button and press it
4. See green "Succesfully Connected!" message.

**Expected behavior**
To get an error stating username and password are mandatory fields.

**Screenshots**
![image](https://user-images.githubusercontent.com/1846840/131192517-ef5741f6-0308-4d32-9358-bd2cbbd5433b.png)

**Desktop (please complete the following information):**
 - SQLTools Version v0.23.0
 - VSCode Version: 1.59.1
 - OS: [ Mac]
 - Driver: 
   - [ ] PostgreSQL/Redshift
   - [X] MySQL/MariaDB
   - [ ] MSSQL/Azure
   - [ ] SQLite
   - [ ] Other? Which...
 - Database version: MySQL v8.0

**Additional context**
* Root has no password.
* If ask password is selected under "use password", a password prompt shows up, and entering any garbage, login still succeeds.
* If a user is specified, with any garbage password, login still succeeds.

**Comment by gjsjohnmurray** [comment]
Fix has been merged.
