### ISSUE TITLE
Execute full SQL script

### ISSUE THREAD

**Issue by myriamhanna** [mtxr/vscode-sqltools#862]
**Describe the bug**
Using SQLTools, I can only run my sql script line by line. I can't find any way to run the whole script in one run

**Desktop (please complete the following information):**
 - SQLTools Version v0.23.0
 - VSCode Version: 1.59.1
 - OS: Linux
 - Driver: 
   - [ ] PostgreSQL/Redshift
   - [X] MySQL/MariaDB
   - [ ] MSSQL/Azure
   - [ ] SQLite
   - [ ] Other? Which...
 - Database version: MySQL Ver 15.1 Distrib 10.3.29-MariaDB

**Additional context**
My SQL script is a bit long and to be able to execute the whole script would be better

**Comment by gimbo** [comment]
What happens when you run the "Run This File" command provided by the extension? For me that runs all of the queries in the file, one at a time.

**Comment by myriamhanna** [comment]
Works perfectly
