### ISSUE TITLE
Running multiple INSERT INTO statements results in error.

### ISSUE THREAD

**Issue by AlpBilgin** [mtxr/vscode-sqltools#864]
**Describe the bug**

When I use the "run on active connection" button on  an .sql file with multiple INSERT INTO statements, the statements are all successfully executed but the extension throws a javascript looking error "Cannot destructure property name of  'undefined' as it is undefined".

When I run the statements individually everything works out fine.

I similarly tried running multiple SELECT statements just to cross check and I get a similar message.

I guess the extension can't handle the object returned from executing multiple statements?

**To Reproduce**
1. make an SQL file with multiple statements
2.  "run on active connection" button 
3. Observe SQL Console

**Expected behavior**
Maybe extension can display multiple result panes?

**Screenshots**

**Desktop (please complete the following information):**
 - SQLTools Version 0.23.0
 - VSCode Version: 1.59.1
 - OS: win10
 - Driver: 
   - [ ] PostgreSQL/Redshift
   - [ x] MySQL/MariaDB
   - [ ] MSSQL/Azure
   - [ ] SQLite
   - [ ] Other? Which...
 - Database version: 10.5.12 mariadb

**Additional context**
Running mariadb from bitnami docker image

**Comment by nvmker** [comment]
Same issue here, voting for fix that.

**Comment by gjsjohnmurray** [comment]
Fixed in today's 0.4.0 MySQL driver release.
