### ISSUE TITLE
How to volunteer to fix your tutorials, documentation, UI, installation, basically the entire thing?

### ISSUE THREAD

**Issue by caesarsamsi** [mtxr/vscode-sqltools#865]
**Is your feature request related to a problem? Please describe.**
I am always frustrated when using an extension. There isn't an obvious way to make use of the extension or its drivers. Documentation is not available. This is poorly done for sqltools. You have a great feature list, I installed it, great, now what do I do to use those touted features???

**Describe the solution you'd like**
I want to open Visual Studio install the SQLTools extension, then use a wizard to configure it. Once configured I want to have a clear user interface to make use of its features. For example SQL Beautifier, how in the world can I use it? I found it once on an obscure web page. Can't find it again now.

Once I've configured it, I might want to configure it a different way, change it. I can read JSON well enough, but where the heck again do I plug that stuff in???

Now we get to working with it. I installed SQLTools, then opened a .sql file. Nothing happens, the SQL statements just flop on the file like dead fish. How the heck do I execute the .sql file or highlighted statements???

Oh I found the beautifier, highlight the statement, then right click and click on "Format Selected Query For Any Document" ??? How discoverable is that??? I would be right clicking on the statement without any though to highlight the statement first??

**Describe alternatives you've considered**
Yes I'm frigging ranting, I don't how 1M users can use this tool as is??? Is there a tutorial somewhere, I don't see a link. Oh and the documentation link? That goes to "Page Not Found"???

**Additional context**
You'll very likely ignore me, your loss, I hope you become at least aware of your shortcomings.

Oh yeah, because you folks are such sorry ass geeks that just want to write code, well, I want to volunteer to fix up your sorry ass tool.

Let me know: cmsamsi@gmail.com

**Comment by gjsjohnmurray** [comment]
@caesarsamsi are you still interested in doing this? The project is now open for PRs again. Documentation source is in .mdx files under the /docs section of the repo. Another idea would be to leverage VS Code's walkthroughs[walkthroughs](https://code.visualstudio.com/api/ux-guidelines/walkthroughs)  feature.
