### ISSUE TITLE
PostgreSQL Connection Reports no Schemas

### ISSUE THREAD

**Issue by ScriptPup** [mtxr/vscode-sqltools#866]
**Describe the bug**
When connecting to PostgresSQL from SQLTools, the connection works correctly but the database explorer shows "Nothing here" under schemas, despite the company having a ton of schemas defined. It seems that the explorer just isn't working for some reason. The output from SQLTools doesn't show any errors in the /GetChildrenForTreeItemRequest request.

The only error from webdevloper is workbench.html:1 Not allowed to load local resource: file:///C:/Users%0<username>.vscode%0Extensionsmtxr.sqltools-driver-pg-0.2.0iconspg%C2%ACtive.png

**To Reproduce**
1. Connect to postgreSQL environment
2. Open the connection and the schema and note the "nothing here" message

**Expected behavior**
All schemas listed, with the ability to drill down to table and to columns

**Screenshots**
![image](https://user-images.githubusercontent.com/6163646/132582146-ceae75cd-381a-47a6-b24b-ac47c92b8dda.png)

**Desktop (please complete the following information):**
 - SQLTools Version 0.23.0
 - VSCode Version: 1.60.0
 - OS: Windows
 - Driver: 
   - [x] PostgreSQL/Redshift
   - [ ] MySQL/MariaDB
   - [ ] MSSQL/Azure
   - [ ] SQLite
   - [ ] Other? Which...
 - Database version: PostgreSQL 8.3.23 (Greenplum Database 5.28.6 build commit:aa6d6ae7fe28fecb80e78ff49662e4e23ba1e274) on x86_64-pc-linux-gnu, compiled by GCC gcc (GCC) 6.2.0, 64-bit compiled on Mar  3 2021 02:48:32

**Additional context**
I know our company is using a horribly old version of PostgreSQL, so I'm wondering if that's part of the problem. I was hoping someone had some ideas to troubleshoot though. I like the SQLTools lightweight connector way more than the other options I currently have.

**Comment by gjsjohnmurray** [comment]
Does the problem still occur with the current release of the SQLTools extension and driver?

**Comment by haobibo** [comment]
@gjsjohnmurray  The problem still occurs in the latest version.

As a comparison, using PyCharm/DataGrip to connect to GreenplumDB requries users to set the following options:
 - Do not use xmin in queries to pgdatabase
 - Introspect using JDBC metadata

![image](https://user-images.githubusercontent.com/1597350/233155854-dd2e0688-6ecd-4706-90a3-5403c2bdd67b.png)

**Comment by gjsjohnmurray** [comment]
@haobibo thanks for the information.

Given that Pycharm/Datagrip needs some special configuration in order to connect, this makes me think the PostgreSQL driver for SQLTools would need to be forked to create a Greenplum-specific driver extension. Ideally someone out there would step up and [contribute the driver](https://vscode-sqltools.mteixeira.dev/en/contributing/support-new-drivers). Alternatively, funded development could be undertaken via [my employer](http://georgejames.com/#d-VSCode).

**Comment by Tesla9527** [comment]
@haobibo have you fixed the issue? I also have the problem

**Comment by haobibo** [comment]
@Tesla9527  Not yet.
