### ISSUE TITLE
Formatting issues "--"

### ISSUE THREAD

**Issue by kfordaccela** [mtxr/vscode-sqltools#87]
### Issue Type

* [X] Bug
* [ ] Enhancement 
* [ ] Feature Request
* [ ] Question
* [ ] Other

### Prerequisites (For bugfixes)

* [Y] Are you running the latest version?
* [ ] Did you check the logs?
* [ ] Did you check the Setup?

### Description

I feel as though I generally write pretty consistent SQL code, however using the reformat option the following code has major issues.
```sql
-- Testing SQL Formatting 
SELECT
-- This is a nice comment label
1 Value1,
-- Start of Tables
FROM DUAL
```

will become the following by using "ctrl+e ctrl+b", which is unusable. Note the " ' " character was included so that the format didn't do anything strange.
```sql
-- Testing SQL Formatting
SELECT
  -- This is a nice comment label 
  1 Value1,
  -- Start of Tables
FROM
  DUAL
```

**Comment by kfordaccela** [comment]
> - - Testing SQL Formatting
SELECT
  - - This is a nice comment label 1 Value1,
  - - Start of Tables
FROM
  DUAL

**Comment by kfordaccela** [comment]
`- - Testing SQL Formatting
SELECT
  - - This is a nice comment label 1 Value1,
  - - Start of Tables
FROM
  DUAL`

**Comment by mtxr** [comment]
Duplicate #97 

I'll keep the tracking in #97 because it' really well described and seems to be the same issue.
