### ISSUE TITLE
Connections

### ISSUE THREAD

**Issue by kdmiltner** [mtxr/vscode-sqltools#870]
Issue Type: <b>Bug</b>

I set my database connections (about 10) - a mix of Redshift and PostgreSQL. They seemed to be working fine, but when after I finished for the night and came back to my laptop the next morning they were missing (this was on 9/20/2021). I reset a handful today (9/21/2021) and those were also working fine, until after I closed my computer and came back a couple hours later they were missing again. Now, I'm unable to add connections and keep seeing an error that says "Element with id [name of a prior set connection] is already registered." I get this error regardless of if I'm using the same connection name or not.

Extension version: 0.23.0
VS Code version: Code 1.60.1 (Universal) (83bd43bc519d15e50c4272c6cf5c1479df196a4d, 2021-09-10T17:09:14.403Z)
OS version: Darwin arm64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 2|
|Memory (System)|16.00GB (0.22GB free)|
|Process Argv|--crash-reporter-id 2b04a0f4-2003-450e-bc25-8b0e426c637f|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt678:30270856
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscorecescf:30358481
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwt:30364497
pythonvssor306:30344512
bridge0708:30335490
pygetstartedc2:30360494
dockerwalkthrucf:30369616
bridge0723:30353136
pythonrunftest32:30365366
pythonf5test824:30361777
javagetstartedt:30364666
pythonvspyt187:30365361
pydsgst2:30361792
vssid140cf:30363604
vssur157:30367808

```

</details>

**Comment by gjsjohnmurray** [comment]
Maybe #872 is relevant. Please check workspace level `settings.json` file as well as user level one.

**Comment by gjsjohnmurray** [comment]
Or perhaps https://github.com/mtxr/vscode-sqltools/issues/668#issuecomment-991088634
