### ISSUE TITLE
Bigquery Support

### ISSUE THREAD

**Issue by awoehrl** [mtxr/vscode-sqltools#874]
Hi,

it would be great to have Google BigQuery support as well. There are ODBC and JDBC drivers for BQ:, maybe these would help? 

https://cloud.google.com/bigquery/docs/reference/odbc-jdbc-drivers

Best
Andreas

**Comment by OmarArain** [comment]
Hi, I second this. Support for BQ would simplify the number of IDE-like tools I need to open for my daily workflows.  What would it take to add support for ODBC/JDBC drivers in this extension?

**Comment by davehowell** [comment]
Community drivers can be created and there are [useful docs to support this](https://vscode-sqltools.mteixeira.dev/contributing/support-new-drivers)  as well as a [github template repository](https://github.com/mtxr/vsc-sqltools-driver-template) to start from.

The README.md also has this message:

> I'm looking for maintainers for each driver, if you are interested on maintain/test any driver, please contact me.
> https://mteixeira.dev/

It won't use ODBC/JDBC, as a VSCode extension it is node.js/Typescript so would likely need to use the [Google Bigquery Node.js Client](https://cloud.google.com/nodejs/docs/reference/bigquery/latest)

**Comment by archiewood** [comment]
Has anyone made a start on this yet?

We're considering using SQL tools as part of the user experience at https://github.com/evidence-dev/evidence-VSCode

We're a Nodejs shop so may be able to help out

**Comment by gjsjohnmurray** [comment]
I am not aware of anyone working on this. Doing it in NodeJS is going to be a better fit than trying to leverage xDBC drivers, IMO.

**Comment by mtxr** [comment]
@lucasKr has shown interest in the past. Not sure if you are still up to it

**Comment by archiewood** [comment]
Okay, so have a work in progress version up here:
- [GitHub](https://github.com/evidence-dev/sqltools-bigquery-driver)
- [VSCode Marketplace](https://marketplace.visualstudio.com/items?itemName=Evidence.sqltools-bigquery-driver)


Still quite a few issues to iron out, but it works to query data and explore the db

Hoping I can squash most of the bugs this week.

Once I have, would appreciate some testers if there are any around!

**Comment by archiewood** [comment]
I've published a version 0.0.2 on the [VSCode Marketplace](https://marketplace.visualstudio.com/items?itemName=Evidence.sqltools-bigquery-driver)

Squashed the bugs I found, and it's feeling pretty nice for me to drive around my DB

It has connection options for:
- Service Accounts
- GCloudCLI
- OAuth Access Token

Any testing much appreciated!

One thing I couldn't really get my head around was how to implement intellisense for column / table completions, but happy to leave that for later!

**Comment by archiewood** [comment]
@mtxr this issue can probably now be closed?

**Comment by mtxr** [comment]
For sure
