### ISSUE TITLE
Not possible to query temporal tables with "Run selected query"  command

### ISSUE THREAD

**Issue by ofajardo** [mtxr/vscode-sqltools#877]
**Describe the bug**
If I create a temporal table with a statement by clicking on "Run on active connection", delete the query and then type a second query selecting from that temporal table, everything works as expected. 

However, if I have the two queries one after the other in the same editor, then I first highlight the create temp table statement, do right click and click on "Run selected query" (this works fine), and then highlight the select query  and click on "Run selected query", I get the error temporal table does not exist. 

I create a temporal table and afterwards I cannot query from it if I have 

**To Reproduce**

queries: 

create temp table test as 
select true as dummy;

select * from test;

1. Paste these two queries in the same editor. 
2. Highlight the first one (create), right click -> "Run selected query"
3. Highlight the second one (select), right click -> "Run selected query"

**Expected behavior**
I would expect that I can query the temporal table I created. It looks as if every time you hit "Run selected query" a new connection is made. 

Typically I use SQL to explore data, so I need to write a query, eventually create a temporal table, and then continue exploring, create a second temporal table, and finally join my temporal tables to get the final result. I want to have all my slq statements on the same script so that I can better control on the flow of the process. This kind of work is impossible if creating a new connection every time (I assume that is what is doing, maybe it is something else). 

**Screenshots**
I think not needed? But happy to provide later if not enough clarity on the issue. 

**Desktop (please complete the following information):**
 - SQLTools Version [e.g. v0.17.x] v0.23.0
 - VSCode Version: [e.g 1.x.y] 1.61
 - OS: [e.g. Windows, Linux, Mac] Mac
 - Driver: 
   - [ x] PostgreSQL/Redshift: Redshift dedicated version
   - [ ] MySQL/MariaDB
   - [ ] MSSQL/Azure
   - [ ] SQLite
   - [ ] Other? Which...
 - Database version: [e.g. MySQL v5.6, PostgreSQL vX...] 

**Additional context**
Probably the same as #504

**Comment by ofajardo** [comment]
As a side note : 

If I have these two queries in one editor and click on "Run active connection", I get a multiple query result window with two tabs, both show "Query returned 0 rows", while I would expect to see one row coming back from the second query. 
If I add a third line, just a commented empty line ("--"), then I get three tabs, the two first say query returned 0 rows, and the third one returns the one row I am expecting from my select query. 

I would expect the results from the select query would come back in the second tab.

**Comment by tlifke01** [comment]
Bumping this issue that I'm having as well.

Example:

I run this create table query:
`CREATE TABLE #new_temp_table as (
select count (distinct identifier) id_count
from database1.table1)
`

Then try to pull from it:
`
select id_count
FROM #new_temp_table
`

And get the error
`relation #new_temp_table does not exist`

I'll note that when I don't make new_temp_table a temporary table (i.e. new_temp_table instead of #new_temp_table) it still creates a table that I can reference without issue.

Desktop (please complete the following information):

SQLTools Version: v0.23.0
VSCode Version: 1.60
OS: Mac
Driver:
 Redshift (dedicated ver) https://marketplace.visualstudio.com/items?itemName=kj.sqltools-driver-redshift
Database version: Redshift v3.0.50

**Comment by tlifke01** [comment]
Previously linked issue provided solution. This issue can be closed.

**Comment by ofajardo** [comment]
thanks @tlifke01! that indeed solves the issue with creating temporal tables. 

The issue described in the side note is still there, so I leave it here for the developer's consideration.

**Comment by gjsjohnmurray** [comment]
Side note split into separate issue.

**Comment by Sehajbirsingh** [comment]
Hi I am still getting same issue as you mentioned each query establishes its own unique connection in VS CODE,
is there a way for queries to be run under same connection so we don't face issue with temp table creation and then accessing it again ?
Please help if you found the solution @gjsjohnmurray

**Comment by gjsjohnmurray** [comment]
@Sehajbirsingh which database driver are you using?

**Comment by Sehajbirsingh** [comment]
> @Sehajbirsingh which database driver are you using?

@gjsjohnmurray MySQL
