### ISSUE TITLE
404 on docs

### ISSUE THREAD

**Issue by emil14** [mtxr/vscode-sqltools#889]
https://vscode-sqltools.mteixeira.dev/features

**Comment by george-james-software** [comment]
emil14, where does this link originate?  There isn't supposed to be a page at that url so the 404 is correct, but what did you click on to be directed there?

**Comment by george-james-software** [comment]
Found it.  There's a link on this page that is bad: https://vscode-sqltools.mteixeira.dev/#features

**Comment by gjsjohnmurray** [comment]
See also #853

**Comment by mtxr** [comment]
Dup of #853
