### ISSUE TITLE
How do I connect to multiple databases at the same time?

### ISSUE THREAD

**Issue by CodeMan-P** [mtxr/vscode-sqltools#89]
"sqltools.connections": [
        {
            "name": "MySQL_local",
            "server": "127.0.0.1",
            "port": 3306,
            "database": "db1,db2,db3",
            "username": "root",
            "dialect": "MySQL"
        }
    ]

**Comment by mtxr** [comment]
It's being developed but I'm a quite busy right now.

It will take advantage of the new Activity Bar api to handle connections like WebStorm. Does it fit?

**Comment by mtxr** [comment]
Duplicate #69
