### ISSUE TITLE
feature request related to a problem

### ISSUE THREAD

**Issue by hemanttaskology** [mtxr/vscode-sqltools#891]
**Is your feature request related to a problem%3F Please describe.**%0AA clear and concise description of what the problem is. Ex. I'm always frustrated when [...]%0A%0A**Describe the solution you'd like**%0AA clear and concise description of what you want to happen.%0A%0A**Describe alternatives you've considered**%0AA clear and concise description of any alternative solutions or features you've considered.%0A%0A**Additional context**%0AAdd any other context or screenshots about the feature request here.%0A

**Comment by george-james-software** [comment]
Not an issue.
