### ISSUE TITLE
Formatter breaks the postgres timescaledb => syntax

### ISSUE THREAD

**Issue by msdrigg** [mtxr/vscode-sqltools#893]
**Describe the bug**
The formatter breaks the timescaledb => syntax. This may be standard postgres syntax, but I have only seen it in timescaledb's documentation (https://docs.timescale.com/timescaledb/latest/how-to-guides/continuous-aggregates/create-a-continuous-aggregate/#creating-a-continuous-aggregate).

**To Reproduce**
1. Create a test.sql document and add this function
```sql
SELECT add_continuous_aggregate_policy('conditions_summary_daily',
     start_offset => INTERVAL '1 month',
     end_offset => INTERVAL '1 day',
     schedule_interval => INTERVAL '1 hour');
```
2. Format the document with sqltools
3. Notice that the arrows `=>` are changed to `= >`
4. Try to run the formatted document in timescaledb and verify that there are syntax errors

**Expected behavior**
Arrows don't change (or have some configuration to prevent arrows from changing)

**Desktop (please complete the following information):**
 - SQLTools Version v0.23.0

**Comment by gjsjohnmurray** [comment]
See also #764
