### ISSUE TITLE
New maintainers! Meet @george-james-software and @gjsjohnmurray!

### ISSUE THREAD

**Issue by mtxr** [mtxr/vscode-sqltools#896]
Hey guys, I'm not able to focus in the project like I used to do and that's why I'm looking for maintainers.

Currently I need to focus more on my family, my kid is growing and I want to spend more time with him on my free time. Also I have a lot to do in my current company and I've been far from SQL databases in the past 18 months.

That said, if you have interest on maintaining the project, reach out to me thought github@mteixeira.dev.

It has been great developing this project while I could, but the project needs to move forward with more attention that i can provide.

Thanks!

**Comment by mtxr** [comment]
Hi everyone! Glad to be back here!

Today I wanted to share some good news! As you guys know, I haven't been close to the project like in the old years. That said, I'm happy to say that we know have new project maintainers!

Please meet @george-james-software and @gjsjohnmurray!

They are two of the oldest and most faithful users the project has ever had!

I'll keep in touch with them and I hope we can get the project back on a good shape in no time.

@george-james-software and @gjsjohnmurray, as we talked before, you have my full trust to guide and take the best decisions for the project and the long term roadmap.

Thank you for taking over on this journey!

Best,
Matheus

**Comment by gjsjohnmurray** [comment]
We are pleased to announce the first new release since we became maintainers.

https://github.com/mtxr/vscode-sqltools/releases/tag/v0.24.0

We hope to get the new versions of the extensions published on Marketplace and Open VSX soon. Until that happens you can download them from the link above and drop the VSIX files individually onto the Extensions view of VS Code.
