### ISSUE TITLE
SQLTools increases cpu usage to 100% for no reason

### ISSUE THREAD

**Issue by ImreC** [mtxr/vscode-sqltools#902]
Issue Type: <b>Bug</b>

I don't know. I am unable to load other extensions or copy files with this enabled currently

Extension version: 0.23.0
VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:49:24.808Z)
OS version: Linux x64 5.17.5-76051705-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 x 3693)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|7, 4, 3|
|Memory (System)|15.33GB (1.90GB free)|
|Process Argv|--new-window /home/imre/Development/ammp_dba --crash-reporter-id 4ee97d15-3245-4085-8b48-4aebe18d3322|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|pop|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|pop|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30492333
vscaac:30438847
vsclangdf:30486550

```

</details>

**Comment by gjsjohnmurray** [comment]
Does this problem still happen with the latest SQLTools (0.24.0) and the latest VS Code (1.71)?

If so, does it happen as soon as you start VS Code? Or when you try to connect? Or when defining a connection? If connection-related, which driver are you using?

**Comment by gjsjohnmurray** [comment]
Maybe related to #505, but we need more information from @ImreC

**Comment by ImreC** [comment]
This is not related. For me sqltools crashed without any querying. I think it has to do with processing large sql files (for example pg_dump outputs). That completely crashes sqltools. I think there should be a mechanism to recognize large files and stop processing them. Would be difficult for me to reproduce now as I reported this 4 months ago an have not been using sqltools since.

**Comment by gjsjohnmurray** [comment]
Thanks for the info. I'm going to link this to #907 and close it as a duplicate.
