### ISSUE TITLE
Unable to install sqlte3. 

### ISSUE THREAD

**Issue by TKDMzq** [mtxr/vscode-sqltools#904]
**Describe the bug**
When Tryingto connect to SQLite db SQLTools prompts for dependency install that fails due to asking for outdated version of the package and having issue with dependency. 

Failes due to __node-pre-gyp__ beeing deprecated
It advises to use __@mapbox/node-pre-gyp__

**To Reproduce**
1. Craete connection to SQLite DB
2. Click on 'connect'
3. Aprove instaltion of the package
4. It will fail during this step

**Expected behavior**
Instaling sqlite3 without failing. 

**Screenshots**

**Desktop (please complete the following information):**
 - SQLTools Version [e.g. v0.23.]
 - VSCode Version: [e.g 1.67.2]
 - OS: [e.g. Windows, Linux, Mac]
 - Driver: 
   - [ ] PostgreSQL/Redshift
   - [ ] MySQL/MariaDB
   - [ ] MSSQL/Azure
   - [x] SQLite 0.2.0
   - [ ] Other? Which...
 - Database version: [e.g. MySQL v5.6, PostgreSQL vX...]

**Additional context**

**Comment by GongT** [comment]
I can install `sqlite3` with npm from commandline, but fail when install by this extension.

And I can't find document about `sqltools.useNodeRuntime`,

**Comment by gjsjohnmurray** [comment]
See also #858

**Comment by mtxr** [comment]
Closing in favor of #858 . Seems to be the same issue. @TKDMzq feel free to re-open if you disagree
