### ISSUE TITLE
Cannot activate the 'SQLTools MySQL/MariaDB' extension because it depends on the 'SQLTools' extension, which is not installed. Would you like to install the extension and reload the window?

### ISSUE THREAD

**Issue by tschaffter** [mtxr/vscode-sqltools#906]
**Describe the bug**
See issue description [here](https://github.com/Sage-Bionetworks/challenge-registry/issues/277).

**To Reproduce**
The steps are described in the above issue.

**Expected behavior**
The error message should not appear and the extension `SQLTools MySQL/MariaDB` should be activated when the devcontainer starts for the first time.

**Screenshots**
Screenshots and logs are included in the above ticket.

**Desktop (please complete the following information):**
 - SQLTools Version: 0.23.0
 - VSCode Version: 1.67.2
 - OS: Windows - WSL
 - Driver: 
   - [ ] PostgreSQL/Redshift
   - [x] MySQL/MariaDB Version: 0.2.0
   - [ ] MSSQL/Azure
   - [ ] SQLite
   - [ ] Other? Which...
 - Database version: not relevant as the issue does not involve connecting to a DB instance

**Additional context**

Thank you for this excellent tool!

**Comment by gjsjohnmurray** [comment]
See https://github.com/microsoft/vscode/issues/149309

**Comment by gjsjohnmurray** [comment]
Let's hope that https://github.com/microsoft/vscode/pull/150333/files gets approved and merged in time for the next VS Code release.

**Comment by gjsjohnmurray** [comment]
New PR to watch is https://github.com/microsoft/vscode/pull/159822

**Comment by gjsjohnmurray** [comment]
Fixed in today's Insiders
```
Version: 1.72.0-insider
Commit: d17726fe4beae5abe87ba9e9429cd298be8b53c4
Date: 2022-09-05T05:21:30.535Z (3 hrs ago)
```
