### ISSUE TITLE
Freezes when trying to run large SQL script

### ISSUE THREAD

**Issue by KHVBui** [mtxr/vscode-sqltools#907]
- Issue Type: `Bug`
- Extension Name: `sqltools`
- Extension Version: `0.23.0`
- OS Version: `Darwin x64 20.6.0`
- VS Code version: `1.67.2`

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 59,
		"activateCallTime": 14,
		"activateResolvedTime": 12,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "mtxr.sqltools",
				"_lower": "mtxr.sqltools"
			},
			"activationEvent": "*"
		}
	},
	"runtimeErrors": [],
	"runningLocation": {
		"affinity": 0,
		"kind": 1
	}
}
```

**Comment by gjsjohnmurray** [comment]
Which driver? By large do you mean one that returns a lot of rows? Or that selects a small number of records from a large table?

**Comment by KHVBui** [comment]
I basically had a script that created table and populated it with many lines of values using a lot of lines of "INSERT INTO". The SQL file was 1.9 MB so it's a lot of queries.

When I ran chunks of the script at a time instead of the whole thing at once, it worked.

I attached the SQL script below as a txt file.

[Chinook_PostgreSql.txt](https://github.com/mtxr/vscode-sqltools/files/9172246/Chinook_PostgreSql.txt)

**Comment by davehowell** [comment]
This is not an issue with SQL Tools, you're going to run into this same issue no matter which SQL client you use. There is no strict limit in postgres for how large the query can be but its a lot of parsing to do and there are a few workarounds or alternatives.

1. Chunk it into a few scripts - as you already tried.
2. use psql and/or `COPY FROM` to do bulk inserts,  see https://dba.stackexchange.com/a/130211 and https://stackoverflow.com/a/36879218/1335793
3. Make the queries shorter by inserting multiple rows in a single statement as per the [postgreSQL docs](https://www.postgresql.org/docs/current/sql-insert.html)  
e.g.
```
INSERT INTO films (code, title, did, date_prod, kind) VALUES
    ('B6717', 'Tampopo', 110, '1985-02-10', 'Comedy'),
    ('HG120', 'The Dinner Game', 140, DEFAULT, 'Comedy');
```

**Comment by Anutrix** [comment]
Same issue when I just open any large(25000+ lines) .sql file in VSCode editor.
renderer1.log has:
```
[2022-09-15 01:06:03.179] [renderer1] [info] UNRESPONSIVE extension host: starting to profile NOW
[2022-09-15 01:06:08.316] [renderer1] [warning] UNRESPONSIVE extension host: 'mtxr.sqltools' took 88% of 5087.599ms, saved PROFILE here: '<REDACTED>' [{"id":"gc","total":592679,"percentage":12},{"id":"mtxr.sqltools","total":4494678,"percentage":88},{"id":"self","total":135,"percentage":0}]
```

VSCode doesn't freeze but all actions like global searching, git features, etc. just don't finish. As if they are waiting for some action to be finished. Making it unusable till restart.

Closing and opening the folder/vscode fixes it until I open the large file again.
Same error is seen in rendered1.log after each slow down.

Using SQLTools with MySQL driver on Intel Mac.

**Comment by gjsjohnmurray** [comment]
@Anutrix if your issue is about the time it takes to open and format a very large SQL query,  #977 may be relevant.

**Comment by Anutrix** [comment]
> @Anutrix if your issue is about the time it takes to open and format a very large SQL query, #977 may be relevant.

@gjsjohnmurray Not exactly. I don't need to format it. Just opening a large `.sql` file makes VSCode completely unuseably slow. Searches never start/end. Every extension actions gets stuck. As if waiting for some previous action to end.

**Comment by gjsjohnmurray** [comment]
@Anutrix please open a new issue for your problem. This one is about **running** a large SQL script.

If possible please attach a .sql that demonstrates the problem to your new issue. Make sure it doesn't contain any confidential data.

**Comment by brunom63** [comment]
@Anutrix did you manage to open a new issue about this? I tried searching but didn't find any.
Same problem here running a 19,000 line mariadb query on Linux VSCode 1.95.1, SQLTools 0.28.3. Query is confidential, can't post it here.
I know a query this size is a bit ludacris, but no way to run from it.
Problem doesn't occur on other IDEs.

![image](https://github.com/user-attachments/assets/c07aaa92-63df-4488-b80f-9e57922b4f04)

**Comment by brunom63** [comment]
Actually, I just checked that this does happen on other IDEs as well, but after 25,000 lines. I'm guessing this is more of a computational problem than a bug fore-say. 

Maybe a query that big is just too heavy for all the lints, validations, etc on an averaged equipped computer.

I suppose the best solution is to rethink the strategy and shorten all queries ...or be patient.

**Comment by davehowell** [comment]
@brunom63  Most databases have optimized bulk insert options. It's going to be way faster and not have these kinds of headaches. For MariaDB it is `LOAD DATA INFILE` or the mariadb-import tool, which automates the load data infile command for you. See https://mariadb.com/kb/en/how-to-quickly-insert-data-into-mariadb/#loading-text-files and https://mariadb.com/kb/en/load-data-infile/


This issue should be closed, it's not a SQL Tools specific problem, or even a VS Code specific problem, and I don't see how it could be solved. Eventually there is an upper limit for what is reasonable for parsing & rendering, and increasing that limit just kicks the can down the road a little bit.

**Comment by Anutrix** [comment]
> @Anutrix did you manage to open a new issue about this? I tried searching but didn't find any. Same problem here running a 19,000 line mariadb query on Linux VSCode 1.95.1, SQLTools 0.28.3. Query is confidential, can't post it here. I know a query this size is a bit ludacris, but no way to run from it. Problem doesn't occur on other IDEs.
> 
> ![image](https://private-user-images.githubusercontent.com/14306426/383719342-c07aaa92-63df-4488-b80f-9e57922b4f04.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5OTU2NTAsIm5iZiI6MTczMDk5NTM1MCwicGF0aCI6Ii8xNDMwNjQyNi8zODM3MTkzNDItYzA3YWFhOTItNjNkZi00NDg4LWI4MGYtOWU1NzkyMmI0ZjA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA3VDE2MDIzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2OTUwMmQyNGZiN2Q3ZGUwNTEzYWY0NTMxZGI4NWVhNGFlZTExMmUyNTQ0YjQyNDk4ODQ4MjhlZWU1NTBmMWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7uK8kJf01j-CcirqYPFxaCJWtGvILe7OSeqW4vjy1Jo)

Your issue seems unrelated. As davehowell mentioned, it seems like a fundamental SQL problem. All the best solving it.
My issue was just opening a file in VSCode and did not involve doing any SQL operations. Regardless, since you asked, here's my ticket link for reference: https://github.com/mtxr/vscode-sqltools/issues/989.
