### ISSUE TITLE
Tests connection button always returns success status even if it shouldn't

### ISSUE THREAD

**Issue by SethFalco** [mtxr/vscode-sqltools#912]
**Describe the bug**
When creating a new connection, you can put any value for `Server Address*` and `Port*` and when clicking `TEST CONNECTION`, it will be a successful connection even though it shouldn't be.

Once the connection saved, the UI displays that we're connected but if one actually attempts to execute queries, it'll just throw errors.

```
getaddrinfo ENOTFOUND host_does_not_exist
```

When I save settings with the host, `host_does_not_exist`, this is the output in the dev tools:
```json
{
    "ns": "settings"
}

"Message received: %s %O"

"RESPONSE:TEST_CONNECTION_SUCCESS"

{
    "connInfo": {
        "mysqlOptions": {
            "authProtocol": "default"
        },
        "previewLimit": 50,
        "server": "host_does_not_exist",
        "port": 3306,
        "driver": "MySQL",
        "name": "Joomla DB",
        "database": "joomla",
        "username": "joomla",
        "password": "{REDACTED}"
    }
}
```

When I click `TEST CONNECTION` to a host with a random IP, this is the output in the dev tools::
```json
{
    "ns": "settings"
}

"Message received: %s %O"

"RESPONSE:TEST_CONNECTION_SUCCESS"

{
    "connInfo": {
        "mysqlOptions": {
            "authProtocol": "default"
        },
        "previewLimit": 50,
        "server": "222.222.222.222",
        "port": 3306,
        "driver": "MySQL",
        "name": "Joomla DB",
        "database": "joomla",
        "username": "joomla",
        "password": "{REDACTED}"
    }
}
```

But for both of these, after clicking `SAVE CONNECTION` and trying to perform a query, errors occur.

**To Reproduce**
1. Go to the `SQL Tools` sidebar menu.
2. Go to `Add New Connection
3. Go to `MySQL`
4. Populate the form, but intentionally put a bad input for `Server Address*` or `Port*`.
5. Click `TEST CONNECTION`
6. Observe that it passes, when it should be failing.

**Expected behavior**

When clicking `TEST CONNECTION`, it should return a failure message if it can't connect to the host.

**Screenshots**
![image](https://user-images.githubusercontent.com/22801583/177009448-e5c6017d-6839-4003-980d-6a02db11e131.png)

Observe that the connection test was successful, but when I actually try to make queries, there's an `ENOTFOUND` at the bottom of the screenshot.

**Desktop (please complete the following information):**
 - SQLTools Version: v0.23.0
 - VSCode Version: 1.69.0-insider
 - OS: Linux
 - Driver: 
   - [ ] PostgreSQL/Redshift
   - [x] MySQL/MariaDB
   - [ ] MSSQL/Azure
   - [ ] SQLite
   - [ ] Other? Which...
 - Database version: MySQL v5.7.35

**Comment by gjsjohnmurray** [comment]
Also #860

**Comment by gjsjohnmurray** [comment]
Fix has been merged.
