### ISSUE TITLE
Enable CodeLens integration only for *.session.sql files / Command to enable on demand for other files

### ISSUE THREAD

**Issue by philipmat** [mtxr/vscode-sqltools#915]
**Is your feature request related to a problem? Please describe.**
Frequently I need to change a SQL file and have no need to execute the lines within. Yet SQLTools appends "Execute" decorators for almost every single line:
![image](https://user-images.githubusercontent.com/709928/180011251-cd3d850c-a5c3-4599-bcc1-e313d4857a9f.png)

**Describe the solution you'd like**
I would like to have a way to disable the CodeLens integration for most files, while keeping the rest of the functionality (highlight, completion, etc).

Ideally it should only be enable by default for `*.session.sql` files, and enabled on request for other sql files.

**Describe alternatives you've considered**
I tried associating `*.session.sql` files with another language and enabling  `"sqltools.codelensLanguages"` for that language [as per settings docs](https://vscode-sqltools.mteixeira.dev/settings),
but I still see the "Execute" code lens decorators in SQL files.

```json
    "files.associations": {
        "*.session.sql": "slim"
    },
    "sqltools.codelensLanguages": [
        "slim"
    ],
```

![image](https://user-images.githubusercontent.com/709928/180016024-3c510c76-e241-4288-82a5-cf96aa958161.png)

This was even after restarting VSCode.

**Additional context**
- SQLTool v0.23.0
- SQLTools PostgreSQL/Redshift Driver v0.2.0
- VSCode v1.69.2 on macOS Monterey 12.4

**Comment by gjsjohnmurray** [comment]
Are you certain that the "⏯️ Execute" codelens is coming from the SQLTools extension? I've never seen it, nor can I find source code that's creating it.

**Comment by philipmat** [comment]
You're absolutely right, @gjsjohnmurray  - it did come from a different extension ("cweijan.vscode-redis-client").

Thank you for pointing that out.
