### ISSUE TITLE
Build failures - has CODECOV_TOKEN expired?

### ISSUE THREAD

**Issue by gjsjohnmurray** [mtxr/vscode-sqltools#924]
See https://github.com/mtxr/vscode-sqltools/runs/7577287610

**Comment by gjsjohnmurray** [comment]
Still seems to be broken. See https://github.com/mtxr/vscode-sqltools/actions/runs/2776548495

**Comment by mtxr** [comment]
https://github.com/mtxr/vscode-sqltools/actions/workflows/test-formatter.yml @gjsjohnmurray newer builds are working fine apparently. 

I see no issue when I go to the actions page. the link you shared is from a PR that had a outdated branch. the formatter token was renamed to CODECOV_TOKEN_FORMATTER, so old PRs might still fail :/. newer will work just fine

**Comment by gjsjohnmurray** [comment]
@mtxr they've only been working because I created https://github.com/mtxr/vscode-sqltools/pull/929 to comment out the upload to codecov again, I got @george-james-software to approve it. Then I merged it to dev, then merged dev into a dependabot PR, approved it, used `gh api` to manually set the `build (10.x)` status check to `success`, then merged the PR. Repeated that cycle lots of times until all the dependabot PRs were merged.

**Comment by gjsjohnmurray** [comment]
Hmm, still not working for Formatter Test & Build actions triggered by my pushes.

For example:

https://github.com/mtxr/vscode-sqltools/runs/7949447061?check_suite_focus=true

Details:

![image](https://user-images.githubusercontent.com/6726799/185901082-fcacbbf7-a866-4653-b43c-641e47fb31a5.png)

Compare with this one triggered by a push by @mtxr:

https://github.com/mtxr/vscode-sqltools/runs/7937133670?check_suite_focus=true

Details which I think show this run has more permissions:

![image](https://user-images.githubusercontent.com/6726799/185900692-a51f7231-471d-4b41-bdd9-9e4c64aa6790.png)

**Comment by gjsjohnmurray** [comment]
@mtxr maybe the test-formatter.yml action should only do its codecov/codecov-action@v1.0.2 step on pull_request and not on push to the dev branch, because in the latter case it seems the action job has fewer permissions (perhaps because it is operating on files that may have been pushed from a fork so shouldn't yet be trusted).
