### ISSUE TITLE
UTF8 mysql

### ISSUE THREAD

**Issue by Lewiscowles1986** [mtxr/vscode-sqltools#925]
**Describe the bug**

The plugin struggles with `utf8mb4` encoded fields, even if the database is correctly setup.

I Verified it is the plugin, by connecting using command-line `mysql-client-core-8.0` (ubuntu package name), and executing the same query.

**To Reproduce**
1. Install this plugin in vscode
2. Ensure you have a database you can connect to
3. Run the following SQL

    ```sql
    CREATE DATABASE IF NOT EXISTS wp_interview_futz;
    USE wp_interview_futz;

    CREATE TABLE IF NOT EXISTS rusty_inc_names (
        id mediumint(9) NOT NULL AUTO_INCREMENT,
        name VARCHAR (255) NOT NULL UNIQUE ,
        is_outdated TIMESTAMP NULL,
        PRIMARY KEY (id)
    ) DEFAULT CHARSET = utf8mb4 DEFAULT COLLATE = utf8mb4_unicode_ci;

    CREATE TABLE IF NOT EXISTS rusty_inc_tree (
        name_id mediumint(9) NOT NULL,
        emoji tinytext NOT NULL,
        parent_id mediumint(9),
        PRIMARY KEY (name_id)
    ) DEFAULT CHARSET = utf8mb4 DEFAULT COLLATE = utf8mb4_unicode_ci;

    /* This was me messing around with the encoding as I wasn't sure if something was wrong with the sql creating the db & tables */
    ALTER DATABASE wp_interview_futz CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

    ALTER TABLE rusty_inc_tree CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

    ALTER TABLE rusty_inc_tree CHANGE emoji emoji VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

    INSERT INTO rusty_inc_names (id, name) VALUES (1, "Rusty Corp."), (2, "Food"), (3, "Canine Therapy"), (4, "Massages"), (5, "Games"), (6, "Treats"), (7, "Paw Cosmetics");

    INSERT INTO rusty_inc_tree (name_id, emoji, parent_id) VALUES (1, '🐕', null), (2, '🥩', 1), (3, '😌', 1), (4, '💆', 3), (5, '🎾', 3);
    ```
4. See error in console `ER_TRUNCATED_WRONG_VALUE_FOR_FIELD: Incorrect string value: '\xFo\x9F\x90\x95' for column emoji at row 1`

**Expected behavior**

Insert query works (as it does in mysql cli)

```
Query OK, 5 rows affected (0.03 sec)
Records: 5  Duplicates: 0  Warnings: 0
```

**Screenshots**

![Screenshot from 2022-07-31 15-35-27](https://user-images.githubusercontent.com/2605791/182031847-9b9995b9-0e5d-4b7e-929f-7ac2413240a8.png)
![Screenshot from 2022-07-31 15-35-40](https://user-images.githubusercontent.com/2605791/182031848-f03f8aba-f6c1-453d-b175-c5b091b1235d.png)
![Screenshot from 2022-07-31 15-35-57](https://user-images.githubusercontent.com/2605791/182031849-4b1860ce-ba7f-41c4-aa0c-8e011b1c6e81.png)

**Desktop (please complete the following information):**
 - SQLTools Version latest stable (downloaded fresh today via packages in vscode)
 - VSCode Version: latest (downloaded fresh today via vscode website)
 - OS: Linux (I would be surprised if this were OS specific)
 - Driver: 
   - [ ] PostgreSQL/Redshift
   - [X] MySQL/MariaDB
   - [ ] MSSQL/Azure
   - [ ] SQLite
   - [ ] Other? Which...
 - Database version: MySQL 5.7

**Additional context**

The table view after I insert from CLI is also messed up.

**Comment by Lewiscowles1986** [comment]
Looks like you are using npm package `mysql`. Here is a helpful link to it's documentation about collation, which confusingly (mysql specific) `utf` is 3-byte utf8 not 4-byte utf8.

[npmjs mysql package connection `charset` option](https://www.npmjs.com/package/mysql#connection-flags:~:text=charset%3A%20The%20charset%20for%20the%20connection.%20This%20is%20called%20%22collation%22%20in%20the%20SQL%2Dlevel%20of%20MySQL%20(like%20utf8_general_ci).%20If%20a%20SQL%2Dlevel%20charset%20is%20specified%20(like%20utf8mb4)%20then%20the%20default%20collation%20for%20that%20charset%20is%20used.%20(Default%3A%20%27UTF8_GENERAL_CI%27))

Here is a link to the code where I think this should be passed through. I'm actually not that sure how this all fits together having only worked on much simpler vs code extensions, but if someone could guide me, or point me to relevant docs, I'd be happy to contribute this fix.

https://github.com/mtxr/vscode-sqltools/blob/9fc92aba222ee3e30c09529b4589164c349965a9/packages/driver.mysql/src/ls/default.ts#L25-L38

I'll look to test this out by manually editing the plugin to see if that fixes.

**Comment by Lewiscowles1986** [comment]
Interestingly, although `charset` does fix the SQL `INSERT` statement, it does not fix the view of the table. For now would you be open to a literal one-liner? I'll open it anyway.

Update, it did eventually fix the table. Unsure why it took a while to show.
![Screenshot from 2022-07-31 16-29-10](https://user-images.githubusercontent.com/2605791/182033701-51b4411d-8faa-4317-9e34-ea6fc77ab7ca.png)

**Comment by gjsjohnmurray** [comment]
Please use the example at https://github.com/mtxr/vscode-sqltools/issues/491#issuecomment-628091743 to add a `charset` property with the correct value to the `mysqlOptions` object property of your connection definition.

**Comment by Lewiscowles1986** [comment]
Hi, thanks for responding on a weekend. 

Unfortunately, you've linked an issue 2.5 years old, still open, which hasn't clarified where or what to add. I did notice there was some pairing file which defines user configurable options.

As this field is not presently user configurable, and should not affect viewing (or interacting with) utf8 3-byte data-sets, are we sure we need to go through all that trouble to fix this bug? (it may be a while)

Best.

**Comment by gjsjohnmurray** [comment]
In the JSON where your connection is defined, find the `"driver": "MySQL"` line and add a `mysqlOptions` property after it to get the following:

```json
        "driver": "MySQL",
        "mysqlOptions": {
          "charset": "utf8mb4_general_ci"
        },
```

With this in place the published driver should have the same behaviour as you are proposing in your PR.

Another tactic with the current published driver is to run this statement immediately after connection:
```sql
SET NAMES 'utf8mb4' COLLATE 'utf8mb4_general_ci';
```

I am concerned that by changing what the driver uses as the default charset property for the connection your PR will break things for other users.

Instead I suggest extending the driver's connection config page to add a field in which users can optionally specify a string to use as the value of that property. From a MySQL perspective values put in here should be ones that appear in the resultset of a `SHOW COLLATION` statement on the target server.

**Comment by Lewiscowles1986** [comment]
Sorry, didn't see this until just now. I'll try to use this tonight maybe, see if it can work. Anything that avoids is good for me.

If this works without a PR 🏆 probably worth documenting for people, but very much appreciate your time and patience on this.

**Comment by gjsjohnmurray** [comment]
@Lewiscowles1986 were you able to try my suggestion?

**Comment by Lewiscowles1986** [comment]
I was, it did not work. But perhaps I misunderstood. I re-downloaded the plugin (to remove any edits) and followed the guidance to add to `"charset": "utf8mb4_general_ci"`. I Closed VS-Code and re-opened, and then connected.

**Comment by Lewiscowles1986** [comment]
The command to set the charset seems to not work at all, but then compound commands don't seem to be working either. I've switched to DBeaver instead.

**Comment by gjsjohnmurray** [comment]
Thanks for testing anyway. Since you're no longer using the extension I'm closing this.
