### ISSUE TITLE
Be an AuthenticationProvider so connection passwords can be held in keystore

### ISSUE THREAD

**Issue by gjsjohnmurray** [mtxr/vscode-sqltools#927]
Connection passwords can either be stored as plaintext in the connection definition or else be prompted for every time you connect.

Become an [AuthenticationProvider](https://code.visualstudio.com/api/references/vscode-api#AuthenticationProvider) that can store passwords in the workstation keystore/keychain. This API arrived in [VS Code 1.54](https://code.visualstudio.com/updates/v1_54#_authentication-provider-api).

I think this is better approach than the env-variables one suggested in #452.

**Comment by DaveParr** [comment]
@gjsjohnmurray thanks for taking on the feedback. Is this live right now? 

If it's on the main current release I'll go and re-install the extension today :)

**Comment by gjsjohnmurray** [comment]
@DaveParr no it isn't implemented yet. When it is we will update this issue.

**Comment by gjsjohnmurray** [comment]
Today's 0.27.0 release of the main extension implements this, and the 0.5.0 release of the MySQL/MariaDB driver leverages the new capability.
