### ISSUE TITLE
How to show mysql's meta database, like `information_schema`?

### ISSUE THREAD

**Issue by GKilm** [mtxr/vscode-sqltools#932]
How to show mysql's meta database, like `information_schema`?

If there is not  the feature , please make it.

**Comment by gjsjohnmurray** [comment]
The driver explicitly excludes some databases from the it displays in the connection manager:

- information_schema
- performance_schema
- sys
- mysql

A future enhancement could change this. Meanwhile you can run your own queries on tables in those databases.

**Comment by gjsjohnmurray** [comment]
Resolved by #938 (merged but not yet published)
