### ISSUE TITLE
Merged update to documentation hasn't been published

### ISSUE THREAD

**Issue by gjsjohnmurray** [mtxr/vscode-sqltools#933]
PR #922 added a new page named Testing to the documentation. The PR was merged several days ago but the new page hasn't yet appeared under the Contributing section at https://vscode-sqltools.mteixeira.dev/

I had understood that the public doc site got updated from the repo once a day.

**Comment by gjsjohnmurray** [comment]
@mtxr please investigate.

**Comment by mtxr** [comment]
Fixed
