### ISSUE TITLE
This repo is missing latest release 0.23.0 and vsix's

### ISSUE THREAD

**Issue by idantr** [mtxr/vscode-sqltools#937]
**Describe the bug**
This repo is missing latest release 0.23.0 
I was able to download 0.23.0.vsix file from vscode marketplace and https://open-vsx.org/api/mtxr/sqltools/0.23.0/file/mtxr.sqltools-0.23.0.vsix
can this release please be added with links to all the updated vsix's including the drivers

**Expected behavior**
This repos should include all the release versions and artifacts

**Screenshots**

**Desktop (please complete the following information):**
 - SQLTools Version [v0.23.0]
 - VSCode Version: [v1.69.2]
 - OS: [Linux]
 - Driver: 
   - [ ] PostgreSQL/Redshift
   - [ ] MySQL/MariaDB
   - [ ] MSSQL/Azure
   - [X] SQLite
   - [X] HANA
 - Database version: [e.g. MySQL v5.6, PostgreSQL vX...]

**Comment by gjsjohnmurray** [comment]
It may be too late to create a release record in GitHub for the exact commit at which @mtxr built and released 0.23 and the bundled extensions. We plan to record the next release here though.

Please help us understand why you want the VSIX artifacts attached to the release record here in addition to being published on Marketplace.

**Comment by gjsjohnmurray** [comment]
I have created https://github.com/mtxr/vscode-sqltools/releases/tag/v0.23.0
