### ISSUE TITLE
GH workflow triggered on release is failing

### ISSUE THREAD

**Issue by gjsjohnmurray** [mtxr/vscode-sqltools#942]
https://github.com/mtxr/vscode-sqltools/blob/6eaa1c266a33ef6916e5263081f781326d105d4d/.github/workflows/upload-release-assets.yml#L40

That file was deleted in this commit:

https://github.com/mtxr/vscode-sqltools/commit/c4b163886d245c680efb630c5ab8125de8ce5c0c

**Comment by gjsjohnmurray** [comment]
Log files of example failed run
[logs_2486.zip](https://github.com/mtxr/vscode-sqltools/files/9329229/logs_2486.zip)

**Comment by mtxr** [comment]
I need to revisit this guy. I believe things have changed here since the last release. I'll keep you posted
