### ISSUE TITLE
SQLTools not supported in vscode for web

### ISSUE THREAD

**Issue by idantr** [mtxr/vscode-sqltools#944]
**Is your feature request related to a problem? Please describe.**
Microsoft released vscode framework in web : https://vscode.dev/

**Describe the solution you'd like**
Currently sqltools is not working on this new platform 
I am also trying to implement sqltools with sqllite support(driver) in vscode for web and it is not working for me

**Describe alternatives you've considered**
Currently i am using another open source that is supported https://github.com/qwtel/sqlite-viewer-vscode

**Additional context**

**Comment by idantr** [comment]
@mtxr can someone look at the above request, we would like to use this opensource in out web product but it is not working in it's latest version

**Comment by gjsjohnmurray** [comment]
@idantr having reviewed the information [here](https://code.visualstudio.com/api/extension-guides/web-extensions#migrate-extension-with-code) I don't think it will be possible to achieve this without major re-engineering. In particular, the SQLite driver uses the [sqlite3](https://www.npmjs.com/package/sqlite3) package which is written in C++. The VS Code browser runtime environment only supports the execution of JavaScript and [WebAssembly](https://webassembly.org/).

**Comment by zachary-wang12** [comment]
Maybe we are meeting the same issue #919

**Comment by idantr** [comment]
@gjsjohnmurray sorry, 
you are correct our setup is different then vscode web, we are using something more similar to 
vscode on "code spaces" and we have other issues with this opens source probably related to how we setup the environment variables 
i am closing this as irrelevant
