### ISSUE TITLE
Export issue

### ISSUE THREAD

**Issue by joncard1** [mtxr/vscode-sqltools#949]
**Describe the bug**
This is something that I have been able to do in the past, so I assume it was introduced in the latest update. When I perform a query (the same query I have previously saved in a .sql file and was able to export), I get a result and there is a button at the bottom of the window that says, "Export". When I click this button, there is no response. I have looked in the logs, and see no entry in the log .../exthost1/output_logging_20220824T134455/3-SQLTools.log. I see entries in this log when I push "Open", but not when I push "Re-Run Query" or "Console"; I don't know whether that is normal or not. I am not used to logging this kind of bug, so I'm not familiar with the Visual Studio Code log ecosystem.

Thank you for reading this. Please let me know if there are logs or additional data that I can gather to help diagnose the problem.

**To Reproduce**
I have described the reproduction above. I don't know enough about the issue to give better information for a developer to reproduce the problem themselves.

**Expected behavior**
Historically, this has resulted in the command menu opening with a prompt for exporting as CSV or another format that I don't use so I don't remember.

**Screenshots**
Not sure if this would be helpful, since the bug is that it doesn't do anything.

**Desktop (please complete the following information):**
Mac Big Sur
VSCode Version: 1.70.2
SQL Tools last updated 8/19/2022, 08:44:25
InterSystems IRIS driver last updated 5/20/2021, 06:22:25 (I'm not sure how to verify that the version installed is a particular version; I'm taking this from the driver's page. I am up-to-date on all updates)
InterSystems IRIS 2020.1.1 (Build 408U)

**Comment by joncard1** [comment]
I actually got the results I was looking for by clicking "Open"; I had thought that was to open a file that had results in it. Perhaps this bug is that it's not clear to me the difference between "Open" and "Export" at this point.

**Comment by gjsjohnmurray** [comment]
Prior to being fixed in #880 the Export button wasn't wired up to do anything.

The fix will appear in the next release.
