### ISSUE TITLE
Run current file

### ISSUE THREAD

**Issue by casbon** [mtxr/vscode-sqltools#96]
### Issue Type

* [ ] Bug
* [ ] Enhancement 
* [X] Feature Request
* [ ] Question
* [ ] Other

### Prerequisites (For bugfixes)

* [ ] Are you running the latest version?
* [ ] Did you check the logs?
* [ ] Did you check the Setup?

### Description

Add ability to run sql file.

Unless, I'm mistaken I can run:
 - a query I type in a box 
 - a query I bookmark

But I cant run the current file (or selection)?  Please add this.

**Comment by mtxr** [comment]
Example:

![image](https://user-images.githubusercontent.com/707561/45925306-01b38600-bee9-11e8-99c6-09031ce5b451.png)
