### ISSUE TITLE
Formatting comments, new lines are not kept

### ISSUE THREAD

**Issue by PapsOu** [mtxr/vscode-sqltools#97]
### Issue Type

* [x] Bug
* [ ] Enhancement 
* [ ] Feature Request
* [ ] Question
* [ ] Other

### Prerequisites (For bugfixes)

* [x] Are you running the latest version?
* [x] Did you check the logs?
* [x] Did you check the Setup?

### Description

I've got a similar bug to this issue (#87) when formatting simple queries with comments :

```sql
SELECT * FROM user;

-- RESET ALL PASSWORD REQUESTS

UPDATE user SET password_requested_at = NULL, confirmation_token = NULL;
```

### Steps to Reproduce (For bugfixes)

1. Create a .sql file with file content type set as SQL
2. Put those simple queries into the file
3. Apply `format document` command

**Expected behavior:** [What you expected to happen]

The file should be formatted as bellow, the comment should keep its new lines (before and after)

```sql
SELECT
    *
FROM
    user;

-- RESET ALL PASSWORD REQUESTS

UPDATE
    user
SET
    password_requested_at = NULL,
    confirmation_token = NULL;
```

**Actual behavior:** [What actually happened]

The comment is after the last sql part without any new lines.

```sql
SELECT
    *
FROM
    user;-- RESET ALL PASSWORD REQUESTS
UPDATE
    user
SET
    password_requested_at = NULL,
    confirmation_token = NULL;
```

### Versions

- *Version*: v0.15.0 (vscode 1.26.1)
- *OS*: fedora 28
- *SGDB*: PostgresSQL (but it doesn't look like to be related to a specific database vendor)

**Comment by mtxr** [comment]
Just opened an issue https://github.com/zeroturnaround/sql-formatter/issues/50 in the 3rd party lib.

**Comment by Jule-** [comment]
@mtxr Hi! For me this issue is still happening. Are you sure it is fixed? If so what could possibly be wrong on my side?
Thanks in advance.
