### ISSUE TITLE
Cannot add new connection

### ISSUE THREAD

**Issue by Stycos** [mtxr/vscode-sqltools#972]
I cannot create a new connection. When I click on the circled locations in VS code there is no response. 

![image](https://user-images.githubusercontent.com/17010448/190509915-318747e9-95a0-42fb-967c-70c1cfe1c520.png)

If I use Ctrl+Shift+P then type in "SQLTools Management: Add New Connection" I get the error seen above. 

**Expected behavior**
See a list of Drivers 

**Desktop:**
 - SQLTools Version v.0.25.0
 - VS Code Version: 1.68.1 & 1.69.2 & 1.70.2, 
 - OS: Windows 10
 - Driver: N/A
 - Database version: N/A

**Comment by gjsjohnmurray** [comment]
Please go to the Output view (one way is <kbd>F1</kbd>, start typing "Focus on output" and choose the command). In the dropdown on Output view choose "SQLTools". Use the button by the dropdown to clear the output. Then use Command Palette (F1) to run `Developer: Reload Window`. When the reload has completed, check the SQLTools Output for error information and paste it here.

**Comment by Stycos** [comment]
I just get the following: 

[1663279824883] INFO  (ext): SQLTools is starting
[1663279824901] INFO  (ext): initializing language client...
[1663279824902] INFO  (ext): Detecting node path (if this stalls check Terminal view for the stuck session and kill it)...
    ns: "lc"

**Comment by gjsjohnmurray** [comment]
Please inster the following line as line 2 of your settings.json file, which you can open by running `Preferences: Open User Settings (JSON)` from Command Palette:

```
"sqltools.useNodeRuntime": false,
```

Save the change, restart VS Code, and see if the problem remains.

**Comment by Stycos** [comment]
That worked! Thank you!

**Comment by gjsjohnmurray** [comment]
@Stycos thanks for confirming this as a resolution. We have released 0.25.1 which reverts the default of this setting. It is now `false`, which is how it was in 0.24 and earlier versions. The only official driver that needs the setting to have a different value is the [SQLite](https://vscode-sqltools.mteixeira.dev/driver/sqlite) one.
