### ISSUE TITLE
Does the extension provide linting functionalities?

### ISSUE THREAD

**Issue by simplemind** [mtxr/vscode-sqltools#974]
Hi,
Could you please let me know if the extension has the functionality to highlight errors in SQL code? I could not find an answer within the list of features.
I code in MySQL and I have installed MySQL driver. SQLTools does not prompt any errors and I would like to know if this is because it is not designed to lint SQL code. Or because there is something missing on my end.
Thank you
Karolis

**Comment by gjsjohnmurray** [comment]
No, the extension doesn't yet leverage any of the [Diagnostic](https://code.visualstudio.com/api/references/vscode-api#Diagnostic)-related parts of the VS Code API, which is how extensions contribute to the Problems view, nor [CodeAction](https://code.visualstudio.com/api/references/vscode-api#CodeAction)s which linters typically use to offer fixes.

Interesting idea though...

**Comment by simplemind** [comment]
Thank you for a quick reply. Good to know its an idea worth considering

**Comment by mtxr** [comment]
possibly duplicate of #943

**Comment by gjsjohnmurray** [comment]
@mtxr I agree. Tagged as duplicate and closed.
