### ISSUE TITLE
Running multiple queries at once

### ISSUE THREAD

**Issue by freddietattersall** [mtxr/vscode-sqltools#986]
**Is your feature request related to a problem? Please describe.**
It is quite frustrating not being able to run multiple queries at once. When writing a full sql script, it is often a requirement to build tables as you go before arriving at the final product. Running queries one by one is very inefficient and slows down any updates 

**Describe the solution you'd like**
I would like to be able to highlight multiple queries, separated by a semi-colon (;), hit run queries once in order to run the highlighted queries sequentially

**Comment by gjsjohnmurray** [comment]
Which database driver are you using?

**Comment by freddietattersall** [comment]
Hi @gjsjohnmurray - thanks for getting back quickly. I'm using the snowflake driver. Thanks, Freddie

**Comment by gjsjohnmurray** [comment]
Please raise this at https://github.com/koszti/sqltools-snowflake-driver
