### ISSUE TITLE
Formatting comments and non-latin aliases

### ISSUE THREAD

**Issue by qoolek** [mtxr/vscode-sqltools#99]
### Issue Type

* [x] Bug
* [ ] Enhancement 
* [ ] Feature Request
* [ ] Question
* [ ] Other

### Prerequisites (For bugfixes)

* [x] Are you running the latest version?
* [ ] Did you check the logs?
* [ ] Did you check the Setup?

### Description

I've got two problem with formatting comments and non-latin aliases
1. After formatting, for each cyrillic simbol in alias, space is added
2. If comment starts with SQL statements, then '--' is replaced by two minuses
```
select t.column1 Кириллица_cyrilic_alias
    , t.column2 Latin_alias
from db_table t
where a >= some_date1  -- from
  and a <  some_date2  -- to 
  and b >= some_date3  -- and 
  and b <  some_date4  -- where, select etc.
  and 1 = 1
```

### Steps to Reproduce (For bugfixes)

1. Create a .sql file with file content type set as SQL
2. Put those simple queries into the file
3. Apply format document command

**Expected behavior:** [What you expected to happen]
```
select
    t.column1 Кириллица_cirilic_alias,
    t.column2 Latin_alias
from
    db_table t
where
    a >= some_date1 -- from
    and a < some_date2 -- to
    and b >= some_date3 -- and
    and b < some_date4 -- where, select etc.
    and 1 = 1
```

**Actual behavior:** [What actually happened]

```
select
    t.column1 К и р и л л и ц а _cirilic_alias,
    t.column2 Latin_alias
from
    db_table t
where
    a >= some_date1 - -
from
    and a < some_date2 - - to
    and b >= some_date3 - -
    and
    and b < some_date4 - -
where,
select
    etc.
    and 1 = 1
```

### Versions

- *Version*: v0.15.0 (vscode 1.26.1)
- *OS*: Win10
- *SGDB*: MySQL

**Comment by mtxr** [comment]
This is very annoying.

I'll code it there. Can't wait them anymore.

**Comment by mtxr** [comment]
I've made literally a workaround in the extension. 

Let's wait for them now.

Releasing now v0.16.7
