### ISSUE TITLE
connection error

### ISSUE THREAD

**Issue by Anwen954** [mtxr/vscode-sqltools#990]
**Describe the bug**
ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client

**To Reproduce**
1. MySQL版本          mysql  Ver 8.0.28 for Win64 on x86_64 (MySQL Community Server - GPL)
2. 操作系统名称	Microsoft Windows 11 专业版
3. 操作系统版本	10.0.22000 版本 22000
4. 报错信息              ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client

**Expected behavior**
测试连接成功

**Screenshots**
![image](https://user-images.githubusercontent.com/74594718/192092385-f8a92a29-005c-4bc5-bcf5-bea5c7b533bb.png)

**Desktop (please complete the following information):**
 - SQLTools Version v0.25.1
 - VS Code Version: 1.71.2
 - OS: Windows
 - Driver:
   - [ ] PostgreSQL/Redshift
   - [x] MySQL/MariaDB
   - [ ] MSSQL/Azure
   - [ ] SQLite
   - [ ] Other? Which...
 - Database version: MySQL Ver 8.0.28 for Win64 on x86_64 (MySQL Community Server - GPL)

**Comment by gjsjohnmurray** [comment]
Please see https://vscode-sqltools.mteixeira.dev/en/drivers/mysql/ where there is a section titled "MySQL 8 and ER_NOT_SUPPORTED_AUTH_MODE".
