### ISSUE TITLE
0.25.0 release record needs finalizing and 0.25.1 record needs adding

### ISSUE THREAD

**Issue by gjsjohnmurray** [mtxr/vscode-sqltools#997]
On 15-Sep-2022 I published 0.25.0 on Marketplace along with 0.4.0 of MySQL and SQLite drivers.

I had intended to create the GH release from dev (https://github.com/mtxr/vscode-sqltools/commit/36bea5f3956ebda6d10c23f816ef11df9442112a) but found that @mtxr had already started drafting one. Opening this issue to track the completion of this release record.

Once 0.25.0 record is in place we need to create one for the 0.25.1 recovery release which was published on 16-Sep-2022 from https://github.com/mtxr/vscode-sqltools/commit/1d5235f67218f19be287234d7eea4399827304cd

Let's aim to get this completed before we do the next release.

**Comment by gjsjohnmurray** [comment]
@mtxr please attach the new driver VSIX files to the 0.25.0 release record when you publish it. Similarly the main extension VSIX onto 0.25.1. 

See https://github.com/mtxr/vscode-sqltools/issues/858#issuecomment-1264653395

**Comment by mtxr** [comment]
Just did 0.25.1, sorry for taking longer on this.

**Comment by gjsjohnmurray** [comment]
@mtxr no problem. Thanks for doing that!
